import { db } from '../../lib/db';
import { caseStudies } from '../schema';

type KeyAction = {
  action: string;
  impact: string;
  difficulty?: 'easy' | 'moderate' | 'hard';
};

const batch3CaseStudies = [
  // ========== HEALTHCARE ==========
  {
    companyName: 'Viome Life Sciences',
    industry: 'healthcare',
    subIndustry: 'gut_testing',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Complex biotech development', 'Regulatory hurdles', 'Consumer education'],
      capabilities: ['Scientific research', 'AI/ML expertise'],
      marketPosition: 'New entrant in gut health',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '100_plus',
      revenueGrowth: '100x+',
      achievements: ['$30M+ annual revenue', 'Leading gut testing company', 'AI-powered health insights'],
      newCapabilities: ['Direct-to-consumer testing', 'Personalized nutrition', 'Microbiome analysis'],
      marketPosition: 'Market leader in gut health testing',
    },
    strategyType: 'product_innovation',
    expansionType: 'vertical',
    targetMarket: 'health_conscious_consumers',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Developed proprietary gut microbiome testing', impact: 'Unique product offering', difficulty: 'hard' },
      { action: 'Built AI-powered health recommendations', impact: 'Personalized value proposition', difficulty: 'hard' },
      { action: 'Direct-to-consumer model', impact: 'Scalable distribution', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Combining cutting-edge science with consumer-friendly products creates defensible market position.',
    sourceUrl: 'https://www.starterstory.com/stories/i-started-a-30m-year-gut-testing-company',
    sourcePlatform: 'starter_story',
    tags: ['healthcare', 'biotech', 'ai', 'dtc', 'gut_health'],
    matchingKeywords: ['healthcare', 'gut testing', 'microbiome', 'wellness'],
    confidenceLevel: 'high',
    summary: 'Momo Vuyisich built Viome to $30M+ annually by combining AI with gut microbiome testing.',
  },
  {
    companyName: 'Flo Health',
    industry: 'healthcare',
    subIndustry: 'womens_health',
    location: 'Belarus/USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Crowded app market', 'Sensitive health data', 'User trust'],
      capabilities: ['Mobile development', 'Health expertise'],
      marketPosition: 'New period tracking app',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '100_plus',
      revenueGrowth: '1000x+',
      achievements: ['Unicorn valuation', '$100M+ ARR', '300M+ downloads'],
      newCapabilities: ['AI health predictions', 'Content platform', 'Community features'],
      marketPosition: 'Global leader in women\'s health apps',
    },
    strategyType: 'platform_play',
    expansionType: 'horizontal',
    targetMarket: 'women_health',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Built comprehensive period tracking app', impact: 'Core user base', difficulty: 'moderate' },
      { action: 'Expanded to pregnancy and fertility', impact: 'Lifetime user value', difficulty: 'moderate' },
      { action: 'Added AI-powered health insights', impact: 'Premium differentiation', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'Two brothers built a billion-dollar women\'s health app by focusing on user trust and comprehensive health tracking.',
    sourceUrl: 'https://www.starterstory.com/flo-health-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['healthcare', 'mobile_app', 'womens_health', 'unicorn'],
    matchingKeywords: ['women health', 'period tracker', 'fertility', 'pregnancy'],
    confidenceLevel: 'high',
    summary: 'Dmitry Gurski and brother built Flo Health from startup to unicorn status with 300M+ downloads.',
  },
  {
    companyName: 'Kinetik',
    industry: 'healthcare',
    subIndustry: 'health_tech',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Healthcare complexity', 'Enterprise sales cycles', 'Regulatory compliance'],
      capabilities: ['Healthcare industry knowledge', 'Tech development'],
      marketPosition: 'New health-tech startup',
    },
    endingState: {
      revenue: '5m_10m',
      teamSize: '50_100',
      revenueGrowth: '50x+',
      achievements: ['$27M funding raised', '77 employees', 'Growing enterprise client base'],
      newCapabilities: ['Enterprise healthcare solutions', 'VC-backed growth'],
      marketPosition: 'Funded health-tech player',
    },
    strategyType: 'venture_backed',
    expansionType: 'vertical',
    targetMarket: 'healthcare_enterprises',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built health-tech platform', impact: 'Product-market fit', difficulty: 'hard' },
      { action: 'Raised $27M in funding', impact: 'Growth capital', difficulty: 'hard' },
      { action: 'Scaled team to 77 employees', impact: 'Execution capacity', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Building in healthcare requires patience but creates defensible moats.',
    sourceUrl: 'https://www.starterstory.com/stories/kinetik',
    sourcePlatform: 'starter_story',
    tags: ['healthcare', 'health_tech', 'venture_capital', 'b2b'],
    matchingKeywords: ['health tech', 'healthcare', 'startup', 'funding'],
    confidenceLevel: 'high',
    summary: 'Sufian Chowdhury built Kinetik health-tech startup and raised $27M in funding.',
  },
  {
    companyName: 'Doctrina',
    industry: 'healthcare',
    subIndustry: 'medical_education',
    location: 'Europe',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Medical content complexity', 'Professional audience', 'Content production'],
      capabilities: ['Healthcare knowledge', 'E-learning development'],
      marketPosition: 'New medical e-learning platform',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '6_10',
      revenueGrowth: '20x+',
      achievements: ['$90K/month revenue', 'Established medical education platform'],
      newCapabilities: ['Comprehensive medical courses', 'Professional certification'],
      marketPosition: 'Recognized healthcare e-learning provider',
    },
    strategyType: 'content_led_growth',
    expansionType: 'vertical',
    targetMarket: 'healthcare_professionals',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Created high-quality medical education content', impact: 'Expert positioning', difficulty: 'hard' },
      { action: 'Built e-learning platform', impact: 'Scalable delivery', difficulty: 'moderate' },
      { action: 'Targeted healthcare professionals', impact: 'Premium pricing', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Professional education in specialized fields commands premium pricing.',
    sourceUrl: 'https://www.starterstory.com/healthcare-elarning-platform',
    sourcePlatform: 'starter_story',
    tags: ['healthcare', 'education', 'e-learning', 'medical'],
    matchingKeywords: ['medical education', 'healthcare training', 'e-learning'],
    confidenceLevel: 'high',
    summary: 'Jure Pučko built Doctrina to $90K/month healthcare e-learning platform.',
  },

  // ========== CONSTRUCTION / HOME SERVICES ==========
  {
    companyName: 'Carolina Exteriors',
    industry: 'construction',
    subIndustry: 'exterior_remodeling',
    location: 'North Carolina, USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Capital constraints', 'Seasonal business', 'Competition'],
      capabilities: ['Remodeling skills', 'Sales ability'],
      marketPosition: 'Small local contractor',
    },
    endingState: {
      revenue: '5m_10m',
      teamSize: '26_50',
      revenueGrowth: '2500x+',
      achievements: ['$9M/year revenue', 'Regional market leader', 'Multi-crew operation'],
      newCapabilities: ['Large project management', 'Sales team', 'Marketing systems'],
      marketPosition: 'Leading exterior remodeling company in region',
    },
    strategyType: 'market_expansion',
    expansionType: 'geographic',
    targetMarket: 'homeowners',
    timeline: { totalMonths: 180 },
    keyActions: [
      { action: 'Started with $3,500 investment', impact: 'Low-risk launch', difficulty: 'easy' },
      { action: 'Built reputation for quality work', impact: 'Referral engine', difficulty: 'moderate' },
      { action: 'Scaled with systems and processes', impact: 'Consistent growth', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 2500 },
    lessonsLearned: 'Starting small in home services with quality focus creates long-term growth.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-exterior-remodelling-company',
    sourcePlatform: 'starter_story',
    tags: ['construction', 'home_services', 'remodeling', 'exterior'],
    matchingKeywords: ['exterior remodeling', 'home improvement', 'construction'],
    confidenceLevel: 'high',
    summary: 'Clifton Muckenfuss grew Carolina Exteriors from $3.5K to $9M/year.',
  },
  {
    companyName: 'MPC Builders',
    industry: 'construction',
    subIndustry: 'custom_home_building',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Capital intensive', 'Long project cycles', 'Subcontractor management'],
      capabilities: ['Construction expertise', 'Project management'],
      marketPosition: 'New home builder',
    },
    endingState: {
      revenue: '5m_10m',
      teamSize: '11_25',
      revenueGrowth: '100x+',
      achievements: ['$6M/year revenue', '$500K+/month', 'Custom home builder reputation'],
      newCapabilities: ['Multiple simultaneous projects', 'Design-build capability'],
      marketPosition: 'Premier custom home builder',
    },
    strategyType: 'premium_positioning',
    expansionType: 'vertical',
    targetMarket: 'luxury_homebuyers',
    timeline: { totalMonths: 120 },
    keyActions: [
      { action: 'Focused on custom high-end homes', impact: 'Premium margins', difficulty: 'hard' },
      { action: 'Built design-build capability', impact: 'Full-service offering', difficulty: 'moderate' },
      { action: 'Navigated material shortages', impact: 'Client trust', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Custom home building requires managing complexity but offers premium margins.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-building-company',
    sourcePlatform: 'starter_story',
    tags: ['construction', 'home_building', 'custom_homes', 'luxury'],
    matchingKeywords: ['home building', 'custom homes', 'construction', 'builder'],
    confidenceLevel: 'high',
    summary: 'Michael J Parnell built MPC Builders to $500K/month custom home building company.',
  },
  {
    companyName: 'Hometown Painting LLC',
    industry: 'home_services',
    subIndustry: 'painting',
    location: 'Oklahoma, USA',
    startingState: {
      revenue: 'zero',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Starting from zero', 'Competition', 'Seasonal demand'],
      capabilities: ['Painting skills', 'Customer service'],
      marketPosition: 'New painting company',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '2_5',
      revenueGrowth: 'startup_to_profit',
      achievements: ['$100K+ net profit/year', 'Husband & wife team success'],
      newCapabilities: ['Efficient operations', 'Repeat customer base'],
      marketPosition: 'Established local painting company',
    },
    strategyType: 'lifestyle_business',
    expansionType: 'local',
    targetMarket: 'homeowners',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Started painting business from scratch', impact: 'Zero to revenue', difficulty: 'moderate' },
      { action: 'Built reputation for quality', impact: 'Referrals', difficulty: 'moderate' },
      { action: 'Optimized as husband-wife team', impact: 'Low overhead', difficulty: 'easy' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'A couple can build a profitable painting business with quality work and good systems.',
    sourceUrl: 'https://www.starterstory.com/stories/hometown-painting-llc',
    sourcePlatform: 'starter_story',
    tags: ['home_services', 'painting', 'family_business', 'local'],
    matchingKeywords: ['painting', 'home services', 'small business'],
    confidenceLevel: 'high',
    summary: 'Matt Stone and wife built Hometown Painting to $100K+ net profit/year.',
  },

  // ========== EDUCATION / TUTORING ==========
  {
    companyName: 'Menking Tutoring',
    industry: 'education',
    subIndustry: 'tutoring',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Career transition', 'Building client base', 'Pricing expertise'],
      capabilities: ['Wall Street analytical skills', 'Teaching ability'],
      marketPosition: 'New tutoring service',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '6_10',
      revenueGrowth: '20x+',
      achievements: ['$500K/year revenue', '$41.7K/month', 'Premium tutoring brand'],
      newCapabilities: ['Tutor network', 'Premium test prep'],
      marketPosition: 'Premium tutoring service',
    },
    strategyType: 'premium_positioning',
    expansionType: 'service',
    targetMarket: 'affluent_families',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Leveraged Wall Street background for credibility', impact: 'Premium positioning', difficulty: 'easy' },
      { action: 'Built network of quality tutors', impact: 'Scalable delivery', difficulty: 'moderate' },
      { action: 'Focused on high-stakes test prep', impact: 'Premium pricing', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Elite professional backgrounds translate well to premium tutoring services.',
    sourceUrl: 'https://www.starterstory.com/menking-tutoring-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['education', 'tutoring', 'test_prep', 'premium'],
    matchingKeywords: ['tutoring', 'test prep', 'education', 'SAT', 'ACT'],
    confidenceLevel: 'high',
    summary: 'Steve Menking, former Wall Street trader, built $500K/year tutoring business.',
  },
  {
    companyName: 'Teacher Jade\'s Writing Academy',
    industry: 'education',
    subIndustry: 'online_courses',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Part-time commitment', 'Course creation', 'Marketing'],
      capabilities: ['Teaching expertise', 'Writing skills'],
      marketPosition: 'Part-time tutor',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: 'solo',
      revenueGrowth: '10x+',
      achievements: ['$120K/year from online courses', 'Thousands of students'],
      newCapabilities: ['Course creation', 'Online marketing', 'Passive income'],
      marketPosition: 'Established online writing educator',
    },
    strategyType: 'content_led_growth',
    expansionType: 'digital',
    targetMarket: 'students',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Transitioned from tutoring to courses', impact: 'Scalable income', difficulty: 'moderate' },
      { action: 'Created comprehensive writing curriculum', impact: 'Product value', difficulty: 'moderate' },
      { action: 'Built online audience', impact: 'Distribution channel', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Teachers can scale their expertise through online courses.',
    sourceUrl: 'https://www.starterstory.com/stories/teacher-jade-masterclass',
    sourcePlatform: 'starter_story',
    tags: ['education', 'online_courses', 'writing', 'passive_income'],
    matchingKeywords: ['online courses', 'writing', 'education', 'tutoring'],
    confidenceLevel: 'high',
    summary: 'Jade Weatherington went from part-time tutor to $120K/year selling online courses.',
  },
  {
    companyName: 'LanguaTalk',
    industry: 'education',
    subIndustry: 'language_learning',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['No coding skills', 'Marketplace chicken-egg', 'Competition from giants'],
      capabilities: ['Business acumen', 'Language learning passion'],
      marketPosition: 'New language tutoring platform',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '2_5',
      revenueGrowth: '30x+',
      achievements: ['$60K/month revenue', '1,500+ teachers', 'Built without coding'],
      newCapabilities: ['No-code platform', 'Teacher marketplace', 'Payment processing'],
      marketPosition: 'Growing language tutoring platform',
    },
    strategyType: 'marketplace',
    expansionType: 'platform',
    targetMarket: 'language_learners',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built platform with no-code tools', impact: 'Fast launch', difficulty: 'moderate' },
      { action: 'Recruited quality language tutors', impact: 'Supply side', difficulty: 'moderate' },
      { action: 'Focused on user experience', impact: 'Retention', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 30 },
    lessonsLearned: 'No-code tools enable non-technical founders to build marketplace businesses.',
    sourceUrl: 'https://www.starterstory.com/language-tutoring-online',
    sourcePlatform: 'starter_story',
    tags: ['education', 'language_learning', 'marketplace', 'no_code'],
    matchingKeywords: ['language learning', 'tutoring', 'marketplace', 'education'],
    confidenceLevel: 'high',
    summary: 'Alex Redfern built LanguaTalk to $60K/month with no coding skills.',
  },
  {
    companyName: 'SoFlo Tutors',
    industry: 'education',
    subIndustry: 'sat_prep',
    location: 'Florida, USA',
    startingState: {
      revenue: 'zero',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Still in college', 'Building credibility', 'Scaling time'],
      capabilities: ['High SAT scores', 'Teaching ability'],
      marketPosition: 'College student tutor',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '11_25',
      revenueGrowth: 'startup_to_profit',
      achievements: ['$15K/month revenue', 'Built while in college', 'Tutor network'],
      newCapabilities: ['Tutor recruitment', 'Sales process', 'Online delivery'],
      marketPosition: 'Growing SAT tutoring company',
    },
    strategyType: 'service_business',
    expansionType: 'team',
    targetMarket: 'high_school_students',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Started tutoring while in college', impact: 'Low-risk start', difficulty: 'easy' },
      { action: 'Built network of college tutors', impact: 'Scalable delivery', difficulty: 'moderate' },
      { action: 'Systematized sales and delivery', impact: 'Consistent growth', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'College students can build tutoring businesses leveraging their recent test success.',
    sourceUrl: 'https://www.starterstory.com/start-sat-tutoring-business',
    sourcePlatform: 'starter_story',
    tags: ['education', 'sat_prep', 'tutoring', 'college_entrepreneur'],
    matchingKeywords: ['SAT tutoring', 'test prep', 'education', 'tutoring'],
    confidenceLevel: 'high',
    summary: 'Adam Shlomi built SoFlo Tutors to $15K/month while still in college.',
  },

  // ========== FITNESS ==========
  {
    companyName: 'SWEAT',
    industry: 'fitness',
    subIndustry: 'fitness_app',
    location: 'Australia',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['App development', 'User acquisition', 'Fitness content creation'],
      capabilities: ['Personal training', 'Social media presence'],
      marketPosition: 'Instagram fitness influencer',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '100_plus',
      revenueGrowth: '1000x+',
      achievements: ['$400M exit', '$100M+ ARR', '$8.33M/month', 'Global fitness app'],
      newCapabilities: ['App platform', 'Multiple trainers', 'Global community'],
      marketPosition: 'Leading women\'s fitness app',
    },
    strategyType: 'influencer_to_business',
    expansionType: 'platform',
    targetMarket: 'women_fitness',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Built Instagram following with fitness content', impact: 'Massive audience', difficulty: 'hard' },
      { action: 'Created Bikini Body Guide ebook', impact: 'Product validation', difficulty: 'moderate' },
      { action: 'Launched SWEAT app', impact: 'Scalable platform', difficulty: 'hard' },
      { action: 'Sold to iFIT for $400M', impact: 'Massive exit', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'Influencers can build billion-dollar businesses by productizing their expertise.',
    sourceUrl: 'https://www.starterstory.com/sweat-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['fitness', 'mobile_app', 'influencer', 'exit'],
    matchingKeywords: ['fitness app', 'workout', 'women fitness', 'SWEAT'],
    confidenceLevel: 'high',
    summary: 'Kayla Itsines built SWEAT fitness app empire and sold for $400M.',
  },
  {
    companyName: 'Gymdesk',
    industry: 'fitness',
    subIndustry: 'gym_software',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Bootstrapping', 'Competitive market', 'Sales cycles'],
      capabilities: ['Software development', 'Gym industry knowledge'],
      marketPosition: 'New gym management software',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '6_10',
      revenueGrowth: '50x+',
      achievements: ['$32.5M exit', 'Bootstrapped success', 'Thousands of gym customers'],
      newCapabilities: ['Full gym management suite', 'Payment processing', 'Member management'],
      marketPosition: 'Leading gym management solution',
    },
    strategyType: 'bootstrap_to_exit',
    expansionType: 'vertical',
    targetMarket: 'gym_owners',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Built comprehensive gym management software', impact: 'Product-market fit', difficulty: 'hard' },
      { action: 'Bootstrapped entire journey', impact: 'Full ownership', difficulty: 'hard' },
      { action: 'Sold for $32.5M', impact: 'Successful exit', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Bootstrapping B2B SaaS can lead to significant exits without raising capital.',
    sourceUrl: 'https://www.starterstory.com/gymdesk-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['fitness', 'saas', 'gym_software', 'bootstrap', 'exit'],
    matchingKeywords: ['gym software', 'gym management', 'fitness SaaS'],
    confidenceLevel: 'high',
    summary: 'Eran Galperin bootstrapped Gymdesk gym management software to $32.5M exit.',
  },
  {
    companyName: 'Gym Streak',
    industry: 'fitness',
    subIndustry: 'fitness_app',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Solo development', 'App store competition', 'User acquisition'],
      capabilities: ['iOS development', 'Fitness knowledge'],
      marketPosition: 'New workout tracking app',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: 'solo',
      revenueGrowth: '100x+',
      achievements: ['$2.5M annually', '$208K/month', 'Solo founder success'],
      newCapabilities: ['AI workout planning', 'Subscription model'],
      marketPosition: 'Top workout tracking app',
    },
    strategyType: 'product_led_growth',
    expansionType: 'digital',
    targetMarket: 'gym_goers',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Built AI-powered workout app', impact: 'Unique value prop', difficulty: 'hard' },
      { action: 'Focused on App Store optimization', impact: 'Organic discovery', difficulty: 'moderate' },
      { action: 'Maintained as solo founder', impact: 'Maximum margins', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Solo founders can build multi-million dollar apps with focus and persistence.',
    sourceUrl: 'https://www.starterstory.com/gym-streak-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['fitness', 'mobile_app', 'solo_founder', 'ai'],
    matchingKeywords: ['fitness app', 'workout tracker', 'gym app'],
    confidenceLevel: 'high',
    summary: 'Joseph Mambwe bootstrapped Gym Streak fitness app to $2.5M annually as solo founder.',
  },
  {
    companyName: 'GymBros',
    industry: 'fitness',
    subIndustry: 'fitness_app',
    location: 'USA',
    startingState: {
      revenue: 'zero',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['New to market', 'User acquisition', 'Competition'],
      capabilities: ['App development', 'Social media savvy'],
      marketPosition: 'New gym social app',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '2_5',
      revenueGrowth: 'startup_to_$19k_mrr',
      achievements: ['$19K MRR in months', 'TikTok viral growth'],
      newCapabilities: ['Viral marketing', 'Community building'],
      marketPosition: 'Growing gym social app',
    },
    strategyType: 'viral_growth',
    expansionType: 'social',
    targetMarket: 'young_gym_goers',
    timeline: { totalMonths: 12 },
    keyActions: [
      { action: 'Built gym social networking app', impact: 'Unique positioning', difficulty: 'moderate' },
      { action: 'Leveraged TikTok for viral growth', impact: 'Rapid user acquisition', difficulty: 'moderate' },
      { action: 'Focused on Gen Z gym culture', impact: 'Target market fit', difficulty: 'easy' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'TikTok can drive rapid growth for apps targeting younger demographics.',
    sourceUrl: 'https://www.starterstory.com/gym-bros-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['fitness', 'mobile_app', 'tiktok', 'social'],
    matchingKeywords: ['gym app', 'fitness social', 'workout buddies'],
    confidenceLevel: 'high',
    summary: 'GymBros leveraged TikTok to achieve $19K MRR in months.',
  },
  {
    companyName: 'Bells of Steel',
    industry: 'ecommerce',
    subIndustry: 'fitness_equipment',
    location: 'Canada',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Capital for inventory', 'Shipping logistics', 'Competition'],
      capabilities: ['Gym enthusiast', 'Ecommerce knowledge'],
      marketPosition: 'New fitness equipment seller',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '26_50',
      revenueGrowth: '500x+',
      achievements: ['$15M/year revenue', 'Major fitness equipment brand'],
      newCapabilities: ['Product development', 'Supply chain', 'Direct-to-consumer'],
      marketPosition: 'Leading home gym equipment brand',
    },
    strategyType: 'ecommerce_brand',
    expansionType: 'product',
    targetMarket: 'home_gym_owners',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Started selling fitness equipment online', impact: 'Market entry', difficulty: 'moderate' },
      { action: 'Developed own product line', impact: 'Better margins', difficulty: 'hard' },
      { action: 'Built direct-to-consumer brand', impact: 'Customer relationships', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 500 },
    lessonsLearned: 'Passion for fitness can translate into major ecommerce success.',
    sourceUrl: 'https://www.starterstory.com/stories/being-a-gym-freak-led-me-to-start-a-15m-year-fitness-equipment-e-commerce',
    sourcePlatform: 'starter_story',
    tags: ['ecommerce', 'fitness_equipment', 'dtc', 'home_gym'],
    matchingKeywords: ['fitness equipment', 'home gym', 'weights', 'ecommerce'],
    confidenceLevel: 'high',
    summary: 'Kaevon Khoozani turned gym passion into $15M/year fitness equipment ecommerce.',
  },

  // ========== LEGAL ==========
  {
    companyName: 'Attorney Brian White Personal Injury Lawyers',
    industry: 'legal',
    subIndustry: 'personal_injury',
    location: 'Texas, USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Building reputation', 'Marketing', 'Case acquisition'],
      capabilities: ['Legal expertise', 'Trial experience'],
      marketPosition: 'New personal injury attorney',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '50_100',
      revenueGrowth: '1000x+',
      achievements: ['$5M/month revenue', 'Major regional law firm'],
      newCapabilities: ['Marketing machine', 'Large legal team', 'Multi-office'],
      marketPosition: 'Leading personal injury firm in Texas',
    },
    strategyType: 'market_domination',
    expansionType: 'geographic',
    targetMarket: 'accident_victims',
    timeline: { totalMonths: 180 },
    keyActions: [
      { action: 'Focused exclusively on personal injury', impact: 'Specialization', difficulty: 'moderate' },
      { action: 'Invested heavily in marketing', impact: 'Case volume', difficulty: 'hard' },
      { action: 'Built large legal team', impact: 'Capacity', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'Personal injury law can scale massively with marketing and team building.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-law-firm-personal-injury-cases',
    sourcePlatform: 'starter_story',
    tags: ['legal', 'personal_injury', 'law_firm'],
    matchingKeywords: ['personal injury', 'law firm', 'attorney', 'legal'],
    confidenceLevel: 'high',
    summary: 'Brian White built personal injury law firm to $5M/month revenue.',
  },
  {
    companyName: 'Document Crunch',
    industry: 'legal_tech',
    subIndustry: 'legal_automation',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Legal industry conservatism', 'Product development', 'Enterprise sales'],
      capabilities: ['Legal expertise', 'Tech development'],
      marketPosition: 'New legal tech startup',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '50_100',
      revenueGrowth: '50x+',
      achievements: ['$4.5M ARR', '$375K/month', '55 employees'],
      newCapabilities: ['AI document analysis', 'Enterprise contracts'],
      marketPosition: 'Growing legal tech player',
    },
    strategyType: 'b2b_saas',
    expansionType: 'vertical',
    targetMarket: 'construction_legal',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built AI-powered legal document analysis', impact: 'Unique technology', difficulty: 'hard' },
      { action: 'Focused on construction industry', impact: 'Niche domination', difficulty: 'moderate' },
      { action: 'Scaled enterprise sales', impact: 'Revenue growth', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Legal tech can succeed by focusing on specific industry verticals.',
    sourceUrl: 'https://www.starterstory.com/document-crunch-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['legal_tech', 'saas', 'ai', 'construction'],
    matchingKeywords: ['legal tech', 'document analysis', 'AI legal'],
    confidenceLevel: 'high',
    summary: 'Josh Levy built Document Crunch legal tech to $4.5M ARR.',
  },
  {
    companyName: 'SeedLegals',
    industry: 'legal_tech',
    subIndustry: 'startup_legal',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Complex legal processes', 'Lawyer resistance', 'User trust'],
      capabilities: ['Tech development', 'Legal knowledge'],
      marketPosition: 'New startup legal automation',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '26_50',
      revenueGrowth: '40x+',
      achievements: ['$375K/month revenue', '40 employees', 'Leading UK startup legal platform'],
      newCapabilities: ['Automated legal documents', 'Funding round management'],
      marketPosition: 'Go-to platform for UK startup legals',
    },
    strategyType: 'platform_play',
    expansionType: 'product',
    targetMarket: 'startups',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Automated startup legal documents', impact: 'Time and cost savings', difficulty: 'hard' },
      { action: 'Built funding round management', impact: 'End-to-end solution', difficulty: 'hard' },
      { action: 'Became UK startup ecosystem staple', impact: 'Network effects', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 40 },
    lessonsLearned: 'Automating complex legal processes creates massive value for startups.',
    sourceUrl: 'https://www.starterstory.com/automated-startup-legals',
    sourcePlatform: 'starter_story',
    tags: ['legal_tech', 'startups', 'automation', 'uk'],
    matchingKeywords: ['startup legal', 'legal automation', 'funding', 'UK'],
    confidenceLevel: 'high',
    summary: 'Anthony Rose built SeedLegals to $375K/month automating startup legals.',
  },
  {
    companyName: 'ZenBusiness',
    industry: 'legal_services',
    subIndustry: 'business_formation',
    location: 'Texas, USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Competing with LegalZoom', 'Customer acquisition', 'Service delivery'],
      capabilities: ['Tech background', 'Customer service focus'],
      marketPosition: 'New business formation service',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '100_plus',
      revenueGrowth: '1000x+',
      achievements: ['$80M ARR', 'Skyrocketed growth in 4 years', 'Major LegalZoom competitor'],
      newCapabilities: ['Full business services platform', 'Registered agent', 'Compliance'],
      marketPosition: 'Leading business formation platform',
    },
    strategyType: 'platform_play',
    expansionType: 'horizontal',
    targetMarket: 'entrepreneurs',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built superior business formation experience', impact: 'Customer love', difficulty: 'moderate' },
      { action: 'Focused on customer service', impact: 'NPS and retention', difficulty: 'moderate' },
      { action: 'Expanded to full business services', impact: 'Lifetime value', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'Better customer experience can disrupt established players like LegalZoom.',
    sourceUrl: 'https://www.starterstory.com/zenbusiness-pbc-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['legal_services', 'business_formation', 'platform'],
    matchingKeywords: ['LLC formation', 'business formation', 'ZenBusiness'],
    confidenceLevel: 'high',
    summary: 'Ross Buhrdorf skyrocketed ZenBusiness from startup to $80M ARR in 4 years.',
  },
  {
    companyName: 'Albers & Associates',
    industry: 'legal',
    subIndustry: 'law_firm',
    location: 'Maryland, USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Building practice', 'Client acquisition', 'Reputation'],
      capabilities: ['Legal expertise', 'Entrepreneurial drive'],
      marketPosition: 'New law firm',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '11_25',
      revenueGrowth: '20x+',
      achievements: ['$150K/month revenue', 'Growing law firm'],
      newCapabilities: ['Multiple practice areas', 'Associate attorneys'],
      marketPosition: 'Established regional law firm',
    },
    strategyType: 'professional_services',
    expansionType: 'team',
    targetMarket: 'individuals_businesses',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Started solo law practice', impact: 'Initial clients', difficulty: 'moderate' },
      { action: 'Built team of attorneys', impact: 'Capacity', difficulty: 'moderate' },
      { action: 'Expanded practice areas', impact: 'Client base', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Law firms can grow significantly with team building and marketing.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-law-firm',
    sourcePlatform: 'starter_story',
    tags: ['legal', 'law_firm', 'professional_services'],
    matchingKeywords: ['law firm', 'attorney', 'legal services'],
    confidenceLevel: 'high',
    summary: 'Ross Albers built Albers & Associates law firm to $150K/month.',
  },

  // ========== ACCOUNTING / FINANCIAL ==========
  {
    companyName: 'SoftLedger',
    industry: 'saas',
    subIndustry: 'accounting_software',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Competing with QuickBooks', 'Enterprise features', 'Sales cycles'],
      capabilities: ['Accounting expertise', 'Software development'],
      marketPosition: 'New cloud accounting software',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '6_10',
      revenueGrowth: '10x+',
      achievements: ['10x growth', 'Growing enterprise client base'],
      newCapabilities: ['Multi-entity accounting', 'API-first platform'],
      marketPosition: 'Growing cloud accounting platform',
    },
    strategyType: 'b2b_saas',
    expansionType: 'product',
    targetMarket: 'mid_market_businesses',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Built modern cloud accounting platform', impact: 'Technical differentiation', difficulty: 'hard' },
      { action: 'Focused on multi-entity accounting', impact: 'Enterprise niche', difficulty: 'hard' },
      { action: 'API-first approach', impact: 'Integration value', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Modern cloud-native approach can compete with established accounting software.',
    sourceUrl: 'https://www.starterstory.com/softledger-com-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'accounting', 'fintech', 'b2b'],
    matchingKeywords: ['accounting software', 'cloud accounting', 'financial software'],
    confidenceLevel: 'high',
    summary: 'Ben Taylor built SoftLedger cloud accounting to 10x growth.',
  },
  {
    companyName: 'Free Cash Flow',
    industry: 'services',
    subIndustry: 'accounting_services',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Niche market', 'Unique client needs', 'Service delivery'],
      capabilities: ['Accounting expertise', 'Creator economy knowledge'],
      marketPosition: 'New niche accounting service',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '2_5',
      revenueGrowth: '10x+',
      achievements: ['$300K/year revenue', 'Trusted by major YouTubers'],
      newCapabilities: ['Creator-specific accounting', 'Tax optimization'],
      marketPosition: 'Go-to accountant for content creators',
    },
    strategyType: 'niche_specialization',
    expansionType: 'service',
    targetMarket: 'content_creators',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Specialized in YouTuber/creator accounting', impact: 'Niche expertise', difficulty: 'moderate' },
      { action: 'Built relationships with major creators', impact: 'Referrals', difficulty: 'moderate' },
      { action: 'Developed creator-specific services', impact: 'Unique value', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Specializing in underserved niches like content creators creates loyal clients.',
    sourceUrl: 'https://www.starterstory.com/stories/free-cash-flow',
    sourcePlatform: 'starter_story',
    tags: ['accounting', 'creators', 'youtube', 'niche'],
    matchingKeywords: ['accounting', 'YouTubers', 'content creators', 'taxes'],
    confidenceLevel: 'high',
    summary: 'Free Cash Flow built $300K/year accounting business serving YouTubers and content creators.',
  },
  {
    companyName: 'Keap',
    industry: 'saas',
    subIndustry: 'crm_marketing',
    location: 'Arizona, USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Bootstrapping', 'Product development', 'Market education'],
      capabilities: ['Software development', 'Small business knowledge'],
      marketPosition: 'Garage startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '100_plus',
      revenueGrowth: '1000x+',
      achievements: ['$90M revenue', '323 employees', 'Major CRM/marketing platform'],
      newCapabilities: ['Full CRM suite', 'Marketing automation', 'Payment processing'],
      marketPosition: 'Leading small business CRM',
    },
    strategyType: 'bootstrap_to_scale',
    expansionType: 'platform',
    targetMarket: 'small_businesses',
    timeline: { totalMonths: 288 },
    keyActions: [
      { action: 'Started in garage with simple CRM', impact: 'Product foundation', difficulty: 'hard' },
      { action: 'Built marketing automation features', impact: 'Differentiation', difficulty: 'hard' },
      { action: 'Scaled to enterprise-grade platform', impact: 'Market leadership', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'Garage startups can become industry leaders with persistence and customer focus.',
    sourceUrl: 'https://www.starterstory.com/keap-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'crm', 'marketing_automation', 'small_business'],
    matchingKeywords: ['CRM', 'marketing automation', 'small business', 'Infusionsoft'],
    confidenceLevel: 'high',
    summary: 'Scott Martineau grew Keap (formerly Infusionsoft) from garage startup to $90M revenue.',
  },

  // ========== APP DEVELOPMENT ==========
  {
    companyName: 'Appetiser',
    industry: 'services',
    subIndustry: 'app_development',
    location: 'Australia',
    startingState: {
      revenue: 'zero',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['No capital', 'Building team', 'Client acquisition'],
      capabilities: ['App development', 'Business development'],
      marketPosition: 'New app agency',
    },
    endingState: {
      revenue: '5m_10m',
      teamSize: '50_100',
      revenueGrowth: '1000x+',
      achievements: ['$8.4M/year revenue', 'Started with $0', 'Major app development agency'],
      newCapabilities: ['Full-service app development', 'Global client base'],
      marketPosition: 'Leading app development agency',
    },
    strategyType: 'service_business',
    expansionType: 'team',
    targetMarket: 'startups_enterprises',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Started app agency with no capital', impact: 'Bootstrap success', difficulty: 'hard' },
      { action: 'Built high-quality development team', impact: 'Delivery capability', difficulty: 'hard' },
      { action: 'Scaled to major agency', impact: 'Market presence', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'App development agencies can scale significantly with quality focus.',
    sourceUrl: 'https://www.starterstory.com/stories/we-started-an-8-4m-year-app-development-agency-with-0',
    sourcePlatform: 'starter_story',
    tags: ['app_development', 'agency', 'mobile', 'bootstrap'],
    matchingKeywords: ['app development', 'mobile agency', 'iOS', 'Android'],
    confidenceLevel: 'high',
    summary: 'Appetiser built $8.4M/year app development agency starting with $0.',
  },
  {
    companyName: 'The Jed Mahonis Group',
    industry: 'services',
    subIndustry: 'app_development',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Client acquisition', 'Project management', 'Scaling'],
      capabilities: ['iOS/Android development', 'Design'],
      marketPosition: 'Freelance app developer',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '6_10',
      revenueGrowth: '20x+',
      achievements: ['$82K/month revenue', 'Custom iOS/Android agency'],
      newCapabilities: ['Full-service development', 'Team delivery'],
      marketPosition: 'Established app development agency',
    },
    strategyType: 'service_business',
    expansionType: 'team',
    targetMarket: 'businesses',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Started as freelance developer', impact: 'Initial revenue', difficulty: 'moderate' },
      { action: 'Built development team', impact: 'Capacity', difficulty: 'moderate' },
      { action: 'Systematized delivery', impact: 'Consistency', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Freelancers can grow into agencies with team building and systems.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-ios-androind-app-development-agency',
    sourcePlatform: 'starter_story',
    tags: ['app_development', 'agency', 'ios', 'android'],
    matchingKeywords: ['iOS development', 'Android development', 'mobile agency'],
    confidenceLevel: 'high',
    summary: 'Rob Bentley built The Jed Mahonis Group to $82K/month custom app agency.',
  },
  {
    companyName: 'Wolfpack Digital',
    industry: 'services',
    subIndustry: 'app_development',
    location: 'Romania',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Remote team building', 'Client acquisition', 'Quality control'],
      capabilities: ['Web/mobile development', 'Design'],
      marketPosition: 'New development agency',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '50_100',
      revenueGrowth: '50x+',
      achievements: ['80 person team', 'International client base', 'Multiple platforms'],
      newCapabilities: ['Full-service digital agency', 'Own product development'],
      marketPosition: 'Leading Eastern European digital agency',
    },
    strategyType: 'service_business',
    expansionType: 'team',
    targetMarket: 'global_businesses',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Built team in Romania', impact: 'Cost advantage', difficulty: 'moderate' },
      { action: 'Acquired international clients', impact: 'Revenue growth', difficulty: 'hard' },
      { action: 'Developed own platform', impact: 'Productization', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Eastern European agencies can compete globally with quality and value.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-web-app-development-company',
    sourcePlatform: 'starter_story',
    tags: ['app_development', 'agency', 'romania', 'digital'],
    matchingKeywords: ['web development', 'app development', 'digital agency'],
    confidenceLevel: 'high',
    summary: 'Georgina Lupu Florian grew Wolfpack Digital to 80-person team.',
  },
  {
    companyName: 'Locket',
    industry: 'consumer_app',
    subIndustry: 'social_app',
    location: 'USA',
    startingState: {
      revenue: 'zero',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Solo development', 'Viral growth', 'Retention'],
      capabilities: ['iOS development', 'Product sense'],
      marketPosition: 'Unknown indie developer',
    },
    endingState: {
      revenue: '5m_10m',
      teamSize: '6_10',
      revenueGrowth: 'viral',
      achievements: ['50M+ signups', 'Built in 14 days', 'Viral app success'],
      newCapabilities: ['Viral product development', 'Rapid scaling'],
      marketPosition: 'Top social app',
    },
    strategyType: 'viral_growth',
    expansionType: 'organic',
    targetMarket: 'gen_z',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built widget app in 14 days', impact: 'Fast launch', difficulty: 'moderate' },
      { action: 'Created viral photo sharing mechanic', impact: 'Word of mouth', difficulty: 'moderate' },
      { action: 'Scaled rapidly to 50M users', impact: 'Massive growth', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'Simple, focused apps can go viral with the right mechanic.',
    sourceUrl: 'https://www.starterstory.com/locket-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['consumer_app', 'social', 'viral', 'widget'],
    matchingKeywords: ['photo sharing', 'widget', 'social app', 'viral'],
    confidenceLevel: 'high',
    summary: 'Matt Moss built Locket in 14 days and reached 50M signups.',
  },
  {
    companyName: 'LowCode Agency',
    industry: 'services',
    subIndustry: 'no_code_development',
    location: 'Latin America',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['New market category', 'Client education', 'Tool limitations'],
      capabilities: ['No-code tools expertise', 'Business development'],
      marketPosition: 'New no-code agency',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '2_5',
      revenueGrowth: '10x+',
      achievements: ['$10K/month revenue', 'Pioneer in no-code agencies'],
      newCapabilities: ['No-code app development', 'Client training'],
      marketPosition: 'Established no-code agency',
    },
    strategyType: 'emerging_tech',
    expansionType: 'service',
    targetMarket: 'startups_smbs',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Mastered no-code tools', impact: 'Technical capability', difficulty: 'moderate' },
      { action: 'Educated market on no-code benefits', impact: 'Demand creation', difficulty: 'moderate' },
      { action: 'Delivered apps faster and cheaper', impact: 'Value proposition', difficulty: 'easy' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'No-code tools enable new agency models with faster delivery.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-app-building-agency-using-no-code-tools',
    sourcePlatform: 'starter_story',
    tags: ['no_code', 'agency', 'app_development'],
    matchingKeywords: ['no-code', 'low-code', 'app builder', 'agency'],
    confidenceLevel: 'high',
    summary: 'Jesus Vargas built $10K/month app agency using no/low-code tools.',
  },

  // ========== CLEANING SERVICES ==========
  {
    companyName: 'CleanLots',
    industry: 'services',
    subIndustry: 'commercial_cleaning',
    location: 'USA/Canada',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Night work', 'Scaling', 'Route optimization'],
      capabilities: ['Work ethic', 'Business development'],
      marketPosition: 'Solo litter cleaner',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '2_5',
      revenueGrowth: '20x+',
      achievements: ['$40-60K/month revenue', 'Book on business model', 'Franchise-ready'],
      newCapabilities: ['Route optimization', 'Training systems', 'Recurring contracts'],
      marketPosition: 'Leading commercial litter cleaning service',
    },
    strategyType: 'niche_service',
    expansionType: 'geographic',
    targetMarket: 'commercial_properties',
    timeline: { totalMonths: 360 },
    keyActions: [
      { action: 'Started cleaning parking lots at night', impact: 'Low-competition niche', difficulty: 'easy' },
      { action: 'Built recurring contract base', impact: 'Stable revenue', difficulty: 'moderate' },
      { action: 'Created training and systems', impact: 'Scalability', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Simple services like litter cleaning can build significant businesses with persistence.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-cleaning-service',
    sourcePlatform: 'starter_story',
    tags: ['cleaning', 'commercial', 'service_business', 'recurring'],
    matchingKeywords: ['commercial cleaning', 'parking lot cleaning', 'litter'],
    confidenceLevel: 'high',
    summary: 'Brian Winch built CleanLots to $40-60K/month commercial litter cleaning service.',
  },
  {
    companyName: 'MaidThis Franchise',
    industry: 'services',
    subIndustry: 'home_cleaning',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Staffing', 'Quality control', 'Scheduling'],
      capabilities: ['Business development', 'Operations'],
      marketPosition: 'New cleaning service',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '26_50',
      revenueGrowth: '20x+',
      achievements: ['$100K+/month revenue', 'Franchise model', 'Airbnb specialty'],
      newCapabilities: ['Franchise system', 'Airbnb partnerships', 'Technology platform'],
      marketPosition: 'Leading Airbnb cleaning franchise',
    },
    strategyType: 'franchise',
    expansionType: 'geographic',
    targetMarket: 'airbnb_hosts',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Started home cleaning for Airbnb hosts', impact: 'Niche focus', difficulty: 'moderate' },
      { action: 'Built technology and systems', impact: 'Scalability', difficulty: 'hard' },
      { action: 'Launched franchise model', impact: 'Rapid expansion', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Airbnb cleaning is a growing niche that supports franchise expansion.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-cleaning-service-for-airbnb',
    sourcePlatform: 'starter_story',
    tags: ['cleaning', 'franchise', 'airbnb', 'home_services'],
    matchingKeywords: ['Airbnb cleaning', 'vacation rental cleaning', 'maid service'],
    confidenceLevel: 'high',
    summary: 'Neel Parekh built MaidThis to $100K+/month serving Airbnb hosts.',
  },
];

async function seedBatch3() {
  console.log('Seeding case studies batch 3...');
  console.log(`Total case studies to seed: ${batch3CaseStudies.length}`);

  let successCount = 0;
  let errorCount = 0;

  for (const cs of batch3CaseStudies) {
    try {
      await db.insert(caseStudies).values({
        ...cs,
        startingState: cs.startingState,
        endingState: cs.endingState,
        timeline: cs.timeline,
        keyActions: cs.keyActions as KeyAction[],
        outcomes: cs.outcomes,
        pitfalls: [],
      });
      console.log(`✓ Seeded: ${cs.companyName}`);
      successCount++;
    } catch (error: unknown) {
      const err = error as Error;
      console.error(`✗ Error seeding ${cs.companyName}:`, err.message);
      errorCount++;
    }
  }

  console.log(`\nBatch 3 seeding complete!`);
  console.log(`✓ Successfully seeded: ${successCount}`);
  console.log(`✗ Errors: ${errorCount}`);
  process.exit(0);
}

seedBatch3().catch((e) => {
  console.error('Seed failed:', e);
  process.exit(1);
});
