import { db } from '../../lib/db';
import { caseStudies } from '../schema';

type CaseStudyInsert = typeof caseStudies.$inferInsert;

const batch5CaseStudies = [
  // MANUFACTURING
  {
    companyName: 'Bryden Apparel',
    industry: 'manufacturing',
    subIndustry: 'clothing_manufacturing',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Finding manufacturing partners', 'Building brand trust', 'Quality control'],
      capabilities: ['Industry experience', 'Design skills'],
      marketPosition: 'New clothing manufacturer',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '2_5',
      revenueGrowth: '10x+',
      achievements: ['$74K monthly revenue', 'Established B2B client base', 'Streamlined production'],
      newCapabilities: ['Low MOQ production', 'Quality control systems'],
      marketPosition: 'Startup-focused clothing manufacturer',
    },
    strategyType: 'niche_focus',
    expansionType: 'vertical',
    targetMarket: 'startup_brands',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Focused on low MOQ for startups', impact: 'Attracted emerging brand clientele', difficulty: 'moderate' },
      { action: 'Built quality control processes', impact: 'Reduced defect rates', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Structure payment terms carefully to manage cash flow with production lead times.',
    sourceUrl: 'https://www.starterstory.com/stories/how-we-started-a-clothing-manufacturing-business',
    sourcePlatform: 'starter_story',
    tags: ['manufacturing', 'apparel', 'b2b', 'startup_focused'],
    matchingKeywords: ['clothing manufacturing', 'apparel', 'fashion production'],
    confidenceLevel: 'high',
    summary: 'Started a clothing manufacturing business serving startups with low minimum order quantities.',
  },
  {
    companyName: 'Hawthorn',
    industry: 'manufacturing',
    subIndustry: 'clothing_manufacturing',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Competing with overseas manufacturers', 'Building local supply chain'],
      capabilities: ['Fashion industry experience', 'UK manufacturing connections'],
      marketPosition: 'New UK clothing manufacturer',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '11_25',
      revenueGrowth: '10x+',
      achievements: ['$50K monthly revenue', 'Lowest MOQ in industry', 'UK manufacturing leader'],
      newCapabilities: ['50-piece minimum orders', 'Menswear specialization'],
      marketPosition: 'Leading UK startup clothing manufacturer',
    },
    strategyType: 'niche_focus',
    expansionType: 'vertical',
    targetMarket: 'startup_brands',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Offered 50-piece minimums', impact: 'Opened market to startups', difficulty: 'hard' },
      { action: 'Specialized in menswear', impact: 'Built expertise and reputation', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Compete on value, not price when facing overseas competition.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-clothing-manufacturing-business',
    sourcePlatform: 'starter_story',
    tags: ['manufacturing', 'apparel', 'uk', 'menswear'],
    matchingKeywords: ['clothing manufacturing', 'UK manufacturer', 'menswear'],
    confidenceLevel: 'high',
    summary: 'UK-based clothing manufacturer with industry-lowest minimum order quantities from 50 pieces.',
  },
  {
    companyName: 'FUSH Ltd',
    industry: 'manufacturing',
    subIndustry: 'sustainable_manufacturing',
    location: 'Serbia',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Building sustainable supply chain', 'Competing globally from Serbia'],
      capabilities: ['Manufacturing expertise', 'Local workforce'],
      marketPosition: 'New eco-conscious manufacturer',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '100_plus',
      revenueGrowth: '100x+',
      achievements: ['$284K monthly revenue', '170 employees', 'Eco-conscious certification'],
      newCapabilities: ['Sustainable production', 'International clients'],
      marketPosition: 'Leading eco-conscious clothing manufacturer',
    },
    strategyType: 'differentiation',
    expansionType: 'vertical',
    targetMarket: 'eco_conscious_brands',
    timeline: { totalMonths: 216 },
    keyActions: [
      { action: 'Invested in sustainable practices', impact: 'Attracted eco-conscious brands', difficulty: 'hard' },
      { action: 'Built skilled workforce in Serbia', impact: 'Competitive costs with quality', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Sustainable practices attract premium clients willing to pay more.',
    sourceUrl: 'https://www.starterstory.com/stories/fush-ltd',
    sourcePlatform: 'starter_story',
    tags: ['manufacturing', 'sustainable', 'eco_friendly', 'apparel'],
    matchingKeywords: ['eco manufacturing', 'sustainable fashion', 'green production'],
    confidenceLevel: 'high',
    summary: 'Built a $284K/month eco-conscious clothing manufacturer from Belgrade, Serbia.',
  },
  {
    companyName: 'American Bench Craft',
    industry: 'manufacturing',
    subIndustry: 'leather_goods',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Learning leather crafting', 'No manufacturing space'],
      capabilities: ['Garage workspace', 'Family support'],
      marketPosition: 'Garage leather startup',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '11_25',
      revenueGrowth: '20x+',
      achievements: ['$1.2M annual revenue', 'Made in USA brand', 'Wholesale partnerships'],
      newCapabilities: ['100+ product line', 'Proper manufacturing facility'],
      marketPosition: 'Established American leather goods maker',
    },
    strategyType: 'bootstrap_growth',
    expansionType: 'horizontal',
    targetMarket: 'american_made_consumers',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Started from garage', impact: 'Minimal overhead to learn and iterate', difficulty: 'moderate' },
      { action: 'Emphasized Made in USA', impact: 'Built brand differentiation', difficulty: 'easy' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Start scrappy, upgrade when ready. Reinvest profits into proper facility.',
    sourceUrl: 'https://www.starterstory.com/stories/american-bench-craft',
    sourcePlatform: 'starter_story',
    tags: ['manufacturing', 'leather', 'made_in_usa', 'craftsmanship'],
    matchingKeywords: ['leather goods', 'American made', 'craftsmanship'],
    confidenceLevel: 'high',
    summary: 'Started leather manufacturing from parents garage, grew to $1.2M/year.',
  },
  {
    companyName: 'STOCK MFG Co',
    industry: 'manufacturing',
    subIndustry: 'uniform_manufacturing',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Custom production complexity', 'Building hospitality relationships'],
      capabilities: ['Fashion industry background', 'Chicago location'],
      marketPosition: 'New uniform manufacturer',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '11_25',
      revenueGrowth: '50x+',
      achievements: ['$300K monthly revenue', 'Major hospitality clients', 'Custom design capability'],
      newCapabilities: ['Full custom design services', 'Hospitality industry expertise'],
      marketPosition: 'Leading custom uniform manufacturer',
    },
    strategyType: 'niche_focus',
    expansionType: 'vertical',
    targetMarket: 'hospitality_industry',
    timeline: { totalMonths: 144 },
    keyActions: [
      { action: 'Specialized in hospitality uniforms', impact: 'Built niche expertise', difficulty: 'moderate' },
      { action: 'Offered custom design services', impact: 'Increased order values', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Custom work requires robust systems. Build streamlined design-to-production process.',
    sourceUrl: 'https://www.starterstory.com/stories/stock-mfg-co',
    sourcePlatform: 'starter_story',
    tags: ['manufacturing', 'uniforms', 'hospitality', 'custom'],
    matchingKeywords: ['uniform manufacturing', 'hospitality', 'custom uniforms'],
    confidenceLevel: 'high',
    summary: 'Built a $3.4M/year custom uniforms manufacturing business for hospitality.',
  },
  {
    companyName: 'KO-Pack',
    industry: 'manufacturing',
    subIndustry: 'contract_manufacturing',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Building manufacturing facility', 'FDA compliance'],
      capabilities: ['Industry experience', 'Team of 5 founders'],
      marketPosition: 'New copacking business',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '11_25',
      revenueGrowth: '30x+',
      achievements: ['$250K monthly revenue', 'FDA compliant facility', 'Major CPG partnerships'],
      newCapabilities: ['End-to-end copacking', 'Certification compliance'],
      marketPosition: 'Trusted CPG manufacturing partner',
    },
    strategyType: 'service_excellence',
    expansionType: 'vertical',
    targetMarket: 'cpg_brands',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Invested in FDA compliance early', impact: 'Attracted quality-conscious brands', difficulty: 'hard' },
      { action: 'Offered end-to-end copacking', impact: 'Became one-stop solution for CPG', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 30 },
    lessonsLearned: 'Match capacity to actual demand. Phased expansion based on demand works.',
    sourceUrl: 'https://www.starterstory.com/stories/ko-pack',
    sourcePlatform: 'starter_story',
    tags: ['manufacturing', 'copacking', 'cpg', 'fda_compliant'],
    matchingKeywords: ['contract manufacturing', 'copacking', 'CPG production'],
    confidenceLevel: 'high',
    summary: 'Built a $150K/month contract manufacturing and copacking business serving CPG brands.',
  },

  // LOGISTICS & FULFILLMENT
  {
    companyName: 'MyFBAPrep',
    industry: 'logistics',
    subIndustry: '3pl_fulfillment',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Competitive 3PL market', 'Building warehouse network'],
      capabilities: ['E-commerce experience', 'Technical skills'],
      marketPosition: 'New FBA prep service',
    },
    endingState: {
      revenue: '5m_10m',
      teamSize: '50_100',
      revenueGrowth: '100x+',
      achievements: ['$6M annual revenue in 3 years', 'Multi-warehouse network', 'Amazon SPN certified'],
      newCapabilities: ['10+ warehouse locations', 'Tech platform for tracking'],
      marketPosition: 'Leading FBA prep service',
    },
    strategyType: 'market_timing',
    expansionType: 'horizontal',
    targetMarket: 'amazon_sellers',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Specialized in FBA prep', impact: 'Captured growing Amazon seller market', difficulty: 'moderate' },
      { action: 'Built tech platform for tracking', impact: 'Improved client experience', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Systems before scale. Invest heavily in processes and training.',
    sourceUrl: 'https://www.starterstory.com/stories/we-built-a-6m-3pl-company-in-3-years',
    sourcePlatform: 'starter_story',
    tags: ['logistics', '3pl', 'amazon', 'fulfillment'],
    matchingKeywords: ['FBA prep', '3PL', 'Amazon fulfillment', 'ecommerce logistics'],
    confidenceLevel: 'high',
    summary: 'Built a $6M 3PL company in 3 years specializing in Amazon FBA prep.',
  },
  {
    companyName: 'ShipHero',
    industry: 'logistics',
    subIndustry: 'warehouse_management',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Complex software development', 'Building fulfillment infrastructure'],
      capabilities: ['Technical expertise', 'E-commerce knowledge'],
      marketPosition: 'New WMS startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '100_plus',
      revenueGrowth: '500x+',
      achievements: ['$30M annual revenue', 'SaaS + fulfillment model', '5000+ customers'],
      newCapabilities: ['Warehouse management software', 'Fulfillment services'],
      marketPosition: 'Leading WMS + fulfillment provider',
    },
    strategyType: 'platform_play',
    expansionType: 'horizontal',
    targetMarket: 'ecommerce_merchants',
    timeline: { totalMonths: 120 },
    keyActions: [
      { action: 'Built software-first approach', impact: 'Created recurring revenue model', difficulty: 'hard' },
      { action: 'Added fulfillment as upsell', impact: 'Increased customer LTV', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 500 },
    lessonsLearned: 'SaaS and services are different businesses. Build separate teams for each.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-ecommerce-fulfillment-business',
    sourcePlatform: 'starter_story',
    tags: ['logistics', 'saas', 'fulfillment', 'wms'],
    matchingKeywords: ['warehouse management', 'fulfillment software', 'ecommerce logistics'],
    confidenceLevel: 'high',
    summary: 'Built a $30M/year warehouse management software and ecommerce fulfillment business.',
  },
  {
    companyName: 'OTW Shipping',
    industry: 'logistics',
    subIndustry: 'ecommerce_fulfillment',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['No capital as students', 'Building warehouse operations'],
      capabilities: ['Hustle and determination', 'Technical skills'],
      marketPosition: 'College startup fulfillment center',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '11_25',
      revenueGrowth: '50x+',
      achievements: ['$3M annual revenue', 'Scaled from college dorm', 'Major brand clients'],
      newCapabilities: ['50,000 orders per month', 'DTC brand specialization'],
      marketPosition: 'Growing e-commerce fulfillment center',
    },
    strategyType: 'bootstrap_growth',
    expansionType: 'vertical',
    targetMarket: 'dtc_brands',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Started with zero capital', impact: 'Proved scrappy execution works', difficulty: 'hard' },
      { action: 'Focused on DTC brands', impact: 'Built niche in growing market', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Know when to commit fully. Eventually went full-time from college.',
    sourceUrl: 'https://www.starterstory.com/stories/otw-shipping',
    sourcePlatform: 'starter_story',
    tags: ['logistics', 'fulfillment', 'bootstrap', 'dtc'],
    matchingKeywords: ['ecommerce fulfillment', 'DTC logistics', 'order fulfillment'],
    confidenceLevel: 'high',
    summary: 'Two broke college students built a $3M/year eCommerce fulfillment center.',
  },
  {
    companyName: 'ShipMonk',
    industry: 'logistics',
    subIndustry: 'ecommerce_fulfillment',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['New to US market', 'Building infrastructure'],
      capabilities: ['Entrepreneurial drive', 'Technical background'],
      marketPosition: 'Immigrant-founded startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '500_plus',
      revenueGrowth: '1000x+',
      achievements: ['$60M annual revenue', '600+ employees', 'Multiple fulfillment centers'],
      newCapabilities: ['Technology platform', 'Multi-location network'],
      marketPosition: 'Leading e-commerce fulfillment provider',
    },
    strategyType: 'technology_driven',
    expansionType: 'horizontal',
    targetMarket: 'ecommerce_brands',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Built technology platform', impact: 'Differentiated from traditional 3PLs', difficulty: 'hard' },
      { action: 'Focused on e-commerce niche', impact: 'Rode the DTC wave', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'Growth requires infrastructure. Heavy investment in people and systems.',
    sourceUrl: 'https://www.starterstory.com/stories/how-this-immigrant-entrepreneur-built-a-60m-year-fulfillment-business',
    sourcePlatform: 'starter_story',
    tags: ['logistics', 'fulfillment', 'immigrant_founder', 'tech'],
    matchingKeywords: ['fulfillment center', 'ecommerce logistics', 'order fulfillment'],
    confidenceLevel: 'high',
    summary: 'Immigrant entrepreneur built a $60M/year fulfillment business.',
  },
  {
    companyName: 'Ordoro',
    industry: 'logistics',
    subIndustry: 'order_management',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Complex multi-channel e-commerce', 'Building integrations'],
      capabilities: ['Technical team', 'Austin startup ecosystem'],
      marketPosition: 'New order management platform',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '11_25',
      revenueGrowth: '50x+',
      achievements: ['50% YoY growth', 'Multi-channel platform', '3000+ merchants'],
      newCapabilities: ['Comprehensive integrations', 'Inventory management'],
      marketPosition: 'Mid-market order management leader',
    },
    strategyType: 'steady_growth',
    expansionType: 'horizontal',
    targetMarket: 'mid_market_merchants',
    timeline: { totalMonths: 168 },
    keyActions: [
      { action: 'Built multi-channel integrations', impact: 'Solved real merchant pain points', difficulty: 'hard' },
      { action: 'Focused on mid-market', impact: 'Found underserved segment', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Do fewer things better. Stayed focused on core use cases.',
    sourceUrl: 'https://www.starterstory.com/order-management-software',
    sourcePlatform: 'starter_story',
    tags: ['logistics', 'saas', 'order_management', 'multi_channel'],
    matchingKeywords: ['order management', 'inventory software', 'multi-channel'],
    confidenceLevel: 'high',
    summary: 'Created an e-commerce fulfillment platform growing 50% YoY.',
  },
  {
    companyName: 'Honest FulPhilment',
    industry: 'logistics',
    subIndustry: 'china_fulfillment',
    location: 'China',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Operating in China as foreigner', 'Quality control across cultures'],
      capabilities: ['China connections', 'Bilingual team'],
      marketPosition: 'New China-based fulfillment',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '100_plus',
      revenueGrowth: '500x+',
      achievements: ['$24M annual revenue', 'Bridge between East and West', '500+ brands served'],
      newCapabilities: ['Western-facing operations', 'Quality assurance systems'],
      marketPosition: 'Leading China fulfillment for Western brands',
    },
    strategyType: 'geographic_arbitrage',
    expansionType: 'horizontal',
    targetMarket: 'western_brands',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Positioned as Western-facing China partner', impact: 'Built trust with international brands', difficulty: 'hard' },
      { action: 'Invested in quality control', impact: 'Reduced defects and returns', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 500 },
    lessonsLearned: 'Invest in cultural bridges. Built bilingual management team.',
    sourceUrl: 'https://www.starterstory.com/stories/i-built-a-24m-year-branding-and-fulfillment-company-based-in-china',
    sourcePlatform: 'starter_story',
    tags: ['logistics', 'china', 'fulfillment', 'international'],
    matchingKeywords: ['China fulfillment', 'international logistics', 'cross-border'],
    confidenceLevel: 'high',
    summary: 'Built a $24M/year branding and fulfillment company based in China.',
  },

  // FINTECH
  {
    companyName: 'FundKite',
    industry: 'fintech',
    subIndustry: 'small_business_lending',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Regulatory compliance', 'Building underwriting models'],
      capabilities: ['Finance background', 'Technology expertise'],
      marketPosition: 'New SMB financing platform',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '50_100',
      revenueGrowth: '1000x+',
      achievements: ['$70M annual revenue', '$5.83M monthly', '91 employees'],
      newCapabilities: ['Proprietary underwriting tech', 'Automated loan processing'],
      marketPosition: 'Leading SMB financing provider',
    },
    strategyType: 'technology_driven',
    expansionType: 'vertical',
    targetMarket: 'small_businesses',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Built proprietary underwriting tech', impact: 'Better risk assessment than competitors', difficulty: 'hard' },
      { action: 'Focused on underserved small businesses', impact: 'Found large addressable market', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'Technology-driven underwriting is key to managing default risk in SMB lending.',
    sourceUrl: 'https://www.starterstory.com/fundkite-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['fintech', 'lending', 'smb', 'underwriting'],
    matchingKeywords: ['small business lending', 'fintech', 'business financing'],
    confidenceLevel: 'high',
    summary: 'Grew to a $70M revenue fintech powerhouse in 8 years providing SMB financing.',
  },
  {
    companyName: 'FinChat',
    industry: 'fintech',
    subIndustry: 'investment_research',
    location: 'Canada',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Competing with Bloomberg terminals', 'AI accuracy for finance'],
      capabilities: ['Finance expertise', 'Technical skills'],
      marketPosition: 'New AI research platform',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '11_25',
      revenueGrowth: '100x+',
      achievements: ['$875K monthly revenue', '$1M+ ARR', 'AI-powered research'],
      newCapabilities: ['Financial AI', 'Data partnerships'],
      marketPosition: 'Leading AI investment research platform',
    },
    strategyType: 'product_innovation',
    expansionType: 'vertical',
    targetMarket: 'retail_investors',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Applied AI to investment research', impact: 'Democratized institutional-grade research', difficulty: 'hard' },
      { action: 'Focused on retail investor needs', impact: 'Found underserved market', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Finance AI needs extra accuracy measures. Built verification systems.',
    sourceUrl: 'https://www.starterstory.com/finchat-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['fintech', 'ai', 'investment', 'research'],
    matchingKeywords: ['AI finance', 'investment research', 'financial analysis'],
    confidenceLevel: 'high',
    summary: 'Three founders built FinChat to $1M ARR revolutionizing investment research with AI.',
  },
  {
    companyName: 'KYC Hub',
    industry: 'fintech',
    subIndustry: 'compliance_tech',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Complex regulatory landscape', 'Building verification systems'],
      capabilities: ['Compliance expertise', 'Technical team'],
      marketPosition: 'New compliance platform',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '50_100',
      revenueGrowth: '100x+',
      achievements: ['$298K monthly revenue', '58 employees', 'Global compliance platform'],
      newCapabilities: ['Comprehensive KYC solution', 'Multi-country support'],
      marketPosition: 'Leading financial crime compliance platform',
    },
    strategyType: 'compliance_focus',
    expansionType: 'horizontal',
    targetMarket: 'financial_institutions',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Built comprehensive KYC solution', impact: 'One-stop compliance platform', difficulty: 'hard' },
      { action: 'Focused on growing fintech market', impact: 'Rode the compliance wave', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Build flexible architecture for regulatory changes. Modular compliance modules.',
    sourceUrl: 'https://www.starterstory.com/stories/kyc-hub',
    sourcePlatform: 'starter_story',
    tags: ['fintech', 'compliance', 'kyc', 'regtech'],
    matchingKeywords: ['KYC', 'compliance', 'anti-money laundering', 'financial crime'],
    confidenceLevel: 'high',
    summary: 'Built a $298K/month platform to mitigate financial crime risks.',
  },
  {
    companyName: 'Tilled',
    industry: 'fintech',
    subIndustry: 'payment_processing',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Complex payment regulations', 'Competing with Stripe'],
      capabilities: ['Payment industry experience', 'Technical skills'],
      marketPosition: 'New payment infrastructure startup',
    },
    endingState: {
      revenue: '5m_10m',
      teamSize: '26_50',
      revenueGrowth: '200x+',
      achievements: ['$942K monthly revenue', 'PayFac-as-a-Service model', '40 employees'],
      newCapabilities: ['Embedded payments platform', 'PayFac infrastructure'],
      marketPosition: 'Leading PayFac-as-a-Service provider',
    },
    strategyType: 'product_innovation',
    expansionType: 'vertical',
    targetMarket: 'saas_companies',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Created PayFac-as-a-Service model', impact: 'Enabled SaaS to embed payments', difficulty: 'hard' },
      { action: 'Simplified payment integration', impact: 'Reduced implementation time', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 200 },
    lessonsLearned: 'Make hard things simple. Abstract complexity for customers.',
    sourceUrl: 'https://www.starterstory.com/tilled-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['fintech', 'payments', 'payfac', 'embedded'],
    matchingKeywords: ['payment processing', 'PayFac', 'embedded payments'],
    confidenceLevel: 'high',
    summary: 'Built Tilled to simplify payments and hit seven-figure revenues as PayFac-as-a-Service.',
  },
  {
    companyName: 'VizyPay',
    industry: 'fintech',
    subIndustry: 'payment_processing',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Competing with payment giants', 'Building merchant network'],
      capabilities: ['Payment industry experience', 'Entrepreneurial drive'],
      marketPosition: 'New SMB payment processor',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '100_plus',
      revenueGrowth: '200x+',
      achievements: ['$1.7M monthly revenue', '110 employees', 'Nationwide SMB network'],
      newCapabilities: ['Sales agent network', 'SMB-focused solutions'],
      marketPosition: 'Major SMB payment processor',
    },
    strategyType: 'channel_strategy',
    expansionType: 'horizontal',
    targetMarket: 'small_businesses',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Focused on underserved SMBs', impact: 'Found market ignored by big players', difficulty: 'moderate' },
      { action: 'Built sales agent network', impact: 'Scaled merchant acquisition', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 200 },
    lessonsLearned: 'Retention is key in payment processing. Invested heavily in customer success.',
    sourceUrl: 'https://www.starterstory.com/stories/vizpay',
    sourcePlatform: 'starter_story',
    tags: ['fintech', 'payments', 'smb', 'sales'],
    matchingKeywords: ['payment processing', 'merchant services', 'SMB payments'],
    confidenceLevel: 'high',
    summary: 'Built an $18M/year business providing payment processing to SMBs.',
  },
  {
    companyName: 'ComplYant',
    industry: 'fintech',
    subIndustry: 'tax_compliance',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Complex tax regulations', 'Fundraising as Black founder'],
      capabilities: ['Tax expertise', 'Technical skills'],
      marketPosition: 'New tax compliance app',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '11_25',
      revenueGrowth: '50x+',
      achievements: ['$7.3M raised', '500% revenue growth', 'Major VC backing'],
      newCapabilities: ['Automated tax tracking', 'User-friendly tax UX'],
      marketPosition: 'Growing tax compliance platform',
    },
    strategyType: 'fundraising',
    expansionType: 'vertical',
    targetMarket: 'small_businesses',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Made taxes approachable for SMBs', impact: 'Solved painful problem', difficulty: 'hard' },
      { action: 'Persisted through fundraising challenges', impact: 'Secured $7.3M', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Investor fit matters enormously. Find mission-aligned investors.',
    sourceUrl: 'https://www.starterstory.com/stories/complyant-inc',
    sourcePlatform: 'starter_story',
    tags: ['fintech', 'tax', 'compliance', 'diverse_founder'],
    matchingKeywords: ['tax compliance', 'small business tax', 'tax software'],
    confidenceLevel: 'high',
    summary: 'Built a tax app to $28K/month in 8 months, raised $7.3M and grew revenue 500%.',
  },
  {
    companyName: 'Float',
    industry: 'fintech',
    subIndustry: 'cashflow_forecasting',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Competing with spreadsheets', 'Accounting software integrations'],
      capabilities: ['Finance background', 'Technical skills'],
      marketPosition: 'New cash forecasting tool',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '11_25',
      revenueGrowth: '50x+',
      achievements: ['66K monthly traffic', '20 employees', 'Profitable and growing'],
      newCapabilities: ['Accounting integrations', 'Visual forecasting'],
      marketPosition: 'Leading cashflow forecasting platform',
    },
    strategyType: 'steady_growth',
    expansionType: 'vertical',
    targetMarket: 'small_businesses',
    timeline: { totalMonths: 144 },
    keyActions: [
      { action: 'Integrated with accounting software', impact: 'Reduced friction for adoption', difficulty: 'hard' },
      { action: 'Focused on visual cash forecasting', impact: 'Made complex data accessible', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Multi-tier sales approach works. Built self-serve for smaller customers.',
    sourceUrl: 'https://www.starterstory.com/float-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['fintech', 'cashflow', 'forecasting', 'accounting'],
    matchingKeywords: ['cashflow forecasting', 'financial planning', 'cash management'],
    confidenceLevel: 'high',
    summary: 'Built Float cashflow forecasting app that revolutionized business growth strategies.',
  },

  // TRAVEL & HOSPITALITY
  {
    companyName: 'Rayna Tours',
    industry: 'travel',
    subIndustry: 'tour_operator',
    location: 'UAE',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Building tour partnerships', 'Competing in Dubai market'],
      capabilities: ['Local knowledge', 'Tourism connections'],
      marketPosition: 'New Dubai tour operator',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '500_plus',
      revenueGrowth: '500x+',
      achievements: ['$35M annual revenue', '670 employees', 'Leading Dubai tour operator'],
      newCapabilities: ['Comprehensive tour packages', 'Strong brand reputation'],
      marketPosition: 'Market leader in Dubai tours',
    },
    strategyType: 'market_leadership',
    expansionType: 'horizontal',
    targetMarket: 'tourists',
    timeline: { totalMonths: 216 },
    keyActions: [
      { action: 'Built comprehensive Dubai tour packages', impact: 'Became one-stop shop for tourists', difficulty: 'moderate' },
      { action: 'Invested in customer experience', impact: 'Built strong reputation', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 500 },
    lessonsLearned: 'Seasonal businesses need diversification. Diversified tour offerings year-round.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-tour-operator',
    sourcePlatform: 'starter_story',
    tags: ['travel', 'tourism', 'dubai', 'tours'],
    matchingKeywords: ['tour operator', 'Dubai tours', 'travel business'],
    confidenceLevel: 'high',
    summary: 'Started Dubai\'s leading tour operator, now doing $35M/year with 670 employees.',
  },

  // FASHION & APPAREL
  {
    companyName: 'TomboyX',
    industry: 'fashion',
    subIndustry: 'gender_neutral_apparel',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Creating new category', 'Manufacturing gender-neutral sizing'],
      capabilities: ['Fashion industry experience', 'Community connections'],
      marketPosition: 'New gender-neutral underwear brand',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '26_50',
      revenueGrowth: '200x+',
      achievements: ['$2M monthly revenue', '34 employees', 'Category leader'],
      newCapabilities: ['Inclusive sizing', 'Loyal LGBTQ+ customer base'],
      marketPosition: 'Leading gender-neutral underwear brand',
    },
    strategyType: 'category_creation',
    expansionType: 'vertical',
    targetMarket: 'lgbtq_consumers',
    timeline: { totalMonths: 120 },
    keyActions: [
      { action: 'Created inclusive sizing and marketing', impact: 'Built loyal LGBTQ+ customer base', difficulty: 'hard' },
      { action: 'Focused on undergarments first', impact: 'Found underserved niche', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 200 },
    lessonsLearned: 'Innovation requires custom manufacturing. Developed custom size patterns.',
    sourceUrl: 'https://www.starterstory.com/tomboyx',
    sourcePlatform: 'starter_story',
    tags: ['fashion', 'gender_neutral', 'inclusive', 'underwear'],
    matchingKeywords: ['gender neutral clothing', 'inclusive fashion', 'LGBTQ apparel'],
    confidenceLevel: 'high',
    summary: 'A gender neutral garment became a $500K/month business serving underserved market.',
  },
  {
    companyName: 'Blvck Paris',
    industry: 'fashion',
    subIndustry: 'lifestyle_brand',
    location: 'France',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Building brand identity', 'Standing out in fashion'],
      capabilities: ['Design skills', 'Social media knowledge'],
      marketPosition: 'New lifestyle brand',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '6_10',
      revenueGrowth: '20x+',
      achievements: ['$1.2M annual revenue', '3M+ Instagram followers', 'Global brand recognition'],
      newCapabilities: ['Massive social following', 'Strong visual identity'],
      marketPosition: 'Iconic all-black lifestyle brand',
    },
    strategyType: 'audience_first',
    expansionType: 'horizontal',
    targetMarket: 'minimalist_consumers',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built audience before products', impact: 'Had customers ready at launch', difficulty: 'hard' },
      { action: 'Created strong visual identity', impact: 'Instantly recognizable brand', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Own your audience when possible. Diversified to multiple channels.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-lifestyle-brand',
    sourcePlatform: 'starter_story',
    tags: ['fashion', 'lifestyle', 'minimalist', 'instagram'],
    matchingKeywords: ['lifestyle brand', 'minimalist fashion', 'all black aesthetic'],
    confidenceLevel: 'high',
    summary: 'Started a $1.2M/year all-black lifestyle brand built around minimalist aesthetic.',
  },
  {
    companyName: 'Leze the Label',
    industry: 'fashion',
    subIndustry: 'sustainable_fashion',
    location: 'Canada',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Sustainable supply chain', 'Competing with fast fashion'],
      capabilities: ['Fashion design skills', 'Sustainability passion'],
      marketPosition: 'New sustainable workwear brand',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '2_5',
      revenueGrowth: '10x+',
      achievements: ['$45K monthly revenue', 'Sustainable production', 'Loyal customer base'],
      newCapabilities: ['Recycled materials expertise', 'Eco-conscious positioning'],
      marketPosition: 'Growing sustainable workwear brand',
    },
    strategyType: 'sustainability_focus',
    expansionType: 'vertical',
    targetMarket: 'eco_conscious_professionals',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Used recycled materials', impact: 'Attracted eco-conscious customers', difficulty: 'hard' },
      { action: 'Focused on workwear niche', impact: 'Less competition than casual wear', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Premium positioning for sustainable products. Educated customers on value.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-womens-workwear-brand',
    sourcePlatform: 'starter_story',
    tags: ['fashion', 'sustainable', 'workwear', 'recycled'],
    matchingKeywords: ['sustainable fashion', 'eco workwear', 'recycled clothing'],
    confidenceLevel: 'high',
    summary: 'Started a $45K/month women\'s workwear brand from recycled materials.',
  },
  {
    companyName: 'CAPO Clothing',
    industry: 'fashion',
    subIndustry: 'athleisure',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Starting with only £250', 'Competing with major athleisure brands'],
      capabilities: ['Entrepreneurial drive', 'Social media skills'],
      marketPosition: 'Bootstrapped athleisure startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '26_50',
      revenueGrowth: '75000x',
      achievements: ['£15M revenue from £250', 'Major athleisure brand', 'Rapid growth'],
      newCapabilities: ['Quality athleisure at accessible prices'],
      marketPosition: 'Leading UK athleisure brand',
    },
    strategyType: 'bootstrap_growth',
    expansionType: 'vertical',
    targetMarket: 'athleisure_consumers',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Started with minimal capital', impact: 'Proved scrappy execution works', difficulty: 'hard' },
      { action: 'Made quality athleisure accessible', impact: 'Found underserved market gap', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 75000 },
    lessonsLearned: 'Cash flow management is critical. Pre-orders and quick turns.',
    sourceUrl: 'https://www.starterstory.com/capo-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['fashion', 'athleisure', 'bootstrap', 'uk'],
    matchingKeywords: ['athleisure', 'activewear', 'sportswear'],
    confidenceLevel: 'high',
    summary: 'Grew a clothing brand from £250 to £15M, making affordable high-quality athleisure.',
  },

  // BEAUTY & SKINCARE
  {
    companyName: 'Glow Recipe',
    industry: 'beauty',
    subIndustry: 'skincare',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Introducing K-beauty to US market', 'Building brand awareness'],
      capabilities: ['Beauty industry experience', 'Korean beauty connections'],
      marketPosition: 'New K-beauty brand',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '50_100',
      revenueGrowth: '1000x+',
      achievements: ['$100M in sales', '$8.33M monthly revenue', 'Major Sephora partnership'],
      newCapabilities: ['K-beauty expertise', 'Major retail distribution'],
      marketPosition: 'Leading K-beauty skincare brand',
    },
    strategyType: 'first_mover',
    expansionType: 'horizontal',
    targetMarket: 'skincare_enthusiasts',
    timeline: { totalMonths: 120 },
    keyActions: [
      { action: 'Pioneered K-beauty in US market', impact: 'First mover advantage', difficulty: 'hard' },
      { action: 'Built Sephora partnership', impact: 'Massive distribution reach', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'Own brands have better margins. Built brand equity first before pivoting.',
    sourceUrl: 'https://www.starterstory.com/glow-recipe-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['beauty', 'skincare', 'kbeauty', 'sephora'],
    matchingKeywords: ['K-beauty', 'skincare brand', 'Sephora brand'],
    confidenceLevel: 'high',
    summary: 'Christine & Sarah grew Glow Recipe to $100 million in sales with K-beauty.',
  },
  {
    companyName: 'The Quick Flick',
    industry: 'beauty',
    subIndustry: 'cosmetics',
    location: 'Australia',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Inventing new beauty tool', 'Manufacturing innovation'],
      capabilities: ['Product idea', 'Entrepreneurial drive'],
      marketPosition: 'New beauty tool inventor',
    },
    endingState: {
      revenue: '5m_10m',
      teamSize: '11_25',
      revenueGrowth: '200x+',
      achievements: ['$10M empire by age 24', 'Innovative product category', 'Global distribution'],
      newCapabilities: ['Product innovation', 'Social media virality'],
      marketPosition: 'Leading eyeliner tool brand',
    },
    strategyType: 'product_innovation',
    expansionType: 'horizontal',
    targetMarket: 'makeup_users',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Solved common makeup problem', impact: 'Huge product-market fit', difficulty: 'moderate' },
      { action: 'Leveraged social media virality', impact: 'Low-cost customer acquisition', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 200 },
    lessonsLearned: 'First mover needs to build fast. Copycats emerged quickly.',
    sourceUrl: 'https://www.starterstory.com/the-quick-flick-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['beauty', 'cosmetics', 'innovation', 'eyeliner'],
    matchingKeywords: ['eyeliner stamp', 'beauty innovation', 'makeup tool'],
    confidenceLevel: 'high',
    summary: 'Iris Smit built a $10M beauty empire by age 24 with innovative eyeliner stamp.',
  },
  {
    companyName: 'Evolue Skincare',
    industry: 'beauty',
    subIndustry: 'natural_skincare',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Formulating clean products', 'Competing with big beauty brands'],
      capabilities: ['Chemistry background', 'Passion for clean beauty'],
      marketPosition: 'New clean skincare brand',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '6_10',
      revenueGrowth: '50x+',
      achievements: ['$200K monthly revenue', 'Clean beauty pioneer', 'Spa and retail distribution'],
      newCapabilities: ['Clean formulations', 'Professional spa partnerships'],
      marketPosition: 'Established clean skincare brand',
    },
    strategyType: 'clean_beauty',
    expansionType: 'vertical',
    targetMarket: 'health_conscious_consumers',
    timeline: { totalMonths: 180 },
    keyActions: [
      { action: 'Focused on clean ingredients', impact: 'Attracted health-conscious consumers', difficulty: 'hard' },
      { action: 'Built spa partnerships', impact: 'Professional credibility', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Premium products need education. Educated customers on value.',
    sourceUrl: 'https://www.starterstory.com/how-to-create-natural-organic-skincare-brand',
    sourcePlatform: 'starter_story',
    tags: ['beauty', 'skincare', 'natural', 'organic'],
    matchingKeywords: ['natural skincare', 'organic beauty', 'clean beauty'],
    confidenceLevel: 'high',
    summary: 'Created a $2.4M/year natural organic skincare brand with clean formulations.',
  },
  {
    companyName: 'BLAQ',
    industry: 'beauty',
    subIndustry: 'skincare',
    location: 'Australia',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Creating new product category', 'Building brand in Australia'],
      capabilities: ['Product innovation', 'E-commerce skills'],
      marketPosition: 'New activated charcoal brand',
    },
    endingState: {
      revenue: '5m_10m',
      teamSize: '2_5',
      revenueGrowth: '100x+',
      achievements: ['$658K monthly revenue', '$7M+ empire', 'International distribution'],
      newCapabilities: ['Charcoal expertise', 'Influencer marketing'],
      marketPosition: 'Leading activated charcoal skincare brand',
    },
    strategyType: 'category_creation',
    expansionType: 'horizontal',
    targetMarket: 'skincare_consumers',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Created unique activated charcoal products', impact: 'First mover in category', difficulty: 'moderate' },
      { action: 'Leveraged influencer marketing', impact: 'Rapid brand awareness', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Trends need to evolve into brands. Expanded to full skincare line.',
    sourceUrl: 'https://www.starterstory.com/stories/blaq',
    sourcePlatform: 'starter_story',
    tags: ['beauty', 'skincare', 'charcoal', 'viral'],
    matchingKeywords: ['activated charcoal', 'charcoal skincare', 'beauty trend'],
    confidenceLevel: 'high',
    summary: 'Built a $7M Aussie skincare empire with activated charcoal products.',
  },
  {
    companyName: 'Ceremonia',
    industry: 'beauty',
    subIndustry: 'haircare',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Launching during pandemic', 'Building Latinx beauty category'],
      capabilities: ['Marketing expertise', 'Latinx heritage'],
      marketPosition: 'New Latinx haircare brand',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '11_25',
      revenueGrowth: '50x+',
      achievements: ['$100K in 100 days', 'Sephora partnership', 'Category creator'],
      newCapabilities: ['Latinx-first branding', 'Clean haircare formulations'],
      marketPosition: 'Leading Latinx-inspired haircare brand',
    },
    strategyType: 'category_creation',
    expansionType: 'vertical',
    targetMarket: 'latinx_consumers',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Created Latinx-first beauty brand', impact: 'Served underrepresented market', difficulty: 'moderate' },
      { action: 'Built beautiful brand identity', impact: 'Stood out in crowded market', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Crisis can create opportunity. Leaned into D2C during COVID.',
    sourceUrl: 'https://www.starterstory.com/ceremonia-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['beauty', 'haircare', 'latinx', 'sephora'],
    matchingKeywords: ['Latinx beauty', 'haircare brand', 'diverse beauty'],
    confidenceLevel: 'high',
    summary: 'Latina entrepreneur Babba Rivera grew Ceremonia to $100K in 100 days.',
  },
  {
    companyName: 'Fur',
    industry: 'beauty',
    subIndustry: 'body_care',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Taboo product category', 'Retail buyer skepticism'],
      capabilities: ['Marketing expertise', 'Product innovation'],
      marketPosition: 'New body hair care brand',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '100_plus',
      revenueGrowth: '200x+',
      achievements: ['Millions in revenue', '100+ employees', '267K monthly traffic'],
      newCapabilities: ['Category normalization', 'D2C and retail distribution'],
      marketPosition: 'Leading body hair care brand',
    },
    strategyType: 'category_creation',
    expansionType: 'horizontal',
    targetMarket: 'body_care_consumers',
    timeline: { totalMonths: 108 },
    keyActions: [
      { action: 'Normalized taboo category', impact: 'Created new market', difficulty: 'hard' },
      { action: 'Started with $10K', impact: 'Proved bootstrap model works', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 200 },
    lessonsLearned: 'D2C can prove market before retail. Built D2C first, proved demand.',
    sourceUrl: 'https://www.starterstory.com/fur-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['beauty', 'body_care', 'taboo', 'category_creation'],
    matchingKeywords: ['body hair care', 'body care', 'beauty innovation'],
    confidenceLevel: 'high',
    summary: 'Two founders bootstrapped a taboo beauty business to millions by normalizing body hair care.',
  },
];

async function seedBatch5() {
  console.log('Seeding case studies batch 5...');
  console.log('Total case studies to seed:', batch5CaseStudies.length);

  let successCount = 0;
  let errorCount = 0;

  for (const study of batch5CaseStudies) {
    try {
      await db.insert(caseStudies).values(study as CaseStudyInsert);
      console.log('✓ Seeded:', study.companyName);
      successCount++;
    } catch (error: unknown) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      console.error('✗ Error seeding', study.companyName, ':', errorMessage);
      errorCount++;
    }
  }

  console.log('\nBatch 5 seeding complete!');
  console.log('✓ Successfully seeded:', successCount);
  console.log('✗ Errors:', errorCount);

  process.exit(0);
}

seedBatch5().catch((error) => {
  console.error('Fatal error:', error);
  process.exit(1);
});
