import { db } from '../../lib/db';
import { caseStudies } from '../schema';

type CaseStudyInsert = typeof caseStudies.$inferInsert;

const batch15 = [
  // MEDIA & CONTENT
  {
    companyName: 'Morning Brew',
    industry: 'media',
    subIndustry: 'newsletter',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Email newsletter saturation', 'Content differentiation', 'Monetization'],
      capabilities: ['Business journalism', 'Email marketing', 'Content creation'],
      marketPosition: 'Student newsletter',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$75M exit',
      achievements: ['2.5M subscribers', '$75M acquisition', 'Media empire'],
      newCapabilities: ['Multiple newsletters', 'Podcast network', 'Events'],
      marketPosition: 'Newsletter media leader',
    },
    strategyType: 'content_empire',
    expansionType: 'product',
    targetMarket: 'business_professionals',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built business newsletter to 2.5M subscribers', impact: 'Massive audience', difficulty: 'hard' },
      { action: 'Sold company for $75M', impact: 'Successful exit', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 750 },
    lessonsLearned: 'Consistent, high-quality email content builds massive value.',
    sourceUrl: 'https://www.starterstory.com/stories/morning-brew-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['media', 'newsletter', 'content', 'acquisition'],
    matchingKeywords: ['morning brew', 'alex lieberman', 'newsletter'],
    confidenceLevel: 'high',
    summary: 'Grew newsletter to 2.5M subscribers and sold for $75M.',
  },
  {
    companyName: 'Riverside.fm',
    industry: 'media',
    subIndustry: 'podcast_tools',
    location: 'Israel',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Remote recording quality', 'Zoom competition', 'Podcast market'],
      capabilities: ['Audio/video engineering', 'Product development', 'Market timing'],
      marketPosition: 'Podcast tool startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$2.6M/month ($9.5M total)',
      achievements: ['$2.6M/month', 'Podcast recording leader', 'Used by major creators'],
      newCapabilities: ['Studio-quality remote recording', 'AI editing', 'Enterprise features'],
      marketPosition: 'Podcast recording leader',
    },
    strategyType: 'product_innovation',
    expansionType: 'product',
    targetMarket: 'podcasters',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built high-quality remote podcast recording platform', impact: 'Product differentiation', difficulty: 'hard' },
      { action: 'Brothers scaled to $9.5M podcast powerhouse', impact: 'Market leadership', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 95 },
    lessonsLearned: 'Superior product quality can win against established competitors.',
    sourceUrl: 'https://www.starterstory.com/riverside-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['media', 'podcast', 'tools', 'saas'],
    matchingKeywords: ['riverside', 'podcast recording', 'remote recording'],
    confidenceLevel: 'high',
    summary: 'Two brothers built podcast recording platform to $9.5M.',
  },
  {
    companyName: 'Goldcast',
    industry: 'media',
    subIndustry: 'video_events',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Virtual event market', 'Zoom fatigue', 'Enterprise sales'],
      capabilities: ['Harvard network', 'Technical skills', 'B2B focus'],
      marketPosition: 'Virtual event startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$833K/month ($10M+)',
      achievements: ['$833K/month', 'Enterprise video events leader', 'Harvard trio success'],
      newCapabilities: ['Enterprise events platform', 'Virtual event production', 'Analytics'],
      marketPosition: 'B2B video events leader',
    },
    strategyType: 'enterprise_focus',
    expansionType: 'product',
    targetMarket: 'enterprises',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built B2B video event platform during pandemic', impact: 'Market timing', difficulty: 'hard' },
      { action: 'Scaled to enterprise customers', impact: 'Premium positioning', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'B2B focus and enterprise features command premium pricing.',
    sourceUrl: 'https://www.starterstory.com/goldcast-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['media', 'video', 'events', 'enterprise'],
    matchingKeywords: ['goldcast', 'video events', 'virtual events'],
    confidenceLevel: 'high',
    summary: 'Harvard trio scaled video event platform to $10M+.',
  },
  {
    companyName: 'Captions',
    industry: 'media',
    subIndustry: 'ai_video',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['AI video market', 'Creator tools competition', 'User acquisition'],
      capabilities: ['AI development', 'Mobile apps', 'Creator focus'],
      marketPosition: 'AI video startup',
    },
    endingState: {
      revenue: '5m_10m',
      teamSize: '51_200',
      revenueGrowth: '$508K/month ($6.1M)',
      achievements: ['$508K/month', '10M creators globally', 'AI video leader'],
      newCapabilities: ['AI captions', 'Video editing', 'Creator monetization'],
      marketPosition: 'AI creator tools leader',
    },
    strategyType: 'ai_innovation',
    expansionType: 'product',
    targetMarket: 'content_creators',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built AI-powered captions and video tools', impact: 'Creator empowerment', difficulty: 'hard' },
      { action: 'Reached 10M creators globally', impact: 'Massive adoption', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 61 },
    lessonsLearned: 'AI tools for creators can achieve massive scale quickly.',
    sourceUrl: 'https://www.starterstory.com/captions-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['media', 'ai', 'video', 'creators'],
    matchingKeywords: ['captions', 'ai video', 'creator tools'],
    confidenceLevel: 'high',
    summary: 'AI video tools reached 10M creators, $6.1M revenue.',
  },
  {
    companyName: 'SwellAI',
    industry: 'media',
    subIndustry: 'ai_content',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['AI content competition', 'Bootstrapped constraints', 'Market positioning'],
      capabilities: ['AI expertise', 'Marketing background', 'Product vision'],
      marketPosition: 'AI content startup',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '1_5',
      revenueGrowth: 'Bootstrapped to profitability',
      achievements: ['Bootstrapped success', 'AI content leader', 'Profitable growth'],
      newCapabilities: ['AI content generation', 'Podcast repurposing', 'Content automation'],
      marketPosition: 'AI content creation leader',
    },
    strategyType: 'bootstrapped_ai',
    expansionType: 'product',
    targetMarket: 'content_creators',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Bootstrapped AI content creation platform', impact: 'Capital efficiency', difficulty: 'hard' },
      { action: 'Dominated AI content creation niche', impact: 'Market leadership', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Bootstrapped AI companies can compete through focus and efficiency.',
    sourceUrl: 'https://www.starterstory.com/swellai-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['media', 'ai', 'content', 'bootstrapped'],
    matchingKeywords: ['swellai', 'ai content', 'cody schneider'],
    confidenceLevel: 'high',
    summary: 'Bootstrapped AI content platform to market leadership.',
  },
  {
    companyName: 'GetPoppy AI',
    industry: 'media',
    subIndustry: 'ai_writing',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['AI writing competition', 'Email focus', 'User acquisition'],
      capabilities: ['AI development', 'Email marketing expertise', 'Product design'],
      marketPosition: 'AI email startup',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '6_20',
      revenueGrowth: '$4M/year',
      achievements: ['$4M/year', 'AI email leader', 'Email copywriting automation'],
      newCapabilities: ['AI email writing', 'Sales copy generation', 'Template library'],
      marketPosition: 'AI email writing leader',
    },
    strategyType: 'vertical_ai',
    expansionType: 'product',
    targetMarket: 'marketers',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Built AI specifically for email copywriting', impact: 'Vertical focus', difficulty: 'hard' },
      { action: 'Scaled to $4M/year', impact: 'Rapid growth', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 40 },
    lessonsLearned: 'Vertical AI applications can outperform general-purpose tools.',
    sourceUrl: 'https://www.starterstory.com/stories/poppyai-write-emails-that-sell',
    sourcePlatform: 'starter_story',
    tags: ['media', 'ai', 'email', 'copywriting'],
    matchingKeywords: ['poppy ai', 'getpoppy', 'ai email'],
    confidenceLevel: 'high',
    summary: 'Built $4M/year AI email writing app.',
  },
  {
    companyName: 'Content Academy',
    industry: 'education',
    subIndustry: 'creator_education',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Young founder (21)', 'Online course competition', 'Authority building'],
      capabilities: ['Content expertise', 'Teaching ability', 'Social media presence'],
      marketPosition: 'Young creator educator',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '1_5',
      revenueGrowth: '$20K+/month',
      achievements: ['$20K+/month', '21-year-old success', 'Content education leader'],
      newCapabilities: ['Course creation', 'Community building', 'Creator coaching'],
      marketPosition: 'Creator education leader',
    },
    strategyType: 'creator_education',
    expansionType: 'service',
    targetMarket: 'aspiring_creators',
    timeline: { totalMonths: 12 },
    keyActions: [
      { action: '21-year-old built content education business', impact: 'Youth success', difficulty: 'medium' },
      { action: 'Reached $20K+/month in 12 months', impact: 'Rapid scaling', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 24 },
    lessonsLearned: 'Age is not a barrier to building education businesses.',
    sourceUrl: 'https://www.starterstory.com/content-academy-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['education', 'creator', 'content', 'young_founder'],
    matchingKeywords: ['content academy', 'mino lee', 'creator education'],
    confidenceLevel: 'high',
    summary: '21-year-old grew content academy to $20K+/month in 12 months.',
  },

  // CYBERSECURITY
  {
    companyName: 'Huntress',
    industry: 'cybersecurity',
    subIndustry: 'smb_security',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['SMB security market', 'Enterprise competition', 'Trust building'],
      capabilities: ['NSA background', 'Security expertise', 'SMB focus'],
      marketPosition: 'SMB security startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '200_plus',
      revenueGrowth: '$8.33M/month ($100M ARR)',
      achievements: ['$100M ARR', 'SMB cybersecurity leader', 'NSA-founded'],
      newCapabilities: ['Managed detection', 'Threat hunting', 'SMB-focused security'],
      marketPosition: 'SMB cybersecurity leader',
    },
    strategyType: 'smb_focus',
    expansionType: 'market',
    targetMarket: 'smb',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Built cybersecurity specifically for SMBs', impact: 'Market focus', difficulty: 'hard' },
      { action: 'Reached $100M ARR revolutionizing SMB security', impact: 'Market leadership', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'Underserved markets (SMB security) can support massive businesses.',
    sourceUrl: 'https://www.starterstory.com/huntress-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['cybersecurity', 'smb', 'managed_security', 'b2b'],
    matchingKeywords: ['huntress', 'smb security', 'kyle hanslovan'],
    confidenceLevel: 'high',
    summary: 'NSA veterans built SMB cybersecurity to $100M ARR.',
  },
  {
    companyName: 'Coro',
    industry: 'cybersecurity',
    subIndustry: 'all_in_one_security',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Security market fragmentation', 'Enterprise competition', 'Funding'],
      capabilities: ['Security expertise', 'Product vision', 'Enterprise experience'],
      marketPosition: 'Security startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '200_plus',
      revenueGrowth: '$8.33M/month ($100M revenue, $750M valuation)',
      achievements: ['$100M revenue', '$750M valuation', 'All-in-one security leader'],
      newCapabilities: ['Unified security platform', 'Enterprise sales', 'Global presence'],
      marketPosition: 'Enterprise security leader',
    },
    strategyType: 'platform_consolidation',
    expansionType: 'product',
    targetMarket: 'enterprises',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Built all-in-one cybersecurity platform', impact: 'Consolidation play', difficulty: 'hard' },
      { action: 'Four founders scaled to $100M revenue', impact: 'Team success', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'Consolidating fragmented markets creates massive value.',
    sourceUrl: 'https://www.starterstory.com/coro-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['cybersecurity', 'enterprise', 'platform', 'unicorn'],
    matchingKeywords: ['coro', 'cybersecurity platform', 'all in one security'],
    confidenceLevel: 'high',
    summary: 'Four founders built $100M revenue cybersecurity ($750M valuation).',
  },
  {
    companyName: 'Vanta',
    industry: 'cybersecurity',
    subIndustry: 'compliance',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Compliance automation', 'SOC 2 complexity', 'Enterprise trust'],
      capabilities: ['Technical expertise', 'Compliance knowledge', 'Product vision'],
      marketPosition: 'Compliance startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '200_plus',
      revenueGrowth: '$8.33M/month ($100M+)',
      achievements: ['$100M+ compliance empire', 'SOC 2 automation leader', 'Unicorn status'],
      newCapabilities: ['Automated compliance', 'Multiple frameworks', 'Enterprise scale'],
      marketPosition: 'Compliance automation leader',
    },
    strategyType: 'automation_play',
    expansionType: 'product',
    targetMarket: 'startups_enterprises',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Automated SOC 2 and security compliance', impact: 'Pain point solution', difficulty: 'hard' },
      { action: 'Built $100M+ security compliance empire', impact: 'Market creation', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'Automating painful compliance processes creates massive businesses.',
    sourceUrl: 'https://www.starterstory.com/vanta-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['cybersecurity', 'compliance', 'automation', 'soc2'],
    matchingKeywords: ['vanta', 'soc 2', 'compliance automation'],
    confidenceLevel: 'high',
    summary: 'Built $100M+ security compliance automation empire.',
  },
  {
    companyName: 'Eden Data',
    industry: 'cybersecurity',
    subIndustry: 'consulting',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Startup security needs', 'Consulting competition', 'Trust building'],
      capabilities: ['Cybersecurity expertise', 'Startup understanding', 'Consulting skills'],
      marketPosition: 'Security consultant',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '6_20',
      revenueGrowth: '$45K/month',
      achievements: ['$45K/month', 'Startup cybersecurity leader', 'Trusted advisor'],
      newCapabilities: ['Startup security programs', 'Compliance consulting', 'vCISO services'],
      marketPosition: 'Startup security consultant leader',
    },
    strategyType: 'niche_consulting',
    expansionType: 'service',
    targetMarket: 'startups',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Built cybersecurity consulting for startups', impact: 'Niche positioning', difficulty: 'medium' },
      { action: 'Scaled to $45K/month consulting revenue', impact: 'Service business growth', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 54 },
    lessonsLearned: 'Niche consulting for startups can be highly profitable.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-cybersecurity-consulting-firm',
    sourcePlatform: 'starter_story',
    tags: ['cybersecurity', 'consulting', 'startups', 'vciso'],
    matchingKeywords: ['eden data', 'cybersecurity consulting', 'startup security'],
    confidenceLevel: 'high',
    summary: 'Built $45K/month cybersecurity consulting for startups.',
  },
  {
    companyName: 'Clerk',
    industry: 'technology',
    subIndustry: 'authentication',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Auth competition', 'Developer adoption', 'Enterprise trust'],
      capabilities: ['Developer experience', 'Auth expertise', 'Product design'],
      marketPosition: 'Auth startup',
    },
    endingState: {
      revenue: '5m_10m',
      teamSize: '51_200',
      revenueGrowth: '$833K/month',
      achievements: ['$833K/month', '16M users', '$30M funding'],
      newCapabilities: ['User management', 'Authentication', 'Developer tools'],
      marketPosition: 'Developer authentication leader',
    },
    strategyType: 'developer_first',
    expansionType: 'product',
    targetMarket: 'developers',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built developer-friendly authentication platform', impact: 'DX focus', difficulty: 'hard' },
      { action: 'Accelerated to 16M users and $30M funding', impact: 'Rapid adoption', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Developer experience drives adoption in technical products.',
    sourceUrl: 'https://www.starterstory.com/clerk-com-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['technology', 'authentication', 'developer_tools', 'saas'],
    matchingKeywords: ['clerk', 'authentication', 'user management'],
    confidenceLevel: 'high',
    summary: 'Built authentication platform to 16M users, $30M funding.',
  },

  // INSURANCE & INSURTECH
  {
    companyName: 'Ledgebrook',
    industry: 'insurance',
    subIndustry: 'insurtech',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Insurance industry disruption', 'Regulatory hurdles', 'Capital requirements'],
      capabilities: ['Insurance expertise', 'Technology skills', 'Industry connections'],
      marketPosition: 'Insurtech startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$100M run rate',
      achievements: ['$100M run rate', 'Built in 19 months', 'Insurtech leader'],
      newCapabilities: ['Digital insurance platform', 'Rapid underwriting', 'Tech-enabled distribution'],
      marketPosition: 'Insurtech leader',
    },
    strategyType: 'rapid_scale',
    expansionType: 'market',
    targetMarket: 'insurance_buyers',
    timeline: { totalMonths: 19 },
    keyActions: [
      { action: 'Built insurtech to $100M run rate in 19 months', impact: 'Extraordinary speed', difficulty: 'hard' },
      { action: 'Disrupted traditional insurance with technology', impact: 'Industry disruption', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'Speed to market in insurtech can create massive value quickly.',
    sourceUrl: 'https://www.starterstory.com/ledgebrook-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['insurance', 'insurtech', 'fintech', 'rapid_growth'],
    matchingKeywords: ['ledgebrook', 'insurtech', 'insurance technology'],
    confidenceLevel: 'high',
    summary: 'Built $100M run rate insurtech in just 19 months.',
  },
  {
    companyName: 'AgentSync',
    industry: 'insurance',
    subIndustry: 'insurance_compliance',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Insurance compliance complexity', 'B2B enterprise sales', 'Market education'],
      capabilities: ['Insurance expertise', 'Compliance knowledge', 'Technical skills'],
      marketPosition: 'Insurance compliance startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '200_plus',
      revenueGrowth: '$20.3M/month (unicorn)',
      achievements: ['Unicorn in 3 years', '$20.3M/month', 'Insurance SaaS leader'],
      newCapabilities: ['Agent licensing', 'Compliance automation', 'Enterprise platform'],
      marketPosition: 'Insurance compliance unicorn',
    },
    strategyType: 'vertical_saas',
    expansionType: 'product',
    targetMarket: 'insurance_companies',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built SaaS for insurance agent compliance', impact: 'Vertical focus', difficulty: 'hard' },
      { action: 'Two founders built SaaS unicorn in 3 years', impact: 'Rapid unicorn', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 2000 },
    lessonsLearned: 'Vertical SaaS in regulated industries can reach unicorn status.',
    sourceUrl: 'https://www.starterstory.com/agentsync-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['insurance', 'saas', 'compliance', 'unicorn'],
    matchingKeywords: ['agentsync', 'insurance compliance', 'agent licensing'],
    confidenceLevel: 'high',
    summary: 'Two founders built insurance SaaS unicorn in 3 years.',
  },

  // ENERGY & SOLAR
  {
    companyName: 'Renogy',
    industry: 'energy',
    subIndustry: 'solar_diy',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['DIY solar education', 'Product development', 'Distribution'],
      capabilities: ['Engineering background', 'Solar expertise', 'E-commerce skills'],
      marketPosition: 'DIY solar startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$3.27M/month ($60M/year)',
      achievements: ['$60M/year', 'DIY solar leader', 'Renewable energy pioneer'],
      newCapabilities: ['Solar product line', 'Global distribution', 'Brand leadership'],
      marketPosition: 'DIY solar market leader',
    },
    strategyType: 'product_leadership',
    expansionType: 'product',
    targetMarket: 'diy_solar_enthusiasts',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Built DIY solar product company', impact: 'Market creation', difficulty: 'hard' },
      { action: 'Scaled to $60M/year in renewable energy', impact: 'Industry leadership', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 600 },
    lessonsLearned: 'DIY renewable energy market has massive potential.',
    sourceUrl: 'https://www.starterstory.com/renewal-enery-solar-diy-panels',
    sourcePlatform: 'starter_story',
    tags: ['energy', 'solar', 'diy', 'renewable'],
    matchingKeywords: ['renogy', 'diy solar', 'solar panels'],
    confidenceLevel: 'high',
    summary: 'Built $60M/year DIY solar company.',
  },
  {
    companyName: 'Solar Energy Partners',
    industry: 'energy',
    subIndustry: 'solar_installation',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Local competition', 'Installation scaling', 'Customer acquisition'],
      capabilities: ['Solar installation', 'Sales skills', 'Local market knowledge'],
      marketPosition: 'Local solar installer',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$24M/year',
      achievements: ['$24M/year', 'Regional solar leader', 'Installation excellence'],
      newCapabilities: ['Regional operations', 'Sales team', 'Installation fleet'],
      marketPosition: 'Regional solar installation leader',
    },
    strategyType: 'regional_expansion',
    expansionType: 'geographic',
    targetMarket: 'homeowners',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Scaled solar installation to regional leader', impact: 'Geographic expansion', difficulty: 'hard' },
      { action: 'Built $24M/year installation business', impact: 'Service scaling', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 240 },
    lessonsLearned: 'Solar installation can scale to significant regional businesses.',
    sourceUrl: 'https://www.starterstory.com/stories/our-small-solar-consultancy-today-business-makes-24m-year',
    sourcePlatform: 'starter_story',
    tags: ['energy', 'solar', 'installation', 'service'],
    matchingKeywords: ['solar energy partners', 'solar installation', 'solar business'],
    confidenceLevel: 'high',
    summary: 'Scaled solar installation business to $24M/year.',
  },

  // FASHION & ACCESSORIES
  {
    companyName: 'Tini Lux',
    industry: 'fashion',
    subIndustry: 'jewelry',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Jewelry market competition', 'Hypoallergenic niche', 'E-commerce growth'],
      capabilities: ['Product design', 'Niche understanding', 'E-commerce skills'],
      marketPosition: 'Niche jewelry startup',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '6_20',
      revenueGrowth: '$4M/year (10x growth)',
      achievements: ['$4M/year', '10x growth', 'Hypoallergenic earring leader'],
      newCapabilities: ['Titanium jewelry', 'DTC brand', 'Niche leadership'],
      marketPosition: 'Hypoallergenic jewelry leader',
    },
    strategyType: 'niche_focus',
    expansionType: 'product',
    targetMarket: 'sensitive_skin_consumers',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Created hypoallergenic titanium earrings', impact: 'Niche creation', difficulty: 'medium' },
      { action: 'Grew niche earring brand 10x to $4M/year', impact: 'Niche dominance', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 40 },
    lessonsLearned: 'Solving specific customer problems creates loyal niche markets.',
    sourceUrl: 'https://www.starterstory.com/stories/tini-lux',
    sourcePlatform: 'starter_story',
    tags: ['fashion', 'jewelry', 'niche', 'dtc'],
    matchingKeywords: ['tini lux', 'hypoallergenic earrings', 'titanium jewelry'],
    confidenceLevel: 'high',
    summary: 'Grew hypoallergenic earring brand 10x to $4M/year.',
  },

  // AI & TECHNOLOGY LEADERS
  {
    companyName: 'Anthropic',
    industry: 'technology',
    subIndustry: 'ai_research',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['AI safety focus', 'OpenAI competition', 'Massive funding needs'],
      capabilities: ['AI research', 'Safety expertise', 'OpenAI alumni'],
      marketPosition: 'AI research startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '200_plus',
      revenueGrowth: '$250M/month ($200M+ in 2024)',
      achievements: ['$200M+ revenue', '100K customers', 'Claude AI leader'],
      newCapabilities: ['Claude AI', 'Enterprise AI', 'Safety research'],
      marketPosition: 'AI safety and research leader',
    },
    strategyType: 'research_commercialization',
    expansionType: 'product',
    targetMarket: 'enterprises_developers',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built Claude AI with safety-first approach', impact: 'Differentiated positioning', difficulty: 'hard' },
      { action: 'Reached $200M+ revenue and 100K customers', impact: 'Rapid commercialization', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 2000 },
    lessonsLearned: 'AI safety focus can be a commercial differentiator.',
    sourceUrl: 'https://www.starterstory.com/anthropic-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['technology', 'ai', 'research', 'enterprise'],
    matchingKeywords: ['anthropic', 'claude ai', 'dario amodei'],
    confidenceLevel: 'high',
    summary: 'Built Claude AI to $200M+ revenue with safety-first approach.',
  },
  {
    companyName: 'Photoroom',
    industry: 'technology',
    subIndustry: 'ai_photo',
    location: 'France',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Photo editing competition', 'AI development', 'User acquisition'],
      capabilities: ['AI expertise', 'Mobile development', 'Product design'],
      marketPosition: 'AI photo startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$50M ARR',
      achievements: ['$50M ARR', 'From $2M funding', 'AI photo editing leader'],
      newCapabilities: ['Background removal', 'AI editing', 'E-commerce tools'],
      marketPosition: 'AI photo editing leader',
    },
    strategyType: 'capital_efficiency',
    expansionType: 'product',
    targetMarket: 'ecommerce_sellers',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built AI photo editing with minimal funding', impact: 'Capital efficiency', difficulty: 'hard' },
      { action: 'Scaled to $50M ARR from $2M funding', impact: '25x efficiency', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 500 },
    lessonsLearned: 'Capital-efficient AI companies can achieve massive scale.',
    sourceUrl: 'https://www.starterstory.com/photoroom-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['technology', 'ai', 'photo', 'ecommerce'],
    matchingKeywords: ['photoroom', 'ai photo editing', 'background removal'],
    confidenceLevel: 'high',
    summary: 'Scaled AI photo editing to $50M ARR from $2M funding.',
  },
  {
    companyName: 'Nooks',
    industry: 'technology',
    subIndustry: 'sales_ai',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Sales tech competition', 'AI dialer market', 'Enterprise adoption'],
      capabilities: ['AI development', 'Sales knowledge', 'Technical skills'],
      marketPosition: 'Sales AI startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$70M',
      achievements: ['$70M', 'Sales AI leader', 'Revolutionized sales calls'],
      newCapabilities: ['AI sales dialer', 'Virtual floor', 'Sales analytics'],
      marketPosition: 'AI sales call leader',
    },
    strategyType: 'ai_innovation',
    expansionType: 'product',
    targetMarket: 'sales_teams',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built AI-powered sales calling platform', impact: 'Sales transformation', difficulty: 'hard' },
      { action: '3 founders built to $70M revolutionizing sales', impact: 'Market leadership', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 700 },
    lessonsLearned: 'AI can transform traditional sales workflows.',
    sourceUrl: 'https://www.starterstory.com/nooks-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['technology', 'ai', 'sales', 'b2b'],
    matchingKeywords: ['nooks', 'ai sales', 'sales dialer'],
    confidenceLevel: 'high',
    summary: '3 founders built AI sales platform to $70M.',
  },
  {
    companyName: 'OpenPhone',
    industry: 'technology',
    subIndustry: 'business_phone',
    location: 'Canada',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Telecom competition', 'Business phone market', 'SMB sales'],
      capabilities: ['Product design', 'Telecom knowledge', 'Growth hacking'],
      marketPosition: 'Business phone startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '100K customers',
      achievements: ['100K customers', 'Business phone leader', 'Scrappy growth'],
      newCapabilities: ['Business phone system', 'CRM integration', 'Team collaboration'],
      marketPosition: 'Modern business phone leader',
    },
    strategyType: 'scrappy_growth',
    expansionType: 'market',
    targetMarket: 'small_businesses',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Used scrappy tactics to acquire customers', impact: 'Growth efficiency', difficulty: 'medium' },
      { action: 'Attracted 100K customers redefining business phones', impact: 'Market disruption', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Scrappy growth tactics can beat well-funded competitors.',
    sourceUrl: 'https://www.starterstory.com/openphone-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['technology', 'telecom', 'business_phone', 'smb'],
    matchingKeywords: ['openphone', 'business phone', 'phone system'],
    confidenceLevel: 'high',
    summary: 'Scrappy tactics attracted 100K customers to business phone.',
  },
  {
    companyName: 'ZenBusiness',
    industry: 'technology',
    subIndustry: 'business_formation',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['LegalZoom competition', 'Business formation market', 'SMB trust'],
      capabilities: ['Legal tech', 'SMB focus', 'Product design'],
      marketPosition: 'Business formation startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '200_plus',
      revenueGrowth: '$80M ARR',
      achievements: ['$80M ARR', 'Startup to scale in 4 years', 'Business formation leader'],
      newCapabilities: ['LLC formation', 'Registered agent', 'Business services'],
      marketPosition: 'Business formation alternative leader',
    },
    strategyType: 'challenger_brand',
    expansionType: 'product',
    targetMarket: 'entrepreneurs',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built LegalZoom alternative for business formation', impact: 'Competitive positioning', difficulty: 'hard' },
      { action: 'Skyrocketed from startup to $80M ARR in 4 years', impact: 'Rapid scale', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 800 },
    lessonsLearned: 'Challenger brands can grow quickly against established players.',
    sourceUrl: 'https://www.starterstory.com/zenbusiness-pbc-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['technology', 'legal_tech', 'business_formation', 'smb'],
    matchingKeywords: ['zenbusiness', 'llc formation', 'business formation'],
    confidenceLevel: 'high',
    summary: 'Grew business formation platform from startup to $80M ARR in 4 years.',
  },
];

async function seed() {
  console.log('🌱 Seeding Batch 15: Media, Security, Insurance, Energy, Fashion, AI Leaders...');

  let successCount = 0;
  let errorCount = 0;

  for (const study of batch15) {
    try {
      await db.insert(caseStudies).values(study as CaseStudyInsert);
      console.log(`  ✓ ${study.companyName}`);
      successCount++;
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : 'Unknown error';
      if (message.includes('duplicate')) {
        console.log(`  ⊘ ${study.companyName} (already exists)`);
      } else {
        console.log(`  ✗ ${study.companyName}: ${message}`);
        errorCount++;
      }
    }
  }

  console.log(`\nBatch 15 seeding complete!`);
  console.log(`✓ Successfully seeded: ${successCount}`);
  console.log(`✗ Errors: ${errorCount}`);

  process.exit(0);
}

seed().catch((e) => {
  console.error('Seed failed:', e);
  process.exit(1);
});
