import { db } from '../../lib/db';
import { caseStudies } from '../schema';

type CaseStudyInsert = typeof caseStudies.$inferInsert;

const batch16 = [
  // SPORTS & FITNESS
  {
    companyName: 'SWEAT (Kayla Itsines)',
    industry: 'fitness',
    subIndustry: 'fitness_app',
    location: 'Australia',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Fitness app competition', 'Monetization', 'Content creation'],
      capabilities: ['Fitness expertise', 'Social media following', 'Program design'],
      marketPosition: 'Fitness influencer',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '200_plus',
      revenueGrowth: '$8.33M/month ($400M exit)',
      achievements: ['$400M exit to iFIT', 'Fitness app empire', 'Global brand'],
      newCapabilities: ['Mobile app platform', 'Global fitness community', 'Multiple programs'],
      marketPosition: 'Fitness app leader',
    },
    strategyType: 'influencer_to_product',
    expansionType: 'product',
    targetMarket: 'women_fitness',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Built fitness app empire from influencer status', impact: 'Platform creation', difficulty: 'hard' },
      { action: 'Sold SWEAT app for $400M', impact: 'Massive exit', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 4000 },
    lessonsLearned: 'Influencer audiences can be monetized through product platforms.',
    sourceUrl: 'https://www.starterstory.com/sweat-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['fitness', 'app', 'influencer', 'acquisition'],
    matchingKeywords: ['sweat', 'kayla itsines', 'fitness app'],
    confidenceLevel: 'high',
    summary: 'Built fitness app empire sold for $400M.',
  },
  {
    companyName: 'Allbirds',
    industry: 'fashion',
    subIndustry: 'sustainable_footwear',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Footwear market competition', 'Sustainable materials', 'DTC scaling'],
      capabilities: ['Product design', 'Sustainability focus', 'Branding'],
      marketPosition: 'Sustainable shoe startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '200_plus',
      revenueGrowth: '$20M/month ($600M brand)',
      achievements: ['$600M brand', 'Sustainable footwear pioneer', 'DTC success'],
      newCapabilities: ['Sustainable materials', 'Global retail', 'Brand recognition'],
      marketPosition: 'Sustainable shoe leader',
    },
    strategyType: 'sustainability_brand',
    expansionType: 'product',
    targetMarket: 'eco_conscious_consumers',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Created sustainable wool footwear', impact: 'Category creation', difficulty: 'hard' },
      { action: 'Bootstrapped to $600M sustainable shoe brand', impact: 'Brand building', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 6000 },
    lessonsLearned: 'Sustainability can be a powerful differentiator in commodity markets.',
    sourceUrl: 'https://www.starterstory.com/allbirds-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['fashion', 'sustainability', 'footwear', 'dtc'],
    matchingKeywords: ['allbirds', 'sustainable shoes', 'tim brown'],
    confidenceLevel: 'high',
    summary: 'Bootstrapped sustainable shoe brand to $600M.',
  },
  {
    companyName: 'Cotopaxi',
    industry: 'fashion',
    subIndustry: 'outdoor_gear',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Outdoor gear competition', 'Humanitarian mission', 'Brand differentiation'],
      capabilities: ['Product design', 'Mission-driven', 'Adventure focus'],
      marketPosition: 'Mission-driven outdoor startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$100M+ brand',
      achievements: ['$100M+ brand', 'B-Corp certified', 'Humanitarian impact'],
      newCapabilities: ['Sustainable outdoor gear', 'Adventure events', 'Social impact'],
      marketPosition: 'Mission-driven outdoor leader',
    },
    strategyType: 'mission_driven',
    expansionType: 'product',
    targetMarket: 'outdoor_adventurers',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Created outdoor gear brand with humanitarian mission', impact: 'Differentiated positioning', difficulty: 'hard' },
      { action: 'Built $100M+ mission-driven brand', impact: 'Values-based growth', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'Mission-driven brands can compete against established players.',
    sourceUrl: 'https://www.starterstory.com/davis-smith',
    sourcePlatform: 'starter_story',
    tags: ['fashion', 'outdoor', 'mission', 'sustainability'],
    matchingKeywords: ['cotopaxi', 'outdoor gear', 'davis smith'],
    confidenceLevel: 'high',
    summary: 'Built $100M+ outdoor gear brand with humanitarian mission.',
  },
  {
    companyName: 'Good Sport',
    industry: 'ecommerce',
    subIndustry: 'sports_brand',
    location: 'USA',
    startingState: {
      revenue: '1m_5m',
      teamSize: '6_20',
      yearsInBusiness: 5,
      challenges: ['Brand launch strategy', 'YouTuber partnership', 'Product development'],
      capabilities: ['E-commerce expertise', 'Influencer relationships', 'Brand building'],
      marketPosition: '8-figure e-commerce company',
    },
    endingState: {
      revenue: '5m_10m',
      teamSize: '21_50',
      revenueGrowth: 'Joint brand success',
      achievements: ['YouTuber collaboration', '15M followers partnership', 'Brand launch'],
      newCapabilities: ['Influencer partnerships', 'Sports branding', 'Content marketing'],
      marketPosition: 'Influencer-backed sports brand',
    },
    strategyType: 'influencer_partnership',
    expansionType: 'product',
    targetMarket: 'sports_enthusiasts',
    timeline: { totalMonths: 12 },
    keyActions: [
      { action: 'Partnered with 15M subscriber YouTuber', impact: 'Instant audience', difficulty: 'medium' },
      { action: '8-figure company launched influencer brand', impact: 'Leverage success', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 3 },
    lessonsLearned: 'Influencer partnerships can accelerate brand launches.',
    sourceUrl: 'https://www.starterstory.com/stories/good-sport',
    sourcePlatform: 'starter_story',
    tags: ['ecommerce', 'sports', 'influencer', 'youtube'],
    matchingKeywords: ['good sport', 'influencer brand', 'sports'],
    confidenceLevel: 'high',
    summary: '8-figure company partnered with 15M YouTuber for brand launch.',
  },

  // DESIGN & CREATIVE
  {
    companyName: 'Design Joy',
    industry: 'design_agency',
    subIndustry: 'subscription_design',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Agency model scaling', 'Solo founder', 'Pricing innovation'],
      capabilities: ['Design skills', 'Business acumen', 'Subscription thinking'],
      marketPosition: 'Solo designer',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '1_5',
      revenueGrowth: '$1.7M ARR',
      achievements: ['$1.7M ARR solo', 'Subscription design pioneer', 'Design productization'],
      newCapabilities: ['Productized service', 'Async workflow', 'Premium positioning'],
      marketPosition: 'Subscription design leader',
    },
    strategyType: 'productized_service',
    expansionType: 'service',
    targetMarket: 'startups',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Created subscription-based design service', impact: 'Model innovation', difficulty: 'hard' },
      { action: 'Solo founder built to $1.7M ARR', impact: 'Efficiency mastery', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 170 },
    lessonsLearned: 'Productized services can scale without hiring.',
    sourceUrl: 'https://www.starterstory.com/stories/design-joy-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['design', 'subscription', 'solo_founder', 'productized'],
    matchingKeywords: ['design joy', 'brett williams', 'subscription design'],
    confidenceLevel: 'high',
    summary: 'Solo founder built subscription design to $1.7M ARR.',
  },
  {
    companyName: 'Baked Design',
    industry: 'design_agency',
    subIndustry: 'subscription_design',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Design agency competition', 'Rapid scaling', 'Service delivery'],
      capabilities: ['Design expertise', 'Business skills', 'Subscription model'],
      marketPosition: 'New design agency',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '6_20',
      revenueGrowth: '$100K MRR in 6 months',
      achievements: ['$100K MRR', '6-month scale', 'Subscription design success'],
      newCapabilities: ['High-volume design', 'Subscription fulfillment', 'Team scaling'],
      marketPosition: 'Growing subscription agency',
    },
    strategyType: 'rapid_scale',
    expansionType: 'service',
    targetMarket: 'startups_smbs',
    timeline: { totalMonths: 6 },
    keyActions: [
      { action: 'Launched subscription design agency', impact: 'Model validation', difficulty: 'medium' },
      { action: 'Scaled to $100K MRR in 6 months', impact: 'Rapid growth', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 120 },
    lessonsLearned: 'Subscription design agencies can scale rapidly.',
    sourceUrl: 'https://www.starterstory.com/baked-design-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['design', 'subscription', 'agency', 'rapid_growth'],
    matchingKeywords: ['baked design', 'subscription agency', 'design subscription'],
    confidenceLevel: 'high',
    summary: 'Scaled design subscription agency to $100K MRR in 6 months.',
  },
  {
    companyName: 'Looka',
    industry: 'technology',
    subIndustry: 'ai_design',
    location: 'Canada',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['AI logo competition', 'Design quality', 'User acquisition'],
      capabilities: ['AI development', 'Design understanding', 'Product vision'],
      marketPosition: 'AI logo startup',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '21_50',
      revenueGrowth: '$70K/month',
      achievements: ['$70K/month', 'AI logo design leader', 'Self-service branding'],
      newCapabilities: ['AI logo generation', 'Brand kit creation', 'Self-service design'],
      marketPosition: 'AI logo design leader',
    },
    strategyType: 'ai_democratization',
    expansionType: 'product',
    targetMarket: 'small_businesses',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built AI-powered logo design platform', impact: 'Design democratization', difficulty: 'hard' },
      { action: 'Transformed logo design into $70K/month business', impact: 'Market creation', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 84 },
    lessonsLearned: 'AI can democratize professional design services.',
    sourceUrl: 'https://www.starterstory.com/looka-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['technology', 'ai', 'design', 'logos'],
    matchingKeywords: ['looka', 'ai logo', 'logo design'],
    confidenceLevel: 'high',
    summary: 'AI logo design platform reaching $70K/month.',
  },
  {
    companyName: 'DesignCode',
    industry: 'education',
    subIndustry: 'design_education',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Online education competition', 'Course creation', 'Community building'],
      capabilities: ['Design expertise', 'Teaching ability', 'Content creation'],
      marketPosition: 'Design educator',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '6_20',
      revenueGrowth: '$83.3K/month ($1M/year)',
      achievements: ['$1M/year', 'Design education leader', 'Community building'],
      newCapabilities: ['Course platform', 'Design community', 'Premium education'],
      marketPosition: 'Design education leader',
    },
    strategyType: 'expertise_monetization',
    expansionType: 'product',
    targetMarket: 'designers',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Built design education business', impact: 'Knowledge monetization', difficulty: 'medium' },
      { action: 'Reached $1M/year in design education', impact: 'Education scale', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Design expertise can be monetized through education.',
    sourceUrl: 'https://www.starterstory.com/designcode-io-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['education', 'design', 'courses', 'community'],
    matchingKeywords: ['designcode', 'meng to', 'design education'],
    confidenceLevel: 'high',
    summary: 'Built $1M/year design education business.',
  },
  {
    companyName: 'MadeByShape',
    industry: 'design_agency',
    subIndustry: 'web_design',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['$200 website pricing', 'Value perception', 'Premium positioning'],
      capabilities: ['Web design skills', 'Client relationships', 'Growth mindset'],
      marketPosition: 'Cheap web designer',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '6_20',
      revenueGrowth: '$600K/year ($100K projects)',
      achievements: ['$600K/year', '$100K projects', 'Premium agency'],
      newCapabilities: ['Premium positioning', 'Enterprise clients', 'Full-service agency'],
      marketPosition: 'Premium web design agency',
    },
    strategyType: 'premium_positioning',
    expansionType: 'service',
    targetMarket: 'enterprises',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Evolved from $200 websites to $100K projects', impact: 'Value evolution', difficulty: 'hard' },
      { action: 'Built $600K/year premium web design agency', impact: 'Premium scaling', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 3000 },
    lessonsLearned: 'Premium positioning transforms service business economics.',
    sourceUrl: 'https://www.starterstory.com/stories/i-went-from-designing-website-for-200-to-starting-a-studio-that-makes-100k-projects',
    sourcePlatform: 'starter_story',
    tags: ['design', 'web_design', 'agency', 'premium'],
    matchingKeywords: ['madebyshape', 'web design', 'andy golpys'],
    confidenceLevel: 'high',
    summary: 'From $200 websites to $600K/year agency with $100K projects.',
  },
  {
    companyName: 'Art.com',
    industry: 'ecommerce',
    subIndustry: 'art_marketplace',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Art marketplace creation', 'E-commerce scaling', 'Inventory management'],
      capabilities: ['E-commerce skills', 'Art market knowledge', 'Technology'],
      marketPosition: 'Art e-commerce startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '200_plus',
      revenueGrowth: '$8.33M/month ($200M/year sold to Walmart)',
      achievements: ['$200M/year', 'Sold to Walmart', 'Art e-commerce leader'],
      newCapabilities: ['Art marketplace', 'Global shipping', 'Print-on-demand'],
      marketPosition: 'Art e-commerce leader',
    },
    strategyType: 'marketplace_building',
    expansionType: 'market',
    targetMarket: 'art_buyers',
    timeline: { totalMonths: 240 },
    keyActions: [
      { action: 'Bootstrapped art marketplace from $35K', impact: 'Capital efficiency', difficulty: 'hard' },
      { action: 'Built to $200M/year and sold to Walmart', impact: 'Strategic exit', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 5700 },
    lessonsLearned: 'Niche marketplaces can achieve massive scale.',
    sourceUrl: 'https://www.starterstory.com/art-com-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['ecommerce', 'art', 'marketplace', 'acquisition'],
    matchingKeywords: ['art.com', 'art marketplace', 'walmart acquisition'],
    confidenceLevel: 'high',
    summary: 'Bootstrapped to $200M/year art marketplace, sold to Walmart.',
  },

  // HOME & INTERIOR
  {
    companyName: 'Heather Garrett Design',
    industry: 'services',
    subIndustry: 'interior_design',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Interior design competition', 'Client acquisition', 'Portfolio building'],
      capabilities: ['Interior design skills', 'Client relationships', 'Project management'],
      marketPosition: 'New interior designer',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '1_5',
      revenueGrowth: 'Established design firm',
      achievements: ['Successful design firm', 'High-end clients', 'Industry recognition'],
      newCapabilities: ['Full-service design', 'Project management', 'Vendor relationships'],
      marketPosition: 'Established interior designer',
    },
    strategyType: 'personal_brand',
    expansionType: 'service',
    targetMarket: 'homeowners',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built interior design business', impact: 'Service establishment', difficulty: 'medium' },
      { action: 'Developed high-end client base', impact: 'Premium positioning', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Interior design businesses scale through reputation and referrals.',
    sourceUrl: 'https://www.starterstory.com/interior-design',
    sourcePlatform: 'starter_story',
    tags: ['services', 'interior_design', 'personal_brand', 'home'],
    matchingKeywords: ['heather garrett', 'interior design', 'design firm'],
    confidenceLevel: 'high',
    summary: 'Built successful interior design firm.',
  },

  // ADDITIONAL TECH & SaaS
  {
    companyName: 'Hexbox Fitness',
    industry: 'fitness',
    subIndustry: 'fitness_facility',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Gym market competition', 'Unique concept', 'Location selection'],
      capabilities: ['Fitness expertise', 'Business planning', 'Concept innovation'],
      marketPosition: 'New gym concept',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '6_20',
      revenueGrowth: 'Subscription-based gym',
      achievements: ['Unique fitness concept', 'Membership model', 'Local success'],
      newCapabilities: ['Innovative equipment', 'Membership management', 'Community building'],
      marketPosition: 'Innovative local gym',
    },
    strategyType: 'concept_innovation',
    expansionType: 'service',
    targetMarket: 'fitness_enthusiasts',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Created unique fitness facility concept', impact: 'Differentiation', difficulty: 'medium' },
      { action: 'Built subscription membership model', impact: 'Recurring revenue', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Innovative concepts can differentiate in crowded markets.',
    sourceUrl: 'https://www.starterstory.com/stories/hexbox-fitness-a-business-model-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['fitness', 'gym', 'subscription', 'local'],
    matchingKeywords: ['hexbox fitness', 'gym concept', 'fitness facility'],
    confidenceLevel: 'high',
    summary: 'Built innovative subscription-based fitness facility.',
  },
  {
    companyName: 'Vidovo',
    industry: 'creator_economy',
    subIndustry: 'ugc_platform',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['UGC market creation', 'Creator marketplace', 'Brand adoption'],
      capabilities: ['Product development', 'Marketplace skills', 'Creator understanding'],
      marketPosition: 'UGC platform startup',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '6_20',
      revenueGrowth: '$1M/year',
      achievements: ['$1M/year', 'UGC video platform', 'Bootstrapped success'],
      newCapabilities: ['Creator marketplace', 'UGC production', 'Brand connections'],
      marketPosition: 'UGC platform leader',
    },
    strategyType: 'marketplace_creation',
    expansionType: 'product',
    targetMarket: 'brands_creators',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built UGC video ads platform', impact: 'Market creation', difficulty: 'hard' },
      { action: 'Bootstrapped creator app to $1M/year', impact: 'Profitable growth', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'UGC marketplaces can be bootstrapped to profitability.',
    sourceUrl: 'https://www.starterstory.com/stories/vidovo-com-ugc-video-ads-made-easy',
    sourcePlatform: 'starter_story',
    tags: ['creator_economy', 'ugc', 'marketplace', 'video'],
    matchingKeywords: ['vidovo', 'ugc platform', 'video ads'],
    confidenceLevel: 'high',
    summary: 'Bootstrapped UGC video platform to $1M/year.',
  },
];

async function seed() {
  console.log('🌱 Seeding Batch 16: Sports, Design, Art, Home...');

  let successCount = 0;
  let errorCount = 0;

  for (const study of batch16) {
    try {
      await db.insert(caseStudies).values(study as CaseStudyInsert);
      console.log(`  ✓ ${study.companyName}`);
      successCount++;
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : 'Unknown error';
      if (message.includes('duplicate')) {
        console.log(`  ⊘ ${study.companyName} (already exists)`);
      } else {
        console.log(`  ✗ ${study.companyName}: ${message}`);
        errorCount++;
      }
    }
  }

  console.log(`\nBatch 16 seeding complete!`);
  console.log(`✓ Successfully seeded: ${successCount}`);
  console.log(`✗ Errors: ${errorCount}`);

  process.exit(0);
}

seed().catch((e) => {
  console.error('Seed failed:', e);
  process.exit(1);
});
