import { db } from '../../lib/db';
import { caseStudies } from '../schema';

type CaseStudyInsert = typeof caseStudies.$inferInsert;

const batch8CaseStudies = [
  // === SAAS / SOFTWARE ===
  {
    companyName: 'Cledara',
    industry: 'saas',
    subIndustry: 'fintech',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['SaaS subscription chaos', 'No visibility into software spend', 'Manual tracking processes'],
      capabilities: ['Banking experience', 'Fintech background', 'Product vision'],
      marketPosition: 'New SaaS management platform',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '50_200',
      revenueGrowth: '$2.5M/month (~$30M ARR)',
      achievements: ['$30M ARR', 'Profitable', 'Leading SaaS management platform'],
      newCapabilities: ['Enterprise sales', 'Global expansion', 'Platform integrations'],
      marketPosition: 'Top SaaS spend management solution',
    },
    strategyType: 'product_led_growth',
    expansionType: 'vertical',
    targetMarket: 'finance_teams',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Built subscription management platform for finance teams', impact: 'Solved real pain point', difficulty: 'hard' },
      { action: 'Focused on visibility and control of SaaS spend', impact: 'Clear value proposition', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 300 },
    lessonsLearned: 'B2B fintech solving specific pain points can scale rapidly with focused positioning.',
    sourceUrl: 'https://www.starterstory.com/cledara-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'fintech', 'b2b', 'subscription_management'],
    matchingKeywords: ['saas management', 'subscription tracking', 'fintech'],
    confidenceLevel: 'high',
    summary: 'Built Cledara to nearly $30M ARR as a SaaS subscription management platform.',
  },
  {
    companyName: 'Rippling',
    industry: 'saas',
    subIndustry: 'hr_tech',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Previous company failure (Zenefits)', 'Reputation rebuild', 'Crowded HR market'],
      capabilities: ['Deep HR tech experience', 'Previous scale-up knowledge', 'Technical expertise'],
      marketPosition: 'New HR & IT platform',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '500_plus',
      revenueGrowth: '$350M ARR',
      achievements: ['$350M ARR', '$13.5B valuation', '2000+ employees', 'Unified HR & IT platform'],
      newCapabilities: ['Full employee lifecycle platform', 'IT management', 'Global payroll'],
      marketPosition: 'Leading workforce management platform',
    },
    strategyType: 'platform_scale',
    expansionType: 'horizontal',
    targetMarket: 'mid_market_enterprise',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Unified HR and IT into single employee graph', impact: 'Breakthrough architecture', difficulty: 'hard' },
      { action: 'Built comprehensive workforce platform', impact: 'Higher ARPU than competitors', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 3500 },
    lessonsLearned: 'Founder redemption stories with better execution can lead to massive outcomes.',
    sourceUrl: 'https://www.starterstory.com/rippling-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'hr_tech', 'unicorn', 'platform'],
    matchingKeywords: ['hr software', 'it management', 'workforce platform'],
    confidenceLevel: 'high',
    summary: 'Built Rippling to $350M ARR unified HR & IT platform after Zenefits failure.',
  },
  {
    companyName: 'Keap',
    industry: 'saas',
    subIndustry: 'crm',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Started in garage', 'No funding initially', 'Competitive CRM market'],
      capabilities: ['Technical skills', 'Sales background', 'Persistence'],
      marketPosition: 'New small business CRM',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '200_500',
      revenueGrowth: '$7.5M/month ($90M/year)',
      achievements: ['$90M revenue', '323 employees', '652K monthly traffic', 'Profitable'],
      newCapabilities: ['Marketing automation', 'E-commerce integration', 'Enterprise features'],
      marketPosition: 'Leading SMB CRM platform',
    },
    strategyType: 'bootstrapped_growth',
    expansionType: 'vertical',
    targetMarket: 'small_business',
    timeline: { totalMonths: 276 },
    keyActions: [
      { action: 'Bootstrapped from garage to enterprise', impact: 'Sustainable growth', difficulty: 'hard' },
      { action: 'Focused exclusively on small business needs', impact: 'Strong market position', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 900 },
    lessonsLearned: 'Long-term bootstrapped growth focused on SMB can build massive sustainable businesses.',
    sourceUrl: 'https://www.starterstory.com/keap-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'crm', 'bootstrapped', 'smb'],
    matchingKeywords: ['crm software', 'small business', 'marketing automation'],
    confidenceLevel: 'high',
    summary: 'Grew Keap from garage startup to $90M/year SMB CRM business.',
  },
  {
    companyName: 'Customer.io',
    industry: 'saas',
    subIndustry: 'marketing_automation',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Started with $120/year first customer', 'Bootstrapped', 'Competitive email market'],
      capabilities: ['Technical expertise', 'Customer focus', 'Product vision'],
      marketPosition: 'New customer messaging platform',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '50_200',
      revenueGrowth: '$5.83M/month ($70M ARR)',
      achievements: ['$70M ARR', '336K monthly traffic', 'Profitable', 'Remote-first company'],
      newCapabilities: ['Advanced segmentation', 'Multi-channel messaging', 'Data pipeline integrations'],
      marketPosition: 'Leading customer messaging platform',
    },
    strategyType: 'product_led_growth',
    expansionType: 'vertical',
    targetMarket: 'tech_companies',
    timeline: { totalMonths: 144 },
    keyActions: [
      { action: 'Started with $120/year first customer', impact: 'Validated product early', difficulty: 'medium' },
      { action: 'Built powerful automation platform for marketers', impact: 'Developer-friendly differentiation', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 5833 },
    lessonsLearned: 'Starting small with paying customers and iterating can lead to massive growth.',
    sourceUrl: 'https://www.starterstory.com/customer-io-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'email', 'marketing_automation', 'bootstrapped'],
    matchingKeywords: ['customer messaging', 'email marketing', 'automation'],
    confidenceLevel: 'high',
    summary: 'Scaled Customer.io from $120/year first customer to $70M ARR.',
  },
  {
    companyName: 'Ninety',
    industry: 'saas',
    subIndustry: 'business_os',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Solo founder', 'Bootstrapped', 'Competing with established EOS tools'],
      capabilities: ['Business coaching background', 'Product vision', 'Capital from previous exits'],
      marketPosition: 'New business operating system',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '10_50',
      revenueGrowth: '$2.5M/month ($30M/year)',
      achievements: ['$30M revenue', '25 employees', 'Profitable', 'Leading EOS platform'],
      newCapabilities: ['Full EOS implementation', 'Team alignment tools', 'Meeting management'],
      marketPosition: 'Leading EOS software platform',
    },
    strategyType: 'bootstrapped_growth',
    expansionType: 'vertical',
    targetMarket: 'eos_companies',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built comprehensive EOS implementation platform', impact: 'Captured niche market', difficulty: 'medium' },
      { action: 'Bootstrapped to $30M without external funding', impact: 'Full ownership retained', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 300 },
    lessonsLearned: 'Niche markets with passionate communities can support large bootstrapped businesses.',
    sourceUrl: 'https://www.starterstory.com/ninety-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'business_os', 'eos', 'bootstrapped'],
    matchingKeywords: ['eos software', 'business operating system', 'team alignment'],
    confidenceLevel: 'high',
    summary: 'Bootstrapped Ninety to $30M in revenue as solo founder.',
  },
  {
    companyName: 'CAKE.com',
    industry: 'saas',
    subIndustry: 'productivity',
    location: 'Serbia',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Eastern European startup', 'Multiple product pivots', 'Global competition'],
      capabilities: ['Technical skills', 'Product intuition', 'Persistence'],
      marketPosition: 'New productivity suite',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '50_200',
      revenueGrowth: '$8.33M/month ($100M ARR)',
      achievements: ['$100M+ ARR', 'Multiple products', 'Profitable', 'Global user base'],
      newCapabilities: ['Time tracking', 'Project management', 'Team collaboration'],
      marketPosition: 'Leading productivity platform',
    },
    strategyType: 'product_led_growth',
    expansionType: 'horizontal',
    targetMarket: 'global_teams',
    timeline: { totalMonths: 180 },
    keyActions: [
      { action: 'Built Clockify as freemium time tracker', impact: 'Massive user acquisition', difficulty: 'medium' },
      { action: 'Expanded to full productivity suite', impact: 'Higher ARPU', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'Freemium products with viral mechanics can build massive global businesses.',
    sourceUrl: 'https://www.starterstory.com/cake-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'productivity', 'time_tracking', 'freemium'],
    matchingKeywords: ['time tracking', 'productivity software', 'clockify'],
    confidenceLevel: 'high',
    summary: 'Grew CAKE.com to $25M+ ARR SaaS success from Serbia.',
  },
  {
    companyName: 'Chili Piper',
    industry: 'saas',
    subIndustry: 'sales_tech',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Competitive sales tech market', 'Building trust', 'Product-market fit'],
      capabilities: ['Sales experience', 'Technical background', 'Customer obsession'],
      marketPosition: 'New meeting scheduling platform',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '50_200',
      revenueGrowth: '$40M ARR',
      achievements: ['$40M revenue', 'Profitable', 'Leading inbound scheduling platform'],
      newCapabilities: ['Revenue intelligence', 'Lead routing', 'Meeting automation'],
      marketPosition: 'Top B2B scheduling solution',
    },
    strategyType: 'product_led_growth',
    expansionType: 'vertical',
    targetMarket: 'b2b_sales_teams',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Focused on instant meeting scheduling', impact: 'Clear differentiation', difficulty: 'medium' },
      { action: 'Built for revenue teams specifically', impact: 'Strong product-market fit', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 400 },
    lessonsLearned: 'Solving specific pain points for revenue teams can build large vertical SaaS businesses.',
    sourceUrl: 'https://www.starterstory.com/chili-piper-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'sales_tech', 'scheduling', 'b2b'],
    matchingKeywords: ['meeting scheduling', 'sales software', 'lead routing'],
    confidenceLevel: 'high',
    summary: 'Grew Chili Piper to $40M revenue as B2B scheduling platform.',
  },
  {
    companyName: 'Softr',
    industry: 'saas',
    subIndustry: 'no_code',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Crowded no-code market', 'Technical differentiation', 'User education'],
      capabilities: ['Technical expertise', 'Product design skills', 'Market timing'],
      marketPosition: 'New no-code platform',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '10_50',
      revenueGrowth: '35,000+ users in 1 year',
      achievements: ['35,000 users', 'Y Combinator backed', 'Leading Airtable-based app builder'],
      newCapabilities: ['App templates', 'Custom domains', 'User authentication'],
      marketPosition: 'Top no-code app builder',
    },
    strategyType: 'product_led_growth',
    expansionType: 'platform',
    targetMarket: 'non_technical_builders',
    timeline: { totalMonths: 12 },
    keyActions: [
      { action: 'Built no-code platform on top of Airtable', impact: 'Leveraged existing ecosystem', difficulty: 'medium' },
      { action: 'Achieved 35K users in first year', impact: 'Rapid growth', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Building on top of popular platforms can accelerate growth significantly.',
    sourceUrl: 'https://www.starterstory.com/softr-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'no_code', 'platform', 'airtable'],
    matchingKeywords: ['no code', 'app builder', 'airtable'],
    confidenceLevel: 'high',
    summary: 'Built Softr to 35,000 users as no-code platform in 1 year.',
  },
  {
    companyName: 'Ghost',
    industry: 'saas',
    subIndustry: 'publishing',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Competing with WordPress', 'Open source monetization', 'Building community'],
      capabilities: ['Technical expertise', 'Design skills', 'Open source experience'],
      marketPosition: 'New open-source publishing platform',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '10_50',
      revenueGrowth: '$750K ARR',
      achievements: ['$750K ARR', 'Millions of users', 'Profitable non-profit', 'Kickstarter success'],
      newCapabilities: ['Membership features', 'Newsletter integration', 'Subscription commerce'],
      marketPosition: 'Leading open-source publishing platform',
    },
    strategyType: 'open_source_growth',
    expansionType: 'community',
    targetMarket: 'publishers_creators',
    timeline: { totalMonths: 132 },
    keyActions: [
      { action: 'Raised $300K on Kickstarter for open-source platform', impact: 'Community funding model', difficulty: 'medium' },
      { action: 'Built sustainable non-profit business model', impact: 'Mission-driven growth', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 75 },
    lessonsLearned: 'Open source with managed hosting can build sustainable businesses.',
    sourceUrl: 'https://www.starterstory.com/ghost-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'publishing', 'open_source', 'newsletter'],
    matchingKeywords: ['publishing platform', 'open source', 'newsletter'],
    confidenceLevel: 'high',
    summary: 'Grew Ghost to $750K ARR open-source publishing platform.',
  },
  {
    companyName: 'Bannerbear',
    industry: 'saas',
    subIndustry: 'design_automation',
    location: 'Singapore',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Solo founder', 'Technical product', 'API-first approach'],
      capabilities: ['Full-stack development', 'Design background', 'Indie hacker community'],
      marketPosition: 'New image generation API',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '1',
      revenueGrowth: '$50K MRR',
      achievements: ['$50K MRR', 'Solo founder', 'Profitable', 'Automated design at scale'],
      newCapabilities: ['Video generation', 'Template marketplace', 'Advanced API'],
      marketPosition: 'Leading automated image generation API',
    },
    strategyType: 'bootstrapped_growth',
    expansionType: 'vertical',
    targetMarket: 'developers',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built API for automated image/video generation', impact: 'Unique technical product', difficulty: 'hard' },
      { action: 'Stayed solo while reaching $50K MRR', impact: 'Maximum profitability', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Solo founders can build profitable SaaS with focus and automation.',
    sourceUrl: 'https://www.starterstory.com/stories/bannerbear-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'api', 'design_automation', 'solo_founder'],
    matchingKeywords: ['image generation', 'api', 'automation'],
    confidenceLevel: 'high',
    summary: 'Bootstrapped Bannerbear to $50K MRR as solo founder in 3 years.',
  },
  {
    companyName: 'Standuply',
    industry: 'saas',
    subIndustry: 'team_productivity',
    location: 'Russia',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Remote team management', 'Slack app ecosystem', 'Bootstrapped growth'],
      capabilities: ['Technical skills', 'Agile experience', 'Product focus'],
      marketPosition: 'New Slack standup bot',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '6_10',
      revenueGrowth: '$80K MRR',
      achievements: ['$80K MRR', '9 employees', 'Profitable', 'Leading standup bot'],
      newCapabilities: ['Async standups', 'Survey tools', 'Team analytics'],
      marketPosition: 'Top Slack standup solution',
    },
    strategyType: 'bootstrapped_growth',
    expansionType: 'vertical',
    targetMarket: 'remote_teams',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Built Slack bot for async standups', impact: 'Solved remote team problem', difficulty: 'medium' },
      { action: 'Bootstrapped to $80K MRR from Russia', impact: 'Global reach', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 80 },
    lessonsLearned: 'Slack apps serving specific workflows can build sustainable businesses.',
    sourceUrl: 'https://www.starterstory.com/standuply-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'slack', 'productivity', 'remote_work'],
    matchingKeywords: ['standup bot', 'slack app', 'remote teams'],
    confidenceLevel: 'high',
    summary: 'Bootstrapped Standuply to $80K MRR Slack standup bot.',
  },
  {
    companyName: 'Prerender.io',
    industry: 'saas',
    subIndustry: 'seo_tools',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Solo technical founder', 'Niche SEO problem', 'Developer marketing'],
      capabilities: ['Deep technical expertise', 'SEO knowledge', 'Developer background'],
      marketPosition: 'New prerendering service',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '1',
      revenueGrowth: '$2.5M/year',
      achievements: ['$2.5M/year', 'Solo founder', '5 years to scale', 'Profitable'],
      newCapabilities: ['Enterprise features', 'Global CDN', 'Advanced caching'],
      marketPosition: 'Leading JavaScript SEO solution',
    },
    strategyType: 'bootstrapped_growth',
    expansionType: 'vertical',
    targetMarket: 'developers',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built prerendering service for JavaScript SEO', impact: 'Solved technical SEO problem', difficulty: 'hard' },
      { action: 'Scaled to $2.5M as solo founder', impact: 'High-margin business', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 250 },
    lessonsLearned: 'Technical tools solving developer pain points can scale with minimal team.',
    sourceUrl: 'https://www.starterstory.com/how-to-bootstrap-saas-company',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'seo', 'developer_tools', 'solo_founder'],
    matchingKeywords: ['prerendering', 'javascript seo', 'developer tools'],
    confidenceLevel: 'high',
    summary: 'Bootstrapped Prerender.io to $2.5M/year as solo founder.',
  },
  {
    companyName: 'Kovai.co',
    industry: 'saas',
    subIndustry: 'enterprise_software',
    location: 'India',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Building from India', 'Enterprise market', 'Multiple products'],
      capabilities: ['Technical expertise', 'Enterprise experience', 'Product vision'],
      marketPosition: 'New enterprise SaaS suite',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '50_200',
      revenueGrowth: '$10M annual revenue',
      achievements: ['$10M revenue', 'Multi-product enterprise', 'Profitable', 'Global customers'],
      newCapabilities: ['Multiple SaaS products', 'Enterprise integrations', 'Global support'],
      marketPosition: 'Multi-product enterprise SaaS',
    },
    strategyType: 'bootstrapped_growth',
    expansionType: 'horizontal',
    targetMarket: 'enterprise',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Built multiple enterprise SaaS products', impact: 'Diversified revenue', difficulty: 'hard' },
      { action: 'Bootstrapped to $10M from India', impact: 'Proved global reach from India', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Multi-product strategy can diversify risk and accelerate enterprise growth.',
    sourceUrl: 'https://www.starterstory.com/stories/kovai-co',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'enterprise', 'multi_product', 'india'],
    matchingKeywords: ['enterprise saas', 'multi-product', 'india startup'],
    confidenceLevel: 'high',
    summary: 'Bootstrapped Kovai.co to $10M annual revenue multi-product SaaS.',
  },
  {
    companyName: 'PlaybookUX',
    industry: 'saas',
    subIndustry: 'ux_research',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Solo female founder', 'Competitive UX research market', 'Building without funding'],
      capabilities: ['UX research background', 'Technical skills', 'Customer empathy'],
      marketPosition: 'New UX research platform',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '6_10',
      revenueGrowth: '$1.8M/year',
      achievements: ['$1.8M/year', 'Bootstrapped', 'Profitable', 'Strong customer base'],
      newCapabilities: ['User testing', 'Interview tools', 'Analysis features'],
      marketPosition: 'Growing UX research platform',
    },
    strategyType: 'bootstrapped_growth',
    expansionType: 'vertical',
    targetMarket: 'ux_teams',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built UX research software as solo founder', impact: 'Validated without funding', difficulty: 'hard' },
      { action: 'Bootstrapped to $1.8M/year', impact: 'Sustainable growth', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 18 },
    lessonsLearned: 'Domain expertise combined with technical skills enables solo founder success.',
    sourceUrl: 'https://www.starterstory.com/stories/how-i-bootstrapped-a-1-8m-year-ux-research-software',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'ux_research', 'bootstrapped', 'female_founder'],
    matchingKeywords: ['ux research', 'user testing', 'research software'],
    confidenceLevel: 'high',
    summary: 'Bootstrapped PlaybookUX to $1.8M/year UX research software.',
  },
  {
    companyName: 'eWebinar',
    industry: 'saas',
    subIndustry: 'webinar_automation',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Non-technical founder', 'Crowded webinar market', 'Building remotely'],
      capabilities: ['Sales background', 'Product vision', 'Hiring skills'],
      marketPosition: 'New automated webinar platform',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '6_10',
      revenueGrowth: '$50K/month',
      achievements: ['$50K/month', 'Bootstrapped', 'Non-technical founder success'],
      newCapabilities: ['Automated webinars', 'Interaction features', 'Analytics'],
      marketPosition: 'Leading automated webinar solution',
    },
    strategyType: 'bootstrapped_growth',
    expansionType: 'vertical',
    targetMarket: 'marketers',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built automated webinar platform as non-technical founder', impact: 'Proved non-technical success', difficulty: 'hard' },
      { action: 'Bootstrapped to $50K/month', impact: 'Sustainable recurring revenue', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Non-technical founders can build SaaS by hiring well and staying focused.',
    sourceUrl: 'https://www.starterstory.com/stories/ewebinar',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'webinar', 'automation', 'non_technical'],
    matchingKeywords: ['webinar automation', 'automated webinars', 'evergreen webinars'],
    confidenceLevel: 'high',
    summary: 'Non-technical founder bootstrapped eWebinar to $50K/month.',
  },
  {
    companyName: 'Gumroad',
    industry: 'saas',
    subIndustry: 'creator_economy',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Weekend project initially', 'Pivot from VC path', 'Building sustainable model'],
      capabilities: ['Technical skills', 'Design background', 'Creator community'],
      marketPosition: 'New creator commerce platform',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '10_50',
      revenueGrowth: '$200M+ GMV',
      achievements: ['$200M+ GMV', 'Millions of creators', 'Profitable', 'Public about journey'],
      newCapabilities: ['Memberships', 'Email marketing', 'Digital downloads'],
      marketPosition: 'Leading creator commerce platform',
    },
    strategyType: 'platform_scale',
    expansionType: 'community',
    targetMarket: 'creators',
    timeline: { totalMonths: 144 },
    keyActions: [
      { action: 'Built simple creator commerce in a weekend', impact: 'Fast MVP validation', difficulty: 'easy' },
      { action: 'Pivoted from VC-backed to sustainable model', impact: 'Long-term viability', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 200 },
    lessonsLearned: 'Creator economy platforms can pivot from VC growth to sustainable profitability.',
    sourceUrl: 'https://www.starterstory.com/gumroad-case-study',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'creator_economy', 'platform', 'e-commerce'],
    matchingKeywords: ['gumroad', 'creator commerce', 'digital products'],
    confidenceLevel: 'high',
    summary: 'Built Gumroad to $200M+ GMV creator commerce platform.',
  },
  {
    companyName: 'TinySeed',
    industry: 'saas',
    subIndustry: 'investment',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['New fund model', 'Bootstrapper-focused investing', 'Community building'],
      capabilities: ['Podcast audience', 'SaaS founder experience', 'Community trust'],
      marketPosition: 'New accelerator for bootstrappers',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '6_10',
      revenueGrowth: '$133K/month',
      achievements: ['$50M fund', 'Portfolio of bootstrapped SaaS', 'Category creator'],
      newCapabilities: ['Investment thesis', 'Founder network', 'Educational content'],
      marketPosition: 'Leading bootstrapper accelerator',
    },
    strategyType: 'community_led',
    expansionType: 'ecosystem',
    targetMarket: 'bootstrapped_founders',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Created accelerator for bootstrapped SaaS', impact: 'New investment category', difficulty: 'hard' },
      { action: 'Built $50M fund for non-VC startups', impact: 'Filled market gap', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 13 },
    lessonsLearned: 'Serving underserved founder communities can create new investment categories.',
    sourceUrl: 'https://www.starterstory.com/tinyseed-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['investment', 'accelerator', 'bootstrapped', 'saas'],
    matchingKeywords: ['tinyseed', 'bootstrapped funding', 'saas accelerator'],
    confidenceLevel: 'high',
    summary: 'Built TinySeed $50M fund for bootstrapped SaaS startups.',
  },

  // === DTC / CONSUMER BRANDS ===
  {
    companyName: 'XSuit',
    industry: 'fashion',
    subIndustry: 'mens_apparel',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Disrupting traditional suit industry', 'Manufacturing innovation', 'DTC model'],
      capabilities: ['Fashion industry experience', 'Material innovation', 'Marketing skills'],
      marketPosition: 'New performance suit brand',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '6_10',
      revenueGrowth: '$3M/year',
      achievements: ['$3M revenue', 'DTC success', 'Industry disruptor', 'Machine-washable suits'],
      newCapabilities: ['Performance fabrics', 'Direct manufacturing', 'Subscription model'],
      marketPosition: 'Leading performance suit brand',
    },
    strategyType: 'dtc_brand',
    expansionType: 'vertical',
    targetMarket: 'professional_men',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Created machine-washable, stretch suits', impact: 'Product innovation', difficulty: 'hard' },
      { action: 'Built DTC brand disrupting antiquated industry', impact: 'Market disruption', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 30 },
    lessonsLearned: 'Product innovation combined with DTC can disrupt traditional industries.',
    sourceUrl: 'https://www.starterstory.com/stories/xsuit',
    sourcePlatform: 'starter_story',
    tags: ['fashion', 'dtc', 'mens_apparel', 'innovation'],
    matchingKeywords: ['suits', 'mens fashion', 'dtc apparel'],
    confidenceLevel: 'high',
    summary: 'Built $3M DTC brand disrupting traditional suit industry.',
  },
  {
    companyName: 'Allbirds',
    industry: 'fashion',
    subIndustry: 'footwear',
    location: 'New Zealand',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Competing with Nike/Adidas', 'Sustainable materials', 'DTC model'],
      capabilities: ['Professional athlete founder', 'Sustainability focus', 'Design skills'],
      marketPosition: 'New sustainable shoe brand',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '500_plus',
      revenueGrowth: '$20M/month ($240M/year)',
      achievements: ['$240M revenue', 'Public company', 'Sustainability leader', 'Global brand'],
      newCapabilities: ['Sustainable materials R&D', 'Global retail', 'Brand partnerships'],
      marketPosition: 'Leading sustainable footwear brand',
    },
    strategyType: 'dtc_brand',
    expansionType: 'global',
    targetMarket: 'eco_conscious_consumers',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Created sustainable wool sneakers', impact: 'Unique product category', difficulty: 'hard' },
      { action: 'Built global DTC brand to $600M peak valuation', impact: 'Massive scale', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 2400 },
    lessonsLearned: 'Sustainability-focused DTC brands can compete with major incumbents.',
    sourceUrl: 'https://www.starterstory.com/allbirds-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['fashion', 'footwear', 'sustainability', 'dtc'],
    matchingKeywords: ['allbirds', 'sustainable shoes', 'wool sneakers'],
    confidenceLevel: 'high',
    summary: 'From bootstrapped idea to $600M sustainable shoe brand.',
  },
  {
    companyName: 'Beautiful Disaster',
    industry: 'fashion',
    subIndustry: 'womens_apparel',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Building authentic community', 'Standing out in crowded market', 'Scaling production'],
      capabilities: ['Design skills', 'Community building', 'Authentic story'],
      marketPosition: 'New womens lifestyle brand',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '10_50',
      revenueGrowth: '$12M/year',
      achievements: ['$12M revenue', 'Passionate community', 'Lifestyle brand status'],
      newCapabilities: ['Community events', 'Product expansion', 'Brand ambassadors'],
      marketPosition: 'Leading community-driven apparel brand',
    },
    strategyType: 'community_led',
    expansionType: 'brand',
    targetMarket: 'women',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Built authentic community around brand story', impact: 'Deep customer loyalty', difficulty: 'hard' },
      { action: 'Scaled womens apparel brand to $12M', impact: 'Sustainable growth', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 120 },
    lessonsLearned: 'Authentic brand stories create passionate communities that drive growth.',
    sourceUrl: 'https://www.starterstory.com/stories/beautiful-disaster-0c2f1c51-481e-4950-b758-27c2b412e6c1',
    sourcePlatform: 'starter_story',
    tags: ['fashion', 'womens_apparel', 'community', 'lifestyle'],
    matchingKeywords: ['womens clothing', 'lifestyle brand', 'community'],
    confidenceLevel: 'high',
    summary: 'Grew womens apparel brand to $12M/year through community building.',
  },
  {
    companyName: 'Tini Lux',
    industry: 'fashion',
    subIndustry: 'jewelry',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Niche market (sensitive ears)', 'Material sourcing', 'DTC jewelry'],
      capabilities: ['Personal pain point experience', 'E-commerce skills', 'Product research'],
      marketPosition: 'New hypoallergenic earring brand',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '2_5',
      revenueGrowth: '$4M/year (10X growth)',
      achievements: ['$4M revenue', '10X growth update', 'Market leader in niche'],
      newCapabilities: ['Titanium expertise', 'Product line expansion', 'Subscription model'],
      marketPosition: 'Leading hypoallergenic jewelry brand',
    },
    strategyType: 'niche_domination',
    expansionType: 'vertical',
    targetMarket: 'sensitive_ear_consumers',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Created earrings for people with metal sensitivities', impact: 'Underserved market', difficulty: 'medium' },
      { action: 'Scaled niche brand 10X to $4M', impact: 'Niche market leader', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 40 },
    lessonsLearned: 'Personal pain points can reveal large underserved markets.',
    sourceUrl: 'https://www.starterstory.com/stories/tini-lux',
    sourcePlatform: 'starter_story',
    tags: ['fashion', 'jewelry', 'niche', 'dtc'],
    matchingKeywords: ['hypoallergenic jewelry', 'titanium earrings', 'sensitive ears'],
    confidenceLevel: 'high',
    summary: 'Niche earring brand grew 10X to $4M/year.',
  },
  {
    companyName: 'Ceremonia',
    industry: 'beauty',
    subIndustry: 'hair_care',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Crowded beauty market', 'Cultural positioning', 'Retail distribution'],
      capabilities: ['Marketing background', 'Cultural insight', 'Brand building'],
      marketPosition: 'New Latinx hair care brand',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '6_10',
      revenueGrowth: '$100K in 100 days',
      achievements: ['$100K in first 100 days', 'Sephora distribution', 'Cultural beauty leader'],
      newCapabilities: ['Retail partnerships', 'Product line expansion', 'Influencer network'],
      marketPosition: 'Leading Latinx beauty brand',
    },
    strategyType: 'cultural_brand',
    expansionType: 'retail',
    targetMarket: 'latinx_consumers',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built Latinx-focused hair care brand', impact: 'Cultural differentiation', difficulty: 'medium' },
      { action: 'Achieved $100K in first 100 days', impact: 'Fast market validation', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Cultural authenticity creates powerful differentiation in beauty.',
    sourceUrl: 'https://www.starterstory.com/ceremonia-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['beauty', 'hair_care', 'cultural', 'dtc'],
    matchingKeywords: ['latinx beauty', 'hair care', 'ceremonia'],
    confidenceLevel: 'high',
    summary: 'Latinx entrepreneur grew Ceremonia to $100K in 100 days.',
  },
  {
    companyName: 'Fur',
    industry: 'beauty',
    subIndustry: 'body_care',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Taboo product category', 'Market education', 'Bootstrapped'],
      capabilities: ['Brand building', 'Product development', 'Marketing creativity'],
      marketPosition: 'New body hair care brand',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '50_200',
      revenueGrowth: '$143K/month',
      achievements: ['$143K/month', '100 employees', '267K monthly traffic', 'Category creator'],
      newCapabilities: ['Retail distribution', 'Product line expansion', 'Education content'],
      marketPosition: 'Category leader in body hair care',
    },
    strategyType: 'category_creation',
    expansionType: 'retail',
    targetMarket: 'women',
    timeline: { totalMonths: 108 },
    keyActions: [
      { action: 'Created body hair care category', impact: 'Blue ocean market', difficulty: 'hard' },
      { action: 'Bootstrapped taboo product to millions', impact: 'Proved market exists', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 14 },
    lessonsLearned: 'Taboo topics can represent massive underserved markets.',
    sourceUrl: 'https://www.starterstory.com/fur-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['beauty', 'body_care', 'taboo', 'category_creation'],
    matchingKeywords: ['body hair care', 'fur oil', 'intimate care'],
    confidenceLevel: 'high',
    summary: 'Bootstrapped taboo beauty business to millions.',
  },
  {
    companyName: 'Luna Nectar',
    industry: 'beauty',
    subIndustry: 'hair_care',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Hollywood career balance', 'Sustainable products', 'DTC beauty'],
      capabilities: ['Entertainment industry network', 'Sustainability passion', 'Brand vision'],
      marketPosition: 'New sustainable hair care brand',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '2_5',
      revenueGrowth: '$50K/month',
      achievements: ['$50K/month', 'Sustainable products', 'Celebrity-founded brand'],
      newCapabilities: ['Clean formulations', 'DTC excellence', 'Influencer partnerships'],
      marketPosition: 'Growing sustainable hair care brand',
    },
    strategyType: 'dtc_brand',
    expansionType: 'vertical',
    targetMarket: 'eco_conscious_consumers',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built sustainable hair care brand while in Hollywood', impact: 'Unique founder story', difficulty: 'hard' },
      { action: 'Scaled to $50K/month sustainable DTC', impact: 'Validated clean beauty', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Side businesses can grow while maintaining other careers.',
    sourceUrl: 'https://www.starterstory.com/stories/luna-nectar-organics',
    sourcePlatform: 'starter_story',
    tags: ['beauty', 'hair_care', 'sustainable', 'celebrity'],
    matchingKeywords: ['sustainable hair care', 'clean beauty', 'organic'],
    confidenceLevel: 'high',
    summary: 'Started $50K/month sustainable hair products brand alongside Hollywood career.',
  },

  // === FOOD & BEVERAGE ===
  {
    companyName: 'BeatBox Beverages',
    industry: 'food_beverage',
    subIndustry: 'alcohol',
    location: 'USA',
    startingState: {
      revenue: '1m_10m',
      teamSize: '10_50',
      yearsInBusiness: 5,
      challenges: ['Scaling production', 'Distribution expansion', 'Brand awareness'],
      capabilities: ['Shark Tank appearance', 'Party brand positioning', 'Distribution network'],
      marketPosition: 'Growing party punch brand',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '50_200',
      revenueGrowth: 'From $18M to $100M/year',
      achievements: ['$100M/year', '455% growth', 'National distribution', 'Category leader'],
      newCapabilities: ['Mass production', 'National retail', 'Brand extensions'],
      marketPosition: 'Leading party beverage brand',
    },
    strategyType: 'scale_up',
    expansionType: 'national',
    targetMarket: 'young_adults',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Scaled from $18M to $100M revenue', impact: '455% growth', difficulty: 'hard' },
      { action: 'Expanded national distribution', impact: 'Mass market reach', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 5.5 },
    lessonsLearned: 'Party-focused beverage brands can scale massively with right positioning.',
    sourceUrl: 'https://www.starterstory.com/stories/beatbox-beverages',
    sourcePlatform: 'starter_story',
    tags: ['beverage', 'alcohol', 'cpg', 'shark_tank'],
    matchingKeywords: ['party punch', 'alcohol', 'beatbox'],
    confidenceLevel: 'high',
    summary: 'Party punch brand exploded from $18M to $100M/year.',
  },
  {
    companyName: 'Good Girl Snacks',
    industry: 'food_beverage',
    subIndustry: 'snacks',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['No advertising budget', 'Viral marketing needed', 'CPG competition'],
      capabilities: ['Social media skills', 'Product innovation', 'Brand personality'],
      marketPosition: 'New pickle snack brand',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '2_5',
      revenueGrowth: '$6.83K/month (growing)',
      achievements: ['Viral TikTok success', 'Zero ads', 'Profitable', 'Strong brand'],
      newCapabilities: ['Social media mastery', 'Community building', 'Product expansion'],
      marketPosition: 'Viral pickle snack brand',
    },
    strategyType: 'viral_marketing',
    expansionType: 'organic',
    targetMarket: 'snack_lovers',
    timeline: { totalMonths: 18 },
    keyActions: [
      { action: 'Built viral pickle brand with zero ads', impact: 'Organic growth model', difficulty: 'hard' },
      { action: 'Leveraged TikTok for brand building', impact: 'Free customer acquisition', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 7 },
    lessonsLearned: 'Viral social media can replace advertising budget for CPG brands.',
    sourceUrl: 'https://www.starterstory.com/good-girl-snacks-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['food', 'snacks', 'viral', 'tiktok'],
    matchingKeywords: ['pickles', 'snacks', 'viral cpg'],
    confidenceLevel: 'high',
    summary: 'Built viral pickle brand with zero ads through social media.',
  },
  {
    companyName: 'Love Good Fats',
    industry: 'food_beverage',
    subIndustry: 'healthy_snacks',
    location: 'Canada',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Started from dining room', 'Keto market education', 'Retail distribution'],
      capabilities: ['Food industry experience', 'Keto diet knowledge', 'Product development'],
      marketPosition: 'New keto snack brand',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '50_200',
      revenueGrowth: '$36M/year',
      achievements: ['$36M revenue', 'National retail distribution', 'Keto market leader'],
      newCapabilities: ['Mass production', 'Retail relationships', 'Product line expansion'],
      marketPosition: 'Leading keto snack brand',
    },
    strategyType: 'category_creation',
    expansionType: 'retail',
    targetMarket: 'health_conscious',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Started healthy snack business from dining room', impact: 'Low startup costs', difficulty: 'medium' },
      { action: 'Scaled keto snacks to $36M', impact: 'Category leadership', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 360 },
    lessonsLearned: 'Diet-focused CPG brands can scale massively with the right trend.',
    sourceUrl: 'https://www.starterstory.com/stories/i-started-a-36m-year-healthy-snack-business-from-my-dining-room-table-canada',
    sourcePlatform: 'starter_story',
    tags: ['food', 'healthy_snacks', 'keto', 'canada'],
    matchingKeywords: ['keto snacks', 'healthy food', 'love good fats'],
    confidenceLevel: 'high',
    summary: 'Started $36M/year healthy snack business from dining room table.',
  },
  {
    companyName: 'Wondry Wine',
    industry: 'food_beverage',
    subIndustry: 'alcohol',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['$100K starting costs', 'Wine industry barriers', 'National distribution'],
      capabilities: ['Marketing experience', 'Wine passion', 'Brand building'],
      marketPosition: 'New wine brand',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '6_10',
      revenueGrowth: '$250K/month',
      achievements: ['$250K/month', 'National distribution', 'Profitable'],
      newCapabilities: ['Retail partnerships', 'Wine production', 'Brand marketing'],
      marketPosition: 'Growing national wine brand',
    },
    strategyType: 'brand_building',
    expansionType: 'national',
    targetMarket: 'wine_drinkers',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built wine brand to national distribution', impact: 'Wide market reach', difficulty: 'hard' },
      { action: 'Scaled to $250K/month in 3 years', impact: 'Rapid growth', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 30 },
    lessonsLearned: 'Wine brands can scale nationally with strong marketing and distribution focus.',
    sourceUrl: 'https://www.starterstory.com/wondrywine-com-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['beverage', 'wine', 'alcohol', 'brand'],
    matchingKeywords: ['wine brand', 'alcohol', 'wondry'],
    confidenceLevel: 'high',
    summary: 'Grew Wondry Wine to national brand with $250K/month in 3 years.',
  },
  {
    companyName: "Y'all Sweet Tea",
    industry: 'food_beverage',
    subIndustry: 'beverages',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['$300 starting budget', 'Beverage competition', 'Distribution'],
      capabilities: ['Alabama roots', 'Recipe knowledge', 'Hustle'],
      marketPosition: 'New sweet tea brand',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '10_50',
      revenueGrowth: '$333K/month ($5M/year)',
      achievements: ['$5M revenue', '15 employees', 'Profitable', 'Regional expansion'],
      newCapabilities: ['Production scaling', 'Retail distribution', 'Brand building'],
      marketPosition: 'Leading sweet tea brand',
    },
    strategyType: 'bootstrapped_growth',
    expansionType: 'regional',
    targetMarket: 'southern_consumers',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Started sweet tea brand with $300', impact: 'Minimal capital needed', difficulty: 'easy' },
      { action: 'Scaled to $5M in 3 years', impact: 'Rapid regional growth', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 16666 },
    lessonsLearned: 'Regional food brands can scale dramatically with minimal starting capital.',
    sourceUrl: 'https://www.starterstory.com/y-all-sweet-tea-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['beverage', 'tea', 'regional', 'bootstrapped'],
    matchingKeywords: ['sweet tea', 'southern food', 'beverage brand'],
    confidenceLevel: 'high',
    summary: 'Grew sweet tea brand from $300 to $5M in 3 years.',
  },

  // === NEWSLETTERS & MEDIA ===
  {
    companyName: 'The Milk Road',
    industry: 'media',
    subIndustry: 'newsletter',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['$2K starting budget', 'Crypto market volatility', 'Building audience'],
      capabilities: ['Social media following', 'Crypto knowledge', 'Content skills'],
      marketPosition: 'New crypto newsletter',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '1',
      revenueGrowth: '$125K/month (8-figure exit)',
      achievements: ['250K subscribers', '8-figure acquisition', '538K monthly traffic'],
      newCapabilities: ['Newsletter growth', 'Sponsor relationships', 'Exit planning'],
      marketPosition: 'Leading crypto newsletter (acquired)',
    },
    strategyType: 'media_growth',
    expansionType: 'audience',
    targetMarket: 'crypto_enthusiasts',
    timeline: { totalMonths: 12 },
    keyActions: [
      { action: 'Built to 250K subscribers in under a year', impact: 'Explosive growth', difficulty: 'hard' },
      { action: 'Sold for 8-figure amount', impact: 'Massive exit', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 625 },
    lessonsLearned: 'Newsletters in hot markets can grow and exit incredibly fast.',
    sourceUrl: 'https://www.starterstory.com/stories/the-milk-road-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['newsletter', 'crypto', 'media', 'exit'],
    matchingKeywords: ['crypto newsletter', 'milk road', 'newsletter exit'],
    confidenceLevel: 'high',
    summary: 'Built Milk Road to 250K subscribers and sold for 8-figures in under a year.',
  },
  {
    companyName: 'Contrarian Thinking',
    industry: 'media',
    subIndustry: 'newsletter',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Building personal brand', 'Monetization strategy', 'Content creation'],
      capabilities: ['Finance background', 'Social media skills', 'Community building'],
      marketPosition: 'New finance newsletter',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '6_10',
      revenueGrowth: '$3M run rate',
      achievements: ['$3M run rate', 'Strong community', 'Multiple revenue streams'],
      newCapabilities: ['Community monetization', 'Course creation', 'Sponsorships'],
      marketPosition: 'Leading finance creator brand',
    },
    strategyType: 'creator_business',
    expansionType: 'community',
    targetMarket: 'investors',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Built finance newsletter and community', impact: 'Loyal audience', difficulty: 'medium' },
      { action: 'Hit $3M run rate with newsletter business', impact: 'Creator economy success', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 30 },
    lessonsLearned: 'Personal finance brands with strong personalities can build media empires.',
    sourceUrl: 'https://www.starterstory.com/stories/contrarian-thinking',
    sourcePlatform: 'starter_story',
    tags: ['newsletter', 'finance', 'creator', 'community'],
    matchingKeywords: ['finance newsletter', 'contrarian', 'codie sanchez'],
    confidenceLevel: 'high',
    summary: 'Finance newsletter and community hit $3M run rate.',
  },
  {
    companyName: 'Creator Science',
    industry: 'media',
    subIndustry: 'newsletter',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Solo creator', 'Bootstrapped', 'Building audience'],
      capabilities: ['Content creation', 'Podcast skills', 'Community building'],
      marketPosition: 'New creator economy newsletter',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '1',
      revenueGrowth: '$50K/month',
      achievements: ['$50K/month', 'Solo operation', 'Profitable', 'Creator economy authority'],
      newCapabilities: ['Podcast', 'Newsletter', 'Courses'],
      marketPosition: 'Leading creator education brand',
    },
    strategyType: 'creator_business',
    expansionType: 'audience',
    targetMarket: 'creators',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Built creator economy education business', impact: 'Authority positioning', difficulty: 'medium' },
      { action: 'Bootstrapped to $40-50K/month solo', impact: 'High-margin operation', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Teaching creators about the creator economy is a meta-business that works.',
    sourceUrl: 'https://www.starterstory.com/creator-science-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['newsletter', 'creator_economy', 'education', 'solo'],
    matchingKeywords: ['creator science', 'creator education', 'jay clouse'],
    confidenceLevel: 'high',
    summary: 'Bootstrapped Creator Science to $40k/month solo operation.',
  },
  {
    companyName: 'Marketing Examples',
    industry: 'media',
    subIndustry: 'newsletter',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Solo creator', '160 days to build', 'Content differentiation'],
      capabilities: ['Marketing expertise', 'Design skills', 'Content curation'],
      marketPosition: 'New marketing newsletter',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '1',
      revenueGrowth: '130K subscribers',
      achievements: ['130K subscribers', 'Solo operation', 'Profitable', 'Marketing authority'],
      newCapabilities: ['Visual content', 'Newsletter growth', 'Sponsorships'],
      marketPosition: 'Leading marketing examples resource',
    },
    strategyType: 'content_marketing',
    expansionType: 'audience',
    targetMarket: 'marketers',
    timeline: { totalMonths: 42 },
    keyActions: [
      { action: 'Built 130K subscriber marketing newsletter', impact: 'Large audience', difficulty: 'hard' },
      { action: 'Created visual marketing examples format', impact: 'Unique content style', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 13 },
    lessonsLearned: 'Curated examples with strong visuals can build large newsletter audiences.',
    sourceUrl: 'https://www.starterstory.com/marketing-examples-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['newsletter', 'marketing', 'solo', 'content'],
    matchingKeywords: ['marketing examples', 'harry dry', 'marketing newsletter'],
    confidenceLevel: 'high',
    summary: 'Built 130K subscriber marketing newsletter in 3.5 years.',
  },
  {
    companyName: 'ConvertKit',
    industry: 'saas',
    subIndustry: 'email_marketing',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Competing with Mailchimp', 'Solopreneur start', 'Bootstrapped'],
      capabilities: ['Development skills', 'Content marketing', 'Creator focus'],
      marketPosition: 'New email platform for creators',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '50_200',
      revenueGrowth: '$25M/year',
      achievements: ['$25M revenue', 'Creator-first platform', 'Bootstrapped success'],
      newCapabilities: ['Commerce features', 'Creator network', 'Education content'],
      marketPosition: 'Leading creator email platform',
    },
    strategyType: 'bootstrapped_growth',
    expansionType: 'vertical',
    targetMarket: 'creators',
    timeline: { totalMonths: 132 },
    keyActions: [
      { action: 'Built email platform specifically for creators', impact: 'Niche positioning', difficulty: 'hard' },
      { action: 'Bootstrapped to $25M competing with Mailchimp', impact: 'David vs Goliath success', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 250 },
    lessonsLearned: 'Niche focus can win against much larger competitors.',
    sourceUrl: 'https://www.starterstory.com/stories/convertkit-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'email', 'creator_economy', 'bootstrapped'],
    matchingKeywords: ['convertkit', 'email marketing', 'creator tools'],
    confidenceLevel: 'high',
    summary: 'Built $25M/year newsletter platform as solopreneur.',
  },
  {
    companyName: 'TLDR Newsletter',
    industry: 'media',
    subIndustry: 'newsletter',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['$500 starting cost', 'Solo operation', 'News curation'],
      capabilities: ['Tech industry knowledge', 'Writing skills', 'Consistency'],
      marketPosition: 'New tech newsletter',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '1',
      revenueGrowth: '$417K/month ($5M/year)',
      achievements: ['$5M revenue', '0 employees', '1.64M monthly traffic', '80% gross margin'],
      newCapabilities: ['Newsletter network', 'Sponsor relationships', 'Automation'],
      marketPosition: 'Leading tech newsletter',
    },
    strategyType: 'solo_scale',
    expansionType: 'audience',
    targetMarket: 'tech_professionals',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built $5M newsletter with zero employees', impact: 'Maximum efficiency', difficulty: 'hard' },
      { action: 'Achieved 1.64M monthly readers', impact: 'Massive reach', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 10000 },
    lessonsLearned: 'Newsletter businesses can scale to millions with automation and solo operation.',
    sourceUrl: 'https://www.starterstory.com/stories/tldr-newsletter-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['newsletter', 'tech', 'solo', 'media'],
    matchingKeywords: ['tldr', 'tech newsletter', 'dan ni'],
    confidenceLevel: 'high',
    summary: 'Built $5M email newsletter with 0 employees.',
  },
  {
    companyName: 'No Code Exits',
    industry: 'media',
    subIndustry: 'newsletter',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['No-code tools only', 'Solo creator', 'Building audience'],
      capabilities: ['No-code expertise', 'Content creation', 'Community building'],
      marketPosition: 'New no-code newsletter',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '1',
      revenueGrowth: '$33K (growing)',
      achievements: ['$33K business', 'Built entirely with no-code', 'Solo operation'],
      newCapabilities: ['No-code workflows', 'Newsletter automation', 'Community'],
      marketPosition: 'Growing no-code media brand',
    },
    strategyType: 'no_code_build',
    expansionType: 'organic',
    targetMarket: 'no_code_builders',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built newsletter business entirely with no-code', impact: 'Proved no-code viability', difficulty: 'medium' },
      { action: 'Scaled to $33K solo', impact: 'Bootstrapped success', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 3 },
    lessonsLearned: 'No-code tools enable complete business building without technical skills.',
    sourceUrl: 'https://www.starterstory.com/no-code-exits-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['newsletter', 'no_code', 'solo', 'media'],
    matchingKeywords: ['no code', 'newsletter', 'katt risen'],
    confidenceLevel: 'high',
    summary: 'Used no-code to build $33K newsletter business.',
  },

  // === AGENCIES & SERVICES ===
  {
    companyName: 'Tenet Design Agency',
    industry: 'agency',
    subIndustry: 'design',
    location: 'Dubai',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Competitive agency market', 'Building team', 'Premium positioning'],
      capabilities: ['Design expertise', 'Leadership skills', 'Client relationships'],
      marketPosition: 'New design agency',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '10_50',
      revenueGrowth: '$55K/month',
      achievements: ['$55K/month', '40 employees', 'Premium positioning'],
      newCapabilities: ['Large team', 'Enterprise clients', 'Brand strategy'],
      marketPosition: 'Leading Dubai design agency',
    },
    strategyType: 'agency_growth',
    expansionType: 'team',
    targetMarket: 'enterprise',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built premium design agency to 40 employees', impact: 'Scalable service business', difficulty: 'hard' },
      { action: 'Scaled to $55K/month revenue', impact: 'Sustainable agency model', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 55 },
    lessonsLearned: 'Premium positioning enables higher margins and better clients.',
    sourceUrl: 'https://www.starterstory.com/stories/tenet',
    sourcePlatform: 'starter_story',
    tags: ['agency', 'design', 'dubai', 'premium'],
    matchingKeywords: ['design agency', 'branding', 'dubai'],
    confidenceLevel: 'high',
    summary: 'Built $55K/month design agency with 40 employees.',
  },
  {
    companyName: 'Bop Design',
    industry: 'agency',
    subIndustry: 'marketing',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Couple founding team', '120 day launch', 'B2B focus'],
      capabilities: ['Marketing expertise', 'Web design skills', 'Partnership dynamic'],
      marketPosition: 'New B2B marketing agency',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '10_50',
      revenueGrowth: '$2.4M/year',
      achievements: ['$2.4M revenue', 'Power couple success', 'B2B specialization'],
      newCapabilities: ['Full-service B2B', 'Established process', 'Recurring clients'],
      marketPosition: 'Leading B2B marketing agency',
    },
    strategyType: 'agency_growth',
    expansionType: 'vertical',
    targetMarket: 'b2b_companies',
    timeline: { totalMonths: 120 },
    keyActions: [
      { action: 'Built B2B marketing agency in 120 days', impact: 'Fast launch', difficulty: 'hard' },
      { action: 'Scaled to $2.4M as founder couple', impact: 'Partnership success', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 24 },
    lessonsLearned: 'B2B specialization and founder partnerships can accelerate agency growth.',
    sourceUrl: 'https://www.starterstory.com/stories/this-power-couple-started-a-2-4m-year-marketing-agency-in-120-days',
    sourcePlatform: 'starter_story',
    tags: ['agency', 'marketing', 'b2b', 'couple_founded'],
    matchingKeywords: ['marketing agency', 'b2b marketing', 'web design'],
    confidenceLevel: 'high',
    summary: 'Power couple started $2.4M/year marketing agency in 120 days.',
  },
  {
    companyName: 'DesignJoy',
    industry: 'agency',
    subIndustry: 'design',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Solo designer', 'Productized service model', 'Scaling without hiring'],
      capabilities: ['Design expertise', 'Systems thinking', 'Process optimization'],
      marketPosition: 'New productized design service',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '1',
      revenueGrowth: '$1.7M ARR',
      achievements: ['$1.7M ARR', 'Solo operation', 'Productized model pioneer'],
      newCapabilities: ['Subscription design', 'Automated workflows', 'Waitlist demand'],
      marketPosition: 'Leading productized design service',
    },
    strategyType: 'productized_service',
    expansionType: 'scale',
    targetMarket: 'startups',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Created subscription-based design service', impact: 'Recurring revenue model', difficulty: 'medium' },
      { action: 'Scaled to $1.7M ARR as solo designer', impact: 'Maximum efficiency', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 17 },
    lessonsLearned: 'Productized services can scale without traditional agency hiring.',
    sourceUrl: 'https://www.starterstory.com/stories/design-joy-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['agency', 'design', 'productized', 'solo'],
    matchingKeywords: ['productized service', 'design subscription', 'designjoy'],
    confidenceLevel: 'high',
    summary: 'Built DesignJoy to $1.7M ARR as solo designer.',
  },
  {
    companyName: 'Starter Story',
    industry: 'media',
    subIndustry: 'content',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Content creation at scale', 'SEO competition', 'Monetization'],
      capabilities: ['Technical skills', 'Content marketing', 'SEO expertise'],
      marketPosition: 'New founder story platform',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '6_10',
      revenueGrowth: '$1.1M/year',
      achievements: ['$1.1M/year', '1.6M monthly visitors', 'Founder story authority'],
      newCapabilities: ['Database of stories', 'SEO dominance', 'Subscription model'],
      marketPosition: 'Leading founder story platform',
    },
    strategyType: 'content_marketing',
    expansionType: 'organic',
    targetMarket: 'entrepreneurs',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Built database of founder stories', impact: 'Unique content asset', difficulty: 'hard' },
      { action: 'Grew to 1.6M monthly visitors', impact: 'Massive organic reach', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 11 },
    lessonsLearned: 'Content databases with strong SEO can become authoritative resources.',
    sourceUrl: 'https://www.starterstory.com/stories/starter-story-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['media', 'content', 'seo', 'entrepreneurship'],
    matchingKeywords: ['starter story', 'founder stories', 'pat walls'],
    confidenceLevel: 'high',
    summary: 'Built Starter Story to $1.1M/year and 1.6M monthly visitors.',
  },
];

export async function seedBatch8() {
  console.log('🌱 Seeding Batch 8: SaaS, DTC Brands, Bootstrapped Startups, Newsletters, Agencies...');

  let successCount = 0;
  let errorCount = 0;

  for (const study of batch8CaseStudies) {
    try {
      await db.insert(caseStudies).values(study as CaseStudyInsert);
      console.log(`  ✓ ${study.companyName}`);
      successCount++;
    } catch (error) {
      console.error(`  ✗ ${study.companyName}:`, error);
      errorCount++;
    }
  }

  console.log(`\nBatch 8 seeding complete!`);
  console.log(`✓ Successfully seeded: ${successCount}`);
  console.log(`✗ Errors: ${errorCount}`);
}

// Run if called directly
seedBatch8()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
