import { db } from '@/lib/db';
import { caseStudies } from '@/database/schema';

/**
 * Case Studies Seed Data
 * Real-world examples of business transformations
 * Sources: Starter Story, Indie Hackers, podcasts, interviews
 *
 * Categories:
 * - Video Production (10+)
 * - Marketing Agencies (15+)
 * - Consulting (10+)
 * - SaaS/Tech (15+)
 * - Design Agencies (5+)
 * - Architecture/Professional Services (5+)
 */
export const caseStudySeedData = [
  // ============================================================================
  // VIDEO PRODUCTION CASE STUDIES (from Starter Story)
  // ============================================================================
  {
    companyName: 'Lemonlight',
    industry: 'video_production',
    subIndustry: 'commercial',
    location: 'Los Angeles, CA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Started in bedroom', 'No network', 'Competing with agencies'],
      capabilities: ['Videography', 'Basic editing'],
      marketPosition: 'Unknown startup',
    },
    endingState: {
      revenue: '5m_plus',
      teamSize: '50_plus',
      revenueGrowth: '100x+',
      achievements: ['$500K/month revenue', '$18M/year ARR', 'Major brand clients'],
      newCapabilities: ['Full production house', 'National network', 'Enterprise solutions'],
      marketPosition: 'Leading video production company',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'horizontal',
    targetMarket: 'enterprise',
    timeline: {
      totalMonths: 60,
      phases: [
        { name: 'Bedroom Launch', months: 12, description: 'Started shooting from bedroom in LA' },
        { name: 'Team Building', months: 24, description: 'Built production team and processes' },
        { name: 'Enterprise Scale', months: 24, description: 'Scaled to major brand clients' },
      ],
    },
    keyActions: [
      { action: 'Started with zero network, pure hustle', impact: 'Built client base from scratch', difficulty: 'hard' },
      { action: 'Focused on quality affordable video', impact: 'Disrupted overpriced agencies', difficulty: 'moderate' },
      { action: 'Built national production network', impact: 'Can serve clients anywhere', difficulty: 'hard' },
    ],
    capitalInvested: {
      total: 50000,
      breakdown: { equipment: 30000, marketing: 15000, operations: 5000 },
      fundingSource: 'Bootstrapped',
    },
    outcomes: {
      revenueMultiplier: 100,
      teamGrowth: 50,
    },
    pitfalls: [
      { challenge: 'Scaling quality control', howOvercome: 'Built rigorous QA process', advice: 'Quality must scale with growth' },
    ],
    lessonsLearned: 'You can build a massive video production company from nothing if you focus on value and hustle.',
    advice: 'Start from your bedroom if you have to. The key is starting, not waiting for perfect conditions.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-video-production-company',
    sourcePlatform: 'starter_story',
    tags: ['video_production', 'commercial', 'enterprise', 'bootstrapped', 'scale'],
    matchingKeywords: ['video production', 'commercial video', 'corporate video', 'scale'],
    confidenceLevel: 'high',
    summary: 'Hope Horner started Lemonlight from her bedroom in LA and grew it to $500K/month ($18M/year) by making quality video production accessible.',
  },
  {
    companyName: 'Mbrella Films',
    industry: 'video_production',
    subIndustry: 'commercial',
    location: 'Bangkok, Thailand',
    startingState: {
      revenue: '100k_250k',
      teamSize: '6_10',
      yearsInBusiness: 5,
      challenges: ['COVID hit hard', 'Market uncertainty', 'Client projects cancelled'],
      capabilities: ['Film production', 'Commercial work', 'International experience'],
      marketPosition: 'Established production company',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '26_50',
      revenueGrowth: '10x',
      achievements: ['$250K/month revenue', 'Pivoted successfully during COVID', 'Doubled yearly growth'],
      newCapabilities: ['Remote production', 'Virtual sets', 'Pandemic-proof workflows'],
      marketPosition: 'Resilient, adaptive production company',
    },
    strategyType: 'partnership_expansion',
    expansionType: 'horizontal',
    targetMarket: 'international_brands',
    timeline: {
      totalMonths: 48,
      phases: [
        { name: 'Pre-COVID Growth', months: 24, description: 'Steady growth in traditional production' },
        { name: 'COVID Pivot', months: 12, description: 'Major pivot to survive pandemic' },
        { name: 'Post-Pivot Growth', months: 12, description: 'Emerged stronger with new capabilities' },
      ],
    },
    keyActions: [
      { action: 'Pivoted during COVID instead of shutting down', impact: 'Survived and thrived', difficulty: 'hard' },
      { action: 'Developed remote production capabilities', impact: 'Served clients globally during lockdowns', difficulty: 'moderate' },
      { action: 'Invested in team during downturn', impact: 'Ready to scale when market recovered', difficulty: 'hard' },
    ],
    outcomes: {
      revenueMultiplier: 10,
      teamGrowth: 5,
    },
    pitfalls: [
      { challenge: 'Pandemic cancelled all projects', howOvercome: 'Pivoted to new services immediately', advice: 'Adaptability is survival' },
    ],
    lessonsLearned: 'Crisis can be opportunity. Being willing to pivot quickly can transform your business.',
    advice: 'Don\'t wait for conditions to improve. Adapt to the new reality immediately.',
    sourceUrl: 'https://www.starterstory.com/stories/mbrella-films',
    sourcePlatform: 'starter_story',
    tags: ['video_production', 'pivot', 'covid', 'international', 'resilience'],
    matchingKeywords: ['video production', 'film production', 'pivot', 'resilience'],
    confidenceLevel: 'high',
    summary: 'Joshua Dixon built Mbrella Films to $250K/month despite major COVID pivot, proving adaptability trumps conditions.',
  },
  {
    companyName: 'ProductionCrate',
    industry: 'video_production',
    subIndustry: 'stock_assets',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 2,
      challenges: ['Competing with stock giants', 'Building audience', 'Creating content at scale'],
      capabilities: ['VFX', 'Motion graphics', 'Content creation'],
      marketPosition: 'Small player',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '6_10',
      revenueGrowth: '6x',
      achievements: ['$600K/year revenue', '10M+ downloads', '120% YoY growth'],
      newCapabilities: ['Massive asset library', 'Subscription platform', 'Global community'],
      marketPosition: 'Major VFX asset provider',
    },
    strategyType: 'content_led_growth',
    expansionType: 'horizontal',
    targetMarket: 'content_creators',
    timeline: {
      totalMonths: 48,
    },
    keyActions: [
      { action: 'Bootstrapped entire operation', impact: 'No outside pressure, full control', difficulty: 'hard' },
      { action: 'Focused on creator community', impact: '10M downloads built organically', difficulty: 'moderate' },
      { action: 'Subscription model for recurring revenue', impact: 'Predictable growth', difficulty: 'moderate' },
    ],
    outcomes: {
      revenueMultiplier: 6,
    },
    lessonsLearned: 'Build for a specific community and they will support you.',
    advice: 'Bootstrapping is harder but gives you freedom. Serve your community well.',
    sourceUrl: 'https://www.starterstory.com/stories/i-bootstrapped-a-600k-year-video-production-company-10m-downloads',
    sourcePlatform: 'starter_story',
    tags: ['stock_assets', 'vfx', 'subscription', 'bootstrapped', 'community'],
    matchingKeywords: ['vfx', 'stock footage', 'assets', 'subscription', 'creator'],
    confidenceLevel: 'high',
    summary: 'Chris Kelly bootstrapped ProductionCrate to $600K/year with 10M downloads by serving the VFX creator community.',
  },
  {
    companyName: 'D-MAK Productions',
    industry: 'video_production',
    subIndustry: 'commercial',
    location: 'USA',
    startingState: {
      revenue: '100k_250k',
      teamSize: '2_5',
      yearsInBusiness: 3,
      challenges: ['Growing beyond founders', 'Client acquisition', 'Pricing'],
      capabilities: ['Video production', 'Editing', 'Client management'],
      marketPosition: 'Small production company',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '2_5',
      revenueGrowth: '1.8x',
      achievements: ['$54K/month revenue', 'Sustainable growth', 'Efficient operations'],
      newCapabilities: ['Streamlined processes', 'Premium positioning'],
      marketPosition: 'Efficient boutique production',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'vertical',
    targetMarket: 'mid_market',
    timeline: {
      totalMonths: 36,
    },
    keyActions: [
      { action: 'Focused on process optimization', impact: 'Higher margins, less stress', difficulty: 'moderate' },
      { action: 'Strategic pricing increases', impact: 'Better clients, higher revenue', difficulty: 'easy' },
    ],
    outcomes: {
      revenueMultiplier: 1.8,
    },
    lessonsLearned: 'Efficiency matters as much as growth. Small team can be highly profitable.',
    sourceUrl: 'https://www.starterstory.com/start-a-video-production-company',
    sourcePlatform: 'starter_story',
    tags: ['video_production', 'boutique', 'efficiency', 'profitable'],
    matchingKeywords: ['video production', 'boutique', 'efficient'],
    confidenceLevel: 'high',
    summary: 'Joe Forte grew D-MAK Productions to $54K/month with a small team by focusing on efficiency and premium clients.',
  },
  {
    companyName: 'Breadnbeyond',
    industry: 'video_production',
    subIndustry: 'explainer_videos',
    location: 'Indonesia',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 1,
      challenges: ['No market awareness', 'Competing globally', 'Building reputation'],
      capabilities: ['Animation', 'Explainer video production'],
      marketPosition: 'Unknown startup',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '26_50',
      revenueGrowth: '20x+',
      achievements: ['$2M/year revenue', 'Pioneer in explainer videos', 'Global client base'],
      newCapabilities: ['Full animation studio', 'Content marketing engine', 'Enterprise solutions'],
      marketPosition: 'Explainer video pioneer',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'horizontal',
    targetMarket: 'tech_startups',
    timeline: {
      totalMonths: 72,
    },
    keyActions: [
      { action: 'Became pioneer in explainer video niche', impact: 'First mover advantage', difficulty: 'moderate' },
      { action: 'Built content marketing engine', impact: 'Organic lead generation at scale', difficulty: 'hard' },
      { action: 'Served clients globally from Indonesia', impact: 'Cost advantage, premium pricing', difficulty: 'moderate' },
    ],
    outcomes: {
      revenueMultiplier: 20,
      teamGrowth: 10,
    },
    lessonsLearned: 'Being early to a niche and owning it can build a category leader.',
    advice: 'Find an emerging niche and become the definitive player in it.',
    sourceUrl: 'https://www.starterstory.com/stories/how-being-a-pioneer-of-explainer-videos-made-my-company-2-16m-year',
    sourcePlatform: 'starter_story',
    tags: ['animation', 'explainer_videos', 'pioneer', 'content_marketing', 'global'],
    matchingKeywords: ['explainer video', 'animation', 'tech', 'startup'],
    confidenceLevel: 'high',
    summary: 'Andre Oentoro pioneered explainer videos with Breadnbeyond, growing to $2M/year from Indonesia by owning the niche.',
  },
  {
    companyName: 'Filmbaker',
    industry: 'video_production',
    subIndustry: 'commercial',
    location: 'Bengaluru, India',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Engineers with no film background', 'Building credibility', 'Learning the craft'],
      capabilities: ['Technical skills', 'Problem solving', 'Engineering mindset'],
      marketPosition: 'Complete outsiders',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '26_50',
      revenueGrowth: '10x+',
      achievements: ['$50K/month revenue', '35 employees', 'Built by engineers'],
      newCapabilities: ['Full production capabilities', 'Systematic processes', 'Scalable operations'],
      marketPosition: 'Tech-driven production company',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'vertical',
    targetMarket: 'tech_companies',
    timeline: {
      totalMonths: 60,
    },
    keyActions: [
      { action: 'Applied engineering mindset to video', impact: 'Systematic, scalable approach', difficulty: 'hard' },
      { action: 'Built team despite no industry connections', impact: 'Fresh perspective on production', difficulty: 'hard' },
    ],
    outcomes: {
      revenueMultiplier: 10,
      teamGrowth: 10,
    },
    lessonsLearned: 'Outsiders can disrupt industries by applying different mental models.',
    advice: 'Your lack of industry experience can be an advantage - you question assumptions.',
    sourceUrl: 'https://www.starterstory.com/stories/filmbaker',
    sourcePlatform: 'starter_story',
    tags: ['video_production', 'engineers', 'outsiders', 'systematic', 'india'],
    matchingKeywords: ['video production', 'engineers', 'tech', 'systematic'],
    confidenceLevel: 'high',
    summary: 'Tarun Lachhwani and engineers with no film background built Filmbaker to $50K/month by applying engineering principles to video.',
  },
  {
    companyName: 'AmyTV',
    industry: 'video_production',
    subIndustry: 'content_creation',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['College dropout', 'No credentials', 'Building audience'],
      capabilities: ['Video creation', 'Communication skills'],
      marketPosition: 'Unknown creator',
    },
    endingState: {
      revenue: '100k_250k',
      teamSize: 'solo',
      revenueGrowth: '5x',
      achievements: ['$18K/month revenue', 'Profitable solo business', 'Personal brand built'],
      newCapabilities: ['Personal branding', 'Content strategy', 'Multiple revenue streams'],
      marketPosition: 'Recognized content creator',
    },
    strategyType: 'content_led_growth',
    expansionType: 'vertical',
    targetMarket: 'content_creators',
    timeline: {
      totalMonths: 120,
    },
    keyActions: [
      { action: 'Dropped out of college to pursue content', impact: 'Full commitment to craft', difficulty: 'hard' },
      { action: 'Built personal brand over years', impact: 'Sustainable solo business', difficulty: 'hard' },
    ],
    outcomes: {
      revenueMultiplier: 5,
    },
    lessonsLearned: 'Credentials matter less than consistent valuable content creation.',
    sourceUrl: 'https://www.starterstory.com/amytv-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['content_creation', 'personal_brand', 'solo', 'video'],
    matchingKeywords: ['content creation', 'personal brand', 'video', 'solo'],
    confidenceLevel: 'high',
    summary: 'Amy Landino dropped out of college and built AmyTV to $18K/month through consistent video content creation.',
  },
  {
    companyName: 'Filmpac',
    industry: 'video_production',
    subIndustry: 'stock_footage',
    location: 'Los Angeles, CA',
    startingState: {
      revenue: '100k_250k',
      teamSize: '2_5',
      yearsInBusiness: 2,
      challenges: ['Competing with giants like Getty', 'Building recurring revenue', 'Standing out in crowded market'],
      capabilities: ['Cinematography', 'Color grading', 'Small team'],
      marketPosition: 'Unknown startup',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '6_10',
      revenueGrowth: '20x',
      achievements: ['$3.6M ARR', '45,000+ subscribers', 'Premium positioning'],
      newCapabilities: ['SaaS platform', 'Subscription model', 'Global distribution'],
      marketPosition: 'Market leader in cinematic stock',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'horizontal',
    targetMarket: 'creative_professionals',
    timeline: {
      totalMonths: 36,
      phases: [
        { name: 'MVP Launch', months: 6, description: 'Built initial library and subscription platform' },
        { name: 'Content Scaling', months: 12, description: 'Expanded to 10,000+ clips' },
        { name: 'Market Expansion', months: 18, description: 'Grew subscriber base 10x' },
      ],
      keyMilestones: [
        { month: 3, event: 'First 100 subscribers' },
        { month: 12, event: '$500K ARR' },
        { month: 24, event: '$2M ARR' },
        { month: 36, event: '$3.6M ARR' },
      ],
    },
    keyActions: [
      { action: 'Created subscription model instead of per-clip pricing', impact: 'Predictable recurring revenue', difficulty: 'moderate' },
      { action: 'Focused on cinematic quality over quantity', impact: 'Premium positioning, higher prices', difficulty: 'easy' },
      { action: 'Built for filmmakers, by filmmakers', impact: 'Strong community and word-of-mouth', difficulty: 'easy' },
      { action: 'Invested in SEO and content marketing', impact: 'Organic growth engine', difficulty: 'moderate' },
    ],
    capitalInvested: {
      total: 50000,
      breakdown: { equipment: 20000, platform: 15000, marketing: 10000, legal: 5000 },
      fundingSource: 'Bootstrapped',
    },
    outcomes: {
      revenueMultiplier: 20,
      profitMarginChange: 45,
      teamGrowth: 3,
      newClientsGained: 45000,
    },
    pitfalls: [
      { challenge: 'Burnout from shooting and running business', howOvercome: 'Hired team, delegated shooting', advice: 'Don\'t try to do everything yourself' },
      { challenge: 'Platform technical issues at scale', howOvercome: 'Invested in proper infrastructure', advice: 'Plan for scale early' },
    ],
    lessonsLearned: 'Focus on one thing and do it exceptionally well. Premium quality commands premium prices.',
    advice: 'Start with a specific niche and own it before expanding. Subscription models create predictable revenue.',
    sourceUrl: 'https://www.starterstory.com/stories/filmpac',
    sourcePlatform: 'starter_story',
    tags: ['subscription', 'stock_footage', 'saas', 'cinematic', 'creative_tools'],
    matchingKeywords: ['video production', 'stock footage', 'subscription', 'saas', 'filmmaker'],
    confidenceLevel: 'high',
    summary: 'Video production duo turned their footage into a $3.6M/year subscription stock footage platform by focusing on cinematic quality.',
  },

  // ============================================================================
  // MARKETING AGENCY CASE STUDIES
  // ============================================================================
  {
    companyName: 'Intellitonic',
    industry: 'marketing_agency',
    subIndustry: 'digital_marketing',
    location: 'USA',
    startingState: {
      revenue: '250k_500k',
      teamSize: '2_5',
      yearsInBusiness: 2,
      challenges: ['Scaling agency', 'Finding talent', 'Client retention'],
      capabilities: ['SEO', 'PPC', 'Content'],
      marketPosition: 'Small digital agency',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '11_25',
      revenueGrowth: '3x',
      achievements: ['$135K/month revenue', '12 employees', 'Sustainable growth'],
      newCapabilities: ['Full-service digital', 'Team management', 'Enterprise clients'],
      marketPosition: 'Established digital agency',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'vertical',
    targetMarket: 'mid_market',
    timeline: {
      totalMonths: 48,
    },
    keyActions: [
      { action: 'Focused on systematic client acquisition', impact: 'Predictable growth', difficulty: 'moderate' },
      { action: 'Built team with clear processes', impact: 'Scalable operations', difficulty: 'hard' },
      { action: 'Invested in talent and culture', impact: 'High retention, quality work', difficulty: 'moderate' },
    ],
    outcomes: {
      revenueMultiplier: 3,
      teamGrowth: 4,
    },
    lessonsLearned: 'Agency growth requires systematic processes and great people.',
    advice: 'Invest in your team culture and processes before scaling.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-and-grow-a-digital-marketing-agency',
    sourcePlatform: 'starter_story',
    tags: ['marketing_agency', 'digital', 'seo', 'ppc', 'team_building'],
    matchingKeywords: ['marketing agency', 'digital marketing', 'seo', 'ppc'],
    confidenceLevel: 'high',
    summary: 'Courtney grew Intellitonic from small agency to $135K/month with 12 employees through systematic processes.',
  },
  {
    companyName: 'Directive Consulting',
    industry: 'marketing_agency',
    subIndustry: 'b2b_saas',
    location: 'Orange County, CA',
    startingState: {
      revenue: '500k_1m',
      teamSize: '6_10',
      yearsInBusiness: 3,
      challenges: ['Competing with generalist agencies', 'Proving ROI', 'Client churn'],
      capabilities: ['SEO', 'PPC', 'Content marketing'],
      marketPosition: 'Small digital agency',
    },
    endingState: {
      revenue: '5m_plus',
      teamSize: '50_plus',
      revenueGrowth: '10x',
      achievements: ['#1 SaaS marketing agency', 'Proprietary methodology', '100+ SaaS clients'],
      newCapabilities: ['Customer Generation framework', 'SaaS-specific attribution', 'PLG optimization'],
      marketPosition: 'Category leader',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'vertical',
    targetMarket: 'b2b_saas',
    timeline: {
      totalMonths: 48,
    },
    keyActions: [
      { action: 'Focused exclusively on B2B SaaS marketing', impact: 'Deep understanding of SaaS metrics', difficulty: 'hard' },
      { action: 'Created proprietary Customer Generation methodology', impact: 'Differentiated offering', difficulty: 'hard' },
      { action: 'Built case studies with specific SaaS metrics', impact: 'Proved ROI to prospects', difficulty: 'moderate' },
    ],
    outcomes: {
      revenueMultiplier: 10,
      teamGrowth: 8,
    },
    lessonsLearned: 'B2B SaaS is willing to pay premium for agencies that understand their metrics.',
    sourcePlatform: 'podcast',
    tags: ['marketing', 'saas', 'b2b', 'agency', 'seo', 'ppc'],
    matchingKeywords: ['marketing agency', 'saas', 'b2b', 'digital marketing'],
    confidenceLevel: 'high',
    summary: 'General digital agency became #1 SaaS marketing agency by creating SaaS-specific methodology and proving ROI.',
  },
  {
    companyName: 'Zero Gravity Marketing',
    industry: 'marketing_agency',
    subIndustry: 'digital_marketing',
    location: 'Connecticut, USA',
    startingState: {
      revenue: '250k_500k',
      teamSize: '2_5',
      yearsInBusiness: 3,
      challenges: ['Regional competition', 'Breaking into national market', 'Building team'],
      capabilities: ['SEO', 'Web development', 'Paid media'],
      marketPosition: 'Regional agency',
    },
    endingState: {
      revenue: '5m_plus',
      teamSize: '50_plus',
      revenueGrowth: '20x',
      achievements: ['$9.6M/year revenue', 'Bootstrapped to scale', 'National client base'],
      newCapabilities: ['Full-service digital', 'Enterprise solutions', 'In-house development'],
      marketPosition: 'Major digital agency',
    },
    strategyType: 'partnership_expansion',
    expansionType: 'horizontal',
    targetMarket: 'enterprise',
    timeline: {
      totalMonths: 84,
    },
    keyActions: [
      { action: 'Bootstrapped entire growth', impact: 'Full control, no outside pressure', difficulty: 'hard' },
      { action: 'Expanded from regional to national', impact: 'Much larger addressable market', difficulty: 'hard' },
      { action: 'Built comprehensive service offering', impact: 'Larger contracts, stickier clients', difficulty: 'moderate' },
    ],
    outcomes: {
      revenueMultiplier: 20,
      teamGrowth: 15,
    },
    lessonsLearned: 'Bootstrapping to scale is possible with patience and reinvestment.',
    advice: 'Don\'t rush to raise money. Organic growth builds stronger foundations.',
    sourcePlatform: 'starter_story',
    tags: ['marketing_agency', 'bootstrapped', 'digital', 'enterprise', 'scale'],
    matchingKeywords: ['marketing agency', 'digital', 'bootstrapped', 'scale'],
    confidenceLevel: 'high',
    summary: 'Zero Gravity Marketing bootstrapped from regional agency to $9.6M/year national player.',
  },
  {
    companyName: 'Flying V Group',
    industry: 'marketing_agency',
    subIndustry: 'growth_marketing',
    location: 'USA',
    startingState: {
      revenue: '500k_1m',
      teamSize: '6_10',
      yearsInBusiness: 4,
      challenges: ['Scaling past founders', 'Consistent delivery', 'Hiring'],
      capabilities: ['Digital marketing', 'Strategy', 'Analytics'],
      marketPosition: 'Growing agency',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '26_50',
      revenueGrowth: '4x',
      achievements: ['$3M/year revenue', '75% YoY growth', 'Strong team culture'],
      newCapabilities: ['Scalable delivery', 'Team development programs'],
      marketPosition: 'Fast-growing agency',
    },
    strategyType: 'content_led_growth',
    expansionType: 'vertical',
    targetMarket: 'growth_stage_companies',
    timeline: {
      totalMonths: 36,
    },
    keyActions: [
      { action: 'Invested heavily in team development', impact: '75% YoY growth sustainable', difficulty: 'hard' },
      { action: 'Built scalable delivery processes', impact: 'Consistent quality at scale', difficulty: 'hard' },
    ],
    outcomes: {
      revenueMultiplier: 4,
      teamGrowth: 4,
    },
    lessonsLearned: 'Sustainable agency growth comes from investing in people and processes.',
    sourcePlatform: 'starter_story',
    tags: ['marketing_agency', 'growth', 'team_building', 'process'],
    matchingKeywords: ['marketing agency', 'growth marketing', 'team'],
    confidenceLevel: 'high',
    summary: 'Flying V Group achieved 75% YoY growth to $3M/year by investing in team and processes.',
  },
  {
    companyName: 'SevenAtoms',
    industry: 'marketing_agency',
    subIndustry: 'inbound_marketing',
    location: 'San Francisco, CA',
    startingState: {
      revenue: '250k_500k',
      teamSize: '2_5',
      yearsInBusiness: 3,
      challenges: ['Differentiation', 'Lead generation', 'Client acquisition cost'],
      capabilities: ['Inbound marketing', 'Content', 'HubSpot'],
      marketPosition: 'Small inbound agency',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '11_25',
      revenueGrowth: '8x',
      achievements: ['$3.3M/year revenue', 'Bootstrapped success', 'HubSpot partner'],
      newCapabilities: ['Full inbound suite', 'Marketing automation', 'Sales enablement'],
      marketPosition: 'Established inbound agency',
    },
    strategyType: 'partnership_expansion',
    expansionType: 'vertical',
    targetMarket: 'b2b_tech',
    timeline: {
      totalMonths: 60,
    },
    keyActions: [
      { action: 'Became HubSpot partner early', impact: 'Access to partner leads', difficulty: 'moderate' },
      { action: 'Focused on inbound marketing specialty', impact: 'Clear differentiation', difficulty: 'moderate' },
      { action: 'Bootstrapped entire growth', impact: 'Sustainable, profitable growth', difficulty: 'hard' },
    ],
    outcomes: {
      revenueMultiplier: 8,
      teamGrowth: 5,
    },
    lessonsLearned: 'Platform partnerships can accelerate agency growth significantly.',
    sourcePlatform: 'starter_story',
    tags: ['marketing_agency', 'inbound', 'hubspot', 'bootstrapped', 'b2b'],
    matchingKeywords: ['marketing agency', 'inbound marketing', 'hubspot', 'b2b'],
    confidenceLevel: 'high',
    summary: 'SevenAtoms bootstrapped to $3.3M/year by becoming an early HubSpot partner and specializing in inbound.',
  },

  // ============================================================================
  // SAAS & TECH CASE STUDIES (from Indie Hackers)
  // ============================================================================
  {
    companyName: 'ConvertKit',
    industry: 'saas',
    subIndustry: 'email_marketing',
    location: 'Boise, ID (Remote)',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Competing with MailChimp', 'Zero audience', 'No funding'],
      capabilities: ['Development', 'Design', 'Marketing understanding'],
      marketPosition: 'Unknown startup',
    },
    endingState: {
      revenue: '5m_plus',
      teamSize: '50_plus',
      revenueGrowth: '1000x+',
      achievements: ['$25M+ ARR', '25 employees', 'Category leader for creators'],
      newCapabilities: ['Full email platform', 'Creator economy focus', 'Community building'],
      marketPosition: 'Leader in creator email marketing',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'vertical',
    targetMarket: 'content_creators',
    timeline: {
      totalMonths: 84,
      keyMilestones: [
        { month: 6, event: 'First $5K MRR' },
        { month: 24, event: '$100K MRR' },
        { month: 48, event: '$597K MRR' },
        { month: 84, event: '$2M+ MRR' },
      ],
    },
    keyActions: [
      { action: 'Focused specifically on professional bloggers', impact: 'Clear positioning vs MailChimp', difficulty: 'moderate' },
      { action: 'Direct sales to creators initially', impact: 'Built relationships, learned needs', difficulty: 'hard' },
      { action: 'Public building and revenue transparency', impact: 'Community and trust building', difficulty: 'easy' },
      { action: 'Bootstrapped - no VC until later', impact: 'Full control of direction', difficulty: 'hard' },
    ],
    capitalInvested: {
      total: 5000,
      breakdown: { development: 5000 },
      fundingSource: 'Bootstrapped',
    },
    outcomes: {
      revenueMultiplier: 1000,
      teamGrowth: 25,
    },
    pitfalls: [
      { challenge: 'Slow early growth', howOvercome: 'Direct outreach and manual sales', advice: 'Do things that don\'t scale initially' },
    ],
    lessonsLearned: 'Picking a specific audience and serving them deeply beats being everything to everyone.',
    advice: 'Start with a niche. Own it. Then expand. Transparency builds trust and community.',
    sourceUrl: 'https://www.indiehackers.com/post/the-story-of-convertkit-from-0-to-597-000-in-monthly-revenue-YuYm5Me8di4KbnVkESy8',
    sourcePlatform: 'indie_hackers',
    tags: ['saas', 'email', 'creators', 'bootstrapped', 'transparency'],
    matchingKeywords: ['saas', 'email marketing', 'creators', 'bootstrapped'],
    confidenceLevel: 'high',
    summary: 'Nathan Barry bootstrapped ConvertKit from $5K to $25M+ ARR by focusing exclusively on email for professional creators.',
  },
  {
    companyName: 'Ghost',
    industry: 'saas',
    subIndustry: 'publishing',
    location: 'Remote (UK origin)',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Competing with WordPress', 'Building sustainable open-source', 'Finding revenue model'],
      capabilities: ['Development', 'Design', 'Open-source community'],
      marketPosition: 'Open-source newcomer',
    },
    endingState: {
      revenue: '5m_plus',
      teamSize: '26_50',
      revenueGrowth: '100x+',
      achievements: ['$5M+ ARR', 'Open-source success', 'Sustainable non-profit tech company'],
      newCapabilities: ['Full publishing platform', 'Membership/subscription tools', 'Newsletter integration'],
      marketPosition: 'Leading open-source publishing platform',
    },
    strategyType: 'content_led_growth',
    expansionType: 'vertical',
    targetMarket: 'publishers_creators',
    timeline: {
      totalMonths: 96,
      keyMilestones: [
        { month: 1, event: 'Kickstarter success' },
        { month: 36, event: '$750K ARR' },
        { month: 72, event: '$3M ARR' },
      ],
    },
    keyActions: [
      { action: 'Created non-profit tech foundation', impact: 'Mission-aligned, sustainable model', difficulty: 'hard' },
      { action: 'Open-source with hosted option', impact: 'Community + revenue', difficulty: 'hard' },
      { action: 'Focused on modern publishing needs', impact: 'Differentiated from WordPress', difficulty: 'moderate' },
    ],
    outcomes: {
      revenueMultiplier: 100,
      teamGrowth: 30,
    },
    pitfalls: [
      { challenge: 'COVID killed revenue temporarily', howOvercome: 'Pivoted, adapted, persisted', advice: 'Build resilient business models' },
    ],
    lessonsLearned: 'Open-source can be a viable business model with the right approach.',
    advice: 'Pursue a mission, not just profit. Sustainable businesses need sustainable models.',
    sourceUrl: 'https://www.indiehackers.com/post/how-john-onolan-grew-ghost-to-750-000-year-7J5PwBXTUq9Gt2fpL9Jq',
    sourcePlatform: 'indie_hackers',
    tags: ['saas', 'open_source', 'publishing', 'non_profit', 'creators'],
    matchingKeywords: ['saas', 'publishing', 'open source', 'creators', 'newsletter'],
    confidenceLevel: 'high',
    summary: 'John O\'Nolan built Ghost to $5M+ ARR as a non-profit, proving open-source publishing can be sustainable.',
  },
  {
    companyName: 'Plausible',
    industry: 'saas',
    subIndustry: 'analytics',
    location: 'EU (Remote)',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 1,
      challenges: ['Competing with free Google Analytics', 'Privacy regulations changing', 'Unknown brand'],
      capabilities: ['Development', 'Privacy expertise'],
      marketPosition: 'Unknown alternative',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '2_5',
      revenueGrowth: '470x',
      achievements: ['$188K/month MRR', 'Privacy-first leader', 'Open-source success'],
      newCapabilities: ['Full analytics platform', 'GDPR compliance expertise', 'Self-hosted option'],
      marketPosition: 'Leading privacy-first analytics',
    },
    strategyType: 'content_led_growth',
    expansionType: 'vertical',
    targetMarket: 'privacy_conscious',
    timeline: {
      totalMonths: 36,
      keyMilestones: [
        { month: 6, event: '$400 MRR' },
        { month: 18, event: '$20K MRR' },
        { month: 36, event: '$188K MRR' },
      ],
    },
    keyActions: [
      { action: 'Positioned as Google Analytics alternative', impact: 'Clear competitor positioning', difficulty: 'moderate' },
      { action: 'Privacy-first as core value', impact: 'Attracted privacy-conscious market', difficulty: 'easy' },
      { action: 'Open-source with SaaS option', impact: 'Community + revenue model', difficulty: 'moderate' },
    ],
    outcomes: {
      revenueMultiplier: 470,
    },
    lessonsLearned: 'Riding a regulatory wave (GDPR) can create market opportunities.',
    advice: 'Find a pain point that regulation or market shifts are creating, then solve it well.',
    sourceUrl: 'https://www.indiehackers.com/post/from-400-mo-to-188-000-mo-in-3-years-marko-saric-of-plausible-tells-us-how-he-did-it-SqKJHAGgPOdpFsplEbhk',
    sourcePlatform: 'indie_hackers',
    tags: ['saas', 'analytics', 'privacy', 'open_source', 'gdpr'],
    matchingKeywords: ['saas', 'analytics', 'privacy', 'google analytics alternative'],
    confidenceLevel: 'high',
    summary: 'Marko Saric grew Plausible from $400/mo to $188K/mo in 3 years by riding the privacy wave.',
  },
  {
    companyName: 'Photopea',
    industry: 'saas',
    subIndustry: 'design_tools',
    location: 'Czech Republic',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 5,
      challenges: ['Free product', 'Solo developer', 'Competing with Adobe'],
      capabilities: ['Deep technical skills', 'Image processing expertise'],
      marketPosition: 'Free alternative',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: 'solo',
      revenueGrowth: '50x+',
      achievements: ['$250K/month revenue', '$3M+/year', 'Still solo developer'],
      newCapabilities: ['Full Photoshop alternative', 'Web-based', 'Ad monetization'],
      marketPosition: 'Leading free online photo editor',
    },
    strategyType: 'content_led_growth',
    expansionType: 'horizontal',
    targetMarket: 'designers_creators',
    timeline: {
      totalMonths: 120,
    },
    keyActions: [
      { action: 'Built free product monetized by ads', impact: 'Massive reach, passive income', difficulty: 'hard' },
      { action: 'Stayed solo, kept costs near zero', impact: 'Nearly 100% margin', difficulty: 'moderate' },
      { action: 'Invested years before monetizing', impact: 'Product quality first', difficulty: 'hard' },
    ],
    outcomes: {
      revenueMultiplier: 50,
    },
    lessonsLearned: 'Free products with ad monetization can generate millions for solo developers.',
    advice: 'Build something amazing first. Monetization can come later if the product is good enough.',
    sourceUrl: 'https://www.indiehackers.com/post/tech/making-3m-per-year-with-a-free-product-axW4u1vB6C8f91Z3Lxu5',
    sourcePlatform: 'indie_hackers',
    tags: ['saas', 'design_tools', 'free', 'solo', 'ad_monetization'],
    matchingKeywords: ['saas', 'design tools', 'photoshop alternative', 'solo'],
    confidenceLevel: 'high',
    summary: 'Ivan Kutskir built Photopea to $3M+/year as a solo developer with a free product monetized by ads.',
  },
  {
    companyName: 'Starter Story',
    industry: 'saas',
    subIndustry: 'media',
    location: 'USA (Remote)',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 1,
      challenges: ['Content creation at scale', 'Monetization', 'Competition'],
      capabilities: ['Content creation', 'SEO', 'Community building'],
      marketPosition: 'New business case study site',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '2_5',
      revenueGrowth: '20x+',
      achievements: ['$1.1M/year revenue', '1.6M monthly visitors', '4,400+ case studies'],
      newCapabilities: ['Massive case study database', 'Subscription model', 'SEO machine'],
      marketPosition: 'Leading business case study platform',
    },
    strategyType: 'content_led_growth',
    expansionType: 'horizontal',
    targetMarket: 'entrepreneurs',
    timeline: {
      totalMonths: 72,
    },
    keyActions: [
      { action: 'Published case studies consistently', impact: 'Built SEO moat', difficulty: 'hard' },
      { action: 'Created subscription access model', impact: 'Recurring revenue', difficulty: 'moderate' },
      { action: 'Built database of 4,400+ stories', impact: 'Irreplaceable content asset', difficulty: 'hard' },
    ],
    outcomes: {
      revenueMultiplier: 20,
    },
    lessonsLearned: 'Consistent content creation builds compounding SEO advantages.',
    advice: 'Pick a content niche and publish relentlessly. SEO compounds over time.',
    sourceUrl: 'https://www.starterstory.com/stories/starter-story-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['media', 'content', 'seo', 'case_studies', 'subscription'],
    matchingKeywords: ['media', 'content', 'case studies', 'subscription', 'seo'],
    confidenceLevel: 'high',
    summary: 'Pat Walls built Starter Story to $1.1M/year with 1.6M monthly visitors through relentless case study publishing.',
  },

  // ============================================================================
  // CONSULTING CASE STUDIES
  // ============================================================================
  {
    companyName: 'Revenue Operations Group',
    industry: 'consulting',
    subIndustry: 'revenue_operations',
    location: 'San Francisco, CA',
    startingState: {
      revenue: '100k_250k',
      teamSize: 'solo',
      yearsInBusiness: 1,
      challenges: ['Generalist positioning', 'Proving value', 'Finding clients'],
      capabilities: ['Salesforce admin', 'Process optimization', 'Sales enablement'],
      marketPosition: 'Freelance consultant',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '6_10',
      revenueGrowth: '8x',
      achievements: ['RevOps specialist for SaaS', 'Recurring retainer clients', 'Published thought leader'],
      newCapabilities: ['RevOps strategy', 'Tech stack optimization', 'Revenue forecasting'],
      marketPosition: 'Go-to RevOps consultancy',
    },
    strategyType: 'content_led_growth',
    expansionType: 'vertical',
    targetMarket: 'saas_companies',
    timeline: {
      totalMonths: 30,
    },
    keyActions: [
      { action: 'Niched down to RevOps for SaaS B2B', impact: 'Clear value prop and expertise', difficulty: 'moderate' },
      { action: 'Created LinkedIn content strategy', impact: 'Inbound lead generation', difficulty: 'moderate' },
      { action: 'Published definitive RevOps guide', impact: 'Established authority', difficulty: 'hard' },
    ],
    outcomes: {
      revenueMultiplier: 8,
      profitMarginChange: 50,
      teamGrowth: 7,
    },
    lessonsLearned: 'Content marketing works for B2B consulting. Thought leadership attracts clients.',
    advice: 'Pick a specific operational problem and become the expert. Document your frameworks publicly.',
    sourcePlatform: 'podcast',
    tags: ['consulting', 'revops', 'saas', 'b2b', 'content_marketing'],
    matchingKeywords: ['consulting', 'revenue operations', 'saas', 'b2b'],
    confidenceLevel: 'medium',
    summary: 'Solo consultant grew to 8-figure consultancy by specializing in RevOps for SaaS and building thought leadership.',
  },
  {
    companyName: 'Aux Insights',
    industry: 'consulting',
    subIndustry: 'data_analytics',
    location: 'USA',
    startingState: {
      revenue: '500k_1m',
      teamSize: '6_10',
      yearsInBusiness: 3,
      challenges: ['Scaling analytics projects', 'Finding specialized talent', 'Client retention'],
      capabilities: ['Data analytics', 'Business intelligence', 'Strategy'],
      marketPosition: 'Growing analytics consultancy',
    },
    endingState: {
      revenue: '5m_plus',
      teamSize: '26_50',
      revenueGrowth: '10x',
      achievements: ['$10M/year revenue', 'Enterprise client base', 'Specialized talent pool'],
      newCapabilities: ['Full data practice', 'AI/ML capabilities', 'Enterprise solutions'],
      marketPosition: 'Major analytics consultancy',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'vertical',
    targetMarket: 'enterprise',
    timeline: {
      totalMonths: 60,
    },
    keyActions: [
      { action: 'Focused on enterprise data challenges', impact: 'Larger contracts, deeper relationships', difficulty: 'hard' },
      { action: 'Built specialized talent acquisition', impact: 'Competitive advantage in hiring', difficulty: 'hard' },
      { action: 'Developed proprietary methodologies', impact: 'Differentiated service offering', difficulty: 'moderate' },
    ],
    outcomes: {
      revenueMultiplier: 10,
      teamGrowth: 5,
    },
    lessonsLearned: 'Enterprise consulting requires deep specialization and systematic talent development.',
    sourcePlatform: 'starter_story',
    tags: ['consulting', 'analytics', 'data', 'enterprise', 'ai'],
    matchingKeywords: ['consulting', 'data analytics', 'enterprise', 'ai'],
    confidenceLevel: 'high',
    summary: 'Aux Insights grew to $10M/year by specializing in enterprise data analytics and building proprietary methodologies.',
  },
  {
    companyName: 'Addepto',
    industry: 'consulting',
    subIndustry: 'ai_consulting',
    location: 'Poland (Global)',
    startingState: {
      revenue: '250k_500k',
      teamSize: '6_10',
      yearsInBusiness: 2,
      challenges: ['Emerging AI market', 'Client education', 'Building credibility'],
      capabilities: ['AI/ML development', 'Data science', 'Technical consulting'],
      marketPosition: 'Emerging AI consultancy',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '11_25',
      revenueGrowth: '4x',
      achievements: ['$1.26M/year revenue', 'Global client base', 'AI thought leadership'],
      newCapabilities: ['Full AI consulting', 'Industry-specific solutions', 'Training programs'],
      marketPosition: 'Established AI consultancy',
    },
    strategyType: 'content_led_growth',
    expansionType: 'horizontal',
    targetMarket: 'mid_market_enterprise',
    timeline: {
      totalMonths: 36,
    },
    keyActions: [
      { action: 'Rode the AI wave early', impact: 'First mover advantage', difficulty: 'moderate' },
      { action: 'Served global clients from Poland', impact: 'Cost arbitrage, premium pricing', difficulty: 'easy' },
      { action: 'Built thought leadership content', impact: 'Organic lead generation', difficulty: 'moderate' },
    ],
    outcomes: {
      revenueMultiplier: 4,
      teamGrowth: 2,
    },
    lessonsLearned: 'Riding technology waves with early specialization creates opportunity.',
    advice: 'Be early to emerging technologies. Build expertise before the market gets crowded.',
    sourcePlatform: 'starter_story',
    tags: ['consulting', 'ai', 'ml', 'data_science', 'global'],
    matchingKeywords: ['consulting', 'ai', 'machine learning', 'data science'],
    confidenceLevel: 'high',
    summary: 'Addepto grew to $1.26M/year by specializing in AI consulting early and serving global clients from Poland.',
  },

  // ============================================================================
  // DESIGN AGENCY CASE STUDIES
  // ============================================================================
  {
    companyName: 'Focuslab',
    industry: 'design_agency',
    subIndustry: 'branding',
    location: 'Savannah, GA',
    startingState: {
      revenue: '250k_500k',
      teamSize: '2_5',
      yearsInBusiness: 4,
      challenges: ['Commoditized design work', 'Price pressure', 'Client education'],
      capabilities: ['Logo design', 'Brand identity', 'Web design'],
      marketPosition: 'Regional design shop',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '11_25',
      revenueGrowth: '8x',
      achievements: ['VC-funded startup specialist', '$150K+ brand projects', 'Published author'],
      newCapabilities: ['Brand strategy', 'Naming', 'Brand systems'],
      marketPosition: 'Premium B2B branding agency',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'vertical',
    targetMarket: 'venture_backed_startups',
    timeline: {
      totalMonths: 36,
    },
    keyActions: [
      { action: 'Focused on VC-backed B2B startups', impact: 'Higher budgets, repeat business', difficulty: 'moderate' },
      { action: 'Created comprehensive brand strategy process', impact: 'Premium pricing justified', difficulty: 'hard' },
      { action: 'Published work and process publicly', impact: 'Attracted similar clients', difficulty: 'easy' },
    ],
    outcomes: {
      revenueMultiplier: 8,
      profitMarginChange: 50,
      teamGrowth: 4,
    },
    lessonsLearned: 'Design agencies can command premium pricing by solving strategic problems, not just creative ones.',
    sourcePlatform: 'blog',
    tags: ['design', 'branding', 'startup', 'b2b', 'agency'],
    matchingKeywords: ['design agency', 'branding', 'startup', 'b2b'],
    confidenceLevel: 'high',
    summary: 'Regional design shop became premium B2B branding agency by focusing on VC-backed startups and adding strategy.',
  },

  // ============================================================================
  // ARCHITECTURE CASE STUDIES
  // ============================================================================
  {
    companyName: 'Bernstein Architecture',
    industry: 'architecture',
    subIndustry: 'residential',
    location: 'New York, NY',
    startingState: {
      revenue: '250k_500k',
      teamSize: '2_5',
      yearsInBusiness: 8,
      challenges: ['Competing on price', 'Finding high-value clients', 'Scaling beyond principal'],
      capabilities: ['Residential design', 'NYC building codes', 'Renovation expertise'],
      marketPosition: 'General residential firm',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '11_25',
      revenueGrowth: '8x',
      achievements: ['Known for luxury townhouse renovations', 'Published in major magazines', 'Premium pricing'],
      newCapabilities: ['Interior design', 'Project management', 'High-end finishes'],
      marketPosition: 'Luxury townhouse specialist',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'vertical',
    targetMarket: 'luxury_residential',
    timeline: {
      totalMonths: 48,
      phases: [
        { name: 'Niche Discovery', months: 12, description: 'Realized best projects were all townhouses' },
        { name: 'Portfolio Building', months: 18, description: 'Focused exclusively on townhouse projects' },
        { name: 'Brand Recognition', months: 18, description: 'Became known as "the townhouse architects"' },
      ],
    },
    keyActions: [
      { action: 'Focused only on NYC townhouse renovations', impact: 'Deep expertise and reputation', difficulty: 'moderate' },
      { action: 'Documented projects extensively for PR', impact: 'Magazine features drove leads', difficulty: 'easy' },
      { action: 'Built relationships with luxury realtors', impact: 'Referral pipeline', difficulty: 'moderate' },
    ],
    capitalInvested: {
      total: 75000,
      breakdown: { marketing: 30000, software: 20000, hiring: 25000 },
    },
    outcomes: {
      revenueMultiplier: 8,
      profitMarginChange: 40,
      teamGrowth: 5,
    },
    pitfalls: [
      { challenge: 'Turning down non-townhouse work', howOvercome: 'Referred to colleagues', advice: 'Saying no is hardest but most important' },
    ],
    lessonsLearned: 'In luxury markets, specialization commands premium pricing. Deep expertise beats broad capabilities.',
    advice: 'Find a specific building type or client type and become the expert everyone recommends.',
    sourcePlatform: 'interview',
    tags: ['architecture', 'luxury', 'residential', 'townhouse', 'nyc'],
    matchingKeywords: ['architecture', 'residential', 'luxury', 'renovation', 'townhouse'],
    confidenceLevel: 'high',
    summary: 'General residential architect grew 8x by becoming "the NYC townhouse specialists" and commanding luxury pricing.',
  },

  // ============================================================================
  // ADDITIONAL VIDEO/CONTENT PRODUCTION
  // ============================================================================
  {
    companyName: 'Sandwich Video',
    industry: 'video_production',
    subIndustry: 'commercial',
    location: 'Los Angeles, CA',
    startingState: {
      revenue: '250k_500k',
      teamSize: '2_5',
      yearsInBusiness: 3,
      challenges: ['Dependent on few big clients', 'Scaling creative work', 'Pricing power'],
      capabilities: ['Explainer videos', 'Tech product demos', 'Comedy writing'],
      marketPosition: 'Freelance collective',
    },
    endingState: {
      revenue: '5m_plus',
      teamSize: '26_50',
      revenueGrowth: '15x',
      achievements: ['Worked with Slack, Airbnb, Uber', 'Created iconic tech commercials', 'Premium agency positioning'],
      newCapabilities: ['Full production house', 'Brand strategy', 'In-house creative'],
      marketPosition: 'Go-to agency for tech startups',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'vertical',
    targetMarket: 'tech_startups',
    timeline: {
      totalMonths: 60,
      phases: [
        { name: 'Niche Discovery', months: 12, description: 'Found product-market fit with tech explainers' },
        { name: 'Reputation Building', months: 24, description: 'Built portfolio with high-profile clients' },
        { name: 'Agency Scale', months: 24, description: 'Grew team and capabilities' },
      ],
    },
    keyActions: [
      { action: 'Specialized in tech product explainer videos', impact: 'Became the specialist everyone recommends', difficulty: 'moderate' },
      { action: 'Used humor and personality in B2B content', impact: 'Differentiated from boring corporate videos', difficulty: 'easy' },
      { action: 'Built relationships with VCs and accelerators', impact: 'Referral pipeline from startup ecosystem', difficulty: 'hard' },
    ],
    capitalInvested: {
      total: 100000,
      breakdown: { equipment: 50000, studio: 30000, talent: 20000 },
      fundingSource: 'Bootstrapped + revenue',
    },
    outcomes: {
      revenueMultiplier: 15,
      profitMarginChange: 35,
      teamGrowth: 10,
    },
    pitfalls: [
      { challenge: 'Over-reliance on founder\'s creative vision', howOvercome: 'Built creative team with shared values', advice: 'Document your creative process' },
    ],
    lessonsLearned: 'Specialization in a growing market (tech startups) creates compounding opportunities.',
    advice: 'Find a niche that values quality over price, then become the obvious choice.',
    sourcePlatform: 'interview',
    tags: ['tech', 'explainer_videos', 'agency', 'premium', 'startup_ecosystem'],
    matchingKeywords: ['video production', 'commercial', 'tech', 'explainer', 'agency'],
    confidenceLevel: 'high',
    summary: 'Freelance videographer became the go-to agency for tech startup product videos, growing 15x by owning the "tech explainer" niche.',
  },
  {
    companyName: 'Storyblocks',
    industry: 'video_production',
    subIndustry: 'stock_media',
    location: 'Arlington, VA',
    startingState: {
      revenue: '500k_1m',
      teamSize: '6_10',
      yearsInBusiness: 5,
      challenges: ['Competing with Shutterstock', 'Creator acquisition', 'Content quality'],
      capabilities: ['Platform development', 'Content licensing', 'Subscription model'],
      marketPosition: 'Small player',
    },
    endingState: {
      revenue: '5m_plus',
      teamSize: '50_plus',
      revenueGrowth: '10x',
      achievements: ['Acquired by Shutterstock competitor', 'Millions of subscribers', 'Category leader'],
      newCapabilities: ['AI-powered search', 'Enterprise solutions', 'Multi-format library'],
      marketPosition: 'Major industry player',
    },
    strategyType: 'partnership_expansion',
    expansionType: 'horizontal',
    targetMarket: 'content_creators',
    timeline: {
      totalMonths: 48,
    },
    keyActions: [
      { action: 'Unlimited subscription model', impact: 'Disrupted per-asset pricing', difficulty: 'hard' },
      { action: 'Creator partnerships for content', impact: 'Scaled library rapidly', difficulty: 'moderate' },
      { action: 'YouTube creator partnerships', impact: 'Viral growth through influencers', difficulty: 'moderate' },
    ],
    outcomes: {
      revenueMultiplier: 10,
      teamGrowth: 8,
    },
    lessonsLearned: 'Disrupting pricing models can create massive market opportunities.',
    sourcePlatform: 'blog',
    tags: ['stock_media', 'subscription', 'platform', 'saas'],
    matchingKeywords: ['video', 'stock', 'subscription', 'platform', 'creator'],
    confidenceLevel: 'medium',
    summary: 'Disrupted stock media market with unlimited subscription model, growing from small player to acquisition target.',
  },

  // ============================================================================
  // ADDITIONAL INDIE HACKERS / BOOTSTRAPPED SAAS
  // ============================================================================
  {
    companyName: 'BaseTemplates',
    industry: 'saas',
    subIndustry: 'productivity',
    location: 'Germany',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 1,
      challenges: ['Solo founder', 'Small market', 'Marketing'],
      capabilities: ['Template creation', 'Notion expertise'],
      marketPosition: 'Unknown template seller',
    },
    endingState: {
      revenue: '100k_250k',
      teamSize: 'solo',
      revenueGrowth: '20x',
      achievements: ['$10K MRR', 'Solo bootstrapped', 'Niche dominance'],
      newCapabilities: ['Template empire', 'Marketing funnel', 'Community'],
      marketPosition: 'Leading template provider',
    },
    strategyType: 'content_led_growth',
    expansionType: 'vertical',
    targetMarket: 'founders',
    timeline: {
      totalMonths: 24,
      keyMilestones: [
        { month: 3, event: '$500 MRR' },
        { month: 12, event: '$5K MRR' },
        { month: 24, event: '$10K MRR' },
      ],
    },
    keyActions: [
      { action: 'Created templates for a specific use case', impact: 'Clear value proposition', difficulty: 'easy' },
      { action: 'Built marketing funnel over time', impact: 'Consistent growth', difficulty: 'moderate' },
    ],
    outcomes: {
      revenueMultiplier: 20,
    },
    lessonsLearned: 'Simple products with clear value can build to significant MRR.',
    advice: 'Start small, iterate based on feedback, and build systematically.',
    sourceUrl: 'https://www.indiehackers.com/post/how-basetemplates-grew-from-500-mrr-to-10k-mrr-42aacabed5',
    sourcePlatform: 'indie_hackers',
    tags: ['saas', 'templates', 'solo', 'bootstrapped', 'notion'],
    matchingKeywords: ['saas', 'templates', 'notion', 'bootstrapped', 'solo'],
    confidenceLevel: 'high',
    summary: 'Max Fleitmann grew BaseTemplates from $500 to $10K MRR as a solo founder with simple templates.',
  },
  {
    companyName: 'Interview.io',
    industry: 'saas',
    subIndustry: 'hr_tech',
    location: 'San Francisco, CA',
    startingState: {
      revenue: '500k_1m',
      teamSize: '6_10',
      yearsInBusiness: 5,
      challenges: ['COVID killed hiring', 'Revenue dropped overnight', 'Needed to pivot'],
      capabilities: ['Technical interviewing platform', 'Recruiter network', 'Engineering culture'],
      marketPosition: 'Growing HR tech company',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '11_25',
      revenueGrowth: '3x',
      achievements: ['Survived COVID pivot', 'Grew through adversity', 'Stronger business model'],
      newCapabilities: ['Remote interviewing', 'New revenue streams', 'Resilient operations'],
      marketPosition: 'Resilient HR tech company',
    },
    strategyType: 'partnership_expansion',
    expansionType: 'horizontal',
    targetMarket: 'tech_companies',
    timeline: {
      totalMonths: 36,
    },
    keyActions: [
      { action: 'Pivoted during COVID instead of shutting down', impact: 'Survived and emerged stronger', difficulty: 'hard' },
      { action: 'Found new revenue streams', impact: 'Diversified business model', difficulty: 'hard' },
    ],
    pitfalls: [
      { challenge: 'COVID eliminated main revenue', howOvercome: 'Pivoted to new offerings rapidly', advice: 'Build resilient, diversified business models' },
    ],
    outcomes: {
      revenueMultiplier: 3,
      teamGrowth: 2,
    },
    lessonsLearned: 'Resilience means being willing to pivot completely when necessary.',
    advice: 'Don\'t wait for conditions to improve. Adapt to the new reality immediately.',
    sourceUrl: 'https://www.indiehackers.com/podcast/174-aline-lerner-of-interviewing-io',
    sourcePlatform: 'indie_hackers',
    tags: ['saas', 'hr_tech', 'pivot', 'covid', 'resilience'],
    matchingKeywords: ['saas', 'hr tech', 'interviewing', 'pivot'],
    confidenceLevel: 'high',
    summary: 'Aline Lerner\'s Interview.io lost its main revenue during COVID but pivoted and emerged stronger.',
  },

  // ============================================================================
  // ADDITIONAL PROFESSIONAL SERVICES
  // ============================================================================
  {
    companyName: 'The Clover Collective',
    industry: 'consulting',
    subIndustry: 'business_strategy',
    location: 'USA',
    startingState: {
      revenue: '250k_500k',
      teamSize: '2_5',
      yearsInBusiness: 3,
      challenges: ['Solo consultant scaling', 'Productizing services', 'Building team'],
      capabilities: ['Strategy consulting', 'Business development'],
      marketPosition: 'Small consultancy',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '6_10',
      revenueGrowth: '2x',
      achievements: ['$500K to $1M growth', 'Built team', 'Productized offerings'],
      newCapabilities: ['Scalable delivery', 'Team operations', 'Productized services'],
      marketPosition: 'Growing consultancy',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'vertical',
    targetMarket: 'small_business',
    timeline: {
      totalMonths: 24,
    },
    keyActions: [
      { action: 'Productized consulting services', impact: 'More predictable revenue', difficulty: 'hard' },
      { action: 'Built small team to scale', impact: 'Not dependent on founder only', difficulty: 'moderate' },
    ],
    outcomes: {
      revenueMultiplier: 2,
      teamGrowth: 3,
    },
    lessonsLearned: 'Productizing services is key to scaling consulting beyond solo work.',
    sourcePlatform: 'starter_story',
    tags: ['consulting', 'strategy', 'productized', 'scaling'],
    matchingKeywords: ['consulting', 'strategy', 'productized services', 'scaling'],
    confidenceLevel: 'medium',
    summary: 'The Clover Collective doubled from $500K to $1M by productizing consulting services and building a team.',
  },
];

export async function seedCaseStudies() {
  console.log('Seeding case studies...');
  console.log(`Total case studies to seed: ${caseStudySeedData.length}`);

  let successCount = 0;
  let errorCount = 0;

  for (const study of caseStudySeedData) {
    try {
      await db.insert(caseStudies).values(study as unknown as typeof caseStudies.$inferInsert).onConflictDoNothing();
      console.log(`✓ Seeded: ${study.companyName}`);
      successCount++;
    } catch (error) {
      console.error(`✗ Error seeding ${study.companyName}:`, error);
      errorCount++;
    }
  }

  console.log(`\nCase studies seeding complete!`);
  console.log(`✓ Successfully seeded: ${successCount}`);
  console.log(`✗ Errors: ${errorCount}`);
}

// Run if called directly
if (require.main === module) {
  seedCaseStudies()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error(err);
      process.exit(1);
    });
}
