import { db } from '../../lib/db';
import { caseStudies } from '../schema';

type CaseStudyInsert = typeof caseStudies.$inferInsert;

const batch10CaseStudies = [
  // === CRYPTO / WEB3 ===
  {
    companyName: 'WAGMI Games',
    industry: 'gaming',
    subIndustry: 'web3_gaming',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['No VC funding', 'Web3 gaming skepticism', 'Community building'],
      capabilities: ['Gaming experience', 'Web3 knowledge', 'Community focus'],
      marketPosition: 'New Web3 gaming studio',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '10_50',
      revenueGrowth: 'Strong community without VC',
      achievements: ['Growing community', 'Profitable without VC', '4 founders'],
      newCapabilities: ['Web3 game development', 'NFT integration', 'Community management'],
      marketPosition: 'Growing Web3 gaming company',
    },
    strategyType: 'community_funded',
    expansionType: 'organic',
    targetMarket: 'web3_gamers',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built Web3 gaming community without VC funding', impact: 'Self-sustaining model', difficulty: 'hard' },
      { action: 'Created profitable gaming studio', impact: 'Sustainable business', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Web3 gaming can succeed without VC funding through community.',
    sourceUrl: 'https://www.starterstory.com/wagmigames-com-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['web3', 'gaming', 'nft', 'community'],
    matchingKeywords: ['web3 gaming', 'wagmi', 'nft games'],
    confidenceLevel: 'high',
    summary: 'Grew Web3 gaming community without VC funding.',
  },
  {
    companyName: 'Divly',
    industry: 'fintech',
    subIndustry: 'crypto_tax',
    location: 'Sweden',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Crypto tax complexity', 'Regulatory compliance', 'Market timing'],
      capabilities: ['Tax expertise', 'Crypto knowledge', 'Software development'],
      marketPosition: 'New crypto tax SaaS',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '2_5',
      revenueGrowth: '$10K/month ($100K/year)',
      achievements: ['$100K revenue in 1 year', '3 employees', 'Multiple countries'],
      newCapabilities: ['Multi-jurisdiction tax', 'Exchange integrations', 'Automated reporting'],
      marketPosition: 'Growing crypto tax solution',
    },
    strategyType: 'niche_saas',
    expansionType: 'geographic',
    targetMarket: 'crypto_traders',
    timeline: { totalMonths: 12 },
    keyActions: [
      { action: 'Built crypto tax SaaS to $100K in 1 year', impact: 'Fast validation', difficulty: 'medium' },
      { action: 'Solved complex multi-country tax problem', impact: 'Clear differentiation', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Crypto compliance tools can scale quickly with crypto adoption.',
    sourceUrl: 'https://www.starterstory.com/stories/divly',
    sourcePlatform: 'starter_story',
    tags: ['crypto', 'tax', 'saas', 'fintech'],
    matchingKeywords: ['crypto tax', 'divly', 'cryptocurrency taxes'],
    confidenceLevel: 'high',
    summary: 'Built $100K/year crypto tax SaaS in just 1 year.',
  },
  {
    companyName: 'RMRK',
    industry: 'crypto',
    subIndustry: 'nft',
    location: 'Switzerland',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Hobby project initially', 'NFT infrastructure', 'Eco-friendly focus'],
      capabilities: ['Blockchain expertise', 'Polkadot ecosystem', 'Technical innovation'],
      marketPosition: 'New NFT standard',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '10_50',
      revenueGrowth: '$30K/month ($360K/year)',
      achievements: ['$360K revenue', '18 employees', 'Eco-friendly NFTs', 'Polkadot standard'],
      newCapabilities: ['NFT standards', 'Cross-chain', 'Modular NFTs'],
      marketPosition: 'Leading eco-friendly NFT platform',
    },
    strategyType: 'protocol_development',
    expansionType: 'ecosystem',
    targetMarket: 'nft_creators',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built eco-friendly NFT standard from hobby', impact: 'Category innovation', difficulty: 'hard' },
      { action: 'Grew to 18 employees and $360K/year', impact: 'Sustainable crypto business', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 36 },
    lessonsLearned: 'Hobby projects in crypto can become significant businesses.',
    sourceUrl: 'https://www.starterstory.com/stories/rmrk',
    sourcePlatform: 'starter_story',
    tags: ['nft', 'polkadot', 'web3', 'eco_friendly'],
    matchingKeywords: ['rmrk', 'nft standard', 'polkadot nft'],
    confidenceLevel: 'high',
    summary: 'One-man hobby grew to $360K/year eco-friendly NFTs business.',
  },

  // === FINTECH / PAYMENTS ===
  {
    companyName: 'shurjoPay',
    industry: 'fintech',
    subIndustry: 'payments',
    location: 'Bangladesh',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Bangladesh market', 'Payment infrastructure', 'Trust building'],
      capabilities: ['Local market knowledge', 'Technical skills', 'Banking relationships'],
      marketPosition: 'New payment gateway',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '100_200',
      revenueGrowth: '$2M/month',
      achievements: ['$2M/month', '150 employees', 'Bangladesh leader'],
      newCapabilities: ['Payment processing', 'Mobile money', 'Merchant services'],
      marketPosition: 'Leading Bangladesh payment gateway',
    },
    strategyType: 'market_leadership',
    expansionType: 'vertical',
    targetMarket: 'bangladesh_merchants',
    timeline: { totalMonths: 156 },
    keyActions: [
      { action: 'Built payment gateway to $2M/month', impact: 'Market dominance', difficulty: 'hard' },
      { action: 'Scaled to 150 employees in Bangladesh', impact: 'Local market leader', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 200 },
    lessonsLearned: 'Local fintech can dominate emerging markets.',
    sourceUrl: 'https://www.starterstory.com/stories/shurjopay',
    sourcePlatform: 'starter_story',
    tags: ['fintech', 'payments', 'bangladesh', 'gateway'],
    matchingKeywords: ['payment gateway', 'bangladesh fintech', 'shurjopay'],
    confidenceLevel: 'high',
    summary: 'Developed $2M/month payment gateway in Bangladesh.',
  },
  {
    companyName: 'Tilled',
    industry: 'fintech',
    subIndustry: 'payments',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Solo founder', '660 days to build', 'Payment complexity'],
      capabilities: ['Payments expertise', 'Technical skills', 'Industry knowledge'],
      marketPosition: 'New payment facilitation platform',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '10_50',
      revenueGrowth: '$833K/month (7-figure)',
      achievements: ['7-figure revenue', '40 employees', 'Profitable', 'PayFac leader'],
      newCapabilities: ['Payment facilitation', 'White-label solutions', 'API platform'],
      marketPosition: 'Leading PayFac platform',
    },
    strategyType: 'enterprise_saas',
    expansionType: 'vertical',
    targetMarket: 'software_companies',
    timeline: { totalMonths: 66 },
    keyActions: [
      { action: 'Built payment platform to 7-figure revenue', impact: 'Enterprise scale', difficulty: 'hard' },
      { action: 'Simplified payments for SaaS companies', impact: 'Clear value proposition', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 833 },
    lessonsLearned: 'Simplifying complex fintech can create major opportunities.',
    sourceUrl: 'https://www.starterstory.com/tilled-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['fintech', 'payments', 'payfac', 'saas'],
    matchingKeywords: ['tilled', 'payment facilitation', 'payfac'],
    confidenceLevel: 'high',
    summary: 'Built Tilled to 7-figure payments revenue.',
  },

  // === DEVELOPER TOOLS / INFRASTRUCTURE ===
  {
    companyName: 'Databricks',
    industry: 'technology',
    subIndustry: 'data_platform',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '6_10',
      yearsInBusiness: 0,
      challenges: ['$11 starting costs', 'Enterprise data market', 'Apache Spark monetization'],
      capabilities: ['Academic research', 'Apache Spark creators', 'Data expertise'],
      marketPosition: 'New data platform',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '500_plus',
      revenueGrowth: '$200M/month ($62B valuation)',
      achievements: ['$62B valuation', '$200M/month', '1.86M traffic', '7 founders'],
      newCapabilities: ['Data lakehouse', 'ML platform', 'Enterprise data'],
      marketPosition: 'Leading data platform',
    },
    strategyType: 'open_source_commercial',
    expansionType: 'enterprise',
    targetMarket: 'enterprises',
    timeline: { totalMonths: 132 },
    keyActions: [
      { action: 'Commercialized Apache Spark to $62B valuation', impact: 'Massive scale', difficulty: 'hard' },
      { action: 'Created data lakehouse category', impact: 'Category definition', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 20000000 },
    lessonsLearned: 'Open source research can become massive commercial platforms.',
    sourceUrl: 'https://www.starterstory.com/databricks-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['data', 'enterprise', 'open_source', 'platform'],
    matchingKeywords: ['databricks', 'data lakehouse', 'apache spark'],
    confidenceLevel: 'high',
    summary: 'Grew Databricks to $62B valuation in 11 years.',
  },
  {
    companyName: 'Harness',
    industry: 'technology',
    subIndustry: 'devops',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Post-AppDynamics', 'DevOps complexity', 'Enterprise sales'],
      capabilities: ['AppDynamics founder', 'Enterprise experience', 'DevOps expertise'],
      marketPosition: 'New continuous delivery platform',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '500_plus',
      revenueGrowth: '$13M/month (400% ARR growth)',
      achievements: ['400% ARR growth', '1138 employees', 'Profitable', 'CD leader'],
      newCapabilities: ['Continuous delivery', 'Feature flags', 'Cloud cost management'],
      marketPosition: 'Leading DevOps platform',
    },
    strategyType: 'enterprise_expansion',
    expansionType: 'horizontal',
    targetMarket: 'enterprise_devops',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Built DevOps platform with 400% ARR growth', impact: 'Rapid enterprise growth', difficulty: 'hard' },
      { action: 'Serial founder success (post-AppDynamics)', impact: 'Proven playbook', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 1300 },
    lessonsLearned: 'Serial founders can replicate success in adjacent markets.',
    sourceUrl: 'https://www.starterstory.com/harness-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['devops', 'enterprise', 'cd', 'serial_founder'],
    matchingKeywords: ['harness', 'continuous delivery', 'devops platform'],
    confidenceLevel: 'high',
    summary: 'Harness achieved 400% ARR growth revolutionizing continuous delivery.',
  },
  {
    companyName: 'Clerk',
    industry: 'saas',
    subIndustry: 'authentication',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Auth complexity', 'Developer adoption', 'Competition'],
      capabilities: ['MIT background', 'Developer focus', 'Product design'],
      marketPosition: 'New authentication platform',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '50_200',
      revenueGrowth: '$833K/month',
      achievements: ['16M users', '$30M funding', '80 employees', 'Profitable'],
      newCapabilities: ['User management', 'Authentication', 'Developer tools'],
      marketPosition: 'Leading developer authentication',
    },
    strategyType: 'developer_first',
    expansionType: 'platform',
    targetMarket: 'developers',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Built authentication platform to 16M users', impact: 'Massive adoption', difficulty: 'hard' },
      { action: 'Secured $30M funding while profitable', impact: 'Strong position', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 833 },
    lessonsLearned: 'Developer-first auth tools can achieve massive scale.',
    sourceUrl: 'https://www.starterstory.com/clerk-com-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['auth', 'developer_tools', 'saas', 'platform'],
    matchingKeywords: ['clerk', 'authentication', 'user management'],
    confidenceLevel: 'high',
    summary: 'Clerk accelerated to 16M users and $30M funding.',
  },
  {
    companyName: 'ToolJet',
    industry: 'saas',
    subIndustry: 'low_code',
    location: 'India',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['60 days to build', 'Open source monetization', 'GitHub discovery'],
      capabilities: ['Development skills', 'Open source knowledge', 'Product focus'],
      marketPosition: 'New low-code platform',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '10_50',
      revenueGrowth: '25K GitHub stars',
      achievements: ['25K GitHub stars', '35 employees', 'Profitable', 'Open source leader'],
      newCapabilities: ['Low-code development', 'Database integrations', 'Self-hosted option'],
      marketPosition: 'Leading open-source low-code',
    },
    strategyType: 'open_source_growth',
    expansionType: 'community',
    targetMarket: 'developers',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built open-source platform to 25K GitHub stars', impact: 'Community growth', difficulty: 'hard' },
      { action: 'Solo founder scaled to 35 employees', impact: 'Team building', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Open-source low-code tools can build large communities.',
    sourceUrl: 'https://www.starterstory.com/tooljet-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['low_code', 'open_source', 'developer_tools', 'india'],
    matchingKeywords: ['tooljet', 'low code', 'open source'],
    confidenceLevel: 'high',
    summary: 'Solo founder built ToolJet to 25K GitHub stars.',
  },
  {
    companyName: 'Inflectra (SpiraPlan)',
    industry: 'saas',
    subIndustry: 'devops',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Solo founder', 'Enterprise software', 'Testing market'],
      capabilities: ['Software development', 'Testing expertise', 'Enterprise experience'],
      marketPosition: 'New testing/project management tool',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '50_200',
      revenueGrowth: '$10M ARR',
      achievements: ['$10M ARR', '30-40% YoY growth', 'Solo founder to enterprise'],
      newCapabilities: ['Test management', 'Project management', 'Automation'],
      marketPosition: 'Enterprise testing leader',
    },
    strategyType: 'bootstrapped_growth',
    expansionType: 'enterprise',
    targetMarket: 'enterprise_dev_teams',
    timeline: { totalMonths: 180 },
    keyActions: [
      { action: 'Built enterprise testing tool to $10M ARR solo', impact: 'Bootstrapped success', difficulty: 'hard' },
      { action: 'Maintained 30-40% YoY growth', impact: 'Consistent scaling', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Solo founders can build enterprise software companies.',
    sourceUrl: 'https://www.starterstory.com/stories/software-testing-project-management-tools',
    sourcePlatform: 'starter_story',
    tags: ['testing', 'devops', 'enterprise', 'solo_founder'],
    matchingKeywords: ['spiraplan', 'test management', 'inflectra'],
    confidenceLevel: 'high',
    summary: 'Solo founder built $10M ARR enterprise testing tool.',
  },
  {
    companyName: 'Brokee',
    industry: 'saas',
    subIndustry: 'hr_tech',
    location: 'Ukraine',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['DevOps hiring complexity', 'Technical assessment', 'Ukraine startup'],
      capabilities: ['DevOps expertise', 'Technical skills', 'Hiring insight'],
      marketPosition: 'New DevOps hiring platform',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '2_5',
      revenueGrowth: 'Growing platform',
      achievements: ['DevOps hiring platform', 'Fun assessment approach', 'Growing user base'],
      newCapabilities: ['Technical assessments', 'Gamification', 'DevOps focus'],
      marketPosition: 'Growing DevOps hiring platform',
    },
    strategyType: 'niche_focus',
    expansionType: 'vertical',
    targetMarket: 'devops_hiring',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Built DevOps-specific hiring platform', impact: 'Niche differentiation', difficulty: 'medium' },
      { action: 'Made hiring fun with gamification', impact: 'Unique approach', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 5 },
    lessonsLearned: 'Niche hiring platforms can differentiate with unique approaches.',
    sourceUrl: 'https://www.starterstory.com/stories/brokee',
    sourcePlatform: 'starter_story',
    tags: ['hr_tech', 'devops', 'hiring', 'ukraine'],
    matchingKeywords: ['devops hiring', 'brokee', 'technical hiring'],
    confidenceLevel: 'medium',
    summary: 'Making DevOps hiring easier and fun for candidates.',
  },

  // === MORE SAAS / TOOLS ===
  {
    companyName: 'Finvault',
    industry: 'fintech',
    subIndustry: 'crypto',
    location: 'India',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Crypto app market', 'Security concerns', 'User trust'],
      capabilities: ['Crypto expertise', 'Mobile development', 'Security focus'],
      marketPosition: 'New crypto app',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '10_50',
      revenueGrowth: '$2.64M/year',
      achievements: ['$2.64M revenue', 'Crypto app success', 'India market'],
      newCapabilities: ['Crypto trading', 'Portfolio management', 'Security features'],
      marketPosition: 'Growing crypto app',
    },
    strategyType: 'mobile_first',
    expansionType: 'vertical',
    targetMarket: 'crypto_users',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built crypto app to $2.64M revenue', impact: 'Market validation', difficulty: 'hard' },
      { action: 'Focused on security and trust', impact: 'Differentiation', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 26 },
    lessonsLearned: 'Crypto apps with security focus can build trust and scale.',
    sourceUrl: 'https://www.starterstory.com/ideas/crypto-app-business/success-stories',
    sourcePlatform: 'starter_story',
    tags: ['crypto', 'mobile', 'fintech', 'india'],
    matchingKeywords: ['crypto app', 'finvault', 'crypto portfolio'],
    confidenceLevel: 'high',
    summary: 'Built $2.64M/year crypto app in India.',
  },
  {
    companyName: 'Cogneve',
    industry: 'marketplace',
    subIndustry: 'software',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Started from garage', 'Software marketplace', 'Solo operation'],
      capabilities: ['Development skills', 'Marketplace knowledge', 'Hustle'],
      marketPosition: 'New software marketplace',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '1',
      revenueGrowth: '$48K/year',
      achievements: ['$48K revenue', 'Garage startup success', 'Solo operation'],
      newCapabilities: ['Software curation', 'Marketplace operations', 'Customer service'],
      marketPosition: 'Growing software marketplace',
    },
    strategyType: 'solo_bootstrap',
    expansionType: 'organic',
    targetMarket: 'software_buyers',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built software marketplace from garage', impact: 'Bootstrapped success', difficulty: 'medium' },
      { action: 'Operated solo to $48K/year', impact: 'Lean operation', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 48 },
    lessonsLearned: 'Software marketplaces can be operated solo from home.',
    sourceUrl: 'https://www.starterstory.com/stories/i-created-48k-year-software-marketplace-from-my-garage',
    sourcePlatform: 'starter_story',
    tags: ['marketplace', 'software', 'solo', 'garage'],
    matchingKeywords: ['software marketplace', 'cogneve', 'garage startup'],
    confidenceLevel: 'high',
    summary: 'Created $48K/year software marketplace from garage.',
  },
  {
    companyName: 'Blawgy',
    industry: 'saas',
    subIndustry: 'content',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Solo founder', '6 months timeline', 'AI content market'],
      capabilities: ['Development skills', 'Content knowledge', 'SEO expertise'],
      marketPosition: 'New AI blogging tool',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '1',
      revenueGrowth: '$1.5K MRR in 6 months',
      achievements: ['$1.5K MRR', '6 months to revenue', 'Solo operation'],
      newCapabilities: ['AI content', 'SEO optimization', 'Blog automation'],
      marketPosition: 'Growing AI blogging platform',
    },
    strategyType: 'rapid_mvp',
    expansionType: 'organic',
    targetMarket: 'bloggers',
    timeline: { totalMonths: 6 },
    keyActions: [
      { action: 'Built AI blogging tool to $1.5K MRR in 6 months', impact: 'Fast validation', difficulty: 'medium' },
      { action: 'Solo bootstrapped operation', impact: 'Lean model', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 1.5 },
    lessonsLearned: 'AI content tools can validate quickly with right positioning.',
    sourceUrl: 'https://www.starterstory.com/blawgy-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['ai', 'content', 'blogging', 'solo'],
    matchingKeywords: ['blawgy', 'ai blogging', 'content automation'],
    confidenceLevel: 'high',
    summary: 'Bootstrapped Blawgy to $1.5K MRR in 6 months.',
  },
  {
    companyName: 'Crustdata',
    industry: 'saas',
    subIndustry: 'data',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Side hustle start', 'B2B data market', 'Solo operation'],
      capabilities: ['Data expertise', 'Development skills', 'Sales skills'],
      marketPosition: 'New data platform',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '2_5',
      revenueGrowth: 'Profitable SaaS (97% margin)',
      achievements: ['97% gross margin', 'Profitable', 'Side hustle success'],
      newCapabilities: ['Company data', 'API access', 'Data enrichment'],
      marketPosition: 'Growing data platform',
    },
    strategyType: 'high_margin_saas',
    expansionType: 'organic',
    targetMarket: 'b2b_companies',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Built profitable SaaS with 97% gross margin', impact: 'High efficiency', difficulty: 'hard' },
      { action: 'Grew from side hustle', impact: 'Risk management', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Data SaaS can achieve exceptional margins.',
    sourceUrl: 'https://www.starterstory.com/stories/crustdata',
    sourcePlatform: 'starter_story',
    tags: ['data', 'saas', 'b2b', 'high_margin'],
    matchingKeywords: ['crustdata', 'company data', 'data api'],
    confidenceLevel: 'high',
    summary: 'Side hustle grew to profitable SaaS with 97% gross margin.',
  },
  {
    companyName: 'The Mallorcan',
    industry: 'media',
    subIndustry: 'newsletter',
    location: 'Spain',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['$100 starting budget', 'Local newsletter', 'Niche market'],
      capabilities: ['Local knowledge', 'Writing skills', 'Community building'],
      marketPosition: 'New local newsletter',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '1',
      revenueGrowth: '$30K/year',
      achievements: ['$30K revenue', '$100 start', 'Local community leader'],
      newCapabilities: ['Local advertising', 'Community events', 'Sponsorships'],
      marketPosition: 'Leading Mallorca newsletter',
    },
    strategyType: 'local_media',
    expansionType: 'organic',
    targetMarket: 'mallorca_residents',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Built local newsletter with $100', impact: 'Minimal capital needed', difficulty: 'easy' },
      { action: 'Grew to $30K/year in niche market', impact: 'Local market success', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 300 },
    lessonsLearned: 'Local newsletters can build sustainable businesses.',
    sourceUrl: 'https://www.starterstory.com/stories/the-mallorcan',
    sourcePlatform: 'starter_story',
    tags: ['newsletter', 'local', 'spain', 'media'],
    matchingKeywords: ['local newsletter', 'mallorca', 'spain media'],
    confidenceLevel: 'high',
    summary: 'Created $30K/year local newsletter with $100.',
  },
];

export async function seedBatch10() {
  console.log('🌱 Seeding Batch 10: Crypto, Fintech, DevTools, Infrastructure...');

  let successCount = 0;
  let errorCount = 0;

  for (const study of batch10CaseStudies) {
    try {
      await db.insert(caseStudies).values(study as CaseStudyInsert);
      console.log(`  ✓ ${study.companyName}`);
      successCount++;
    } catch (error) {
      console.error(`  ✗ ${study.companyName}:`, error);
      errorCount++;
    }
  }

  console.log(`\nBatch 10 seeding complete!`);
  console.log(`✓ Successfully seeded: ${successCount}`);
  console.log(`✗ Errors: ${errorCount}`);
}

seedBatch10()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
