import { db } from '../../lib/db';
import { caseStudies } from '../schema';

type CaseStudyInsert = typeof caseStudies.$inferInsert;

const batch11CaseStudies = [
  // === E-COMMERCE ===
  {
    companyName: 'Exto.io (Recom.ai)',
    industry: 'technology',
    subIndustry: 'ecommerce_tools',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['E-commerce competition', 'Merchant revenue optimization', 'Building recommendation engine'],
      capabilities: ['Development skills', 'E-commerce knowledge', 'AI/ML expertise'],
      marketPosition: 'New entrant',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '11_50',
      revenueGrowth: '$50M+ generated for clients',
      achievements: ['$50M extra revenue for clients', 'Shopify app success', 'Product recommendations'],
      newCapabilities: ['AI recommendations', 'E-commerce optimization', 'Merchant analytics'],
      marketPosition: 'Leading recommendation app',
    },
    strategyType: 'product_led_growth',
    expansionType: 'marketplace',
    targetMarket: 'ecommerce_merchants',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built AI recommendation engine generating $50M+ for clients', impact: 'Massive merchant value', difficulty: 'hard' },
      { action: 'Launched on Shopify app store', impact: 'Distribution channel', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Success in e-commerce tools means directly impacting merchant revenue.',
    sourceUrl: 'https://www.starterstory.com/stories/i-made-an-ecommerce-app-that-generated-over-50m-of-extra-revenue-for-my-clients',
    sourcePlatform: 'starter_story',
    tags: ['ecommerce', 'ai', 'shopify', 'recommendations'],
    matchingKeywords: ['exto', 'recom.ai', 'ecommerce app', 'product recommendations'],
    confidenceLevel: 'high',
    summary: 'Built AI recommendation app that generated $50M+ extra revenue for e-commerce clients.',
  },
  {
    companyName: 'Rush (Order Tracking)',
    industry: 'technology',
    subIndustry: 'ecommerce_tools',
    location: 'Bulgaria',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Dropshipping pain points', 'Order tracking gaps', 'Customer experience'],
      capabilities: ['Dropshipping experience', 'E-commerce knowledge', 'Development skills'],
      marketPosition: 'Solving own problem',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '6_10',
      revenueGrowth: '$20K/month',
      achievements: ['$20K/month recurring', 'Shopify app success', 'Dropshipper solution'],
      newCapabilities: ['Order tracking', 'Customer notifications', 'Branded tracking pages'],
      marketPosition: 'Popular Shopify app',
    },
    strategyType: 'bootstrap',
    expansionType: 'product',
    targetMarket: 'dropshippers',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Built order tracking app from dropshipping experience', impact: 'Solved real problem', difficulty: 'medium' },
      { action: 'Grew to $20K/month on Shopify', impact: 'Sustainable SaaS', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Personal pain points in e-commerce make great SaaS opportunities.',
    sourceUrl: 'https://www.starterstory.com/stories/this-dropshipper-built-a-20k-month-shopify-order-tracking-app',
    sourcePlatform: 'starter_story',
    tags: ['shopify', 'dropshipping', 'order_tracking', 'saas'],
    matchingKeywords: ['rush', 'order tracking', 'shopify app', 'dropshipping'],
    confidenceLevel: 'high',
    summary: 'Dropshipper built $20K/month Shopify order tracking app from personal experience.',
  },
  {
    companyName: 'Tuft & Paw',
    industry: 'consumer_products',
    subIndustry: 'pet_products',
    location: 'Canada',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Ugly cat furniture market', 'Design differentiation', 'DTC competition'],
      capabilities: ['Design sensibility', 'E-commerce skills', 'Pet market knowledge'],
      marketPosition: 'Design-focused entrant',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '11_50',
      revenueGrowth: '$300K/month ($3.6M/year)',
      achievements: ['$300K/month sales', 'Design-forward brand', 'Premium positioning'],
      newCapabilities: ['Product design', 'DTC operations', 'Brand building'],
      marketPosition: 'Premium cat furniture brand',
    },
    strategyType: 'brand_differentiation',
    expansionType: 'product',
    targetMarket: 'cat_owners',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Created designer cat furniture category', impact: 'Premium positioning', difficulty: 'medium' },
      { action: 'Scaled to $300K/month in sales', impact: 'Strong revenue', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 400 },
    lessonsLearned: 'Design-forward products in ugly categories command premium prices.',
    sourceUrl: 'https://www.starterstory.com/stories/tuft-paw',
    sourcePlatform: 'starter_story',
    tags: ['dtc', 'pet_products', 'design', 'ecommerce'],
    matchingKeywords: ['tuft and paw', 'cat furniture', 'designer pet', 'premium'],
    confidenceLevel: 'high',
    summary: 'Built designer cat furniture brand doing $300K/month in premium sales.',
  },
  {
    companyName: 'RIPT Apparel',
    industry: 'consumer_products',
    subIndustry: 'apparel',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['T-shirt market saturation', 'Artist curation', 'Daily deal model'],
      capabilities: ['Design community access', 'E-commerce skills', 'Pop culture knowledge'],
      marketPosition: 'Daily deal t-shirt startup',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '11_50',
      revenueGrowth: '$2.4M/year',
      achievements: ['$2.4M/year revenue', '3 founders collaboration', 'Artist community'],
      newCapabilities: ['Curated designs', 'Print on demand', 'Community building'],
      marketPosition: 'Established pop culture apparel',
    },
    strategyType: 'community_driven',
    expansionType: 'product',
    targetMarket: 'pop_culture_fans',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Launched daily deal t-shirt model with 3 friends', impact: 'Unique urgency model', difficulty: 'medium' },
      { action: 'Built artist community and reached $2.4M/year', impact: 'Sustainable scale', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Daily deal urgency combined with community builds loyal customers.',
    sourceUrl: 'https://www.starterstory.com/stories/how-three-friends-launched-2-4m-t-shirt-startup-ript-apparel',
    sourcePlatform: 'starter_story',
    tags: ['apparel', 'tshirts', 'pop_culture', 'community'],
    matchingKeywords: ['ript apparel', 't-shirts', 'daily deal', 'pop culture'],
    confidenceLevel: 'high',
    summary: 'Three friends launched $2.4M/year pop culture t-shirt startup.',
  },
  {
    companyName: 'FactoryPure',
    industry: 'consumer_products',
    subIndustry: 'home_goods',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Commodity products', 'Online retail competition', 'Logistics complexity'],
      capabilities: ['Family business experience', 'E-commerce skills', 'Product sourcing'],
      marketPosition: 'New e-commerce retailer',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$36M/year',
      achievements: ['$36M/year revenue', 'Two brothers team', 'Multi-category expansion'],
      newCapabilities: ['Large item logistics', 'Customer service', 'Category expertise'],
      marketPosition: 'Major online retailer',
    },
    strategyType: 'operational_excellence',
    expansionType: 'product',
    targetMarket: 'homeowners',
    timeline: { totalMonths: 120 },
    keyActions: [
      { action: 'Built online air purifier and generator business', impact: 'Niche expertise', difficulty: 'medium' },
      { action: 'Scaled to $36M/year with brother partnership', impact: 'Major revenue', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 500 },
    lessonsLearned: 'Family partnerships and category expertise drive e-commerce success.',
    sourceUrl: 'https://www.starterstory.com/stories/these-two-brothers-make-36m-year-selling-air-purifiers-and-generators-online',
    sourcePlatform: 'starter_story',
    tags: ['ecommerce', 'retail', 'home_goods', 'family_business'],
    matchingKeywords: ['factorypure', 'air purifiers', 'generators', 'online retail'],
    confidenceLevel: 'high',
    summary: 'Two brothers built $36M/year online retailer selling air purifiers and generators.',
  },
  {
    companyName: 'Swoveralls',
    industry: 'consumer_products',
    subIndustry: 'apparel',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Silly product concept', 'Viral marketing needed', 'Fashion credibility'],
      capabilities: ['Creative vision', 'Social media skills', 'Product development'],
      marketPosition: 'Novelty product startup',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '6_10',
      revenueGrowth: '$1.2M/year',
      achievements: ['$1.2M/year revenue', 'TikTok viral success', 'Sweatpants overalls category'],
      newCapabilities: ['Viral marketing', 'Social commerce', 'Community building'],
      marketPosition: 'Viral comfort apparel brand',
    },
    strategyType: 'viral_marketing',
    expansionType: 'product',
    targetMarket: 'comfort_seekers',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Turned silly idea into product and went viral on TikTok', impact: 'Massive awareness', difficulty: 'medium' },
      { action: 'Scaled to $1.2M/year from viral momentum', impact: 'Revenue scale', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Silly ideas can become real businesses with the right viral moment.',
    sourceUrl: 'https://www.starterstory.com/stories/swoveralls',
    sourcePlatform: 'starter_story',
    tags: ['apparel', 'viral', 'tiktok', 'comfort'],
    matchingKeywords: ['swoveralls', 'sweatpants overalls', 'viral brand', 'tiktok'],
    confidenceLevel: 'high',
    summary: 'Turned silly sweatpants overalls idea into $1.2M/year viral TikTok brand.',
  },
  {
    companyName: 'Velvety',
    industry: 'consumer_products',
    subIndustry: 'fashion_marketplace',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Ethical fashion discovery', 'Marketplace building', 'Brand curation'],
      capabilities: ['Fashion knowledge', 'Sustainability passion', 'Marketplace skills'],
      marketPosition: 'New ethical fashion platform',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '1_5',
      revenueGrowth: '$24K/month',
      achievements: ['$24K/month revenue', 'Ethical brand curation', 'Sustainable marketplace'],
      newCapabilities: ['Brand vetting', 'Sustainable sourcing', 'Community building'],
      marketPosition: 'Leading ethical fashion marketplace',
    },
    strategyType: 'marketplace',
    expansionType: 'market',
    targetMarket: 'conscious_consumers',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Built curated ethical fashion marketplace', impact: 'Values-driven platform', difficulty: 'medium' },
      { action: 'Grew to $24K/month connecting conscious consumers', impact: 'Sustainable revenue', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 30 },
    lessonsLearned: 'Curation and values create marketplace differentiation.',
    sourceUrl: 'https://www.starterstory.com/stories/velvety',
    sourcePlatform: 'starter_story',
    tags: ['marketplace', 'sustainable', 'fashion', 'ethical'],
    matchingKeywords: ['velvety', 'ethical fashion', 'sustainable marketplace'],
    confidenceLevel: 'high',
    summary: 'Built $24K/month ethical fashion marketplace for conscious consumers.',
  },

  // === HEALTHCARE / HEALTH TECH ===
  {
    companyName: 'Kinetik',
    industry: 'healthcare',
    subIndustry: 'health_tech',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Healthcare complexity', 'VC fundraising', 'Regulatory navigation'],
      capabilities: ['Healthcare domain expertise', 'Technical skills', 'Vision'],
      marketPosition: 'New health-tech startup',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '51_200',
      revenueGrowth: '$27M raised',
      achievements: ['$27M funding raised', '77 employees', 'Health-tech platform'],
      newCapabilities: ['Healthcare platform', 'Enterprise sales', 'Regulatory compliance'],
      marketPosition: 'Funded health-tech company',
    },
    strategyType: 'venture_backed',
    expansionType: 'enterprise',
    targetMarket: 'healthcare_orgs',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Raised $27M to build health-tech platform', impact: 'Major funding', difficulty: 'hard' },
      { action: 'Scaled team to 77 employees', impact: 'Organizational growth', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Health-tech requires significant capital and domain expertise.',
    sourceUrl: 'https://www.starterstory.com/stories/kinetik',
    sourcePlatform: 'starter_story',
    tags: ['healthtech', 'venture', 'healthcare', 'platform'],
    matchingKeywords: ['kinetik', 'health tech', 'healthcare startup'],
    confidenceLevel: 'high',
    summary: 'Built health-tech startup that raised $27M in funding.',
  },
  {
    companyName: 'Ansel Health',
    industry: 'healthcare',
    subIndustry: 'insurtech',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Insurance complexity', 'Supplemental coverage gaps', 'Distribution'],
      capabilities: ['Insurance expertise', 'Product design', 'Technology'],
      marketPosition: 'New insurtech entrant',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$50M raised',
      achievements: ['$50M funding', 'Revolutionized supplemental insurance', 'B2B & B2C model'],
      newCapabilities: ['Insurance products', 'Claims processing', 'Enterprise sales'],
      marketPosition: 'Leading supplemental insurance innovator',
    },
    strategyType: 'venture_backed',
    expansionType: 'enterprise',
    targetMarket: 'employers_employees',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Raised $50M to revolutionize supplemental insurance', impact: 'Major capital', difficulty: 'hard' },
      { action: 'Built B2B and B2C insurance platform', impact: 'Dual distribution', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Insurance innovation requires capital and regulatory expertise.',
    sourceUrl: 'https://www.starterstory.com/ansel-health-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['insurtech', 'healthcare', 'b2b', 'venture'],
    matchingKeywords: ['ansel health', 'supplemental insurance', 'insurtech'],
    confidenceLevel: 'high',
    summary: 'Raised $50M to revolutionize supplemental health insurance.',
  },
  {
    companyName: 'Flo Health',
    industry: 'healthcare',
    subIndustry: 'womens_health',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Women\'s health tracking', 'App monetization', 'User acquisition'],
      capabilities: ['App development', 'Health knowledge', 'UX design'],
      marketPosition: 'New health app',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '500_plus',
      revenueGrowth: 'Unicorn status ($1B+ valuation)',
      achievements: ['Unicorn valuation', 'Two brothers founded', 'Leading women\'s health app'],
      newCapabilities: ['Health AI', 'Subscription model', 'Global scale'],
      marketPosition: 'Top women\'s health app globally',
    },
    strategyType: 'product_led_growth',
    expansionType: 'global',
    targetMarket: 'women',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Two brothers built women\'s health tracking app', impact: 'Market leader', difficulty: 'hard' },
      { action: 'Achieved unicorn status through product excellence', impact: 'Massive valuation', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 10000 },
    lessonsLearned: 'Focus on underserved health niches can create massive value.',
    sourceUrl: 'https://www.starterstory.com/flo-health-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['health_app', 'womens_health', 'unicorn', 'mobile'],
    matchingKeywords: ['flo health', 'period tracker', 'women health app'],
    confidenceLevel: 'high',
    summary: 'Two brothers built Flo Health to unicorn status in women\'s health.',
  },
  {
    companyName: 'ClinicSense',
    industry: 'healthcare',
    subIndustry: 'wellness_saas',
    location: 'Canada',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Wellness practitioner needs', 'Bootstrapping', 'Feature development'],
      capabilities: ['SaaS development', 'Wellness industry knowledge', 'Bootstrap mindset'],
      marketPosition: 'New wellness SaaS',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '11_50',
      revenueGrowth: '7-figures ARR',
      achievements: ['7-figures ARR', 'Bootstrapped success', 'Wellness SaaS leader'],
      newCapabilities: ['Practice management', 'Scheduling', 'Client management'],
      marketPosition: 'Leading wellness practice software',
    },
    strategyType: 'bootstrap',
    expansionType: 'market',
    targetMarket: 'wellness_practitioners',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Bootstrapped wellness SaaS to 7-figures ARR', impact: 'Profitable scale', difficulty: 'hard' },
      { action: 'Built complete practice management solution', impact: 'Full platform', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Vertical SaaS for wellness can be profitably bootstrapped.',
    sourceUrl: 'https://www.starterstory.com/stories/clinicsense',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'wellness', 'bootstrap', 'practice_management'],
    matchingKeywords: ['clinicsense', 'wellness saas', 'practice management'],
    confidenceLevel: 'high',
    summary: 'Bootstrapped wellness practice SaaS to 7-figures ARR.',
  },
  {
    companyName: 'SelfDecode',
    industry: 'healthcare',
    subIndustry: 'genomics',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['DNA analysis complexity', 'Consumer health insights', 'Scientific accuracy'],
      capabilities: ['Genetics knowledge', 'Software development', 'Health passion'],
      marketPosition: 'New genomics platform',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '11_50',
      revenueGrowth: '$2.7M/year',
      achievements: ['$2.7M/year revenue', 'DNA analysis platform', 'Life extension focus'],
      newCapabilities: ['Genomic analysis', 'Health recommendations', 'Personalized insights'],
      marketPosition: 'Leading consumer genomics platform',
    },
    strategyType: 'product_innovation',
    expansionType: 'product',
    targetMarket: 'health_optimizers',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built DNA analysis platform for health optimization', impact: 'Unique value prop', difficulty: 'hard' },
      { action: 'Scaled to $2.7M/year helping people analyze genetics', impact: 'Strong revenue', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Personalized health insights from genetics create loyal customers.',
    sourceUrl: 'https://www.starterstory.com/stories/i-created-a-2-4m-year-software-that-extends-people-s-lives-by-hacking-their-dna',
    sourcePlatform: 'starter_story',
    tags: ['genomics', 'dna', 'health', 'personalization'],
    matchingKeywords: ['selfdecode', 'dna analysis', 'genomics', 'health optimization'],
    confidenceLevel: 'high',
    summary: 'Built $2.7M/year DNA analysis software helping people optimize health.',
  },
  {
    companyName: 'CIONIC',
    industry: 'healthcare',
    subIndustry: 'medical_devices',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Mobility impairment solutions', 'Wearable tech complexity', 'Medical device regulations'],
      capabilities: ['Apple experience', 'Hardware engineering', 'Medical device knowledge'],
      marketPosition: 'New mobility tech startup',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '11_50',
      revenueGrowth: 'First bionic clothing company',
      achievements: ['First bionic clothing', 'Ex-Apple founder', 'Mobility innovation'],
      newCapabilities: ['Bionic wearables', 'Neural interfaces', 'Medical devices'],
      marketPosition: 'Pioneer in bionic clothing',
    },
    strategyType: 'product_innovation',
    expansionType: 'product',
    targetMarket: 'mobility_impaired',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Created first bionic clothing for mobility impairment', impact: 'Category creation', difficulty: 'hard' },
      { action: 'Leveraged Apple experience for medical wearables', impact: 'World-class design', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Big tech experience transfers to medical device innovation.',
    sourceUrl: 'https://www.starterstory.com/stories/cionic',
    sourcePlatform: 'starter_story',
    tags: ['medical_device', 'wearables', 'bionic', 'accessibility'],
    matchingKeywords: ['cionic', 'bionic clothing', 'mobility', 'wearables'],
    confidenceLevel: 'high',
    summary: 'Ex-Apple employee created first bionic clothing for mobility impairment.',
  },

  // === EDUCATION / EDTECH ===
  {
    companyName: 'MasterClass',
    industry: 'education',
    subIndustry: 'online_courses',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Celebrity instructor access', 'Production quality', 'Subscription model'],
      capabilities: ['Vision', 'Media production', 'Fundraising ability'],
      marketPosition: 'New online education concept',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '500_plus',
      revenueGrowth: '$90M+ ARR',
      achievements: ['$90M+ ARR', 'Celebrity-taught courses', 'Premium education brand'],
      newCapabilities: ['Hollywood production', 'Celebrity partnerships', 'Subscription platform'],
      marketPosition: 'Leading celebrity education platform',
    },
    strategyType: 'premium_positioning',
    expansionType: 'content',
    targetMarket: 'lifelong_learners',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Recruited celebrities to teach courses with Hollywood production', impact: 'Premium differentiation', difficulty: 'hard' },
      { action: 'Scaled to $90M+ ARR subscription business', impact: 'Massive scale', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 10000 },
    lessonsLearned: 'Celebrity access and production quality justify premium pricing.',
    sourceUrl: 'https://www.starterstory.com/stories/master-class-breakdown-f7b4645e-de0a-422d-ab33-dac531967031',
    sourcePlatform: 'starter_story',
    tags: ['edtech', 'online_courses', 'celebrity', 'subscription'],
    matchingKeywords: ['masterclass', 'celebrity courses', 'online education'],
    confidenceLevel: 'high',
    summary: 'Built $90M+ ARR celebrity-taught online course platform.',
  },
  {
    companyName: 'Duolingo',
    industry: 'education',
    subIndustry: 'language_learning',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Language learning engagement', 'Monetization', 'Gamification'],
      capabilities: ['Academic research', 'CAPTCHA invention (reCAPTCHA)', 'Product vision'],
      marketPosition: 'New language app',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '500_plus',
      revenueGrowth: '$9 billion valuation',
      achievements: ['$9B valuation', 'EdTech giant', '500M+ users'],
      newCapabilities: ['Gamified learning', 'AI-powered curriculum', 'Global scale'],
      marketPosition: 'World\'s largest language learning platform',
    },
    strategyType: 'freemium',
    expansionType: 'global',
    targetMarket: 'language_learners',
    timeline: { totalMonths: 144 },
    keyActions: [
      { action: 'Gamified language learning at massive scale', impact: 'User engagement', difficulty: 'hard' },
      { action: 'Grew to $9B valuation and 500M+ users', impact: 'EdTech dominance', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 1000000 },
    lessonsLearned: 'Gamification and freemium create massive educational platforms.',
    sourceUrl: 'https://www.starterstory.com/duolingo-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['edtech', 'language', 'gamification', 'freemium'],
    matchingKeywords: ['duolingo', 'language learning', 'edtech'],
    confidenceLevel: 'high',
    summary: 'Built Duolingo to $9 billion EdTech giant with gamified learning.',
  },
  {
    companyName: 'Boot.dev',
    industry: 'education',
    subIndustry: 'coding_education',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Coding education crowded', 'Backend focus differentiation', 'Content creation'],
      capabilities: ['Backend expertise', 'Teaching ability', 'Content creation'],
      marketPosition: 'New coding education platform',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '6_10',
      revenueGrowth: '$110K/month',
      achievements: ['$110K/month revenue', 'Backend development focus', 'Project-based learning'],
      newCapabilities: ['Interactive courses', 'Backend curriculum', 'Community building'],
      marketPosition: 'Leading backend development courses',
    },
    strategyType: 'content_marketing',
    expansionType: 'product',
    targetMarket: 'aspiring_developers',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Created backend-focused coding curriculum', impact: 'Niche differentiation', difficulty: 'medium' },
      { action: 'Grew to $110K/month through content and community', impact: 'Strong revenue', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Niche focus in crowded education markets creates opportunities.',
    sourceUrl: 'https://www.starterstory.com/stories/boot-dev',
    sourcePlatform: 'starter_story',
    tags: ['coding', 'education', 'backend', 'online_courses'],
    matchingKeywords: ['boot.dev', 'backend development', 'coding courses'],
    confidenceLevel: 'high',
    summary: 'Built $110K/month backend development courses platform.',
  },
  {
    companyName: 'designcode.io',
    industry: 'education',
    subIndustry: 'design_education',
    location: 'Canada',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Design education market', 'Course creation', 'Solo founder scale'],
      capabilities: ['Design expertise', 'Teaching ability', 'Content creation'],
      marketPosition: 'New design education platform',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '11_50',
      revenueGrowth: '$1M/year ($83K/month)',
      achievements: ['$1M/year revenue', '14 employees', 'Design education leader'],
      newCapabilities: ['Video courses', 'Design curriculum', 'Community building'],
      marketPosition: 'Leading design education platform',
    },
    strategyType: 'bootstrap',
    expansionType: 'product',
    targetMarket: 'designers',
    timeline: { totalMonths: 120 },
    keyActions: [
      { action: 'Built comprehensive design education platform', impact: 'Market leadership', difficulty: 'medium' },
      { action: 'Grew to $1M/year teaching design skills', impact: 'Strong revenue', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Expert-led design education can scale to seven figures.',
    sourceUrl: 'https://www.starterstory.com/designcode-io-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['design', 'education', 'online_courses', 'bootstrap'],
    matchingKeywords: ['designcode', 'design education', 'ui design courses'],
    confidenceLevel: 'high',
    summary: 'Built $1M/year design education business with 14 employees.',
  },
  {
    companyName: 'OnlinePianist',
    industry: 'education',
    subIndustry: 'music_education',
    location: 'Israel',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Piano learning engagement', 'App development', 'Content licensing'],
      capabilities: ['Music knowledge', 'App development', 'Personal passion'],
      marketPosition: 'New piano learning app',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '6_10',
      revenueGrowth: '$840K/year',
      achievements: ['$840K/year revenue', 'Piano tutorial app success', 'Popular songs catalog'],
      newCapabilities: ['Interactive piano lessons', 'Song catalog', 'Mobile app'],
      marketPosition: 'Leading piano tutorial app',
    },
    strategyType: 'mobile_first',
    expansionType: 'content',
    targetMarket: 'piano_learners',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Built piano tutorial app from personal crisis motivation', impact: 'Authentic product', difficulty: 'medium' },
      { action: 'Grew to $840K/year teaching piano online', impact: 'Strong revenue', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 80 },
    lessonsLearned: 'Personal passion and crisis can fuel successful education products.',
    sourceUrl: 'https://www.starterstory.com/stories/my-personal-crisis-fueled-me-to-build-an-840k-year-piano-tutorial-app',
    sourcePlatform: 'starter_story',
    tags: ['music', 'education', 'mobile_app', 'piano'],
    matchingKeywords: ['onlinepianist', 'piano lessons', 'music education app'],
    confidenceLevel: 'high',
    summary: 'Built $840K/year piano tutorial app fueled by personal crisis.',
  },
  {
    companyName: 'Eduflow',
    industry: 'education',
    subIndustry: 'learning_platform',
    location: 'Denmark',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Learning platform competition', 'B2B sales', 'Feature development'],
      capabilities: ['EdTech experience', 'Product development', 'B2B sales'],
      marketPosition: 'New learning platform SaaS',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '11_50',
      revenueGrowth: '1,000+ customers',
      achievements: ['1,000+ customers', 'Learning platform SaaS', 'Global reach'],
      newCapabilities: ['Course creation', 'Peer learning', 'Assessment tools'],
      marketPosition: 'Established learning platform',
    },
    strategyType: 'product_led_growth',
    expansionType: 'enterprise',
    targetMarket: 'organizations',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built and scaled learning platform SaaS', impact: '1000+ customers', difficulty: 'medium' },
      { action: 'Created peer learning and assessment tools', impact: 'Product differentiation', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'B2B learning platforms scale through product-led growth.',
    sourceUrl: 'https://www.starterstory.com/stories/eduflow',
    sourcePlatform: 'starter_story',
    tags: ['edtech', 'saas', 'learning_platform', 'b2b'],
    matchingKeywords: ['eduflow', 'learning platform', 'peer learning'],
    confidenceLevel: 'high',
    summary: 'Built and scaled learning platform SaaS to 1,000+ customers.',
  },
  {
    companyName: 'Coursebox',
    industry: 'education',
    subIndustry: 'ai_course_creation',
    location: 'Australia',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['AI course creation', 'User acquisition', 'Product development'],
      capabilities: ['AI/ML expertise', 'EdTech knowledge', 'Product skills'],
      marketPosition: 'New AI course creator',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '6_10',
      revenueGrowth: '11K users in 3 months',
      achievements: ['11K users in 3 months', 'AI-powered course creation', 'Rapid growth'],
      newCapabilities: ['AI content generation', 'Course templates', 'Rapid creation'],
      marketPosition: 'Growing AI course platform',
    },
    strategyType: 'product_led_growth',
    expansionType: 'product',
    targetMarket: 'course_creators',
    timeline: { totalMonths: 6 },
    keyActions: [
      { action: 'Built AI-powered course creation platform', impact: 'Fast course creation', difficulty: 'medium' },
      { action: 'Grew to 11K users in just 3 months', impact: 'Rapid adoption', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'AI tools for content creation find immediate product-market fit.',
    sourceUrl: 'https://www.starterstory.com/coursebox-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['ai', 'edtech', 'course_creation', 'saas'],
    matchingKeywords: ['coursebox', 'ai course creation', 'course creator'],
    confidenceLevel: 'high',
    summary: 'Grew AI course creation platform to 11K users in 3 months.',
  },

  // === REAL ESTATE / PROPTECH ===
  {
    companyName: 'HiFello',
    industry: 'real_estate',
    subIndustry: 'real_estate_ai',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Real estate tech competition', 'AI development', 'Agent adoption'],
      capabilities: ['Real estate knowledge', 'AI expertise', 'Product development'],
      marketPosition: 'New real estate AI platform',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '51_200',
      revenueGrowth: '$2M ARR in 18 months',
      achievements: ['$2M ARR', '100 employees', '18-month growth'],
      newCapabilities: ['Real estate AI', 'Agent tools', 'Lead generation'],
      marketPosition: 'Growing real estate AI platform',
    },
    strategyType: 'venture_backed',
    expansionType: 'product',
    targetMarket: 'real_estate_agents',
    timeline: { totalMonths: 18 },
    keyActions: [
      { action: 'Built real estate AI platform to $2M ARR in 18 months', impact: 'Rapid scale', difficulty: 'hard' },
      { action: 'Grew team to 100 employees', impact: 'Fast organizational growth', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 200 },
    lessonsLearned: 'AI in real estate can achieve rapid product-market fit.',
    sourceUrl: 'https://www.starterstory.com/hifello-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['proptech', 'ai', 'real_estate', 'saas'],
    matchingKeywords: ['hifello', 'real estate ai', 'proptech'],
    confidenceLevel: 'high',
    summary: 'Built real estate AI platform to $2M ARR in 18 months with 100 employees.',
  },
  {
    companyName: 'Perch',
    industry: 'real_estate',
    subIndustry: 'mortgage_tech',
    location: 'Canada',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Mortgage industry complexity', 'Consumer trust', 'Fintech regulations'],
      capabilities: ['Fintech experience', 'Mortgage knowledge', 'Product development'],
      marketPosition: 'New proptech startup',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '11_50',
      revenueGrowth: '$960K/year',
      achievements: ['$960K/year revenue', 'Mortgage savings platform', 'Proptech success'],
      newCapabilities: ['Mortgage comparison', 'Rate optimization', 'Consumer fintech'],
      marketPosition: 'Leading mortgage savings platform',
    },
    strategyType: 'consumer_fintech',
    expansionType: 'product',
    targetMarket: 'homeowners',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built proptech platform helping save on mortgages', impact: 'Consumer value', difficulty: 'medium' },
      { action: 'Grew to $960K/year revenue', impact: 'Strong traction', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Helping consumers save money on major purchases creates loyalty.',
    sourceUrl: 'https://www.starterstory.com/stories/my-proptech-startup-makes-960k-year-helping-people-save-money-on-their-mortgage',
    sourcePlatform: 'starter_story',
    tags: ['proptech', 'mortgage', 'fintech', 'consumer'],
    matchingKeywords: ['perch', 'mortgage savings', 'proptech'],
    confidenceLevel: 'high',
    summary: 'Built $960K/year proptech platform helping people save on mortgages.',
  },
  {
    companyName: 'TitleCapture',
    industry: 'real_estate',
    subIndustry: 'title_insurance',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Title industry complexity', 'B2B sales', 'Product development'],
      capabilities: ['Real estate knowledge', 'SaaS development', 'Industry connections'],
      marketPosition: 'New title tech startup',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '11_50',
      revenueGrowth: '$4M ARR',
      achievements: ['$4M ARR', 'Title industry SaaS', 'Real estate B2B'],
      newCapabilities: ['Title quoting', 'Fee calculation', 'Integration APIs'],
      marketPosition: 'Leading title tech platform',
    },
    strategyType: 'vertical_saas',
    expansionType: 'enterprise',
    targetMarket: 'title_companies',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built title industry SaaS product', impact: 'Vertical focus', difficulty: 'medium' },
      { action: 'Grew to $4M ARR in real estate B2B', impact: 'Strong revenue', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Vertical SaaS in real estate can achieve significant scale.',
    sourceUrl: 'https://www.starterstory.com/stories/titlecapture',
    sourcePlatform: 'starter_story',
    tags: ['proptech', 'title_insurance', 'saas', 'b2b'],
    matchingKeywords: ['titlecapture', 'title insurance', 'real estate saas'],
    confidenceLevel: 'high',
    summary: 'Built $4M ARR title industry SaaS in real estate space.',
  },
  {
    companyName: 'PropertyData',
    industry: 'real_estate',
    subIndustry: 'property_analytics',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Property data access', 'UK market focus', 'Investor needs'],
      capabilities: ['Data analytics', 'Property knowledge', 'Product development'],
      marketPosition: 'New property analytics tool',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '6_10',
      revenueGrowth: '$1.54M/year',
      achievements: ['$1.54M/year revenue', 'UK property analytics leader', 'Investor tool'],
      newCapabilities: ['Property valuation', 'Investment analysis', 'Market data'],
      marketPosition: 'Leading UK property analytics',
    },
    strategyType: 'data_product',
    expansionType: 'product',
    targetMarket: 'property_investors',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built UK property investment analytics tool', impact: 'Market leadership', difficulty: 'medium' },
      { action: 'Grew to $1.54M/year helping find investment properties', impact: 'Strong revenue', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 150 },
    lessonsLearned: 'Property data tools create value for investors.',
    sourceUrl: 'https://www.starterstory.com/stories/i-built-1-54m-year-tool-that-finds-the-best-investment-properties-from-uk',
    sourcePlatform: 'starter_story',
    tags: ['proptech', 'property_data', 'analytics', 'investing'],
    matchingKeywords: ['propertydata', 'property analytics', 'uk real estate'],
    confidenceLevel: 'high',
    summary: 'Built $1.54M/year UK property investment analytics tool.',
  },
  {
    companyName: 'TenantCloud',
    industry: 'real_estate',
    subIndustry: 'property_management',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Property management software', 'Landlord-tenant balance', 'Feature development'],
      capabilities: ['SaaS development', 'Property management knowledge', 'Product skills'],
      marketPosition: 'New property management SaaS',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$12M/year',
      achievements: ['$12M/year revenue', 'Property management SaaS', 'Landlord & tenant platform'],
      newCapabilities: ['Rent collection', 'Tenant screening', 'Maintenance tracking'],
      marketPosition: 'Leading property management platform',
    },
    strategyType: 'freemium',
    expansionType: 'market',
    targetMarket: 'landlords_tenants',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Built property management SaaS for landlords and tenants', impact: 'Dual-sided platform', difficulty: 'hard' },
      { action: 'Scaled to $12M/year revenue', impact: 'Major scale', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 150 },
    lessonsLearned: 'Property management SaaS can scale significantly with freemium.',
    sourceUrl: 'https://www.starterstory.com/stories/we-launched-a-12m-year-property-management-saas-for-landlords-tenants',
    sourcePlatform: 'starter_story',
    tags: ['proptech', 'property_management', 'saas', 'freemium'],
    matchingKeywords: ['tenantcloud', 'property management', 'landlord software'],
    confidenceLevel: 'high',
    summary: 'Launched $12M/year property management SaaS for landlords and tenants.',
  },
  {
    companyName: 'StayFi',
    industry: 'real_estate',
    subIndustry: 'vacation_rental_tech',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Airbnb host needs', 'Guest data capture', 'Marketing tools'],
      capabilities: ['Tech development', 'Vacation rental knowledge', 'Marketing skills'],
      marketPosition: 'New vacation rental tech',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '11_50',
      revenueGrowth: '$1M/year',
      achievements: ['$1M/year revenue', 'Airbnb host tool', 'Guest wifi marketing'],
      newCapabilities: ['Wifi marketing', 'Guest data capture', 'Direct booking'],
      marketPosition: 'Leading vacation rental marketing tool',
    },
    strategyType: 'niche_tool',
    expansionType: 'product',
    targetMarket: 'vacation_rental_hosts',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built wifi marketing tool for Airbnb hosts', impact: 'Unique value prop', difficulty: 'medium' },
      { action: 'Grew to $1M/year serving vacation rental market', impact: 'Strong revenue', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Niche tools for vacation rentals can be highly profitable.',
    sourceUrl: 'https://www.starterstory.com/stories/stayfi',
    sourcePlatform: 'starter_story',
    tags: ['proptech', 'airbnb', 'vacation_rental', 'marketing'],
    matchingKeywords: ['stayfi', 'airbnb marketing', 'vacation rental'],
    confidenceLevel: 'high',
    summary: 'Built $1M/year wifi marketing service for Airbnb hosts.',
  },

  // === LEGAL TECH ===
  {
    companyName: 'Document Crunch',
    industry: 'legal_tech',
    subIndustry: 'contract_ai',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Construction contracts complexity', 'AI development', 'Industry adoption'],
      capabilities: ['Legal expertise', 'Construction knowledge', 'AI/ML skills'],
      marketPosition: 'New legal AI startup',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '51_200',
      revenueGrowth: '$4.5M ARR',
      achievements: ['$4.5M ARR', '55 employees', 'Construction legal AI'],
      newCapabilities: ['Contract analysis', 'Risk identification', 'AI processing'],
      marketPosition: 'Leading construction legal AI',
    },
    strategyType: 'vertical_ai',
    expansionType: 'enterprise',
    targetMarket: 'construction_companies',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built AI for construction contract analysis', impact: 'Vertical AI focus', difficulty: 'hard' },
      { action: 'Grew to $4.5M ARR with 55 employees', impact: 'Strong scale', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Vertical AI in legal tech creates significant enterprise value.',
    sourceUrl: 'https://www.starterstory.com/document-crunch-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['legal_tech', 'ai', 'construction', 'contracts'],
    matchingKeywords: ['document crunch', 'construction contracts', 'legal ai'],
    confidenceLevel: 'high',
    summary: 'Built $4.5M ARR AI platform for construction contract analysis.',
  },
  {
    companyName: 'ZenBusiness',
    industry: 'legal_tech',
    subIndustry: 'business_formation',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['LegalZoom competition', 'Business formation market', 'Customer acquisition'],
      capabilities: ['Legal expertise', 'Product development', 'Marketing skills'],
      marketPosition: 'New business formation startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '500_plus',
      revenueGrowth: '$80M ARR in 4 years',
      achievements: ['$80M ARR', '4-year rapid growth', 'Business formation leader'],
      newCapabilities: ['LLC formation', 'Compliance services', 'Business tools'],
      marketPosition: 'Major business formation platform',
    },
    strategyType: 'product_led_growth',
    expansionType: 'market',
    targetMarket: 'entrepreneurs',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Disrupted business formation market dominated by LegalZoom', impact: 'Market share capture', difficulty: 'hard' },
      { action: 'Skyrocketed to $80M ARR in 4 years', impact: 'Rapid scale', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'Better UX in legal services can disrupt established players.',
    sourceUrl: 'https://www.starterstory.com/zenbusiness-pbc-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['legal_tech', 'business_formation', 'llc', 'startup'],
    matchingKeywords: ['zenbusiness', 'llc formation', 'business registration'],
    confidenceLevel: 'high',
    summary: 'Skyrocketed from startup to $80M ARR in 4 years in business formation.',
  },
  {
    companyName: 'Documenso',
    industry: 'legal_tech',
    subIndustry: 'e_signature',
    location: 'Germany',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['DocuSign dominance', 'Open source sustainability', 'Feature parity'],
      capabilities: ['Open source expertise', 'Product development', 'Community building'],
      marketPosition: 'New open source e-signature',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '6_10',
      revenueGrowth: 'Growing open source alternative',
      achievements: ['DocuSign challenger', 'Open source model', 'Growing community'],
      newCapabilities: ['E-signature platform', 'Open source community', 'Enterprise features'],
      marketPosition: 'Leading open source e-signature',
    },
    strategyType: 'open_source',
    expansionType: 'community',
    targetMarket: 'businesses',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Built open source DocuSign alternative', impact: 'Market disruption', difficulty: 'hard' },
      { action: 'Grew community challenging DocuSign dominance', impact: 'Awareness building', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Open source can challenge dominant SaaS players.',
    sourceUrl: 'https://www.starterstory.com/documenso-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['legal_tech', 'e_signature', 'open_source', 'saas'],
    matchingKeywords: ['documenso', 'e-signature', 'docusign alternative'],
    confidenceLevel: 'high',
    summary: 'Built open source DocuSign alternative challenging market dominance.',
  },

  // === TRAVEL / HOSPITALITY ===
  {
    companyName: 'Voyagu',
    industry: 'travel',
    subIndustry: 'travel_agency',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Travel agency competition', 'Customer acquisition', 'Scale challenges'],
      capabilities: ['Travel industry knowledge', 'Sales skills', 'Entrepreneurship'],
      marketPosition: 'New travel startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '8-figure revenue in 2 years',
      achievements: ['8-figure revenue', '2-year growth', 'Travel startup success'],
      newCapabilities: ['Travel booking', 'Customer service', 'Scale operations'],
      marketPosition: 'Major travel company',
    },
    strategyType: 'rapid_scale',
    expansionType: 'market',
    targetMarket: 'travelers',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Built 8-figure travel startup in just 2 years', impact: 'Rapid scale', difficulty: 'hard' },
      { action: 'Achieved massive growth in competitive travel market', impact: 'Market capture', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'Travel industry can scale rapidly with right execution.',
    sourceUrl: 'https://www.starterstory.com/stories/voyagu',
    sourcePlatform: 'starter_story',
    tags: ['travel', 'startup', 'rapid_growth', 'hospitality'],
    matchingKeywords: ['voyagu', 'travel startup', 'travel agency'],
    confidenceLevel: 'high',
    summary: 'Built 8-figure travel startup in just 2 years.',
  },
  {
    companyName: 'TripBFF',
    industry: 'travel',
    subIndustry: 'travel_app',
    location: 'Italy',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Travel app competition', 'User acquisition', 'Monetization'],
      capabilities: ['App development', 'Travel knowledge', 'Product skills'],
      marketPosition: 'New travel app',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '6_10',
      revenueGrowth: '$50K/month',
      achievements: ['$50K/month revenue', 'Travel app success', '170-day build'],
      newCapabilities: ['Trip planning', 'Social travel', 'Mobile experience'],
      marketPosition: 'Growing travel app',
    },
    strategyType: 'mobile_first',
    expansionType: 'product',
    targetMarket: 'travelers',
    timeline: { totalMonths: 12 },
    keyActions: [
      { action: 'Built travel app in 170 days', impact: 'Rapid development', difficulty: 'medium' },
      { action: 'Grew to $50K/month revenue', impact: 'Strong traction', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Travel apps can achieve fast growth with focused execution.',
    sourceUrl: 'https://www.starterstory.com/tripbff-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['travel', 'mobile_app', 'startup', 'trip_planning'],
    matchingKeywords: ['tripbff', 'travel app', 'trip planning'],
    confidenceLevel: 'high',
    summary: 'Two founders grew travel app to $50K/month in 12 months.',
  },
  {
    companyName: 'ITILITE',
    industry: 'travel',
    subIndustry: 'business_travel',
    location: 'India',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Corporate travel complexity', 'Expense management', 'Enterprise sales'],
      capabilities: ['Corporate travel knowledge', 'SaaS development', 'B2B sales'],
      marketPosition: 'New business travel startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '201_500',
      revenueGrowth: '500K+ customers',
      achievements: ['500K+ customers', 'Travel & expense platform', 'Global expansion'],
      newCapabilities: ['Travel booking', 'Expense management', 'Enterprise integration'],
      marketPosition: 'Leading business travel platform',
    },
    strategyType: 'enterprise_saas',
    expansionType: 'global',
    targetMarket: 'enterprises',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Built integrated travel and expense management platform', impact: 'Full solution', difficulty: 'hard' },
      { action: 'Scaled to 500K+ customers across markets', impact: 'Massive scale', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 500 },
    lessonsLearned: 'Business travel SaaS can scale globally with right product.',
    sourceUrl: 'https://www.starterstory.com/stories/simplifying-business-travel',
    sourcePlatform: 'starter_story',
    tags: ['travel', 'expense_management', 'b2b', 'enterprise'],
    matchingKeywords: ['itilite', 'business travel', 'expense management'],
    confidenceLevel: 'high',
    summary: 'Built travel and expense management platform reaching 500K+ customers.',
  },
  {
    companyName: 'Baboo Travel',
    industry: 'travel',
    subIndustry: 'custom_travel',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Custom trip planning', 'Travel agent competition', 'Personalization'],
      capabilities: ['Travel passion', 'Trip planning', 'Customer service'],
      marketPosition: 'New custom travel platform',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '6_10',
      revenueGrowth: '$600K/year',
      achievements: ['$600K/year revenue', 'Custom trip platform', 'Travel hobby monetized'],
      newCapabilities: ['Custom itineraries', 'Travel curation', 'Personalized service'],
      marketPosition: 'Growing custom travel service',
    },
    strategyType: 'passion_business',
    expansionType: 'service',
    targetMarket: 'travelers',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Turned travel hobby into custom trips platform', impact: 'Passion monetization', difficulty: 'medium' },
      { action: 'Grew to $600K/year revenue', impact: 'Strong business', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 60 },
    lessonsLearned: 'Travel passion can become profitable custom trip business.',
    sourceUrl: 'https://www.starterstory.com/stories/my-passion-in-travel-lead-to-build-a-600k-year-custom-trips-platform',
    sourcePlatform: 'starter_story',
    tags: ['travel', 'custom_trips', 'passion_business', 'service'],
    matchingKeywords: ['baboo travel', 'custom trips', 'travel planning'],
    confidenceLevel: 'high',
    summary: 'Turned travel hobby into $600K/year custom trips platform.',
  },
  {
    companyName: 'SeatGeek',
    industry: 'travel',
    subIndustry: 'ticketing',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Ticketmaster dominance', 'Ticket aggregation', 'Consumer trust'],
      capabilities: ['Tech development', 'Market knowledge', 'Fundraising'],
      marketPosition: 'New ticket marketplace',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '500_plus',
      revenueGrowth: '$1 billion in ticket sales',
      achievements: ['$1B ticket sales', '3 founders', 'Major ticketing platform'],
      newCapabilities: ['Ticket aggregation', 'Price comparison', 'Mobile ticketing'],
      marketPosition: 'Major ticket marketplace',
    },
    strategyType: 'marketplace',
    expansionType: 'market',
    targetMarket: 'event_goers',
    timeline: { totalMonths: 144 },
    keyActions: [
      { action: 'Built ticket marketplace challenging Ticketmaster', impact: 'Market disruption', difficulty: 'hard' },
      { action: 'Scaled to $1 billion in ticket sales', impact: 'Massive volume', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 10000 },
    lessonsLearned: 'Aggregation and better UX can challenge ticketing incumbents.',
    sourceUrl: 'https://www.starterstory.com/seatgeek-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['ticketing', 'marketplace', 'events', 'startup'],
    matchingKeywords: ['seatgeek', 'ticket marketplace', 'event tickets'],
    confidenceLevel: 'high',
    summary: 'Three founders scaled SeatGeek to $1 billion in ticket sales.',
  },
];

async function seedBatch11() {
  console.log('🌱 Seeding Batch 11: E-commerce, Healthcare, EdTech, Real Estate, Legal Tech, Travel...');

  let successCount = 0;
  let errorCount = 0;

  for (const caseStudy of batch11CaseStudies) {
    try {
      await db.insert(caseStudies).values({
        ...caseStudy,
        startingState: caseStudy.startingState,
        endingState: caseStudy.endingState,
        timeline: caseStudy.timeline,
        keyActions: caseStudy.keyActions,
        outcomes: caseStudy.outcomes,
      } as CaseStudyInsert);
      console.log(`  ✓ ${caseStudy.companyName}`);
      successCount++;
    } catch (error: unknown) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      console.error(`  ✗ ${caseStudy.companyName}: ${errorMessage}`);
      errorCount++;
    }
  }

  console.log(`\nBatch 11 seeding complete!`);
  console.log(`✓ Successfully seeded: ${successCount}`);
  console.log(`✗ Errors: ${errorCount}`);

  process.exit(0);
}

seedBatch11().catch((error) => {
  console.error('Seeding failed:', error);
  process.exit(1);
});
