import { db } from '../../lib/db';
import { caseStudies } from '../schema';

type CaseStudyInsert = typeof caseStudies.$inferInsert;

const batch13CaseStudies = [
  // === FOOD & BEVERAGE ===
  {
    companyName: 'Love Good Fats',
    industry: 'food_beverage',
    subIndustry: 'healthy_snacks',
    location: 'Canada',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Snack market competition', 'Keto positioning', 'Retail distribution'],
      capabilities: ['Food industry experience', 'Product development', 'Marketing skills'],
      marketPosition: 'Starting from dining room table',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$36M/year',
      achievements: ['$36M/year revenue', 'Dining room to major brand', 'Keto snack leader'],
      newCapabilities: ['CPG operations', 'Retail distribution', 'Brand building'],
      marketPosition: 'Leading keto snack brand',
    },
    strategyType: 'brand_building',
    expansionType: 'distribution',
    targetMarket: 'health_conscious_consumers',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Started healthy snack business from dining room table', impact: 'Humble beginnings', difficulty: 'medium' },
      { action: 'Grew to $36M/year in keto snacks', impact: 'Major scale', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 400 },
    lessonsLearned: 'Keto trend created opportunity for healthy snack brands.',
    sourceUrl: 'https://www.starterstory.com/stories/i-started-a-36m-year-healthy-snack-business-from-my-dining-room-table-canada',
    sourcePlatform: 'starter_story',
    tags: ['food', 'snacks', 'keto', 'cpg'],
    matchingKeywords: ['love good fats', 'keto snacks', 'healthy snacks'],
    confidenceLevel: 'high',
    summary: 'Started $36M/year healthy snack business from dining room table.',
  },
  {
    companyName: 'BeatBox Beverages',
    industry: 'food_beverage',
    subIndustry: 'alcoholic_beverages',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Beverage industry barriers', 'Distribution', 'Brand awareness'],
      capabilities: ['Beverage knowledge', 'Marketing creativity', 'Hustle'],
      marketPosition: 'New party beverage brand',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$100M/year (from $18M)',
      achievements: ['$100M/year', '$18M to $100M explosion', 'Party punch leader'],
      newCapabilities: ['National distribution', 'Brand marketing', 'Retail partnerships'],
      marketPosition: 'Leading party beverage brand',
    },
    strategyType: 'brand_explosion',
    expansionType: 'distribution',
    targetMarket: 'party_consumers',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Exploded from $18M to $100M/year', impact: 'Massive growth', difficulty: 'hard' },
      { action: 'Built party punch category leadership', impact: 'Category dominance', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 1200 },
    lessonsLearned: 'Party beverage brands can scale rapidly with right positioning.',
    sourceUrl: 'https://www.starterstory.com/stories/beatbox-beverages',
    sourcePlatform: 'starter_story',
    tags: ['beverage', 'alcohol', 'party', 'cpg'],
    matchingKeywords: ['beatbox beverages', 'party punch', 'beverage brand'],
    confidenceLevel: 'high',
    summary: 'Party punch beverage exploded from $18M to $100M/year.',
  },
  {
    companyName: 'KPOP Foods',
    industry: 'food_beverage',
    subIndustry: 'specialty_foods',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Korean food market', 'Distribution', 'Brand awareness'],
      capabilities: ['Korean cuisine knowledge', 'CPG experience', 'Marketing'],
      marketPosition: 'New Korean food brand',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '6_10',
      revenueGrowth: '$2.4M/year (10x growth since 2020)',
      achievements: ['$2.4M/year', '10x revenue growth', 'Korean food leader'],
      newCapabilities: ['Retail distribution', 'Korean cuisine expertise', 'Brand building'],
      marketPosition: 'Leading Korean sauce brand',
    },
    strategyType: 'niche_focus',
    expansionType: 'distribution',
    targetMarket: 'food_enthusiasts',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Grew Korean food brand 10x since 2020', impact: 'Rapid growth', difficulty: 'medium' },
      { action: 'Built retail and distribution presence', impact: 'Scale achievement', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 30 },
    lessonsLearned: 'Ethnic food categories have significant growth potential.',
    sourceUrl: 'https://www.starterstory.com/stories/kpop-foods-fed29af9-e0ac-40d7-a551-de36f269f298',
    sourcePlatform: 'starter_story',
    tags: ['food', 'korean', 'sauce', 'cpg'],
    matchingKeywords: ['kpop foods', 'korean sauce', 'specialty food'],
    confidenceLevel: 'high',
    summary: 'Grew Korean food brand 10x to $2.4M/year.',
  },
  {
    companyName: 'Good Girl Snacks',
    industry: 'food_beverage',
    subIndustry: 'snacks',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Pickle market entry', 'Zero ad budget', 'Brand building'],
      capabilities: ['Product development', 'Social media skills', 'Creativity'],
      marketPosition: 'New pickle brand',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '1_5',
      revenueGrowth: 'Viral pickle brand',
      achievements: ['Viral brand', 'Zero ad spend', 'Strong organic growth'],
      newCapabilities: ['Organic marketing', 'Product development', 'Community building'],
      marketPosition: 'Viral pickle brand',
    },
    strategyType: 'viral_organic',
    expansionType: 'product',
    targetMarket: 'snack_lovers',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Built viral pickle brand with zero ads', impact: 'Organic growth', difficulty: 'medium' },
      { action: 'Two founders created authentic brand story', impact: 'Brand differentiation', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Authentic brands can grow virally without paid advertising.',
    sourceUrl: 'https://www.starterstory.com/good-girl-snacks-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['food', 'snacks', 'pickles', 'viral'],
    matchingKeywords: ['good girl snacks', 'pickles', 'viral food'],
    confidenceLevel: 'high',
    summary: 'Built viral pickle brand with zero ads.',
  },
  {
    companyName: 'Y\'all Sweet Tea',
    industry: 'food_beverage',
    subIndustry: 'beverages',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Tea market competition', '$300 starting budget', 'Distribution'],
      capabilities: ['Beverage passion', 'Hustle', 'Sales skills'],
      marketPosition: 'New tea brand',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '11_50',
      revenueGrowth: '$5M in 3 years ($333K/month)',
      achievements: ['$5M in 3 years', '$300 starting cost', '15 employees'],
      newCapabilities: ['Beverage distribution', 'Retail partnerships', 'Brand building'],
      marketPosition: 'Growing national tea brand',
    },
    strategyType: 'bootstrap',
    expansionType: 'distribution',
    targetMarket: 'tea_lovers',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Started with $300 and grew to $5M in 3 years', impact: 'Exceptional ROI', difficulty: 'hard' },
      { action: 'Built national tea distribution', impact: 'Scale achievement', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 17000 },
    lessonsLearned: 'Minimal starting capital can lead to major beverage brands.',
    sourceUrl: 'https://www.starterstory.com/y-all-sweet-tea-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['beverage', 'tea', 'bootstrap', 'cpg'],
    matchingKeywords: ['yall sweet tea', 'tea brand', 'beverage startup'],
    confidenceLevel: 'high',
    summary: 'Grew from $300 investment to $5M tea brand in 3 years.',
  },
  {
    companyName: 'Siren Snacks',
    industry: 'food_beverage',
    subIndustry: 'protein_bars',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Dorm room operations', 'Protein bar competition', 'Retail access'],
      capabilities: ['Product development', 'Student hustle', 'Nutrition knowledge'],
      marketPosition: 'Dorm room startup',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '11_50',
      revenueGrowth: '7,000 retail stores',
      achievements: ['7,000 store distribution', 'Dorm to retail success', 'Women-focused protein'],
      newCapabilities: ['CPG operations', 'Retail relationships', 'Product scaling'],
      marketPosition: 'Growing protein bar brand',
    },
    strategyType: 'bootstrap',
    expansionType: 'distribution',
    targetMarket: 'women',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Started making protein bars in dorm room', impact: 'Humble start', difficulty: 'medium' },
      { action: 'Expanded to 7,000 retail stores', impact: 'Major distribution', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Student founders can build major CPG brands.',
    sourceUrl: 'https://www.starterstory.com/stories/we-started-making-protein-bars-in-our-dorm-room-now-we-re-in-7-000-stores',
    sourcePlatform: 'starter_story',
    tags: ['food', 'protein', 'women', 'retail'],
    matchingKeywords: ['siren snacks', 'protein bars', 'women snacks'],
    confidenceLevel: 'high',
    summary: 'Started making protein bars in dorm room, now in 7,000 stores.',
  },
  {
    companyName: 'Lupii',
    industry: 'food_beverage',
    subIndustry: 'protein_bars',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Plant protein positioning', 'CPG competition', 'Distribution'],
      capabilities: ['Food science', 'Sustainability focus', 'Marketing'],
      marketPosition: 'New plant-based protein bar',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '6_10',
      revenueGrowth: '394% growth',
      achievements: ['394% revenue growth', 'Plant-based leadership', 'Lupini bean innovation'],
      newCapabilities: ['Plant protein', 'Sustainable sourcing', 'Retail distribution'],
      marketPosition: 'Growing plant-based brand',
    },
    strategyType: 'product_innovation',
    expansionType: 'product',
    targetMarket: 'plant_based_consumers',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Achieved 394% growth with plant-based protein', impact: 'Rapid growth', difficulty: 'medium' },
      { action: 'Innovated with lupini bean protein', impact: 'Product differentiation', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 5 },
    lessonsLearned: 'Novel plant proteins create differentiation.',
    sourceUrl: 'https://www.starterstory.com/isabelle-steichen-alexandra-dempster',
    sourcePlatform: 'starter_story',
    tags: ['food', 'plant_based', 'protein', 'sustainable'],
    matchingKeywords: ['lupii', 'plant protein', 'lupini bean'],
    confidenceLevel: 'high',
    summary: 'Achieved 394% growth with plant-based protein bars.',
  },
  {
    companyName: 'Daring Foods',
    industry: 'food_beverage',
    subIndustry: 'plant_based',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Plant chicken competition', 'Fundraising', 'Retail distribution'],
      capabilities: ['Food science', 'CPG experience', 'Vision'],
      marketPosition: 'New plant-based chicken',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '51_200',
      revenueGrowth: '$8M raised',
      achievements: ['$8M investment raised', 'Plant chicken innovation', 'Retail presence'],
      newCapabilities: ['Plant protein R&D', 'Manufacturing', 'Distribution'],
      marketPosition: 'Growing plant chicken brand',
    },
    strategyType: 'venture_backed',
    expansionType: 'product',
    targetMarket: 'plant_based_consumers',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Raised $8M for plant-based chicken', impact: 'Major funding', difficulty: 'hard' },
      { action: 'Built plant chicken category presence', impact: 'Market position', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Plant-based proteins attract significant investment.',
    sourceUrl: 'https://www.starterstory.com/food-startup-plant-based-chicken',
    sourcePlatform: 'starter_story',
    tags: ['food', 'plant_based', 'chicken', 'venture'],
    matchingKeywords: ['daring foods', 'plant chicken', 'plant based'],
    confidenceLevel: 'high',
    summary: 'Raised $8M for plant-based chicken innovation.',
  },
  {
    companyName: 'Wondry Wine',
    industry: 'food_beverage',
    subIndustry: 'alcoholic_beverages',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Wine industry barriers', '$100K starting costs', 'Distribution'],
      capabilities: ['Wine knowledge', 'Brand building', 'Sales skills'],
      marketPosition: 'New wine brand',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '11_50',
      revenueGrowth: 'National brand in 3 years ($250K/month)',
      achievements: ['National distribution', '$250K/month', 'Two founders'],
      newCapabilities: ['Wine production', 'National distribution', 'Brand marketing'],
      marketPosition: 'National wine brand',
    },
    strategyType: 'brand_building',
    expansionType: 'distribution',
    targetMarket: 'wine_consumers',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Grew wine brand to national distribution in 3 years', impact: 'Rapid expansion', difficulty: 'hard' },
      { action: 'Built from $100K to $250K/month', impact: 'Strong growth', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 30 },
    lessonsLearned: 'Wine brands can achieve rapid national distribution.',
    sourceUrl: 'https://www.starterstory.com/wondrywine-com-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['beverage', 'wine', 'alcohol', 'national'],
    matchingKeywords: ['wondry wine', 'wine brand', 'beverage startup'],
    confidenceLevel: 'high',
    summary: 'Grew wine brand to national distribution in 3 years.',
  },
  {
    companyName: 'Ka-Pop! Snacks',
    industry: 'food_beverage',
    subIndustry: 'snacks',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Kitchen recipe development', 'CPG competition', 'Retail distribution'],
      capabilities: ['Recipe development', 'CPG knowledge', 'Hustle'],
      marketPosition: 'Kitchen startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '11_50',
      revenueGrowth: '$10MM/year',
      achievements: ['$10M/year revenue', 'Kitchen to major brand', 'Sorghum innovation'],
      newCapabilities: ['CPG operations', 'Retail distribution', 'Product scaling'],
      marketPosition: 'Major CPG snack brand',
    },
    strategyType: 'product_innovation',
    expansionType: 'distribution',
    targetMarket: 'snack_lovers',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Turned kitchen recipe into $10M/year CPG company', impact: 'Major scale', difficulty: 'hard' },
      { action: 'Innovated with sorghum-based snacks', impact: 'Product differentiation', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 120 },
    lessonsLearned: 'Kitchen recipes can become major CPG brands.',
    sourceUrl: 'https://www.starterstory.com/stories/i-turned-a-recipe-in-my-kitchen-into-a-1-2m-year-cpg-snack-company',
    sourcePlatform: 'starter_story',
    tags: ['food', 'snacks', 'cpg', 'sorghum'],
    matchingKeywords: ['kapop snacks', 'sorghum snacks', 'cpg brand'],
    confidenceLevel: 'high',
    summary: 'Turned kitchen recipe into $10MM/year CPG snack company.',
  },

  // === GAMING / ESPORTS ===
  {
    companyName: 'Stardew Valley',
    industry: 'gaming',
    subIndustry: 'indie_games',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Solo game development', 'Multi-year project', 'No publisher'],
      capabilities: ['Game development', 'Pixel art', 'Music composition'],
      marketPosition: 'Solo indie developer',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '1_5',
      revenueGrowth: '$300M/year',
      achievements: ['$300M/year', 'Solo developer', 'Gaming phenomenon'],
      newCapabilities: ['Complete game development', 'Self-publishing', 'Community building'],
      marketPosition: 'Legendary indie game',
    },
    strategyType: 'solo_development',
    expansionType: 'product',
    targetMarket: 'gamers',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Solo developed video game to $300M/year', impact: 'Extraordinary success', difficulty: 'hard' },
      { action: 'Created all art, music, and code alone', impact: 'Complete vision', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 3000000 },
    lessonsLearned: 'Solo developers can create gaming phenomena.',
    sourceUrl: 'https://www.starterstory.com/stories/stardew-valley-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['gaming', 'indie', 'solo_developer', 'phenomenon'],
    matchingKeywords: ['stardew valley', 'indie game', 'eric barone'],
    confidenceLevel: 'high',
    summary: 'Solo developer built $300M/year video game by himself.',
  },
  {
    companyName: 'ggCircuit',
    industry: 'gaming',
    subIndustry: 'esports_services',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Esports arena market', 'B2B sales', 'Global expansion'],
      capabilities: ['Gaming knowledge', 'Software development', 'Industry connections'],
      marketPosition: 'New esports service provider',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '11_50',
      revenueGrowth: '$3.6M/year',
      achievements: ['$3.6M/year', 'Worldwide esports arenas', 'Premium services'],
      newCapabilities: ['Arena management software', 'Global operations', 'Esports expertise'],
      marketPosition: 'Leading esports arena services',
    },
    strategyType: 'b2b_saas',
    expansionType: 'global',
    targetMarket: 'esports_arenas',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Built premium services for esports arenas worldwide', impact: 'Global reach', difficulty: 'hard' },
      { action: 'Grew to $3.6M/year in B2B esports', impact: 'Strong revenue', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 40 },
    lessonsLearned: 'B2B esports infrastructure is a viable market.',
    sourceUrl: 'https://www.starterstory.com/stories/we-offer-premium-services-for-e-sports-arenas-worldwide-3-6m-year',
    sourcePlatform: 'starter_story',
    tags: ['gaming', 'esports', 'b2b', 'saas'],
    matchingKeywords: ['ggcircuit', 'esports arena', 'gaming services'],
    confidenceLevel: 'high',
    summary: 'Offers premium services for esports arenas worldwide at $3.6M/year.',
  },
  {
    companyName: 'Overgear',
    industry: 'gaming',
    subIndustry: 'gaming_services',
    location: 'Europe',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Gaming services reputation', 'Marketplace building', 'Trust'],
      capabilities: ['Gaming knowledge', 'Marketplace development', 'Community building'],
      marketPosition: 'New gaming services marketplace',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$1M/month',
      achievements: ['$1M/month revenue', 'Gaming boosting marketplace', 'Large user base'],
      newCapabilities: ['Marketplace operations', 'Gaming services', 'Community trust'],
      marketPosition: 'Leading game boosting marketplace',
    },
    strategyType: 'marketplace',
    expansionType: 'product',
    targetMarket: 'gamers',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built $1M/month video game boosting marketplace', impact: 'Major scale', difficulty: 'hard' },
      { action: 'Created trusted gaming services platform', impact: 'Market leadership', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 120 },
    lessonsLearned: 'Gaming services marketplaces can achieve significant scale.',
    sourceUrl: 'https://www.starterstory.com/video-games-boosting-services-marketplace',
    sourcePlatform: 'starter_story',
    tags: ['gaming', 'marketplace', 'services', 'boosting'],
    matchingKeywords: ['overgear', 'game boosting', 'gaming services'],
    confidenceLevel: 'high',
    summary: 'Built $1M/month video game boosting services marketplace.',
  },
  {
    companyName: 'Scirra (Construct)',
    industry: 'gaming',
    subIndustry: 'game_development_tools',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Game engine competition', 'No-code positioning', 'User acquisition'],
      capabilities: ['Game development', 'Tool building', 'Community focus'],
      marketPosition: 'New game development tool',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '6_10',
      revenueGrowth: '$100K/month',
      achievements: ['$100K/month', 'No-code game development', 'Strong community'],
      newCapabilities: ['No-code game engine', 'Educational tools', 'Community building'],
      marketPosition: 'Leading no-code game engine',
    },
    strategyType: 'product_led_growth',
    expansionType: 'product',
    targetMarket: 'game_developers',
    timeline: { totalMonths: 120 },
    keyActions: [
      { action: 'Built no-code game development tool to $100K/month', impact: 'Strong SaaS', difficulty: 'hard' },
      { action: 'Created accessible game development platform', impact: 'Market democratization', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'No-code game development tools serve large market.',
    sourceUrl: 'https://www.starterstory.com/stories/we-created-a-100k-month-no-code-tool-for-video-game-developers',
    sourcePlatform: 'starter_story',
    tags: ['gaming', 'no_code', 'game_engine', 'saas'],
    matchingKeywords: ['construct', 'scirra', 'game development', 'no code'],
    confidenceLevel: 'high',
    summary: 'Created $100K/month no-code tool for video game developers.',
  },
  {
    companyName: 'VastGG',
    industry: 'gaming',
    subIndustry: 'gaming_marketing',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Gamer marketing', 'Influencer partnerships', 'Trust building'],
      capabilities: ['Gaming community knowledge', 'Marketing skills', 'Partnership building'],
      marketPosition: 'New gamer giveaway platform',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '6_10',
      revenueGrowth: '$300K/year',
      achievements: ['$300K/year', 'Pro gamer partnerships', 'Giveaway platform'],
      newCapabilities: ['Influencer marketing', 'Giveaway operations', 'Gamer community'],
      marketPosition: 'Gamer giveaway platform',
    },
    strategyType: 'influencer_marketing',
    expansionType: 'market',
    targetMarket: 'gamers',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built $300K/year giveaway business for pro gamers', impact: 'Niche success', difficulty: 'medium' },
      { action: 'Partnered with professional gaming influencers', impact: 'Distribution channel', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 30 },
    lessonsLearned: 'Gaming influencer marketing creates opportunities.',
    sourceUrl: 'https://www.starterstory.com/stories/we-started-a-300k-year-business-doing-giveaways-for-pro-gamers',
    sourcePlatform: 'starter_story',
    tags: ['gaming', 'giveaways', 'influencer', 'marketing'],
    matchingKeywords: ['vastgg', 'gamer giveaways', 'gaming marketing'],
    confidenceLevel: 'high',
    summary: 'Built $300K/year business doing giveaways for pro gamers.',
  },
  {
    companyName: 'Pogr',
    industry: 'gaming',
    subIndustry: 'gaming_analytics',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Gaming analytics market', 'Fundraising', 'Product development'],
      capabilities: ['Data analytics', 'Gaming knowledge', 'Technical skills'],
      marketPosition: 'New gaming analytics startup',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '11_50',
      revenueGrowth: '$20M raised',
      achievements: ['$20M raised', 'Google Analytics for gaming', 'Strong team'],
      newCapabilities: ['Gaming analytics', 'Data infrastructure', 'Developer tools'],
      marketPosition: 'Gaming analytics platform',
    },
    strategyType: 'venture_backed',
    expansionType: 'product',
    targetMarket: 'game_developers',
    timeline: { totalMonths: 18 },
    keyActions: [
      { action: 'Raised $20M to build Google Analytics for video games', impact: 'Major funding', difficulty: 'hard' },
      { action: 'Built gaming analytics platform', impact: 'Product development', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 200 },
    lessonsLearned: 'Gaming analytics attracted significant VC interest.',
    sourceUrl: 'https://www.starterstory.com/stories/pogr',
    sourcePlatform: 'starter_story',
    tags: ['gaming', 'analytics', 'venture', 'saas'],
    matchingKeywords: ['pogr', 'gaming analytics', 'game developer tools'],
    confidenceLevel: 'high',
    summary: 'Raised $20M to build Google Analytics for video games.',
  },

  // === PET INDUSTRY ===
  {
    companyName: 'iHeartDogs',
    industry: 'pet',
    subIndustry: 'pet_retail',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Pet e-commerce competition', 'Content strategy', 'Brand building'],
      capabilities: ['E-commerce skills', 'Content creation', 'Dog lover passion'],
      marketPosition: 'New dog lifestyle brand',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$1.2M/month ($14.4M/year)',
      achievements: ['$1.2M/month', 'Dog lifestyle leader', 'Mission-driven brand'],
      newCapabilities: ['Pet e-commerce', 'Content marketing', 'Cause marketing'],
      marketPosition: 'Leading dog lifestyle store',
    },
    strategyType: 'content_commerce',
    expansionType: 'product',
    targetMarket: 'dog_owners',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Built $1.2M/month dog lifestyle store', impact: 'Major scale', difficulty: 'hard' },
      { action: 'Combined content and commerce for dog owners', impact: 'Differentiated model', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 150 },
    lessonsLearned: 'Pet content commerce creates loyal customers.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-dog-store',
    sourcePlatform: 'starter_story',
    tags: ['pet', 'ecommerce', 'dogs', 'content'],
    matchingKeywords: ['iheartdogs', 'dog store', 'pet lifestyle'],
    confidenceLevel: 'high',
    summary: 'Built $1.2M/month lifestyle store for dog owners.',
  },
  {
    companyName: 'Woofie\'s',
    industry: 'pet',
    subIndustry: 'pet_services',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Pet care service delivery', 'Scaling services', 'Trust building'],
      capabilities: ['Pet care expertise', 'Service operations', 'Partnership skills'],
      marketPosition: 'New pet care service',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '51_200',
      revenueGrowth: '$250K/month ($3M/year)',
      achievements: ['$250K/month', 'Two friends partnership', 'Professional pet care'],
      newCapabilities: ['Pet care operations', 'Service scaling', 'Team management'],
      marketPosition: 'Professional pet care brand',
    },
    strategyType: 'service_business',
    expansionType: 'market',
    targetMarket: 'pet_owners',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Two friends built $250K/month pet care business', impact: 'Strong partnership', difficulty: 'medium' },
      { action: 'Scaled professional pet care services', impact: 'Service expansion', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 30 },
    lessonsLearned: 'Pet care services scale with right operations.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-pet-care-business',
    sourcePlatform: 'starter_story',
    tags: ['pet', 'services', 'pet_care', 'local'],
    matchingKeywords: ['woofies', 'pet care', 'dog walking'],
    confidenceLevel: 'high',
    summary: 'Two friends built $250K/month professional pet care business.',
  },

  // === CREATOR ECONOMY ===
  {
    companyName: 'Vidovo',
    industry: 'creator_economy',
    subIndustry: 'creator_tools',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Creator tool competition', 'UGC market', 'User acquisition'],
      capabilities: ['Product development', 'Creator knowledge', 'Marketing skills'],
      marketPosition: 'New UGC creator platform',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '6_10',
      revenueGrowth: '$1M/year',
      achievements: ['$1M/year', 'Bootstrapped success', 'UGC video platform'],
      newCapabilities: ['Creator platform', 'Video ads', 'UGC marketplace'],
      marketPosition: 'Growing UGC platform',
    },
    strategyType: 'bootstrap',
    expansionType: 'product',
    targetMarket: 'creators',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Bootstrapped creator app to $1M/year', impact: 'Strong revenue', difficulty: 'medium' },
      { action: 'Built UGC video ads platform', impact: 'Product-market fit', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'UGC creator tools have strong product-market fit.',
    sourceUrl: 'https://www.starterstory.com/stories/vidovo-com-ugc-video-ads-made-easy',
    sourcePlatform: 'starter_story',
    tags: ['creator', 'ugc', 'video', 'saas'],
    matchingKeywords: ['vidovo', 'ugc creator', 'video ads'],
    confidenceLevel: 'high',
    summary: 'Bootstrapped UGC creator app to $1M/year.',
  },
  {
    companyName: 'SARAL',
    industry: 'creator_economy',
    subIndustry: 'influencer_marketing',
    location: 'India/USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Influencer marketing complexity', 'SaaS competition', 'Scale'],
      capabilities: ['Marketing knowledge', 'SaaS development', 'Influencer expertise'],
      marketPosition: 'New influencer marketing SaaS',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '6_10',
      revenueGrowth: '$50K/month',
      achievements: ['$50K/month', '13,000+ influencers', 'Influencer marketing SaaS'],
      newCapabilities: ['Influencer database', 'Campaign management', 'Analytics'],
      marketPosition: 'Growing influencer platform',
    },
    strategyType: 'b2b_saas',
    expansionType: 'product',
    targetMarket: 'brands',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built influencer marketing SaaS with 13,000+ influencers', impact: 'Large database', difficulty: 'hard' },
      { action: 'Grew to $50K/month serving brands', impact: 'Strong revenue', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Influencer marketing SaaS serves growing market.',
    sourceUrl: 'https://www.starterstory.com/stories/saral',
    sourcePlatform: 'starter_story',
    tags: ['influencer', 'marketing', 'saas', 'creator'],
    matchingKeywords: ['saral', 'influencer marketing', 'creator platform'],
    confidenceLevel: 'high',
    summary: 'Built influencer marketing SaaS working with 13,000+ influencers.',
  },
  {
    companyName: 'ContentCreator.com',
    industry: 'creator_economy',
    subIndustry: 'content_production',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Content production scale', 'Client acquisition', 'Operations'],
      capabilities: ['Content creation', 'Production skills', 'Sales'],
      marketPosition: 'New content production agency',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '51_200',
      revenueGrowth: '$6M/year',
      achievements: ['$6M/year', 'Content machine', 'Scale production'],
      newCapabilities: ['Content at scale', 'Creator network', 'Client management'],
      marketPosition: 'Major content production company',
    },
    strategyType: 'service_scale',
    expansionType: 'service',
    targetMarket: 'brands',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built content machine generating $6M/year', impact: 'Major scale', difficulty: 'hard' },
      { action: 'Scaled content production operations', impact: 'Operational excellence', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 70 },
    lessonsLearned: 'Content production scales with right systems.',
    sourceUrl: 'https://www.starterstory.com/stories/content-creator',
    sourcePlatform: 'starter_story',
    tags: ['content', 'production', 'agency', 'creator'],
    matchingKeywords: ['content creator', 'content production', 'content agency'],
    confidenceLevel: 'high',
    summary: 'Built content machine generating $6M in revenue per year.',
  },
  {
    companyName: 'Genflow',
    industry: 'creator_economy',
    subIndustry: 'creator_agency',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Creator management', 'Agency scale', 'Talent acquisition'],
      capabilities: ['Creator relationships', 'Agency operations', 'Business development'],
      marketPosition: 'New creator agency',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$100M agency',
      achievements: ['$100M agency', 'Creator empowerment', 'Major scale'],
      newCapabilities: ['Creator management', 'Brand partnerships', 'Content strategy'],
      marketPosition: 'Leading creator agency',
    },
    strategyType: 'talent_management',
    expansionType: 'market',
    targetMarket: 'creators',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Grew creator agency to $100M scale', impact: 'Massive growth', difficulty: 'hard' },
      { action: 'Empowered creators with brand partnerships', impact: 'Creator value', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 1200 },
    lessonsLearned: 'Creator agencies can achieve massive scale.',
    sourceUrl: 'https://www.starterstory.com/genflow-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['creator', 'agency', 'influencer', 'talent'],
    matchingKeywords: ['genflow', 'creator agency', 'influencer management'],
    confidenceLevel: 'high',
    summary: 'Grew into $100M agency by empowering creators.',
  },
  {
    companyName: 'Charlie Chang (YouTube)',
    industry: 'creator_economy',
    subIndustry: 'youtube',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['YouTube growth', 'Content creation', 'Monetization'],
      capabilities: ['Finance knowledge', 'Content creation', 'Personal brand'],
      marketPosition: 'New finance YouTuber',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '6_10',
      revenueGrowth: '$2.4M/year',
      achievements: ['$2.4M/year', 'YouTube empire', '3-year growth'],
      newCapabilities: ['YouTube strategy', 'Sponsorships', 'Course creation'],
      marketPosition: 'Major finance YouTuber',
    },
    strategyType: 'personal_brand',
    expansionType: 'content',
    targetMarket: 'finance_interested',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built $2.4M/year YouTube empire in 3 years', impact: 'Rapid growth', difficulty: 'hard' },
      { action: 'Created finance content with multiple revenue streams', impact: 'Diversified income', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 250 },
    lessonsLearned: 'YouTube finance content creates multiple revenue streams.',
    sourceUrl: 'https://www.starterstory.com/charlie-chang-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['youtube', 'creator', 'finance', 'personal_brand'],
    matchingKeywords: ['charlie chang', 'youtube creator', 'finance youtube'],
    confidenceLevel: 'high',
    summary: 'Built $2.4M/year YouTube empire in 3 years.',
  },
  {
    companyName: 'AMYTV (Amy Landino)',
    industry: 'creator_economy',
    subIndustry: 'video_content',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['College dropout', 'Video content creation', 'Monetization'],
      capabilities: ['Video production', 'Personal brand', 'Speaking skills'],
      marketPosition: 'New video content creator',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '1_5',
      revenueGrowth: '$18K/month ($216K/year)',
      achievements: ['$18K/month', 'College dropout success', 'Video content business'],
      newCapabilities: ['Video production', 'Speaking', 'Coaching'],
      marketPosition: 'Established video content creator',
    },
    strategyType: 'personal_brand',
    expansionType: 'content',
    targetMarket: 'entrepreneurs',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'College dropout built $18K/month video content business', impact: 'Alternative path', difficulty: 'medium' },
      { action: 'Built personal brand around video content', impact: 'Authority building', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Video content creators can build sustainable businesses.',
    sourceUrl: 'https://www.starterstory.com/amytv-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['video', 'creator', 'personal_brand', 'youtube'],
    matchingKeywords: ['amy landino', 'amytv', 'video content'],
    confidenceLevel: 'high',
    summary: 'College dropout built $18K/month video content business.',
  },
];

async function seedBatch13() {
  console.log('🌱 Seeding Batch 13: Food & Beverage, Gaming, Pet Industry, Creator Economy...');

  let successCount = 0;
  let errorCount = 0;

  for (const caseStudy of batch13CaseStudies) {
    try {
      await db.insert(caseStudies).values({
        ...caseStudy,
        startingState: caseStudy.startingState,
        endingState: caseStudy.endingState,
        timeline: caseStudy.timeline,
        keyActions: caseStudy.keyActions,
        outcomes: caseStudy.outcomes,
      } as CaseStudyInsert);
      console.log(`  ✓ ${caseStudy.companyName}`);
      successCount++;
    } catch (error: unknown) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      console.error(`  ✗ ${caseStudy.companyName}: ${errorMessage}`);
      errorCount++;
    }
  }

  console.log(`\nBatch 13 seeding complete!`);
  console.log(`✓ Successfully seeded: ${successCount}`);
  console.log(`✗ Errors: ${errorCount}`);

  process.exit(0);
}

seedBatch13().catch((error) => {
  console.error('Seeding failed:', error);
  process.exit(1);
});
