import { db } from '@/lib/db';
import { caseStudies } from '@/database/schema';

/**
 * Case Studies Batch 2 - Scraped from Starter Story
 * 100+ Real case studies across all industries
 * Source: starterstory.com
 */
export const caseStudyBatch2 = [
  // ============================================================================
  // VIDEO PRODUCTION & MEDIA (Additional)
  // ============================================================================
  {
    companyName: 'Film Booth',
    industry: 'video_production',
    subIndustry: 'youtube_education',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Starting from scratch', 'Building audience', 'Monetization'],
      capabilities: ['Film production', 'YouTube expertise'],
      marketPosition: 'Unknown creator',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '11_25',
      revenueGrowth: '100x+',
      achievements: ['$4M+ revenue in 2.5 years', '$333K/month', 'Major YouTube education brand'],
      newCapabilities: ['Course creation', 'Community building', 'Multiple revenue streams'],
      marketPosition: 'Leading YouTube education company',
    },
    strategyType: 'content_led_growth',
    expansionType: 'horizontal',
    targetMarket: 'content_creators',
    timeline: { totalMonths: 30 },
    keyActions: [
      { action: 'Built YouTube channel teaching filmmaking', impact: 'Massive organic audience', difficulty: 'hard' },
      { action: 'Created premium courses', impact: 'High-ticket revenue stream', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Teaching what you know can scale faster than client work.',
    sourceUrl: 'https://www.starterstory.com/film-booth-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['youtube', 'education', 'content_creation', 'courses'],
    matchingKeywords: ['video production', 'youtube', 'education', 'courses'],
    confidenceLevel: 'high',
    summary: 'Ed Lawrence built Film Booth to $4M+ in 2.5 years by teaching filmmaking on YouTube.',
  },
  {
    companyName: 'BIGFILMS',
    industry: 'video_production',
    subIndustry: 'vfx_assets',
    location: 'Los Angeles, CA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 1,
      challenges: ['Side project funding', 'Building product library', 'Marketing'],
      capabilities: ['VFX', 'Film production'],
      marketPosition: 'Side project',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '2_5',
      revenueGrowth: '10x',
      achievements: ['$85K best month', '2x revenue growth', 'Passive income model'],
      newCapabilities: ['Asset library', 'Subscription model'],
      marketPosition: 'VFX asset provider',
    },
    strategyType: 'content_led_growth',
    expansionType: 'horizontal',
    targetMarket: 'filmmakers',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Created VFX assets as side project', impact: 'Passive income stream', difficulty: 'moderate' },
      { action: 'Built library over time', impact: 'Compounding asset value', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Side projects can become main income with patience.',
    sourceUrl: 'https://www.starterstory.com/stories/how-we-2x-d-revenue-and-hit-85k-during-our-best-selling-month',
    sourcePlatform: 'starter_story',
    tags: ['vfx', 'assets', 'passive_income', 'filmmaking'],
    matchingKeywords: ['vfx', 'video effects', 'assets', 'filmmaking'],
    confidenceLevel: 'high',
    summary: 'Steven Liszka built BIGFILMS VFX assets to $85K/month as a side project turned main business.',
  },
  {
    companyName: 'Vidovo',
    industry: 'video_production',
    subIndustry: 'ugc_platform',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 1,
      challenges: ['Two-sided marketplace', 'Creator acquisition', 'Brand trust'],
      capabilities: ['Platform development', 'Marketing'],
      marketPosition: 'New entrant',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '6_10',
      revenueGrowth: '20x',
      achievements: ['$1M ARR', '$83K/month', 'UGC marketplace leader'],
      newCapabilities: ['Creator network', 'Brand partnerships', 'Automated matching'],
      marketPosition: 'Growing UGC platform',
    },
    strategyType: 'partnership_expansion',
    expansionType: 'horizontal',
    targetMarket: 'dtc_brands',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Built two-sided marketplace', impact: 'Network effects', difficulty: 'hard' },
      { action: 'Focused on DTC brands', impact: 'Clear target market', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Marketplaces are hard but create strong moats.',
    sourceUrl: 'https://www.starterstory.com/stories/vidovo-com-ugc-video-ads-made-easy',
    sourcePlatform: 'starter_story',
    tags: ['ugc', 'marketplace', 'creators', 'dtc'],
    matchingKeywords: ['ugc', 'user generated content', 'video ads', 'creators'],
    confidenceLevel: 'high',
    summary: 'Elijah Khasabo built Vidovo UGC marketplace to $1M ARR connecting brands with creators.',
  },

  // ============================================================================
  // MARKETING AGENCIES (Additional)
  // ============================================================================
  {
    companyName: 'Ignite Social Media',
    industry: 'marketing_agency',
    subIndustry: 'social_media',
    location: 'Raleigh, NC',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Social media was new', 'Proving ROI', 'Educating clients'],
      capabilities: ['Marketing strategy', 'Early social media expertise'],
      marketPosition: 'Pioneer',
    },
    endingState: {
      revenue: '5m_plus',
      teamSize: '50_plus',
      revenueGrowth: '100x+',
      achievements: ['$500K/month revenue', 'First social media agency', 'Industry pioneer'],
      newCapabilities: ['Full social suite', 'Enterprise clients', 'Thought leadership'],
      marketPosition: 'Industry pioneer',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'horizontal',
    targetMarket: 'enterprise',
    timeline: { totalMonths: 180 },
    keyActions: [
      { action: 'Started before social media platforms existed', impact: 'First mover advantage', difficulty: 'hard' },
      { action: 'Educated market on social media value', impact: 'Built entire category', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Being first to a category creates lasting advantage.',
    sourceUrl: 'https://www.starterstory.com/start-a-social-media-agency',
    sourcePlatform: 'starter_story',
    tags: ['social_media', 'pioneer', 'enterprise', 'agency'],
    matchingKeywords: ['social media', 'marketing agency', 'enterprise'],
    confidenceLevel: 'high',
    summary: 'Jim Tobin started Ignite Social Media in 2007, growing to $500K/month as a social media pioneer.',
  },
  {
    companyName: 'Tetra',
    industry: 'marketing_agency',
    subIndustry: 'email_marketing',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Starting from scratch', 'Finding clients', 'Scaling'],
      capabilities: ['Email marketing', 'Ecommerce expertise'],
      marketPosition: 'Freelancer',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '11_25',
      revenueGrowth: '40x',
      achievements: ['$200K MRR', 'Ecommerce email specialist', 'Productized service'],
      newCapabilities: ['Full email service', 'Team operations', 'Automation'],
      marketPosition: 'Leading email agency',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'vertical',
    targetMarket: 'ecommerce',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Specialized in ecommerce email', impact: 'Clear positioning', difficulty: 'moderate' },
      { action: 'Built productized service model', impact: 'Scalable operations', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 40 },
    lessonsLearned: 'Specialization in a growing niche creates rapid growth.',
    sourceUrl: 'https://www.starterstory.com/stories/tetra',
    sourcePlatform: 'starter_story',
    tags: ['email_marketing', 'ecommerce', 'agency', 'productized'],
    matchingKeywords: ['email marketing', 'ecommerce', 'agency'],
    confidenceLevel: 'high',
    summary: 'Philip Rivers grew Tetra email agency from $5K to $200K MRR by specializing in ecommerce.',
  },
  {
    companyName: 'Custom Creatives',
    industry: 'marketing_agency',
    subIndustry: 'digital_marketing',
    location: 'Los Angeles, CA',
    startingState: {
      revenue: '100k_250k',
      teamSize: '2_5',
      yearsInBusiness: 2,
      challenges: ['Scaling past founders', 'Client acquisition', 'Hiring'],
      capabilities: ['Digital marketing', 'Creative design'],
      marketPosition: 'Small agency',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '26_50',
      revenueGrowth: '15x',
      achievements: ['$300K/month revenue', 'Full service agency', 'Premium clients'],
      newCapabilities: ['Complete digital suite', 'In-house creative', 'Enterprise solutions'],
      marketPosition: 'Major digital agency',
    },
    strategyType: 'partnership_expansion',
    expansionType: 'horizontal',
    targetMarket: 'mid_market',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built full-service offering', impact: 'Larger contracts', difficulty: 'hard' },
      { action: 'Invested in team and culture', impact: 'Scalable operations', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 15 },
    lessonsLearned: 'Full-service agencies can command premium pricing.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-digital-marketing-agency',
    sourcePlatform: 'starter_story',
    tags: ['digital_marketing', 'agency', 'creative', 'full_service'],
    matchingKeywords: ['digital marketing', 'agency', 'creative'],
    confidenceLevel: 'high',
    summary: 'Rahul Alim grew Custom Creatives to $300K/month as a full-service digital agency.',
  },
  {
    companyName: 'The Pedowitz Group',
    industry: 'marketing_agency',
    subIndustry: 'marketing_operations',
    location: 'Atlanta, GA',
    startingState: {
      revenue: '500k_1m',
      teamSize: '6_10',
      yearsInBusiness: 5,
      challenges: ['Competing with big consultancies', 'Scaling expertise', 'Enterprise sales'],
      capabilities: ['Marketing automation', 'RevOps', 'Consulting'],
      marketPosition: 'Growing consultancy',
    },
    endingState: {
      revenue: '5m_plus',
      teamSize: '50_plus',
      revenueGrowth: '20x',
      achievements: ['$1.5M/month revenue', '$20M/year', 'Enterprise leader'],
      newCapabilities: ['Full revenue operations', 'Training programs', 'Enterprise solutions'],
      marketPosition: 'Industry leader',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'vertical',
    targetMarket: 'enterprise',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Focused on revenue operations', impact: 'Differentiated positioning', difficulty: 'hard' },
      { action: 'Built enterprise sales process', impact: 'Large contracts', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Enterprise consulting requires deep specialization and long sales cycles.',
    sourceUrl: 'https://www.starterstory.com/stories/the-pedowitz-group',
    sourcePlatform: 'starter_story',
    tags: ['revops', 'enterprise', 'consulting', 'marketing_automation'],
    matchingKeywords: ['revenue operations', 'marketing operations', 'enterprise'],
    confidenceLevel: 'high',
    summary: 'The Pedowitz Group grew to $1.5M/month as an enterprise revenue operations consultancy.',
  },
  {
    companyName: 'Sievers Creative',
    industry: 'marketing_agency',
    subIndustry: 'full_service',
    location: 'Red Wing, MN',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Side hustle', 'Small town market', 'Building team'],
      capabilities: ['Design', 'Marketing'],
      marketPosition: 'Side hustle',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '11_25',
      revenueGrowth: '50x',
      achievements: ['$250K/month revenue', 'Full service agency', 'Regional leader'],
      newCapabilities: ['Complete marketing suite', 'Team operations'],
      marketPosition: 'Regional leader',
    },
    strategyType: 'partnership_expansion',
    expansionType: 'horizontal',
    targetMarket: 'smb',
    timeline: { totalMonths: 120 },
    keyActions: [
      { action: 'Started as side hustle', impact: 'Low risk start', difficulty: 'easy' },
      { action: 'Expanded service offering', impact: 'Larger contracts', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Side hustles can become major businesses with patience.',
    sourceUrl: 'https://www.starterstory.com/stories/sievers-creative',
    sourcePlatform: 'starter_story',
    tags: ['marketing_agency', 'side_hustle', 'full_service'],
    matchingKeywords: ['marketing agency', 'full service', 'small town'],
    confidenceLevel: 'high',
    summary: 'Roger Sievers grew side hustle Sievers Creative to $250K/month full service agency.',
  },
  {
    companyName: 'Creme Digital',
    industry: 'marketing_agency',
    subIndustry: 'no_code',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['17 years old', 'No experience', 'Building credibility'],
      capabilities: ['No-code development', 'Marketing'],
      marketPosition: 'Teen entrepreneur',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '6_10',
      revenueGrowth: '20x',
      achievements: ['$100K/month', '$1.2M ARR at 17', 'No-code specialist'],
      newCapabilities: ['Full no-code development', 'Team management'],
      marketPosition: 'Leading no-code agency',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'vertical',
    targetMarket: 'startups',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Specialized in no-code', impact: 'Clear differentiation', difficulty: 'moderate' },
      { action: 'Built at 17 years old', impact: 'Unique story and hustle', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Age is no barrier to building a successful agency.',
    sourceUrl: 'https://www.starterstory.com/stories/creme-digital',
    sourcePlatform: 'starter_story',
    tags: ['no_code', 'young_founder', 'agency', 'startups'],
    matchingKeywords: ['no-code', 'agency', 'young founder'],
    confidenceLevel: 'high',
    summary: 'Jacob Klug built $1.2M no-code agency Creme Digital at 17 years old.',
  },

  // ============================================================================
  // SAAS & SOFTWARE (Additional)
  // ============================================================================
  {
    companyName: 'Supademo',
    industry: 'saas',
    subIndustry: 'product_demos',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 1,
      challenges: ['Competitive market', 'Product differentiation', 'Growth'],
      capabilities: ['Product development', 'AI integration'],
      marketPosition: 'New entrant',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '6_10',
      revenueGrowth: '40x',
      achievements: ['$200K/month revenue', 'AI-powered demos', 'Rapid growth'],
      newCapabilities: ['AI demo creation', 'Enterprise features'],
      marketPosition: 'Growing demo platform',
    },
    strategyType: 'content_led_growth',
    expansionType: 'horizontal',
    targetMarket: 'saas_companies',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Built AI-powered demo platform', impact: 'Product differentiation', difficulty: 'hard' },
      { action: 'Focused on product-led growth', impact: 'Organic acquisition', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 40 },
    lessonsLearned: 'AI integration can differentiate in crowded markets.',
    sourceUrl: 'https://www.starterstory.com/stories/supademo',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'ai', 'demos', 'product_led'],
    matchingKeywords: ['saas', 'demo', 'ai', 'product-led growth'],
    confidenceLevel: 'high',
    summary: 'Joseph Lee built Supademo AI demo platform to $200K/month.',
  },
  {
    companyName: 'UserGuiding',
    industry: 'saas',
    subIndustry: 'user_onboarding',
    location: 'Turkey',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 1,
      challenges: ['Bootstrapped', 'International competition', 'Product market fit'],
      capabilities: ['Product development', 'No-code tools'],
      marketPosition: 'Unknown startup',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '26_50',
      revenueGrowth: '20x',
      achievements: ['$200K MRR', 'From $9.4K to $200K MRR in 5 years', 'Bootstrapped success'],
      newCapabilities: ['Full onboarding suite', 'Enterprise features', 'Analytics'],
      marketPosition: 'User onboarding leader',
    },
    strategyType: 'content_led_growth',
    expansionType: 'horizontal',
    targetMarket: 'saas_companies',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built no-code onboarding tool', impact: 'Easy adoption', difficulty: 'hard' },
      { action: 'Focused on content marketing', impact: 'Organic growth', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Bootstrapped SaaS can compete with funded competitors through focus.',
    sourceUrl: 'https://www.starterstory.com/stories/userguiding-985c705f-6fac-497d-9d7e-47da3935883c',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'onboarding', 'bootstrapped', 'no_code'],
    matchingKeywords: ['saas', 'user onboarding', 'bootstrapped'],
    confidenceLevel: 'high',
    summary: 'Osman Koc bootstrapped UserGuiding from $9.4K to $200K MRR in under 5 years.',
  },
  {
    companyName: 'Heptabase',
    industry: 'saas',
    subIndustry: 'note_taking',
    location: 'Taiwan',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Crowded market', 'Product differentiation', 'User acquisition'],
      capabilities: ['Product design', 'Development'],
      marketPosition: 'Unknown startup',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '6_10',
      revenueGrowth: '100x',
      achievements: ['$200K/month revenue', 'Visual note-taking leader', 'Bootstrapped'],
      newCapabilities: ['Visual knowledge management', 'Team features'],
      marketPosition: 'Visual note-taking pioneer',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'vertical',
    targetMarket: 'knowledge_workers',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built visual-first note taking', impact: 'Differentiated from competitors', difficulty: 'hard' },
      { action: 'Bootstrapped growth', impact: 'Full control and profitability', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Visual differentiation can carve space in crowded markets.',
    sourceUrl: 'https://www.starterstory.com/heptabase-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'note_taking', 'visual', 'bootstrapped'],
    matchingKeywords: ['note taking', 'visual', 'knowledge management'],
    confidenceLevel: 'high',
    summary: 'Alan Chan bootstrapped Heptabase visual note-taking to $200K/month.',
  },
  {
    companyName: 'Ninety',
    industry: 'saas',
    subIndustry: 'business_os',
    location: 'USA',
    startingState: {
      revenue: '500k_1m',
      teamSize: '6_10',
      yearsInBusiness: 3,
      challenges: ['Scaling operations', 'Enterprise features', 'Competition'],
      capabilities: ['Business operating systems', 'EOS implementation'],
      marketPosition: 'Growing tool',
    },
    endingState: {
      revenue: '5m_plus',
      teamSize: '50_plus',
      revenueGrowth: '30x',
      achievements: ['$2.5M/month revenue', '$30M ARR', 'Bootstrapped to scale'],
      newCapabilities: ['Full business OS', 'Enterprise features', 'Integration ecosystem'],
      marketPosition: 'Business OS leader',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'vertical',
    targetMarket: 'smb',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Built around EOS methodology', impact: 'Built-in audience', difficulty: 'moderate' },
      { action: 'Bootstrapped entire journey', impact: 'Profitable from start', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 30 },
    lessonsLearned: 'Building around proven methodologies accelerates adoption.',
    sourceUrl: 'https://www.starterstory.com/ninety-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'business_os', 'eos', 'bootstrapped'],
    matchingKeywords: ['business operating system', 'eos', 'management'],
    confidenceLevel: 'high',
    summary: 'Mark Abbott bootstrapped Ninety business OS to $30M revenue.',
  },
  {
    companyName: 'Snappa',
    industry: 'saas',
    subIndustry: 'design_tools',
    location: 'Canada',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 1,
      challenges: ['Competing with Canva', 'User acquisition', 'Feature development'],
      capabilities: ['Product development', 'Design'],
      marketPosition: 'Small player',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '2_5',
      revenueGrowth: '15x',
      achievements: ['$83.5K MRR', '$1M ARR', 'Lean and profitable'],
      newCapabilities: ['Full design suite', 'Social media templates'],
      marketPosition: 'Profitable design tool',
    },
    strategyType: 'content_led_growth',
    expansionType: 'vertical',
    targetMarket: 'marketers',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built simple focused tool', impact: 'Easy to use, clear value prop', difficulty: 'moderate' },
      { action: 'Kept team lean', impact: 'High profitability', difficulty: 'easy' },
    ],
    outcomes: { revenueMultiplier: 15 },
    lessonsLearned: 'Small teams can build profitable SaaS competing with giants.',
    sourceUrl: 'https://www.starterstory.com/stories/how-we-increased-mrr-by-30k-in-one-year',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'design', 'bootstrapped', 'lean'],
    matchingKeywords: ['design tool', 'graphics', 'saas'],
    confidenceLevel: 'high',
    summary: 'Snappa crossed $1M ARR with $83.5K MRR staying lean with small team.',
  },
  {
    companyName: 'ClinicSense',
    industry: 'saas',
    subIndustry: 'wellness_software',
    location: 'Canada',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 2,
      challenges: ['Niche market', 'Feature requests', 'Competition'],
      capabilities: ['Software development', 'Wellness industry knowledge'],
      marketPosition: 'Niche player',
    },
    endingState: {
      revenue: '5m_plus',
      teamSize: '11_25',
      revenueGrowth: '100x',
      achievements: ['$416K/month revenue', '7-figure ARR', 'Bootstrapped wellness SaaS'],
      newCapabilities: ['Full practice management', 'Booking', 'Payments'],
      marketPosition: 'Wellness software leader',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'vertical',
    targetMarket: 'wellness_practitioners',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Focused on wellness niche', impact: 'Deep product-market fit', difficulty: 'moderate' },
      { action: 'Built comprehensive solution', impact: 'Replaced multiple tools', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Vertical SaaS in underserved niches can scale rapidly.',
    sourceUrl: 'https://www.starterstory.com/stories/clinicsense',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'wellness', 'vertical', 'bootstrapped'],
    matchingKeywords: ['wellness software', 'practice management', 'saas'],
    confidenceLevel: 'high',
    summary: 'ClinicSense bootstrapped wellness SaaS to 7-figures with $416K/month.',
  },
  {
    companyName: 'ZenMaid',
    industry: 'saas',
    subIndustry: 'scheduling_software',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 1,
      challenges: ['Niche market', 'Competition', 'Growth'],
      capabilities: ['Development', 'Industry knowledge'],
      marketPosition: 'Unknown',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '6_10',
      revenueGrowth: '20x',
      achievements: ['$120K MRR', '$1.5M ARR', 'Maid service niche leader'],
      newCapabilities: ['Full scheduling suite', 'Team management', 'Customer management'],
      marketPosition: 'Niche leader',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'vertical',
    targetMarket: 'maid_services',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Focused exclusively on maid services', impact: 'Perfect product fit', difficulty: 'moderate' },
      { action: 'Built by founder who ran maid service', impact: 'Deep understanding of needs', difficulty: 'easy' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Building for a market you know intimately creates advantage.',
    sourceUrl: 'https://www.starterstory.com/stories/how-we-grew-120k-mrr-in-2021',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'scheduling', 'vertical', 'niche'],
    matchingKeywords: ['scheduling software', 'maid service', 'saas'],
    confidenceLevel: 'high',
    summary: 'ZenMaid bootstrapped to $120K MRR serving maid services exclusively.',
  },
  {
    companyName: 'TenantCloud',
    industry: 'saas',
    subIndustry: 'property_management',
    location: 'USA',
    startingState: {
      revenue: '500k_1m',
      teamSize: '11_25',
      yearsInBusiness: 5,
      challenges: ['Scaling SaaS', 'Feature development', 'Competition'],
      capabilities: ['Property management software', 'Marketplace'],
      marketPosition: 'Growing platform',
    },
    endingState: {
      revenue: '5m_plus',
      teamSize: '50_plus',
      revenueGrowth: '15x',
      achievements: ['$15M revenue/year', '$1.25M/month', 'Property management leader'],
      newCapabilities: ['Full property suite', 'Marketplace', 'Payment processing'],
      marketPosition: 'Market leader',
    },
    strategyType: 'partnership_expansion',
    expansionType: 'horizontal',
    targetMarket: 'landlords',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Built comprehensive property management', impact: 'All-in-one solution', difficulty: 'hard' },
      { action: 'Added marketplace features', impact: 'Network effects', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 15 },
    lessonsLearned: 'Comprehensive solutions win in fragmented markets.',
    sourceUrl: 'https://www.starterstory.com/stories/we-launched-a-12m-year-property-management-saas-for-landlords-tenants',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'property_management', 'marketplace', 'landlords'],
    matchingKeywords: ['property management', 'landlord', 'saas', 'real estate'],
    confidenceLevel: 'high',
    summary: 'TenantCloud built property management SaaS to $15M/year.',
  },

  // ============================================================================
  // ECOMMERCE & DTC BRANDS
  // ============================================================================
  {
    companyName: 'Bro Glo',
    industry: 'ecommerce',
    subIndustry: 'mens_grooming',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['New category', 'Building brand', 'Marketing'],
      capabilities: ['Product development', 'Social media marketing'],
      marketPosition: 'New entrant',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '6_10',
      revenueGrowth: '60x',
      achievements: ['$300K/month', '6x growth', 'TikTok viral success'],
      newCapabilities: ['Product line expansion', 'Community building'],
      marketPosition: 'Mens self-tan leader',
    },
    strategyType: 'content_led_growth',
    expansionType: 'horizontal',
    targetMarket: 'men',
    timeline: { totalMonths: 30 },
    keyActions: [
      { action: 'Created self-tan for men', impact: 'New category creation', difficulty: 'moderate' },
      { action: 'Leveraged TikTok for viral growth', impact: 'Organic reach at scale', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 60 },
    lessonsLearned: 'Creating new categories for underserved markets can explode.',
    sourceUrl: 'https://www.starterstory.com/stories/bro-glo-d907fb4b-cc97-4d00-9a53-47cad915fea7',
    sourcePlatform: 'starter_story',
    tags: ['ecommerce', 'mens_grooming', 'tiktok', 'dtc'],
    matchingKeywords: ['ecommerce', 'mens grooming', 'self tan', 'dtc'],
    confidenceLevel: 'high',
    summary: 'Bro Glo went viral on TikTok, growing to $300K/month in mens self-tan.',
  },
  {
    companyName: 'LacedUp',
    industry: 'ecommerce',
    subIndustry: 'sneaker_resale',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 1,
      challenges: ['Building inventory', 'Authentication', 'Competition'],
      capabilities: ['Sneaker knowledge', 'Retail experience'],
      marketPosition: 'New store',
    },
    endingState: {
      revenue: '5m_plus',
      teamSize: '26_50',
      revenueGrowth: '50x',
      achievements: ['$1.1M/month revenue', 'Chain of stores', 'High-end sneaker destination'],
      newCapabilities: ['Multiple locations', 'Authentication expertise', 'Consignment model'],
      marketPosition: 'Leading sneaker reseller',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'horizontal',
    targetMarket: 'sneaker_enthusiasts',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Focused on high-end collectibles', impact: 'Premium positioning', difficulty: 'moderate' },
      { action: 'Built chain of retail stores', impact: 'Physical presence and trust', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Physical retail can thrive in high-value collectible markets.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-sneakers-store',
    sourcePlatform: 'starter_story',
    tags: ['retail', 'sneakers', 'resale', 'chain'],
    matchingKeywords: ['sneakers', 'resale', 'retail', 'collectibles'],
    confidenceLevel: 'high',
    summary: 'Two brothers built LacedUp sneaker chain to $1.1M/month revenue.',
  },
  {
    companyName: 'Baloo Living',
    industry: 'ecommerce',
    subIndustry: 'wellness_products',
    location: 'Bali / USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Manufacturing', 'Shipping', 'Competition'],
      capabilities: ['Product design', 'Remote operations'],
      marketPosition: 'Unknown brand',
    },
    endingState: {
      revenue: '5m_plus',
      teamSize: '6_10',
      revenueGrowth: '100x',
      achievements: ['$416K/month revenue', 'Weighted blanket leader', 'Built from Bali'],
      newCapabilities: ['Product line expansion', 'Supply chain mastery'],
      marketPosition: 'Wellness product leader',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'vertical',
    targetMarket: 'wellness_seekers',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built product from Bali', impact: 'Low cost of living, remote freedom', difficulty: 'moderate' },
      { action: 'Focused on quality weighted blankets', impact: 'Premium positioning', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Remote-first ecommerce can scale from anywhere.',
    sourceUrl: 'https://www.starterstory.com/weighted-blankets',
    sourcePlatform: 'starter_story',
    tags: ['ecommerce', 'wellness', 'weighted_blankets', 'remote'],
    matchingKeywords: ['weighted blankets', 'wellness', 'ecommerce'],
    confidenceLevel: 'high',
    summary: 'Elizabeth Grojean built Baloo Living to $416K/month selling weighted blankets from Bali.',
  },
  {
    companyName: 'Braxley Bands',
    industry: 'ecommerce',
    subIndustry: 'accessories',
    location: 'Austin, TX',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['$20 starting capital', 'Building brand', 'Manufacturing'],
      capabilities: ['Product design', 'Hustle'],
      marketPosition: 'Unknown',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '6_10',
      revenueGrowth: '500x',
      achievements: ['$236K/month revenue', 'Started with $20', 'Apple Watch band leader'],
      newCapabilities: ['Product line', 'Manufacturing partnerships'],
      marketPosition: 'Apple Watch accessory brand',
    },
    strategyType: 'content_led_growth',
    expansionType: 'vertical',
    targetMarket: 'apple_users',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Started with only $20', impact: 'Proved lean startup model', difficulty: 'hard' },
      { action: 'Focused on Apple Watch bands', impact: 'Clear niche', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 500 },
    lessonsLearned: 'You can build a major brand with almost no starting capital.',
    sourceUrl: 'https://www.starterstory.com/elastic-apple-watch-bands',
    sourcePlatform: 'starter_story',
    tags: ['ecommerce', 'accessories', 'apple', 'bootstrap'],
    matchingKeywords: ['apple watch', 'bands', 'accessories', 'ecommerce'],
    confidenceLevel: 'high',
    summary: 'Braxley Bands turned $20 into $236K/month Apple Watch band business.',
  },
  {
    companyName: 'Panther RV Products',
    industry: 'ecommerce',
    subIndustry: 'rv_parts',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 2,
      challenges: ['Niche market', 'Inventory', 'Competition with Amazon'],
      capabilities: ['RV knowledge', 'Ecommerce'],
      marketPosition: 'Small player',
    },
    endingState: {
      revenue: '5m_plus',
      teamSize: '11_25',
      revenueGrowth: '50x',
      achievements: ['$400K/month revenue', 'RV parts destination', 'Niche dominance'],
      newCapabilities: ['Wide inventory', 'Fast shipping', 'Customer service'],
      marketPosition: 'Leading RV parts retailer',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'horizontal',
    targetMarket: 'rv_owners',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Specialized in RV parts only', impact: 'Deep inventory and expertise', difficulty: 'moderate' },
      { action: 'Built against Amazon with service', impact: 'Customer loyalty', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Niche ecommerce can beat Amazon with expertise and service.',
    sourceUrl: 'https://www.starterstory.com/start-a-campervan-rv-ecommerce',
    sourcePlatform: 'starter_story',
    tags: ['ecommerce', 'rv', 'parts', 'niche'],
    matchingKeywords: ['rv parts', 'campervan', 'ecommerce'],
    confidenceLevel: 'high',
    summary: 'Panther RV Products built niche RV parts store to $400K/month.',
  },
  {
    companyName: 'Beardbrand',
    industry: 'ecommerce',
    subIndustry: 'mens_grooming',
    location: 'Austin, TX',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['New category', 'Building audience', 'Product development'],
      capabilities: ['Content creation', 'Community building'],
      marketPosition: 'Unknown',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '11_25',
      revenueGrowth: '20x',
      achievements: ['$100K+/month', 'Beard care pioneer', 'YouTube success'],
      newCapabilities: ['Full product line', 'Content empire', 'Community'],
      marketPosition: 'Beard care category leader',
    },
    strategyType: 'content_led_growth',
    expansionType: 'horizontal',
    targetMarket: 'bearded_men',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Built YouTube content first', impact: 'Audience before product', difficulty: 'hard' },
      { action: 'Created beard care category', impact: 'Category ownership', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Content-first approach builds loyal customer base.',
    sourceUrl: 'https://www.starterstory.com/beardbrand',
    sourcePlatform: 'starter_story',
    tags: ['ecommerce', 'mens_grooming', 'content', 'youtube'],
    matchingKeywords: ['beard care', 'mens grooming', 'youtube', 'content'],
    confidenceLevel: 'high',
    summary: 'Eric Bandholz built Beardbrand to $100K+/month pioneering beard care category.',
  },

  // ============================================================================
  // CONSULTING & COACHING
  // ============================================================================
  {
    companyName: 'Consulting Success',
    industry: 'consulting',
    subIndustry: 'consulting_training',
    location: 'Vancouver, Canada',
    startingState: {
      revenue: '100k_250k',
      teamSize: '2_5',
      yearsInBusiness: 5,
      challenges: ['Scaling training', 'Content creation', 'Global reach'],
      capabilities: ['Consulting expertise', 'Training development'],
      marketPosition: 'Growing training company',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '11_25',
      revenueGrowth: '10x',
      achievements: ['$240K/month revenue', 'Global consulting training leader', 'Multiple programs'],
      newCapabilities: ['Online courses', 'Coaching programs', 'Community'],
      marketPosition: 'Consulting training leader',
    },
    strategyType: 'content_led_growth',
    expansionType: 'horizontal',
    targetMarket: 'consultants',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Built training for consultants', impact: 'Niche expertise monetized', difficulty: 'moderate' },
      { action: 'Created multiple programs', impact: 'Recurring revenue from community', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Teaching your expertise scales better than doing the work.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-consultant-training-coaching-business',
    sourcePlatform: 'starter_story',
    tags: ['consulting', 'training', 'coaching', 'courses'],
    matchingKeywords: ['consulting training', 'coaching', 'consultants'],
    confidenceLevel: 'high',
    summary: 'Michael Zipursky built Consulting Success to $240K/month training consultants.',
  },
  {
    companyName: 'Jake & Gino',
    industry: 'consulting',
    subIndustry: 'real_estate_education',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 2,
      challenges: ['Building credibility', 'Content creation', 'Scaling education'],
      capabilities: ['Real estate expertise', 'Teaching ability'],
      marketPosition: 'New educators',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '11_25',
      revenueGrowth: '40x',
      achievements: ['$200K/month revenue', 'Real estate education leader', 'Community of investors'],
      newCapabilities: ['Courses', 'Coaching', 'Community platform'],
      marketPosition: 'Multifamily education leader',
    },
    strategyType: 'content_led_growth',
    expansionType: 'horizontal',
    targetMarket: 'real_estate_investors',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Focused on multifamily education', impact: 'Clear niche', difficulty: 'moderate' },
      { action: 'Built podcast and content engine', impact: 'Organic lead generation', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 40 },
    lessonsLearned: 'Education business can scale faster than actual investing.',
    sourceUrl: 'https://www.starterstory.com/stories/jakeandgino',
    sourcePlatform: 'starter_story',
    tags: ['education', 'real_estate', 'multifamily', 'coaching'],
    matchingKeywords: ['real estate education', 'multifamily', 'coaching'],
    confidenceLevel: 'high',
    summary: 'Jake & Gino built real estate education business to $200K/month.',
  },
  {
    companyName: 'Ecom King Vault',
    industry: 'consulting',
    subIndustry: 'ecommerce_training',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 1,
      challenges: ['Building credibility', 'Content creation', 'Competition'],
      capabilities: ['Dropshipping expertise', 'Teaching'],
      marketPosition: 'Unknown',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '6_10',
      revenueGrowth: '20x',
      achievements: ['$100K/month revenue', 'Dropshipping mentor leader', 'Multiple 6-figure stores'],
      newCapabilities: ['Mentorship programs', 'Community', 'Content'],
      marketPosition: 'Ecommerce training leader',
    },
    strategyType: 'content_led_growth',
    expansionType: 'vertical',
    targetMarket: 'aspiring_entrepreneurs',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built multiple successful dropshipping stores first', impact: 'Credibility through results', difficulty: 'hard' },
      { action: 'Created mentorship program', impact: 'High-ticket recurring revenue', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Teaching what works is more scalable than just doing it.',
    sourceUrl: 'https://www.starterstory.com/dropshipping-mentoring',
    sourcePlatform: 'starter_story',
    tags: ['education', 'dropshipping', 'ecommerce', 'mentoring'],
    matchingKeywords: ['dropshipping', 'ecommerce', 'mentoring', 'training'],
    confidenceLevel: 'high',
    summary: 'Kamil Sattar built Ecom King Vault to $100K/month mentoring dropshippers.',
  },

  // ============================================================================
  // CONTENT & MEDIA
  // ============================================================================
  {
    companyName: 'Making Sense of Cents',
    industry: 'media',
    subIndustry: 'personal_finance_blog',
    location: 'Remote / RV',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 1,
      challenges: ['Building traffic', 'Monetization', 'Consistency'],
      capabilities: ['Writing', 'Finance knowledge'],
      marketPosition: 'Unknown blogger',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: 'solo',
      revenueGrowth: '100x',
      achievements: ['$100K/month revenue', 'Solo blogger', 'RV lifestyle while earning'],
      newCapabilities: ['Affiliate marketing', 'Course creation', 'Sponsorships'],
      marketPosition: 'Top personal finance blog',
    },
    strategyType: 'content_led_growth',
    expansionType: 'vertical',
    targetMarket: 'personal_finance',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Published consistently for years', impact: 'SEO authority built over time', difficulty: 'hard' },
      { action: 'Monetized through affiliates', impact: 'Passive income model', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Consistent blogging compounds into major income over years.',
    sourceUrl: 'https://www.starterstory.com/stories/how-i-started-a-100k-month-blog-about-personal-finance',
    sourcePlatform: 'starter_story',
    tags: ['blog', 'personal_finance', 'affiliate', 'solo'],
    matchingKeywords: ['blog', 'personal finance', 'affiliate marketing'],
    confidenceLevel: 'high',
    summary: 'Michelle Schroeder-Gardner built Making Sense of Cents to $100K/month as solo blogger.',
  },
  {
    companyName: 'Morning Brew',
    industry: 'media',
    subIndustry: 'newsletter',
    location: 'New York, NY',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 1,
      challenges: ['Building subscriber base', 'Monetization', 'Competition'],
      capabilities: ['Content creation', 'Business knowledge'],
      marketPosition: 'Unknown newsletter',
    },
    endingState: {
      revenue: '5m_plus',
      teamSize: '50_plus',
      revenueGrowth: '1000x',
      achievements: ['$4.1M/month before acquisition', 'Sold for $75M', 'Media empire'],
      newCapabilities: ['Multiple newsletters', 'Podcasts', 'Events'],
      marketPosition: 'Major media company',
    },
    strategyType: 'content_led_growth',
    expansionType: 'horizontal',
    targetMarket: 'business_professionals',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Made business news accessible and fun', impact: 'Viral growth', difficulty: 'hard' },
      { action: 'Built referral program', impact: 'Exponential subscriber growth', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'Media companies can scale with right content and distribution.',
    sourceUrl: 'https://www.starterstory.com/ideas/media-company/success-stories',
    sourcePlatform: 'starter_story',
    tags: ['newsletter', 'media', 'business', 'acquisition'],
    matchingKeywords: ['newsletter', 'media', 'business news'],
    confidenceLevel: 'high',
    summary: 'Morning Brew grew to $4.1M/month before $75M acquisition.',
  },
  {
    companyName: 'Contrarian Thinking',
    industry: 'media',
    subIndustry: 'newsletter',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 1,
      challenges: ['Building audience', 'Monetization', 'Differentiation'],
      capabilities: ['Business expertise', 'Writing'],
      marketPosition: 'Unknown',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '6_10',
      revenueGrowth: '60x',
      achievements: ['$3M/year revenue', 'Substack success', 'Business strategy newsletter leader'],
      newCapabilities: ['Paid newsletter', 'Community', 'Events'],
      marketPosition: 'Leading Substack',
    },
    strategyType: 'content_led_growth',
    expansionType: 'vertical',
    targetMarket: 'entrepreneurs',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built unique business strategy content', impact: 'Differentiated voice', difficulty: 'moderate' },
      { action: 'Launched paid Substack', impact: 'Direct monetization', difficulty: 'easy' },
    ],
    outcomes: { revenueMultiplier: 60 },
    lessonsLearned: 'Unique perspective builds loyal paying audience.',
    sourceUrl: 'https://www.starterstory.com/ideas/substack-newsletter/success-stories',
    sourcePlatform: 'starter_story',
    tags: ['newsletter', 'substack', 'business', 'paid'],
    matchingKeywords: ['newsletter', 'substack', 'business strategy'],
    confidenceLevel: 'high',
    summary: 'Contrarian Thinking Substack newsletter grew to $3M/year.',
  },
  {
    companyName: 'Rejoin Media',
    industry: 'media',
    subIndustry: 'web_portfolio',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 2,
      challenges: ['Finding acquisitions', 'Operating multiple sites', 'Growth'],
      capabilities: ['SEO', 'Content marketing'],
      marketPosition: 'Unknown',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '2_5',
      revenueGrowth: '20x',
      achievements: ['$100K/month revenue', 'Portfolio of sites', 'PE model for web properties'],
      newCapabilities: ['Acquisition', 'Operations', 'Growth playbook'],
      marketPosition: 'Web portfolio operator',
    },
    strategyType: 'partnership_expansion',
    expansionType: 'horizontal',
    targetMarket: 'b2c',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built acquisition playbook for websites', impact: 'Scalable growth model', difficulty: 'hard' },
      { action: 'Applied PE model to web properties', impact: 'Portfolio diversification', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Acquiring and growing web properties can build portfolio income.',
    sourceUrl: 'https://www.starterstory.com/stories/how-i-built-a-100k-month-portfolio-of-web-based-businesses',
    sourcePlatform: 'starter_story',
    tags: ['media', 'portfolio', 'acquisition', 'seo'],
    matchingKeywords: ['web portfolio', 'acquisition', 'seo'],
    confidenceLevel: 'high',
    summary: 'Michael Gardon built Rejoin Media to $100K/month through web property acquisitions.',
  },

  // ============================================================================
  // REAL ESTATE & PROPERTY
  // ============================================================================
  {
    companyName: 'T.C. Lewis & Co. Real Estate',
    industry: 'real_estate',
    subIndustry: 'investment',
    location: 'USA',
    startingState: {
      revenue: '100k_250k',
      teamSize: '2_5',
      yearsInBusiness: 3,
      challenges: ['Capital raising', 'Deal sourcing', 'Management'],
      capabilities: ['Real estate expertise', 'Investment analysis'],
      marketPosition: 'Growing investor',
    },
    endingState: {
      revenue: '5m_plus',
      teamSize: '26_50',
      revenueGrowth: '25x',
      achievements: ['$500K/month revenue', 'Real estate empire', 'Multiple properties'],
      newCapabilities: ['Property management', 'Capital raising', 'Development'],
      marketPosition: 'Major real estate investor',
    },
    strategyType: 'partnership_expansion',
    expansionType: 'horizontal',
    targetMarket: 'investors',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Built systematic investment approach', impact: 'Scalable deal flow', difficulty: 'hard' },
      { action: 'Raised capital from investors', impact: 'Larger deals possible', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 25 },
    lessonsLearned: 'Systematic approach to real estate creates scalable business.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-real-state-business',
    sourcePlatform: 'starter_story',
    tags: ['real_estate', 'investment', 'property', 'capital'],
    matchingKeywords: ['real estate', 'investment', 'property management'],
    confidenceLevel: 'high',
    summary: 'Cory Lewis built T.C. Lewis real estate investment to $500K/month.',
  },
  {
    companyName: 'Home Sweet City',
    industry: 'real_estate',
    subIndustry: 'vacation_rental_management',
    location: 'Washington, DC',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 1,
      challenges: ['Building inventory', 'Operations', 'Competition'],
      capabilities: ['Property management', 'Hospitality'],
      marketPosition: 'New manager',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '26_50',
      revenueGrowth: '50x',
      achievements: ['$270K/month revenue', 'Major Airbnb manager', 'Full-service'],
      newCapabilities: ['Full property management', 'Interior design', 'Guest services'],
      marketPosition: 'Leading vacation rental manager',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'vertical',
    targetMarket: 'property_owners',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built full-service vacation rental management', impact: 'Premium positioning', difficulty: 'hard' },
      { action: 'Focused on quality over quantity', impact: 'Higher margins', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Full-service property management commands premium pricing.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-business-managing-vacation-rentals-airbnb',
    sourcePlatform: 'starter_story',
    tags: ['vacation_rentals', 'airbnb', 'property_management'],
    matchingKeywords: ['vacation rental', 'airbnb management', 'property'],
    confidenceLevel: 'high',
    summary: 'Home Sweet City grew vacation rental management to $270K/month in DC.',
  },

  // ============================================================================
  // DESIGN AGENCIES
  // ============================================================================
  {
    companyName: 'Baked Design',
    industry: 'design_agency',
    subIndustry: 'design_subscription',
    location: 'Poland',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['New business model', 'Client acquisition', 'Pricing'],
      capabilities: ['Design', 'Branding'],
      marketPosition: 'Unknown',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '11_25',
      revenueGrowth: '20x',
      achievements: ['$100K MRR in 6 months', 'Design subscription pioneer', 'Rapid scale'],
      newCapabilities: ['Subscription model', 'Process automation'],
      marketPosition: 'Design subscription leader',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'horizontal',
    targetMarket: 'startups',
    timeline: { totalMonths: 6 },
    keyActions: [
      { action: 'Created design subscription model', impact: 'Predictable revenue', difficulty: 'moderate' },
      { action: 'Scaled rapidly with process', impact: 'Fast growth', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Subscription model works for agency services.',
    sourceUrl: 'https://www.starterstory.com/baked-design-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['design', 'subscription', 'agency', 'rapid_growth'],
    matchingKeywords: ['design subscription', 'agency', 'branding'],
    confidenceLevel: 'high',
    summary: 'Alex Szczurek scaled Baked Design to $100K MRR in just 6 months.',
  },
  {
    companyName: 'DesignMe',
    industry: 'design_agency',
    subIndustry: 'ui_ux',
    location: 'Poland',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 1,
      challenges: ['Finding clients', 'Building team', 'Pricing'],
      capabilities: ['UI/UX design', 'Product design'],
      marketPosition: 'Freelancer',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '11_25',
      revenueGrowth: '20x',
      achievements: ['$100K/month', 'Tech startup specialist', 'Premium positioning'],
      newCapabilities: ['Full product design', 'Team operations'],
      marketPosition: 'Tech startup design agency',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'vertical',
    targetMarket: 'tech_startups',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Specialized in tech startup UI/UX', impact: 'Clear positioning', difficulty: 'moderate' },
      { action: 'Built systematic design process', impact: 'Scalable delivery', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Specialization in startup design creates premium positioning.',
    sourceUrl: 'https://starterstory.com/designme-agency-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['design', 'ui_ux', 'startups', 'agency'],
    matchingKeywords: ['ui/ux', 'design agency', 'startups'],
    confidenceLevel: 'high',
    summary: 'Adrian Kuleszo scaled DesignMe to $100K/month serving tech startups.',
  },
  {
    companyName: 'Delesign',
    industry: 'design_agency',
    subIndustry: 'design_subscription',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 1,
      challenges: ['Building team', 'Process', 'Competition'],
      capabilities: ['Design', 'Operations'],
      marketPosition: 'New entrant',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '26_50',
      revenueGrowth: '20x',
      achievements: ['$100K MRR', 'Design subscription at scale', 'Large team'],
      newCapabilities: ['Subscription ops', 'Team management'],
      marketPosition: 'Design subscription leader',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'horizontal',
    targetMarket: 'businesses',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built subscription graphic design service', impact: 'Recurring revenue model', difficulty: 'hard' },
      { action: 'Scaled team systematically', impact: 'Maintained quality at scale', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Design subscription can scale with right team and process.',
    sourceUrl: 'https://www.starterstory.com/stories/our-company-helps-entrepreneurs-utilize-delegation-for-their-design-972k-year',
    sourcePlatform: 'starter_story',
    tags: ['design', 'subscription', 'graphic_design'],
    matchingKeywords: ['graphic design', 'subscription', 'agency'],
    confidenceLevel: 'high',
    summary: 'Shaival Mehta scaled Delesign to nearly $100K MRR with design subscription.',
  },

  // ============================================================================
  // FREELANCE & PLATFORMS
  // ============================================================================
  {
    companyName: 'Browserless',
    industry: 'saas',
    subIndustry: 'developer_tools',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 1,
      challenges: ['Technical complexity', 'Finding market', 'Scaling'],
      capabilities: ['Development', 'Browser automation'],
      marketPosition: 'Unknown',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '2_5',
      revenueGrowth: '10x',
      achievements: ['$50K/month revenue', 'Developer tool success', 'Customer-driven growth'],
      newCapabilities: ['Cloud infrastructure', 'Enterprise features'],
      marketPosition: 'Browser automation leader',
    },
    strategyType: 'content_led_growth',
    expansionType: 'vertical',
    targetMarket: 'developers',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built tool developers actually needed', impact: 'Strong product-market fit', difficulty: 'hard' },
      { action: 'Talked to customers constantly', impact: 'Product improvements', difficulty: 'easy' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Talking to customers is the best growth strategy.',
    sourceUrl: 'https://www.starterstory.com/stories/how-we-increased-revenue-to-50k-month-since-last-year',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'developer_tools', 'automation', 'bootstrapped'],
    matchingKeywords: ['browser automation', 'developer tools', 'saas'],
    confidenceLevel: 'high',
    summary: 'Joel Griffith built Browserless to $50K/month by talking to customers.',
  },
  {
    companyName: 'Flexiple',
    industry: 'marketplace',
    subIndustry: 'freelance_platform',
    location: 'India',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 1,
      challenges: ['Two-sided marketplace', 'Quality control', 'Trust'],
      capabilities: ['Vetting', 'Operations'],
      marketPosition: 'New platform',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '11_25',
      revenueGrowth: '20x',
      achievements: ['$80-100K/month gross revenue', 'Quality freelancer network', 'Enterprise clients'],
      newCapabilities: ['Vetting process', 'Client matching', 'Project management'],
      marketPosition: 'Quality freelancer platform',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'horizontal',
    targetMarket: 'tech_companies',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built quality-focused freelancer vetting', impact: 'Premium positioning', difficulty: 'hard' },
      { action: 'Focused on developers and designers', impact: 'Clear niche', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Quality over quantity wins in freelancer marketplaces.',
    sourceUrl: 'https://www.starterstory.com/connecting-freelance-developers-and-designers-with-companies',
    sourcePlatform: 'starter_story',
    tags: ['marketplace', 'freelance', 'developers', 'designers'],
    matchingKeywords: ['freelance', 'developers', 'designers', 'platform'],
    confidenceLevel: 'high',
    summary: 'Suvansh Bansal built Flexiple freelancer platform to $80-100K/month.',
  },
  {
    companyName: 'Materialize',
    industry: 'services',
    subIndustry: 'software_agency',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 1,
      challenges: ['Self-taught developer', 'Finding clients', 'Building team'],
      capabilities: ['Software development', 'Self-taught skills'],
      marketPosition: 'Freelancer',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '11_25',
      revenueGrowth: '25x',
      achievements: ['$125K/month revenue', 'Self-taught to agency owner', 'Development studio'],
      newCapabilities: ['Full development team', 'Project management'],
      marketPosition: 'Software development studio',
    },
    strategyType: 'partnership_expansion',
    expansionType: 'vertical',
    targetMarket: 'startups',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Self-taught development skills', impact: 'Zero cost to start', difficulty: 'hard' },
      { action: 'Built agency from freelance base', impact: 'Scalable model', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 25 },
    lessonsLearned: 'Self-taught developers can build successful agencies.',
    sourceUrl: 'https://www.starterstory.com/stories/materialize',
    sourcePlatform: 'starter_story',
    tags: ['agency', 'software', 'self_taught', 'development'],
    matchingKeywords: ['software agency', 'development', 'self-taught'],
    confidenceLevel: 'high',
    summary: 'Alex Nordlinger self-taught development and built Materialize to $125K/month.',
  },

  // ============================================================================
  // FOOD & HOSPITALITY
  // ============================================================================
  {
    companyName: 'Roll Up Food Truck',
    industry: 'food_service',
    subIndustry: 'food_truck',
    location: 'Colorado',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Startup costs', 'Location finding', 'Regulations'],
      capabilities: ['Cooking', 'Operations'],
      marketPosition: 'New truck',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '6_10',
      revenueGrowth: '10x',
      achievements: ['$50K/month revenue', 'Popular food truck', 'Multiple events'],
      newCapabilities: ['Catering', 'Events', 'Multiple trucks'],
      marketPosition: 'Popular Colorado food truck',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'horizontal',
    targetMarket: 'foodies',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Started food truck with signature menu', impact: 'Built following', difficulty: 'hard' },
      { action: 'Expanded to events and catering', impact: 'Multiple revenue streams', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Food trucks can scale through events and catering.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-food-truck-in-colorado',
    sourcePlatform: 'starter_story',
    tags: ['food_truck', 'food_service', 'events', 'catering'],
    matchingKeywords: ['food truck', 'catering', 'events'],
    confidenceLevel: 'high',
    summary: 'Bryce Dillingham built Roll Up Food Truck to $50K/month in Colorado.',
  },

  // ============================================================================
  // PRODUCTIZED SERVICES
  // ============================================================================
  {
    companyName: 'Content Allies',
    industry: 'services',
    subIndustry: 'podcast_production',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 1,
      challenges: ['Service productization', 'Scaling', 'Pricing'],
      capabilities: ['Podcast production', 'Marketing'],
      marketPosition: 'Unknown',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '6_10',
      revenueGrowth: '15x',
      achievements: ['$75K MRR', 'Productized podcast service', 'B2B focus'],
      newCapabilities: ['Full production', 'Distribution', 'Repurposing'],
      marketPosition: 'B2B podcast production leader',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'vertical',
    targetMarket: 'b2b_companies',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Productized podcast production', impact: 'Scalable pricing', difficulty: 'moderate' },
      { action: 'Focused on B2B podcasts', impact: 'Higher budgets, recurring work', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 15 },
    lessonsLearned: 'Productized services scale better than custom work.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-podcast-production-services-business',
    sourcePlatform: 'starter_story',
    tags: ['podcast', 'production', 'productized', 'b2b'],
    matchingKeywords: ['podcast production', 'productized service', 'b2b'],
    confidenceLevel: 'high',
    summary: 'Jake Jorgovan built Content Allies podcast production to $75K MRR.',
  },
  {
    companyName: 'Byldd',
    industry: 'services',
    subIndustry: 'mvp_development',
    location: 'India',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 1,
      challenges: ['Finding clients', 'Pricing', 'Scaling'],
      capabilities: ['Development', 'Product strategy'],
      marketPosition: 'Unknown',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '11_25',
      revenueGrowth: '10x',
      achievements: ['$50K/month', '$600K ARR', 'MVP specialist'],
      newCapabilities: ['Full MVP development', 'Product strategy'],
      marketPosition: 'MVP development leader',
    },
    strategyType: 'vertical_specialization',
    expansionType: 'vertical',
    targetMarket: 'non_technical_founders',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Focused on MVPs for non-technical founders', impact: 'Clear positioning', difficulty: 'moderate' },
      { action: 'Built productized packages', impact: 'Predictable pricing', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Serving non-technical founders is a large market.',
    sourceUrl: 'https://www.starterstory.com/stories/byldd',
    sourcePlatform: 'starter_story',
    tags: ['development', 'mvp', 'productized', 'startups'],
    matchingKeywords: ['mvp development', 'non-technical founders', 'startups'],
    confidenceLevel: 'high',
    summary: 'Ayush Singhvi built Byldd MVP development to $50K/month serving non-technical founders.',
  },
];

export async function seedCaseStudiesBatch2() {
  console.log('Seeding case studies batch 2...');
  console.log(`Total case studies to seed: ${caseStudyBatch2.length}`);

  let successCount = 0;
  let errorCount = 0;

  for (const study of caseStudyBatch2) {
    try {
      await db.insert(caseStudies).values(study as unknown as typeof caseStudies.$inferInsert).onConflictDoNothing();
      console.log(`✓ Seeded: ${study.companyName}`);
      successCount++;
    } catch (error) {
      console.error(`✗ Error seeding ${study.companyName}:`, error);
      errorCount++;
    }
  }

  console.log(`\nBatch 2 seeding complete!`);
  console.log(`✓ Successfully seeded: ${successCount}`);
  console.log(`✗ Errors: ${errorCount}`);
}

// Run if called directly
if (require.main === module) {
  seedCaseStudiesBatch2()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error(err);
      process.exit(1);
    });
}
