import { db } from '../../lib/db';
import { caseStudies } from '../schema';

type CaseStudyInsert = typeof caseStudies.$inferInsert;

const batch14 = [
  // MANUFACTURING & PRODUCT
  {
    companyName: 'Six Atomic',
    industry: 'manufacturing',
    subIndustry: 'fashion_tech',
    location: 'Singapore',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Manual clothing grading', 'Fashion industry inefficiency', 'Time-consuming sizing'],
      capabilities: ['AI development', 'Fashion industry knowledge', 'Automation expertise'],
      marketPosition: 'Early-stage startup',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '6_20',
      revenueGrowth: '$40K/month',
      achievements: ['$40K/month', 'AI grading in seconds', 'Fashion automation leader'],
      newCapabilities: ['Real-time fashion', 'On-demand manufacturing', 'AI sizing'],
      marketPosition: 'Fashion tech innovator',
    },
    strategyType: 'technology_innovation',
    expansionType: 'product',
    targetMarket: 'fashion_brands',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Built AI tool that grades clothing designs to any size in seconds', impact: 'Revolutionary speed', difficulty: 'hard' },
      { action: 'Developed Synthesis, Inference, and Envision products', impact: 'Product suite', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 40 },
    lessonsLearned: 'AI can transform traditional industries like fashion manufacturing.',
    sourceUrl: 'https://www.starterstory.com/stories/six-atomic',
    sourcePlatform: 'starter_story',
    tags: ['manufacturing', 'ai', 'fashion', 'automation'],
    matchingKeywords: ['six atomic', 'fashion tech', 'ai manufacturing'],
    confidenceLevel: 'high',
    summary: 'Built AI tool for fashion manufacturing reaching $40K/month.',
  },
  {
    companyName: 'Leze The Label',
    industry: 'manufacturing',
    subIndustry: 'sustainable_fashion',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Sustainable materials sourcing', 'Women workwear gap', 'Recycled fabric manufacturing'],
      capabilities: ['Fashion design', 'Sustainability focus', 'Brand building'],
      marketPosition: 'New entrant',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '6_20',
      revenueGrowth: '$45K/month',
      achievements: ['$45K/month', 'Recycled materials leader', 'Women workwear niche'],
      newCapabilities: ['Sustainable manufacturing', 'DTC brand', 'Workwear design'],
      marketPosition: 'Sustainable workwear leader',
    },
    strategyType: 'niche_focus',
    expansionType: 'product',
    targetMarket: 'professional_women',
    timeline: { totalMonths: 30 },
    keyActions: [
      { action: 'Created women workwear from recycled materials', impact: 'Unique positioning', difficulty: 'medium' },
      { action: 'Built sustainable supply chain', impact: 'Brand differentiation', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 45 },
    lessonsLearned: 'Sustainability can be a key differentiator in fashion.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-womens-workwear-brand',
    sourcePlatform: 'starter_story',
    tags: ['manufacturing', 'sustainable', 'fashion', 'women'],
    matchingKeywords: ['leze label', 'sustainable fashion', 'workwear'],
    confidenceLevel: 'high',
    summary: 'Built sustainable women workwear brand reaching $45K/month.',
  },
  {
    companyName: 'Capo',
    industry: 'manufacturing',
    subIndustry: 'streetwear',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Minimal starting capital (£250)', 'Crowded streetwear market', 'Brand building'],
      capabilities: ['Design skills', 'Brand vision', 'Social media marketing'],
      marketPosition: 'Unknown brand',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '21_50',
      revenueGrowth: '$500K/month ($15M total)',
      achievements: ['$500K/month', 'From £250 to £15M', 'Major streetwear brand'],
      newCapabilities: ['Global distribution', 'Brand community', 'Premium positioning'],
      marketPosition: 'Leading UK streetwear brand',
    },
    strategyType: 'brand_building',
    expansionType: 'product',
    targetMarket: 'streetwear_enthusiasts',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Started clothing brand with just £250', impact: 'Bootstrapped success', difficulty: 'hard' },
      { action: 'Built strong brand community and identity', impact: 'Brand loyalty', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 60000 },
    lessonsLearned: 'Brand building and community can overcome minimal starting capital.',
    sourceUrl: 'https://www.starterstory.com/capo-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['manufacturing', 'streetwear', 'fashion', 'bootstrapped'],
    matchingKeywords: ['capo', 'streetwear', 'dan wilkins'],
    confidenceLevel: 'high',
    summary: 'Grew clothing brand from £250 to £15M through brand building.',
  },
  {
    companyName: 'Buckle Me Baby Coats',
    industry: 'manufacturing',
    subIndustry: 'childrens_apparel',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 1,
      challenges: ['Child safety problem', 'Product development', 'Market education'],
      capabilities: ['Product innovation', 'Problem solving', 'Parenting insight'],
      marketPosition: 'New product category',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '6_20',
      revenueGrowth: '1100% in 3 years',
      achievements: ['Shark Tank deal', '1100% revenue growth', 'Safety innovation leader'],
      newCapabilities: ['National retail', 'TV exposure', 'Product line expansion'],
      marketPosition: 'Category creator',
    },
    strategyType: 'product_innovation',
    expansionType: 'product',
    targetMarket: 'parents',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Landed deal on Shark Tank', impact: 'National exposure', difficulty: 'hard' },
      { action: 'Created car seat safe coats for children', impact: 'Safety innovation', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 12 },
    lessonsLearned: 'Solving a real safety problem creates a defensible niche.',
    sourceUrl: 'https://www.starterstory.com/stories/buckle-me-baby-coats-341686c1-7000-4466-b1d1-6b338a1d4f2a',
    sourcePlatform: 'starter_story',
    tags: ['manufacturing', 'childrens', 'safety', 'shark_tank'],
    matchingKeywords: ['buckle me baby', 'car seat coats', 'shark tank'],
    confidenceLevel: 'high',
    summary: 'Shark Tank deal led to 1100% revenue growth for child safety coats.',
  },
  {
    companyName: 'Project Repat',
    industry: 'manufacturing',
    subIndustry: 'upcycling',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Unique product category', 'Manufacturing process', 'Customer education'],
      capabilities: ['Creative product idea', 'Sustainability focus', 'Emotional product'],
      marketPosition: 'New market creator',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$10M+/year',
      achievements: ['$10M+ business', 'Sentimental product leader', 'Upcycling pioneer'],
      newCapabilities: ['Scale manufacturing', 'National brand', 'Gift market'],
      marketPosition: 'T-shirt quilt category leader',
    },
    strategyType: 'category_creation',
    expansionType: 'product',
    targetMarket: 'sentimental_consumers',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Created business making quilts from old t-shirts', impact: 'New category', difficulty: 'medium' },
      { action: 'Scaled sentimental product manufacturing', impact: 'Operations mastery', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Sentimental products with emotional value command premium prices.',
    sourceUrl: 'https://www.starterstory.com/stories/project-repat',
    sourcePlatform: 'starter_story',
    tags: ['manufacturing', 'upcycling', 'sentimental', 'quilts'],
    matchingKeywords: ['project repat', 't-shirt quilts', 'upcycling'],
    confidenceLevel: 'high',
    summary: 'Built $10M+ business making quilts from old t-shirts.',
  },

  // AGRICULTURE & FARMING
  {
    companyName: 'AeroFarms',
    industry: 'agriculture',
    subIndustry: 'vertical_farming',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Capital intensive', 'Technology development', 'Agriculture disruption'],
      capabilities: ['AgTech innovation', 'Vertical farming expertise', 'Sustainability focus'],
      marketPosition: 'Vertical farming pioneer',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '200_plus',
      revenueGrowth: 'Major AgTech company',
      achievements: ['Vertical farming leader', 'Urban agriculture pioneer', 'VC-backed scale'],
      newCapabilities: ['Indoor farming technology', 'Year-round production', 'Urban farming'],
      marketPosition: 'Industry leader',
    },
    strategyType: 'technology_innovation',
    expansionType: 'market',
    targetMarket: 'food_retailers',
    timeline: { totalMonths: 120 },
    keyActions: [
      { action: 'Pioneered commercial vertical farming technology', impact: 'Industry creation', difficulty: 'hard' },
      { action: 'Built urban farming infrastructure', impact: 'Sustainable agriculture', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Technology can revolutionize traditional agriculture.',
    sourceUrl: 'https://www.starterstory.com/david-rosenberg',
    sourcePlatform: 'starter_story',
    tags: ['agriculture', 'vertical_farming', 'agtech', 'sustainability'],
    matchingKeywords: ['aerofarms', 'vertical farming', 'david rosenberg'],
    confidenceLevel: 'high',
    summary: 'Pioneered commercial vertical farming technology.',
  },
  {
    companyName: 'PrecisionHawk (Aerial Agriculture)',
    industry: 'agriculture',
    subIndustry: 'agtech',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Drone regulations', 'Agriculture adoption', 'Data processing'],
      capabilities: ['Drone technology', 'Data analytics', 'Agriculture expertise'],
      marketPosition: 'AgTech startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$1M/month',
      achievements: ['$1M/month', 'Agricultural drone leader', 'Data platform'],
      newCapabilities: ['Aerial imagery', 'Crop analytics', 'Precision agriculture'],
      marketPosition: 'AgTech leader',
    },
    strategyType: 'technology_innovation',
    expansionType: 'product',
    targetMarket: 'farmers',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built aerial imagery platform for agriculture', impact: 'Precision farming', difficulty: 'hard' },
      { action: 'Scaled drone data analytics for crops', impact: 'Data-driven farming', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 120 },
    lessonsLearned: 'Drone technology can transform agricultural decision-making.',
    sourceUrl: 'https://www.starterstory.com/aerial-imagery-agriculture',
    sourcePlatform: 'starter_story',
    tags: ['agriculture', 'drones', 'agtech', 'data'],
    matchingKeywords: ['aerial imagery', 'agriculture drones', 'precision farming'],
    confidenceLevel: 'high',
    summary: 'Built $1M/month aerial imagery platform for agriculture.',
  },
  {
    companyName: "Drake's Organic Spirits",
    industry: 'agriculture',
    subIndustry: 'organic_spirits',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Farm-to-bottle production', 'Organic certification', 'Spirits competition'],
      capabilities: ['Farming experience', 'Organic production', 'Brand building'],
      marketPosition: 'Farm-based startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '21_50',
      revenueGrowth: '$10.8M/year',
      achievements: ['$10.8M/year', 'Organic spirits leader', 'Farm-to-bottle brand'],
      newCapabilities: ['Organic distilling', 'National distribution', 'Premium positioning'],
      marketPosition: 'Organic spirits leader',
    },
    strategyType: 'vertical_integration',
    expansionType: 'product',
    targetMarket: 'health_conscious_drinkers',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Transitioned from farming to organic spirits production', impact: 'Value-add agriculture', difficulty: 'hard' },
      { action: 'Built farm-to-bottle brand story', impact: 'Brand differentiation', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 108 },
    lessonsLearned: 'Vertical integration from farm to finished product creates premium positioning.',
    sourceUrl: 'https://www.starterstory.com/stories/from-farming-to-creating-a-10-8m-year-organic-spirits-brand',
    sourcePlatform: 'starter_story',
    tags: ['agriculture', 'spirits', 'organic', 'farm_to_bottle'],
    matchingKeywords: ['drakes organic', 'organic spirits', 'farm to bottle'],
    confidenceLevel: 'high',
    summary: 'Farming to $10.8M/year organic spirits brand.',
  },

  // CONSTRUCTION & HOME SERVICES
  {
    companyName: 'Carolina Exteriors',
    industry: 'construction',
    subIndustry: 'exterior_remodeling',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Starting capital ($3.5K)', 'Local competition', 'Trust building'],
      capabilities: ['Construction skills', 'Customer service', 'Local market knowledge'],
      marketPosition: 'Local contractor',
    },
    endingState: {
      revenue: '5m_10m',
      teamSize: '51_200',
      revenueGrowth: '$9M/year',
      achievements: ['$9M/year', 'From $3.5K start', 'Regional leader'],
      newCapabilities: ['Full exterior services', 'Team management', 'Regional operations'],
      marketPosition: 'Regional remodeling leader',
    },
    strategyType: 'service_excellence',
    expansionType: 'geographic',
    targetMarket: 'homeowners',
    timeline: { totalMonths: 180 },
    keyActions: [
      { action: 'Started exterior remodeling with $3.5K', impact: 'Bootstrapped growth', difficulty: 'hard' },
      { action: 'Scaled to regional operations', impact: 'Market leadership', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 2571 },
    lessonsLearned: 'Service quality and reputation drive construction business growth.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-exterior-remodelling-company',
    sourcePlatform: 'starter_story',
    tags: ['construction', 'remodeling', 'home_services', 'bootstrapped'],
    matchingKeywords: ['carolina exteriors', 'exterior remodeling', 'construction'],
    confidenceLevel: 'high',
    summary: 'Grew exterior remodeling from $3.5K to $9M/year.',
  },
  {
    companyName: 'Contractor Foreman',
    industry: 'construction',
    subIndustry: 'construction_software',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Construction tech adoption', 'Software development', 'Industry trust'],
      capabilities: ['Construction experience', 'Software development', 'Industry pain points'],
      marketPosition: 'New SaaS entrant',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '6_20',
      revenueGrowth: '$60K/month',
      achievements: ['$60K/month', 'Construction CRM leader', 'Industry-specific solution'],
      newCapabilities: ['Full CRM platform', 'Project management', 'Industry expertise'],
      marketPosition: 'Construction software leader',
    },
    strategyType: 'vertical_saas',
    expansionType: 'product',
    targetMarket: 'construction_companies',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built CRM specifically for construction companies', impact: 'Vertical focus', difficulty: 'hard' },
      { action: 'Solved industry-specific pain points', impact: 'Product-market fit', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 72 },
    lessonsLearned: 'Vertical SaaS for specific industries can outperform generic solutions.',
    sourceUrl: 'https://www.starterstory.com/crm-for-construction-companies',
    sourcePlatform: 'starter_story',
    tags: ['construction', 'saas', 'crm', 'vertical_software'],
    matchingKeywords: ['contractor foreman', 'construction crm', 'construction software'],
    confidenceLevel: 'high',
    summary: 'Built $60K/month CRM specifically for construction companies.',
  },

  // CLEANING SERVICES
  {
    companyName: 'CleanLots',
    industry: 'services',
    subIndustry: 'commercial_cleaning',
    location: 'Canada',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Niche service education', 'B2B sales', 'Seasonal variations'],
      capabilities: ['Service delivery', 'Commercial relationships', 'Niche expertise'],
      marketPosition: 'Niche service provider',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '6_20',
      revenueGrowth: '$60K/month',
      achievements: ['$60K/month', 'Parking lot cleaning leader', 'Recurring revenue model'],
      newCapabilities: ['Commercial contracts', 'Route optimization', 'Franchise model'],
      marketPosition: 'Niche market leader',
    },
    strategyType: 'niche_focus',
    expansionType: 'service',
    targetMarket: 'commercial_properties',
    timeline: { totalMonths: 240 },
    keyActions: [
      { action: 'Focused on niche commercial litter cleaning', impact: 'Market specialization', difficulty: 'medium' },
      { action: 'Built recurring B2B contracts', impact: 'Stable revenue', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 60 },
    lessonsLearned: 'Niche services can build profitable recurring revenue businesses.',
    sourceUrl: 'https://www.starterstory.com/stories/cleanlots-com-d4ef90a8-d3a5-4952-b3dd-2731bbaa4680',
    sourcePlatform: 'starter_story',
    tags: ['services', 'cleaning', 'commercial', 'niche'],
    matchingKeywords: ['cleanlots', 'parking lot cleaning', 'commercial cleaning'],
    confidenceLevel: 'high',
    summary: 'Built $60K/month niche commercial cleaning service.',
  },
  {
    companyName: 'MaidThis Franchise',
    industry: 'services',
    subIndustry: 'residential_cleaning',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Airbnb market timing', 'Service quality control', 'Franchise scaling'],
      capabilities: ['Cleaning operations', 'Airbnb market knowledge', 'Technology integration'],
      marketPosition: 'Airbnb-focused cleaner',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '51_200',
      revenueGrowth: '$100K+/month',
      achievements: ['$100K+/month', 'Airbnb cleaning leader', 'Franchise network'],
      newCapabilities: ['Franchise operations', 'Tech-enabled cleaning', 'National coverage'],
      marketPosition: 'Airbnb cleaning leader',
    },
    strategyType: 'market_timing',
    expansionType: 'franchise',
    targetMarket: 'airbnb_hosts',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built cleaning service targeting Airbnb hosts', impact: 'Market positioning', difficulty: 'medium' },
      { action: 'Scaled through franchise model', impact: 'Rapid expansion', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 120 },
    lessonsLearned: 'Timing with platform growth (Airbnb) accelerates service business success.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-cleaning-service-for-airbnb',
    sourcePlatform: 'starter_story',
    tags: ['services', 'cleaning', 'airbnb', 'franchise'],
    matchingKeywords: ['maidthis', 'airbnb cleaning', 'vacation rental cleaning'],
    confidenceLevel: 'high',
    summary: 'Built $100K+/month Airbnb cleaning franchise.',
  },

  // AUTOMOTIVE SERVICES
  {
    companyName: 'GetSpiffy',
    industry: 'automotive',
    subIndustry: 'mobile_car_care',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Mobile service logistics', 'Technology platform', 'Fleet management'],
      capabilities: ['Tech background', 'Service innovation', 'Operations expertise'],
      marketPosition: 'Mobile car care startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '200_plus',
      revenueGrowth: '$50M/year',
      achievements: ['$50M/year', 'Mobile car care leader', 'Tech-enabled service'],
      newCapabilities: ['National operations', 'Fleet partnerships', 'Tech platform'],
      marketPosition: 'Industry leader',
    },
    strategyType: 'technology_innovation',
    expansionType: 'geographic',
    targetMarket: 'fleet_and_consumers',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Built tech-enabled mobile car care platform', impact: 'Service innovation', difficulty: 'hard' },
      { action: 'Scaled nationally with fleet partnerships', impact: 'B2B growth', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 500 },
    lessonsLearned: 'Technology can transform traditional service businesses like car care.',
    sourceUrl: 'https://www.starterstory.com/stories/getspiffy',
    sourcePlatform: 'starter_story',
    tags: ['automotive', 'mobile_service', 'technology', 'fleet'],
    matchingKeywords: ['getspiffy', 'mobile car wash', 'car care service'],
    confidenceLevel: 'high',
    summary: 'Built $50M/year mobile car care service.',
  },
  {
    companyName: 'Belk Mobile Detailing',
    industry: 'automotive',
    subIndustry: 'auto_detailing',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Mobile equipment investment', 'Customer acquisition', 'Service consistency'],
      capabilities: ['Detailing skills', 'Customer service', 'Mobile operations'],
      marketPosition: 'Local mobile detailer',
    },
    endingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      revenueGrowth: '$96K/year',
      achievements: ['$96K/year', 'Mobile flexibility', 'Low overhead model'],
      newCapabilities: ['Mobile operations', 'Local reputation', 'Repeat customers'],
      marketPosition: 'Established local business',
    },
    strategyType: 'lifestyle_business',
    expansionType: 'service',
    targetMarket: 'local_car_owners',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Started mobile auto detailing business', impact: 'Low overhead model', difficulty: 'easy' },
      { action: 'Built local customer base through quality', impact: 'Word of mouth growth', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Mobile services can build profitable lifestyle businesses.',
    sourceUrl: 'https://www.starterstory.com/stories/belk-mobile-detailing',
    sourcePlatform: 'starter_story',
    tags: ['automotive', 'detailing', 'mobile', 'lifestyle'],
    matchingKeywords: ['belk mobile', 'auto detailing', 'mobile detailing'],
    confidenceLevel: 'high',
    summary: 'Built $96K/year mobile auto detailing business.',
  },
  {
    companyName: "Wolf's Auto Detailing",
    industry: 'automotive',
    subIndustry: 'auto_detailing',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Part-time operation', 'Equipment investment', 'Customer building'],
      capabilities: ['Detailing passion', 'Customer focus', 'Flexible schedule'],
      marketPosition: 'Part-time detailer',
    },
    endingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      revenueGrowth: '$36K/year working 3 days/week',
      achievements: ['$36K/year part-time', 'Work-life balance', '3-day work week'],
      newCapabilities: ['Efficient operations', 'Premium pricing', 'Flexible lifestyle'],
      marketPosition: 'Lifestyle business owner',
    },
    strategyType: 'lifestyle_business',
    expansionType: 'service',
    targetMarket: 'local_car_owners',
    timeline: { totalMonths: 18 },
    keyActions: [
      { action: 'Built auto detailing business working only 3 days/week', impact: 'Lifestyle freedom', difficulty: 'easy' },
      { action: 'Focused on premium service and pricing', impact: 'Higher margins', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 4 },
    lessonsLearned: 'Lifestyle businesses can provide income and freedom.',
    sourceUrl: 'https://www.starterstory.com/stories/wolfs-auto-detailing',
    sourcePlatform: 'starter_story',
    tags: ['automotive', 'detailing', 'lifestyle', 'part_time'],
    matchingKeywords: ['wolfs auto', 'auto detailing', 'lifestyle business'],
    confidenceLevel: 'high',
    summary: 'Built $36K/year detailing business working 3 days/week.',
  },
  {
    companyName: 'Fresh Look Mobile Auto Detailing',
    industry: 'automotive',
    subIndustry: 'auto_detailing',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 5,
      challenges: ['Tech industry burnout', 'Career change', 'Starting over'],
      capabilities: ['Tech background', 'Customer service', 'Business acumen'],
      marketPosition: 'Career changer',
    },
    endingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      revenueGrowth: 'Successful lifestyle business',
      achievements: ['Left tech successfully', 'Built passion business', 'Work-life balance'],
      newCapabilities: ['Detailing expertise', 'Local business', 'Hobby monetization'],
      marketPosition: 'Established local business',
    },
    strategyType: 'career_pivot',
    expansionType: 'service',
    targetMarket: 'local_car_owners',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Left tech career to pursue passion for car detailing', impact: 'Career freedom', difficulty: 'hard' },
      { action: 'Built local mobile detailing business', impact: 'Passion to profit', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 5 },
    lessonsLearned: 'Hobby-based businesses can provide fulfillment and income.',
    sourceUrl: 'https://www.starterstory.com/stories/i-left-tech-built-my-own-car-detailing-business-my-hobby',
    sourcePlatform: 'starter_story',
    tags: ['automotive', 'detailing', 'career_change', 'passion'],
    matchingKeywords: ['fresh look detailing', 'tech to detailing', 'hobby business'],
    confidenceLevel: 'high',
    summary: 'Left tech to build car detailing business from hobby.',
  },

  // EVENTS & PHOTOGRAPHY
  {
    companyName: 'Photo Booth International',
    industry: 'events',
    subIndustry: 'photo_booth',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Product development', 'Market education', 'Competition'],
      capabilities: ['Product design', 'Sales skills', 'Event industry knowledge'],
      marketPosition: 'Photo booth startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$18M business',
      achievements: ['$18M business', 'Photo booth industry leader', 'B2B and B2C success'],
      newCapabilities: ['Product manufacturing', 'Global distribution', 'Industry leadership'],
      marketPosition: 'Industry leader',
    },
    strategyType: 'product_leadership',
    expansionType: 'product',
    targetMarket: 'event_businesses',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Built photo booth manufacturing and sales business', impact: 'Industry creation', difficulty: 'hard' },
      { action: 'Scaled to $18M through B2B photo booth sales', impact: 'Market dominance', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 180 },
    lessonsLearned: 'Creating an industry category can lead to market leadership.',
    sourceUrl: 'https://www.starterstory.com/stories/photo-booth-international',
    sourcePlatform: 'starter_story',
    tags: ['events', 'photo_booth', 'manufacturing', 'b2b'],
    matchingKeywords: ['photo booth international', 'event equipment', 'photo booth business'],
    confidenceLevel: 'high',
    summary: 'Built $18M business selling photo booths.',
  },
  {
    companyName: 'Briofive',
    industry: 'photography',
    subIndustry: 'personal_branding',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Niche positioning', 'Client education', 'Premium pricing'],
      capabilities: ['Photography skills', 'Personal branding knowledge', 'Marketing expertise'],
      marketPosition: 'Niche photographer',
    },
    endingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      revenueGrowth: 'Premium personal branding business',
      achievements: ['Personal branding niche', 'Premium clients', 'Thought leadership'],
      newCapabilities: ['Personal brand photography', 'Business coaching', 'Premium positioning'],
      marketPosition: 'Personal branding specialist',
    },
    strategyType: 'niche_focus',
    expansionType: 'service',
    targetMarket: 'entrepreneurs',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Specialized in personal branding photography', impact: 'Niche positioning', difficulty: 'medium' },
      { action: 'Built premium positioning for entrepreneurs', impact: 'Higher prices', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 5 },
    lessonsLearned: 'Niche specialization in photography commands premium prices.',
    sourceUrl: 'https://www.starterstory.com/stories/briofive',
    sourcePlatform: 'starter_story',
    tags: ['photography', 'personal_branding', 'niche', 'premium'],
    matchingKeywords: ['briofive', 'personal branding photography', 'entrepreneur photography'],
    confidenceLevel: 'high',
    summary: 'Built personal branding photography business.',
  },

  // AI & TECHNOLOGY
  {
    companyName: 'Lutra AI',
    industry: 'technology',
    subIndustry: 'ai_automation',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['AI market competition', 'Product differentiation', 'Fundraising'],
      capabilities: ['AI expertise', 'Technical team', 'Product vision'],
      marketPosition: 'AI startup',
    },
    endingState: {
      revenue: 'under_100k',
      teamSize: '6_20',
      revenueGrowth: '$3.8M seed funding',
      achievements: ['$3.8M seed funding', 'Rapid traction', 'AI automation leader'],
      newCapabilities: ['AI automation platform', 'Enterprise sales', 'Funded growth'],
      marketPosition: 'Funded AI startup',
    },
    strategyType: 'venture_backed',
    expansionType: 'product',
    targetMarket: 'enterprises',
    timeline: { totalMonths: 12 },
    keyActions: [
      { action: 'Built AI automation platform', impact: 'Product-market fit', difficulty: 'hard' },
      { action: 'Raised $3.8M seed in months', impact: 'Rapid fundraising', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 38 },
    lessonsLearned: 'Strong AI products can attract rapid venture funding.',
    sourceUrl: 'https://www.starterstory.com/lutra-ai-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['technology', 'ai', 'automation', 'venture'],
    matchingKeywords: ['lutra ai', 'ai automation', 'ai startup'],
    confidenceLevel: 'high',
    summary: 'Raised $3.8M seed funding in months for AI automation platform.',
  },
  {
    companyName: 'Cal AI',
    industry: 'technology',
    subIndustry: 'ai_health',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Teen founders', 'Health tech competition', 'User acquisition'],
      capabilities: ['AI development', 'Youth perspective', 'Product innovation'],
      marketPosition: 'Teen-founded startup',
    },
    endingState: {
      revenue: '5m_10m',
      teamSize: '6_20',
      revenueGrowth: '$8M ARR',
      achievements: ['$8M ARR in months', 'Teen founder success', 'Rapid user growth'],
      newCapabilities: ['AI calorie tracking', 'Mobile app scale', 'Viral growth'],
      marketPosition: 'AI health app leader',
    },
    strategyType: 'viral_growth',
    expansionType: 'product',
    targetMarket: 'health_conscious_consumers',
    timeline: { totalMonths: 12 },
    keyActions: [
      { action: 'Built AI calorie tracking app as teenagers', impact: 'Youth innovation', difficulty: 'hard' },
      { action: 'Achieved $8M ARR through viral growth', impact: 'Explosive growth', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 80 },
    lessonsLearned: 'Age is not a barrier to building successful AI products.',
    sourceUrl: 'https://www.starterstory.com/cal-ai-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['technology', 'ai', 'health', 'teen_founders'],
    matchingKeywords: ['cal ai', 'calorie tracking', 'ai health app'],
    confidenceLevel: 'high',
    summary: 'Two teens built AI calorie app to $8M ARR in months.',
  },
  {
    companyName: 'Clay',
    industry: 'technology',
    subIndustry: 'sales_automation',
    location: 'USA',
    startingState: {
      revenue: '100k_500k',
      teamSize: '6_20',
      yearsInBusiness: 1,
      challenges: ['B2B sales complexity', 'Data integration', 'Market education'],
      capabilities: ['Data expertise', 'Sales knowledge', 'Technical team'],
      marketPosition: 'Sales tech startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$31M revenue',
      achievements: ['$31M revenue', 'From $1M to $31M in 5 years', 'Sales automation leader'],
      newCapabilities: ['Data enrichment platform', 'Enterprise sales', 'Market leadership'],
      marketPosition: 'Sales automation leader',
    },
    strategyType: 'product_excellence',
    expansionType: 'product',
    targetMarket: 'sales_teams',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built comprehensive sales data enrichment platform', impact: 'Product differentiation', difficulty: 'hard' },
      { action: 'Grew from $1M to $31M revenue in 5 years', impact: '31x growth', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 31 },
    lessonsLearned: 'Solving complex data problems for sales teams creates massive value.',
    sourceUrl: 'https://www.starterstory.com/clay-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['technology', 'sales', 'data', 'automation'],
    matchingKeywords: ['clay', 'sales automation', 'data enrichment'],
    confidenceLevel: 'high',
    summary: 'Grew from $1M to $31M revenue in 5 years.',
  },
  {
    companyName: 'Metaplane',
    industry: 'technology',
    subIndustry: 'data_observability',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 1,
      challenges: ['Pivot decision', 'Product-market fit', 'Fundraising'],
      capabilities: ['Data engineering', 'Technical team', 'Problem solving'],
      marketPosition: 'Pivoting startup',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '21_50',
      revenueGrowth: '$333K/month',
      achievements: ['$333K/month', '$13.8M Series A', 'Successful pivot'],
      newCapabilities: ['Data observability platform', 'Enterprise sales', 'Funded growth'],
      marketPosition: 'Data observability leader',
    },
    strategyType: 'pivot_success',
    expansionType: 'product',
    targetMarket: 'data_teams',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Pivoted to data observability platform', impact: 'Product-market fit', difficulty: 'hard' },
      { action: 'Raised $13.8M Series A after pivot', impact: 'Validation', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 40 },
    lessonsLearned: 'Successful pivots can lead to stronger product-market fit.',
    sourceUrl: 'https://www.starterstory.com/metaplane-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['technology', 'data', 'observability', 'pivot'],
    matchingKeywords: ['metaplane', 'data observability', 'pivot success'],
    confidenceLevel: 'high',
    summary: 'Pivoted to data observability, raised $13.8M Series A.',
  },
];

async function seed() {
  console.log('🌱 Seeding Batch 14: Manufacturing, Agriculture, Construction, Services, Auto, Events, AI...');

  let successCount = 0;
  let errorCount = 0;

  for (const study of batch14) {
    try {
      await db.insert(caseStudies).values(study as CaseStudyInsert);
      console.log(`  ✓ ${study.companyName}`);
      successCount++;
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : 'Unknown error';
      if (message.includes('duplicate')) {
        console.log(`  ⊘ ${study.companyName} (already exists)`);
      } else {
        console.log(`  ✗ ${study.companyName}: ${message}`);
        errorCount++;
      }
    }
  }

  console.log(`\nBatch 14 seeding complete!`);
  console.log(`✓ Successfully seeded: ${successCount}`);
  console.log(`✗ Errors: ${errorCount}`);

  process.exit(0);
}

seed().catch((e) => {
  console.error('Seed failed:', e);
  process.exit(1);
});
