import { db } from '../../lib/db';
import { caseStudies } from '../schema';

type CaseStudyInsert = typeof caseStudies.$inferInsert;

const batch6CaseStudies = [
  // ===== SaaS =====
  {
    companyName: 'Dashp',
    industry: 'technology',
    subIndustry: 'saas',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Finding niche market', 'Building MVP', 'Customer acquisition'],
      capabilities: ['Software development', 'Industry knowledge'],
      marketPosition: 'New vertical SaaS startup',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '2_5',
      revenueGrowth: '$100K ARR',
      achievements: ['$100K ARR milestone', 'Pest control industry focus', 'Recurring revenue model'],
      newCapabilities: ['Industry-specific features', 'Customer success'],
      marketPosition: 'Niche SaaS leader for pest control',
    },
    strategyType: 'niche_focus',
    expansionType: 'vertical',
    targetMarket: 'pest_control_companies',
    timeline: { totalMonths: 18 },
    keyActions: [
      { action: 'Focused on underserved pest control niche', impact: 'Found product-market fit quickly', difficulty: 'moderate' },
      { action: 'Built industry-specific features', impact: 'Higher retention rates', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 5 },
    lessonsLearned: 'Vertical SaaS targeting specific industries can achieve faster PMF than horizontal solutions.',
    sourceUrl: 'https://www.starterstory.com/stories/dashp',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'vertical_saas', 'pest_control', 'b2b'],
    matchingKeywords: ['saas', 'software', 'pest control', 'vertical saas'],
    confidenceLevel: 'high',
    summary: 'Built a vertical SaaS product for pest control companies reaching $100K ARR.',
  },
  {
    companyName: 'ListKit',
    industry: 'technology',
    subIndustry: 'saas',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Rapid growth pressure', 'Building sales infrastructure', 'Market validation'],
      capabilities: ['Sales expertise', 'Lead generation knowledge'],
      marketPosition: 'New B2B data provider',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '6_10',
      revenueGrowth: '$100K MRR in 90 days',
      achievements: ['$100K MRR in 90 days', 'Hyper-personalized lead data', 'Rapid scaling'],
      newCapabilities: ['Data enrichment', 'B2B sales tools'],
      marketPosition: 'Fast-growing lead data platform',
    },
    strategyType: 'rapid_growth',
    expansionType: 'horizontal',
    targetMarket: 'sales_teams',
    timeline: { totalMonths: 3 },
    keyActions: [
      { action: 'Built hyper-personalized lead data product', impact: 'Strong value proposition', difficulty: 'hard' },
      { action: 'Aggressive go-to-market strategy', impact: 'Hit $100K MRR in 90 days', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Speed to market with a focused product can drive explosive early growth.',
    sourceUrl: 'https://www.starterstory.com/stories/listkit-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'lead_generation', 'b2b', 'sales_tools'],
    matchingKeywords: ['lead data', 'b2b leads', 'sales intelligence'],
    confidenceLevel: 'high',
    summary: 'Built ListKit to $100K MRR in just 90 days with hyper-personalized lead data.',
  },
  {
    companyName: 'Loops',
    industry: 'technology',
    subIndustry: 'saas',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Entering crowded email market', 'Differentiation', 'Building trust'],
      capabilities: ['Product development', 'Marketing expertise'],
      marketPosition: 'New email marketing tool',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '2_5',
      revenueGrowth: '$731K revenue in 2 years',
      achievements: ['$731K revenue', '$61K MRR', 'Modern email platform for SaaS'],
      newCapabilities: ['Email automation', 'SaaS-focused features'],
      marketPosition: 'Modern email tool for SaaS companies',
    },
    strategyType: 'product_innovation',
    expansionType: 'vertical',
    targetMarket: 'saas_companies',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Built modern alternative to legacy email tools', impact: 'Attracted SaaS companies', difficulty: 'hard' },
      { action: 'Focused on developer experience', impact: 'Strong word of mouth', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Reimagining established categories with modern UX can capture market share.',
    sourceUrl: 'https://www.starterstory.com/loops-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'email_marketing', 'b2b', 'developer_tools'],
    matchingKeywords: ['email marketing', 'saas', 'marketing automation'],
    confidenceLevel: 'high',
    summary: 'Two founders built a modern email tool reaching $731K revenue in 2 years.',
  },
  {
    companyName: 'Panintelligence',
    industry: 'technology',
    subIndustry: 'saas',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Productizing internal tool', 'Market validation', 'Enterprise sales'],
      capabilities: ['BI development', 'Data analytics expertise'],
      marketPosition: 'Internal tool becoming product',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '20_50',
      revenueGrowth: '$3.8M/year',
      achievements: ['$3.8M annual revenue', 'Enterprise BI platform', 'Global customer base'],
      newCapabilities: ['Enterprise sales', 'Product management'],
      marketPosition: 'Established BI SaaS company',
    },
    strategyType: 'product_innovation',
    expansionType: 'horizontal',
    targetMarket: 'enterprise',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Transformed internal tool into commercial product', impact: 'Validated market demand', difficulty: 'hard' },
      { action: 'Built enterprise sales motion', impact: 'Landed larger contracts', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 30 },
    lessonsLearned: 'Internal tools that solve real problems often have commercial potential.',
    sourceUrl: 'https://www.starterstory.com/stories/panintelligence',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'business_intelligence', 'enterprise', 'analytics'],
    matchingKeywords: ['business intelligence', 'analytics', 'enterprise software'],
    confidenceLevel: 'high',
    summary: 'Transformed an internal BI tool into a $3.8M/year SaaS company.',
  },
  {
    companyName: 'Userlist',
    industry: 'technology',
    subIndustry: 'saas',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Competing with established players', 'Product differentiation', 'SaaS positioning'],
      capabilities: ['Email automation expertise', 'Product design'],
      marketPosition: 'New SaaS email automation tool',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '2_5',
      revenueGrowth: 'Profitable growth',
      achievements: ['SaaS-focused email automation', 'Strong customer retention', 'Bootstrapped profitability'],
      newCapabilities: ['Behavior-based messaging', 'User segmentation'],
      marketPosition: 'Email automation for SaaS companies',
    },
    strategyType: 'niche_focus',
    expansionType: 'vertical',
    targetMarket: 'saas_founders',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Focused exclusively on SaaS use cases', impact: 'Better product-market fit', difficulty: 'moderate' },
      { action: 'Built behavior-based automation', impact: 'Higher customer value', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 8 },
    lessonsLearned: 'Focusing on a specific customer segment enables better product decisions.',
    sourceUrl: 'https://www.starterstory.com/userlist-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'email_automation', 'b2b', 'bootstrapped'],
    matchingKeywords: ['email automation', 'saas marketing', 'user onboarding'],
    confidenceLevel: 'high',
    summary: 'Mastered SaaS email automation with a niche-focused approach.',
  },
  {
    companyName: 'SEOJuice',
    industry: 'technology',
    subIndustry: 'saas',
    location: 'Germany',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Solo founder limitations', 'SEO tool competition', 'Customer acquisition'],
      capabilities: ['SEO expertise', 'Software development'],
      marketPosition: 'Solo founder SEO tool',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '1',
      revenueGrowth: '$8K/month',
      achievements: ['$8K MRR as solo founder', 'Bootstrapped growth', 'Automated SEO features'],
      newCapabilities: ['AI-powered SEO', 'Self-service model'],
      marketPosition: 'Bootstrapped SEO SaaS',
    },
    strategyType: 'bootstrapped_growth',
    expansionType: 'horizontal',
    targetMarket: 'website_owners',
    timeline: { totalMonths: 18 },
    keyActions: [
      { action: 'Built automated SEO optimization tool', impact: 'Recurring revenue model', difficulty: 'moderate' },
      { action: 'Remained solo to maximize profitability', impact: 'High profit margins', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Solo founders can build profitable SaaS with focused automation.',
    sourceUrl: 'https://www.starterstory.com/stories/seojuice-io',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'seo', 'bootstrapped', 'solo_founder'],
    matchingKeywords: ['seo tool', 'seo automation', 'bootstrapped saas'],
    confidenceLevel: 'high',
    summary: 'Bootstrapped solo SEO app to $8K/month recurring revenue.',
  },

  // ===== Home Services / Cleaning =====
  {
    companyName: 'MaidThis Franchise',
    industry: 'services',
    subIndustry: 'cleaning',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Service consistency', 'Scaling operations', 'Finding cleaners'],
      capabilities: ['Operations management', 'Tech integration'],
      marketPosition: 'New cleaning service startup',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '50_100',
      revenueGrowth: '$100K+/month',
      achievements: ['$100K+ monthly revenue', 'Airbnb cleaning niche', 'Franchise model'],
      newCapabilities: ['Franchise operations', 'Airbnb partnerships'],
      marketPosition: 'Leading Airbnb cleaning franchise',
    },
    strategyType: 'niche_focus',
    expansionType: 'franchise',
    targetMarket: 'airbnb_hosts',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Focused on Airbnb and vacation rental cleaning', impact: 'Found underserved niche', difficulty: 'moderate' },
      { action: 'Built franchise model for scaling', impact: 'Rapid geographic expansion', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Combining niche focus with franchise model enables rapid scaling in services.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-cleaning-service-for-airbnb',
    sourcePlatform: 'starter_story',
    tags: ['cleaning', 'franchise', 'airbnb', 'home_services'],
    matchingKeywords: ['airbnb cleaning', 'vacation rental', 'cleaning franchise'],
    confidenceLevel: 'high',
    summary: 'Built a $100K+/month home cleaning service focused on Airbnb hosts.',
  },
  {
    companyName: 'CleanLots',
    industry: 'services',
    subIndustry: 'cleaning',
    location: 'Canada',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Low startup capital', 'Finding clients', 'Building reputation'],
      capabilities: ['Work ethic', 'Simple equipment needs'],
      marketPosition: 'One-person litter cleanup service',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '1',
      revenueGrowth: '$60K/month',
      achievements: ['$60K monthly revenue', 'Commercial parking lot focus', 'Course business'],
      newCapabilities: ['Commercial contracts', 'Training program'],
      marketPosition: 'Niche commercial litter cleaning leader',
    },
    strategyType: 'niche_focus',
    expansionType: 'vertical',
    targetMarket: 'commercial_properties',
    timeline: { totalMonths: 240 },
    keyActions: [
      { action: 'Focused exclusively on parking lot litter', impact: 'Built unique niche', difficulty: 'easy' },
      { action: 'Created training course for others', impact: 'Additional revenue stream', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 30 },
    lessonsLearned: 'Ultra-niche services with low competition can be highly profitable.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-cleaning-service',
    sourcePlatform: 'starter_story',
    tags: ['cleaning', 'commercial', 'niche', 'solo_business'],
    matchingKeywords: ['litter cleanup', 'parking lot cleaning', 'commercial cleaning'],
    confidenceLevel: 'high',
    summary: 'Grew a niche commercial litter cleaning service to $60K/month.',
  },
  {
    companyName: 'Pinks Window Services',
    industry: 'services',
    subIndustry: 'cleaning',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Laid off from jobs', 'Starting from scratch', 'Building customer base'],
      capabilities: ['Window cleaning skills', 'Hustle mentality'],
      marketPosition: 'New window cleaning startup',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '6_10',
      revenueGrowth: '$58K MRR',
      achievements: ['$58K monthly recurring revenue', '8 employees', 'Franchise expansion'],
      newCapabilities: ['Franchise operations', 'Team management'],
      marketPosition: 'Growing window cleaning franchise',
    },
    strategyType: 'franchise_growth',
    expansionType: 'franchise',
    targetMarket: 'residential_commercial',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Started after being laid off', impact: 'Necessity drove hustle', difficulty: 'hard' },
      { action: 'Built franchise model', impact: 'Scalable growth', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 30 },
    lessonsLearned: 'Adversity can be the catalyst for entrepreneurial success.',
    sourceUrl: 'https://www.starterstory.com/pinks-window-services-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['cleaning', 'window_cleaning', 'franchise', 'comeback_story'],
    matchingKeywords: ['window cleaning', 'franchise', 'home services'],
    confidenceLevel: 'high',
    summary: 'Two laid-off workers built a $58K MRR window cleaning franchise.',
  },

  // ===== Automotive =====
  {
    companyName: 'Belk Mobile Detailing',
    industry: 'automotive',
    subIndustry: 'detailing',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Mobile service logistics', 'Customer acquisition', 'Weather dependency'],
      capabilities: ['Detailing skills', 'Customer service'],
      marketPosition: 'New mobile detailing service',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '2_5',
      revenueGrowth: '$96K/year',
      achievements: ['$96K annual revenue', 'Mobile convenience model', 'Repeat customers'],
      newCapabilities: ['Mobile operations', 'Customer retention systems'],
      marketPosition: 'Established mobile detailing business',
    },
    strategyType: 'service_excellence',
    expansionType: 'local',
    targetMarket: 'car_owners',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Focused on mobile convenience', impact: 'Differentiated from shops', difficulty: 'moderate' },
      { action: 'Built repeat customer base', impact: 'Predictable revenue', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 8 },
    lessonsLearned: 'Mobile services offer convenience that customers will pay premium for.',
    sourceUrl: 'https://www.starterstory.com/stories/belk-mobile-detailing',
    sourcePlatform: 'starter_story',
    tags: ['automotive', 'mobile_service', 'detailing', 'local_business'],
    matchingKeywords: ['auto detailing', 'mobile detailing', 'car care'],
    confidenceLevel: 'high',
    summary: 'Started a $96K/year mobile auto detailing business.',
  },
  {
    companyName: "Wolf's Auto Detailing",
    industry: 'automotive',
    subIndustry: 'detailing',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Part-time constraints', 'Building clientele', 'Pricing strategy'],
      capabilities: ['Detailing passion', 'Attention to detail'],
      marketPosition: 'Part-time detailing side hustle',
    },
    endingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      revenueGrowth: '$36K/year',
      achievements: ['$36K annual on 3 days/week', 'Work-life balance', 'Premium positioning'],
      newCapabilities: ['Premium service delivery', 'Efficient scheduling'],
      marketPosition: 'Lifestyle-focused detailing business',
    },
    strategyType: 'lifestyle_business',
    expansionType: 'local',
    targetMarket: 'car_enthusiasts',
    timeline: { totalMonths: 18 },
    keyActions: [
      { action: 'Limited to 3 days per week intentionally', impact: 'Maintained work-life balance', difficulty: 'easy' },
      { action: 'Focused on premium pricing', impact: 'Higher per-job revenue', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 5 },
    lessonsLearned: 'Lifestyle businesses can be profitable without sacrificing personal time.',
    sourceUrl: 'https://www.starterstory.com/stories/wolfs-auto-detailing',
    sourcePlatform: 'starter_story',
    tags: ['automotive', 'lifestyle_business', 'detailing', 'part_time'],
    matchingKeywords: ['auto detailing', 'side hustle', 'lifestyle business'],
    confidenceLevel: 'high',
    summary: 'Started a $36K/year auto detailing business working only 3 days per week.',
  },
  {
    companyName: 'Fresh Look Mobile Auto Detailing',
    industry: 'automotive',
    subIndustry: 'detailing',
    location: 'USA',
    startingState: {
      revenue: '100k_500k',
      teamSize: '1',
      yearsInBusiness: 5,
      challenges: ['Leaving tech career', 'Career change risk', 'Building new skills'],
      capabilities: ['Tech background', 'Business acumen'],
      marketPosition: 'Career changer starting detailing',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '2_5',
      revenueGrowth: 'Profitable business',
      achievements: ['Successful career pivot', 'Hobby became business', 'Local reputation'],
      newCapabilities: ['Detailing expertise', 'Local marketing'],
      marketPosition: 'Established local detailing business',
    },
    strategyType: 'career_pivot',
    expansionType: 'local',
    targetMarket: 'local_car_owners',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Left tech career to pursue passion', impact: 'Full commitment to business', difficulty: 'hard' },
      { action: 'Leveraged hobby into business', impact: 'Built on existing skills', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 3 },
    lessonsLearned: 'Passion projects can become profitable businesses with commitment.',
    sourceUrl: 'https://www.starterstory.com/stories/i-left-tech-built-my-own-car-detailing-business-my-hobby',
    sourcePlatform: 'starter_story',
    tags: ['automotive', 'career_change', 'detailing', 'passion_project'],
    matchingKeywords: ['career pivot', 'auto detailing', 'hobby business'],
    confidenceLevel: 'high',
    summary: 'Left tech to build a car detailing business from a hobby.',
  },
  {
    companyName: 'GetSpiffy',
    industry: 'automotive',
    subIndustry: 'car_care',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Building tech platform', 'Scaling mobile operations', 'Hiring at scale'],
      capabilities: ['Tech entrepreneurship', 'Operations expertise'],
      marketPosition: 'Tech-enabled car care startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '500_plus',
      revenueGrowth: '$50M/year ($4M/month)',
      achievements: ['$50M annual revenue', '615 employees', 'National expansion'],
      newCapabilities: ['Fleet operations', 'Enterprise sales'],
      marketPosition: 'Leading mobile car-care service',
    },
    strategyType: 'tech_enabled_scale',
    expansionType: 'national',
    targetMarket: 'consumers_fleets',
    timeline: { totalMonths: 120 },
    keyActions: [
      { action: 'Built tech platform for mobile car care', impact: 'Enabled national scaling', difficulty: 'hard' },
      { action: 'Expanded to fleet customers', impact: 'B2B revenue stream', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 500 },
    lessonsLearned: 'Technology can transform traditional service businesses into scalable enterprises.',
    sourceUrl: 'https://www.starterstory.com/stories/getspiffy',
    sourcePlatform: 'starter_story',
    tags: ['automotive', 'tech_enabled', 'mobile_service', 'venture_scale'],
    matchingKeywords: ['mobile car care', 'fleet services', 'car wash'],
    confidenceLevel: 'high',
    summary: 'Built a $50M/year mobile car-care service with 615 employees.',
  },
  {
    companyName: 'Finish Line Towing & Repair',
    industry: 'automotive',
    subIndustry: 'towing_repair',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Leaving stable job', 'Capital requirements', 'Building trust'],
      capabilities: ['Automotive expertise', 'Customer service'],
      marketPosition: 'New towing and repair business',
    },
    endingState: {
      revenue: '5m_10m',
      teamSize: '20_50',
      revenueGrowth: '$5M/year',
      achievements: ['$5M annual revenue', 'Full-service auto shop', 'Community reputation'],
      newCapabilities: ['Large team management', 'Multi-service operations'],
      marketPosition: 'Leading local towing and repair',
    },
    strategyType: 'service_expansion',
    expansionType: 'vertical',
    targetMarket: 'local_drivers',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Combined towing with repair services', impact: 'Multiple revenue streams', difficulty: 'moderate' },
      { action: 'Built strong community reputation', impact: 'Referral-based growth', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Bundling related services increases customer lifetime value.',
    sourceUrl: 'https://www.starterstory.com/stories/finish-line-towing-repair',
    sourcePlatform: 'starter_story',
    tags: ['automotive', 'towing', 'auto_repair', 'local_business'],
    matchingKeywords: ['towing', 'auto repair', 'roadside assistance'],
    confidenceLevel: 'high',
    summary: 'Quit full-time job and launched a $5M/year towing and auto repair business.',
  },

  // ===== Real Estate =====
  {
    companyName: 'Ark7',
    industry: 'real_estate',
    subIndustry: 'investment_platform',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Regulatory compliance', 'Building trust', 'Tech platform development'],
      capabilities: ['Tech development', 'Real estate knowledge'],
      marketPosition: 'New real estate investment platform',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '11_20',
      revenueGrowth: 'Venture-backed growth',
      achievements: ['Fractional real estate investing', 'Regulatory approval', 'Platform launch'],
      newCapabilities: ['SEC compliance', 'Property management'],
      marketPosition: 'Real estate crowdfunding platform',
    },
    strategyType: 'platform_build',
    expansionType: 'horizontal',
    targetMarket: 'retail_investors',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built fractional ownership platform', impact: 'Democratized real estate investing', difficulty: 'hard' },
      { action: 'Navigated regulatory requirements', impact: 'Enabled compliant operation', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Fintech in real estate requires careful regulatory navigation.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-real-estate-investment-platform',
    sourcePlatform: 'starter_story',
    tags: ['real_estate', 'fintech', 'crowdfunding', 'platform'],
    matchingKeywords: ['real estate investing', 'fractional ownership', 'crowdfunding'],
    confidenceLevel: 'high',
    summary: 'Built a real estate investment platform for fractional property ownership.',
  },
  {
    companyName: 'Equity Residences',
    industry: 'real_estate',
    subIndustry: 'vacation_homes',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Accredited investor requirements', 'Property acquisition', 'Trust building'],
      capabilities: ['Investment management', 'Real estate expertise'],
      marketPosition: 'New luxury vacation home fund',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '6_10',
      revenueGrowth: 'Multi-million AUM',
      achievements: ['Luxury vacation home portfolio', 'Debt-free properties', 'Investor returns'],
      newCapabilities: ['Fund management', 'Property curation'],
      marketPosition: 'Luxury vacation home investment fund',
    },
    strategyType: 'premium_positioning',
    expansionType: 'vertical',
    targetMarket: 'accredited_investors',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Bought luxury properties debt-free', impact: 'Lower risk profile', difficulty: 'hard' },
      { action: 'Offered shared ownership with usage rights', impact: 'Unique value proposition', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 15 },
    lessonsLearned: 'Combining investment returns with lifestyle benefits creates unique appeal.',
    sourceUrl: 'https://www.starterstory.com/stories/equity-residences-a-business-model-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['real_estate', 'luxury', 'investment_fund', 'vacation_homes'],
    matchingKeywords: ['luxury real estate', 'vacation homes', 'real estate fund'],
    confidenceLevel: 'high',
    summary: 'Built a platform for accredited investors to collectively own luxury vacation homes.',
  },

  // ===== Marketing Agencies =====
  {
    companyName: 'Huemor',
    industry: 'services',
    subIndustry: 'digital_agency',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Rapid scaling', 'Talent acquisition', 'Process development'],
      capabilities: ['Web development', 'Design skills'],
      marketPosition: 'New digital agency',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '11_20',
      revenueGrowth: '$3M/year in 90 days',
      achievements: ['$3M annual revenue', '100+ international awards', '200+ companies helped'],
      newCapabilities: ['Award-winning design', 'Enterprise clients'],
      marketPosition: 'Award-winning digital agency',
    },
    strategyType: 'rapid_growth',
    expansionType: 'horizontal',
    targetMarket: 'businesses',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Focused on award-winning quality', impact: 'Built strong reputation', difficulty: 'hard' },
      { action: 'Scaled to $3M in 90 days', impact: 'Rapid market capture', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Excellence in craft combined with aggressive growth can produce rapid results.',
    sourceUrl: 'https://www.starterstory.com/stories/our-development-agency-helped-200-companies-won-100-international-awards-and-makes-3m-year',
    sourcePlatform: 'starter_story',
    tags: ['agency', 'digital_marketing', 'web_design', 'awards'],
    matchingKeywords: ['digital agency', 'web design', 'marketing agency'],
    confidenceLevel: 'high',
    summary: 'Built a $3M/year digital marketing agency in just 90 days.',
  },
  {
    companyName: 'Bop Design',
    industry: 'services',
    subIndustry: 'marketing_agency',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Couple dynamics', 'Client acquisition', 'Work-life balance'],
      capabilities: ['Design skills', 'Marketing expertise'],
      marketPosition: 'Husband-wife agency startup',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '11_20',
      revenueGrowth: '$2.4M/year in 120 days',
      achievements: ['$2.4M annual revenue', 'B2B focus', 'Strong team culture'],
      newCapabilities: ['B2B marketing', 'Team leadership'],
      marketPosition: 'B2B marketing agency',
    },
    strategyType: 'rapid_growth',
    expansionType: 'horizontal',
    targetMarket: 'b2b_companies',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Focused on B2B marketing niche', impact: 'Clear positioning', difficulty: 'moderate' },
      { action: 'Scaled rapidly as power couple', impact: 'Complementary skills', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 40 },
    lessonsLearned: 'Complementary skills between founders accelerates growth.',
    sourceUrl: 'https://www.starterstory.com/stories/this-power-couple-started-a-2-4m-year-marketing-agency-in-120-days',
    sourcePlatform: 'starter_story',
    tags: ['agency', 'b2b_marketing', 'couple_founders', 'branding'],
    matchingKeywords: ['b2b marketing', 'branding agency', 'marketing agency'],
    confidenceLevel: 'high',
    summary: 'Power couple started a $2.4M/year marketing agency in 120 days.',
  },
  {
    companyName: 'Sievers Creative',
    industry: 'services',
    subIndustry: 'marketing_agency',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Transitioning from side hustle', 'Scaling operations', 'Hiring'],
      capabilities: ['Marketing skills', 'Creative talent'],
      marketPosition: 'Side hustle agency',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '11_20',
      revenueGrowth: '$100K/month',
      achievements: ['$100K monthly revenue', 'Full-service agency', 'Team of specialists'],
      newCapabilities: ['Full-service marketing', 'Team management'],
      marketPosition: 'Full-service marketing agency',
    },
    strategyType: 'side_hustle_to_main',
    expansionType: 'horizontal',
    targetMarket: 'smbs',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Grew side hustle into full agency', impact: 'Validated before committing', difficulty: 'moderate' },
      { action: 'Expanded to full-service offering', impact: 'Higher client value', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 25 },
    lessonsLearned: 'Side hustles can be tested markets before full commitment.',
    sourceUrl: 'https://www.starterstory.com/stories/sievers-creative',
    sourcePlatform: 'starter_story',
    tags: ['agency', 'marketing', 'side_hustle', 'full_service'],
    matchingKeywords: ['marketing agency', 'full service', 'creative agency'],
    confidenceLevel: 'high',
    summary: 'Grew a side hustle into a $100K/month full service marketing agency.',
  },
  {
    companyName: 'Zero Gravity Marketing',
    industry: 'services',
    subIndustry: 'digital_agency',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Building team', 'Service standardization', 'Client retention'],
      capabilities: ['Digital marketing', 'SEO expertise'],
      marketPosition: 'New digital marketing agency',
    },
    endingState: {
      revenue: '5m_10m',
      teamSize: '50_100',
      revenueGrowth: '$9.6M/year',
      achievements: ['$9.6M annual revenue', '70 employees', 'Full-service digital'],
      newCapabilities: ['Large team operations', 'Enterprise clients'],
      marketPosition: 'Major digital marketing agency',
    },
    strategyType: 'scale_operations',
    expansionType: 'horizontal',
    targetMarket: 'mid_market',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Built comprehensive digital services', impact: 'One-stop shop for clients', difficulty: 'hard' },
      { action: 'Scaled team to 70 employees', impact: 'Capacity for larger clients', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 80 },
    lessonsLearned: 'Building a large team enables serving enterprise-level clients.',
    sourceUrl: 'https://www.starterstory.com/stories/zero-gravity-marketing',
    sourcePlatform: 'starter_story',
    tags: ['agency', 'digital_marketing', 'large_team', 'enterprise'],
    matchingKeywords: ['digital marketing', 'seo agency', 'ppc agency'],
    confidenceLevel: 'high',
    summary: 'Grew digital marketing agency to $9.6M/year with 70 employees.',
  },
  {
    companyName: 'MadeByShape',
    industry: 'services',
    subIndustry: 'web_design',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Low-value projects', 'Pricing confidence', 'Scaling quality'],
      capabilities: ['Web design', 'Front-end development'],
      marketPosition: '$200 website designer',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '6_10',
      revenueGrowth: '$600K/year',
      achievements: ['$600K annual revenue', '$100K+ projects', 'Premium positioning'],
      newCapabilities: ['Enterprise web design', 'UX strategy'],
      marketPosition: 'Premium web design studio',
    },
    strategyType: 'premium_repositioning',
    expansionType: 'vertical',
    targetMarket: 'enterprises',
    timeline: { totalMonths: 120 },
    keyActions: [
      { action: 'Moved from $200 to $100K projects', impact: '500x price increase', difficulty: 'hard' },
      { action: 'Built premium brand and portfolio', impact: 'Attracted bigger clients', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 60 },
    lessonsLearned: 'Premium positioning requires quality, patience, and consistent brand building.',
    sourceUrl: 'https://www.starterstory.com/stories/i-went-from-designing-website-for-200-to-starting-a-studio-that-makes-100k-projects',
    sourcePlatform: 'starter_story',
    tags: ['agency', 'web_design', 'premium', 'price_increase'],
    matchingKeywords: ['web design', 'premium agency', 'enterprise web'],
    confidenceLevel: 'high',
    summary: 'Went from designing websites for $200 to running a $600K/year agency doing $100K projects.',
  },
  {
    companyName: 'Percept',
    industry: 'services',
    subIndustry: 'branding_agency',
    location: 'Australia',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Solo founder scaling', 'Maintaining quality', 'Work-life balance'],
      capabilities: ['Branding expertise', 'Design skills'],
      marketPosition: 'Solo branding consultant',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '1',
      revenueGrowth: '$1.2M/year',
      achievements: ['$1.2M annual revenue as solo', 'One-man-show', 'Premium clients'],
      newCapabilities: ['High-efficiency processes', 'Premium positioning'],
      marketPosition: 'Solo million-dollar agency',
    },
    strategyType: 'solo_scale',
    expansionType: 'vertical',
    targetMarket: 'premium_clients',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Built $1M+ business as solo founder', impact: 'Maximum profit margins', difficulty: 'hard' },
      { action: 'Focused on premium branding only', impact: 'High-value projects', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Solo businesses can reach seven figures with premium positioning and efficiency.',
    sourceUrl: 'https://www.starterstory.com/stories/i-bootstrapped-my-one-man-show-branding-agency-to-1-2m-year',
    sourcePlatform: 'starter_story',
    tags: ['agency', 'branding', 'solo_founder', 'million_dollar'],
    matchingKeywords: ['branding agency', 'solo agency', 'one person business'],
    confidenceLevel: 'high',
    summary: 'Bootstrapped a one-man branding agency to $1.2M/year.',
  },
  {
    companyName: 'The Creative Collective',
    industry: 'services',
    subIndustry: 'marketing_agency',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Working from home', 'Building team', 'Client acquisition'],
      capabilities: ['Marketing expertise', 'Creative direction'],
      marketPosition: 'Home-based agency startup',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '11_20',
      revenueGrowth: '$2.4M/year',
      achievements: ['$2.4M annual revenue', 'Remote team', 'Work from home success'],
      newCapabilities: ['Remote team management', 'Virtual agency operations'],
      marketPosition: 'Remote-first marketing agency',
    },
    strategyType: 'remote_first',
    expansionType: 'horizontal',
    targetMarket: 'businesses',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Built remote-first agency model', impact: 'Lower overhead costs', difficulty: 'moderate' },
      { action: 'Scaled to $2.4M from home', impact: 'Proved remote can scale', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 40 },
    lessonsLearned: 'Remote agencies can achieve significant scale with the right systems.',
    sourceUrl: 'https://www.starterstory.com/stories/i-started-a-2-4m-year-marketing-agency-from-home',
    sourcePlatform: 'starter_story',
    tags: ['agency', 'marketing', 'remote', 'work_from_home'],
    matchingKeywords: ['remote agency', 'marketing agency', 'work from home'],
    confidenceLevel: 'high',
    summary: 'Started a $2.4M/year marketing agency from home.',
  },
  {
    companyName: 'OrangeB (Nordby Design)',
    industry: 'services',
    subIndustry: 'branding_agency',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Brand positioning', 'Client pipeline', 'Team building'],
      capabilities: ['Branding skills', 'Design expertise'],
      marketPosition: 'New branding agency',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '2_5',
      revenueGrowth: '$40K/month',
      achievements: ['$40K monthly revenue', 'Strong brand identity', 'Consistent pipeline'],
      newCapabilities: ['Brand strategy', 'Client retention'],
      marketPosition: 'Established branding agency',
    },
    strategyType: 'brand_building',
    expansionType: 'vertical',
    targetMarket: 'startups_smbs',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built strong agency brand', impact: 'Attracted ideal clients', difficulty: 'moderate' },
      { action: 'Focused on branding expertise', impact: 'Clear positioning', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Agencies must practice what they preach - strong brand attracts clients.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-branding-company',
    sourcePlatform: 'starter_story',
    tags: ['agency', 'branding', 'design', 'small_team'],
    matchingKeywords: ['branding agency', 'design agency', 'brand identity'],
    confidenceLevel: 'high',
    summary: 'Started and grew a branding agency to $40K/month.',
  },

  // ===== Consulting / Coaching =====
  {
    companyName: 'World Renowned Coaching & Consulting',
    industry: 'services',
    subIndustry: 'coaching',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Building credibility', 'Pricing services', 'Client acquisition'],
      capabilities: ['Real estate expertise', 'Coaching skills'],
      marketPosition: 'New real estate coach',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '2_5',
      revenueGrowth: '$48K/month with 96% profit',
      achievements: ['$48K monthly revenue', '96% profit margin', 'High-ticket coaching'],
      newCapabilities: ['High-ticket sales', 'Online delivery'],
      marketPosition: 'Premium real estate coaching',
    },
    strategyType: 'high_margin',
    expansionType: 'vertical',
    targetMarket: 'real_estate_agents',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built high-ticket coaching program', impact: '96% profit margins', difficulty: 'moderate' },
      { action: 'Focused on real estate niche', impact: 'Clear target market', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'High-ticket coaching with niche focus achieves exceptional margins.',
    sourceUrl: 'https://www.starterstory.com/stories/world-renowned-real-estate',
    sourcePlatform: 'starter_story',
    tags: ['coaching', 'real_estate', 'high_ticket', 'high_margin'],
    matchingKeywords: ['coaching business', 'real estate coaching', 'consulting'],
    confidenceLevel: 'high',
    summary: 'Built a coaching business making $48K/month with 96% profit margin.',
  },
  {
    companyName: 'Consulting Success',
    industry: 'services',
    subIndustry: 'consulting',
    location: 'Canada',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Teaching consultants', 'Building authority', 'Content creation'],
      capabilities: ['Consulting experience', 'Training skills'],
      marketPosition: 'New consultant training business',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '6_10',
      revenueGrowth: '$200K/month',
      achievements: ['$200K monthly revenue', 'Leading consultant training', 'Global reach'],
      newCapabilities: ['Online training', 'Community building'],
      marketPosition: 'Leading consultant coaching firm',
    },
    strategyType: 'authority_building',
    expansionType: 'horizontal',
    targetMarket: 'consultants',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Built authority in consultant training', impact: 'Premium positioning', difficulty: 'hard' },
      { action: 'Created comprehensive training programs', impact: 'Scalable delivery', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Teaching your expertise can be more profitable than practicing it.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-consultant-training-coaching-business',
    sourcePlatform: 'starter_story',
    tags: ['consulting', 'training', 'coaching', 'b2b'],
    matchingKeywords: ['consultant coaching', 'consulting training', 'business coaching'],
    confidenceLevel: 'high',
    summary: 'Cousins built a $200K/month consultant training and coaching business.',
  },
  {
    companyName: 'Half a Bubble Out',
    industry: 'services',
    subIndustry: 'marketing_consulting',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Husband-wife dynamics', 'Service positioning', 'Client acquisition'],
      capabilities: ['Marketing expertise', 'Business consulting'],
      marketPosition: 'New marketing consultancy',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '6_10',
      revenueGrowth: '$98K/month',
      achievements: ['$98K monthly revenue', 'Full-service consultancy', 'Strong client relationships'],
      newCapabilities: ['Business strategy', 'Marketing execution'],
      marketPosition: 'Established marketing consultancy',
    },
    strategyType: 'full_service',
    expansionType: 'horizontal',
    targetMarket: 'smbs',
    timeline: { totalMonths: 120 },
    keyActions: [
      { action: 'Combined marketing and business consulting', impact: 'Holistic client service', difficulty: 'moderate' },
      { action: 'Built long-term client relationships', impact: 'Recurring revenue', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 25 },
    lessonsLearned: 'Combining strategy and execution creates sticky client relationships.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-business-consultancy',
    sourcePlatform: 'starter_story',
    tags: ['consulting', 'marketing', 'couple_founders', 'smb'],
    matchingKeywords: ['marketing consulting', 'business consulting', 'smb marketing'],
    confidenceLevel: 'high',
    summary: 'Started a $98K/month marketing and business consultancy.',
  },
  {
    companyName: 'Cain Consulting',
    industry: 'services',
    subIndustry: 'leadership_consulting',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Leaving corporate', 'Building client base', 'Credibility'],
      capabilities: ['Leadership experience', 'Executive background'],
      marketPosition: 'New leadership consultant',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '1',
      revenueGrowth: '$15K/month',
      achievements: ['$15K monthly revenue', 'Solo consulting practice', 'Executive clients'],
      newCapabilities: ['Executive coaching', 'Leadership training'],
      marketPosition: 'Established leadership consultant',
    },
    strategyType: 'expertise_monetization',
    expansionType: 'vertical',
    targetMarket: 'executives',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Leveraged executive experience', impact: 'Credibility with clients', difficulty: 'moderate' },
      { action: 'Built solo consulting practice', impact: 'High margins, flexibility', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 8 },
    lessonsLearned: 'Executive experience translates well into consulting with proper positioning.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-leadership-consulting-business',
    sourcePlatform: 'starter_story',
    tags: ['consulting', 'leadership', 'executive', 'solo'],
    matchingKeywords: ['leadership consulting', 'executive coaching', 'management consulting'],
    confidenceLevel: 'high',
    summary: 'Started a $15K/month leadership consulting business.',
  },
  {
    companyName: '1ON1 SEO Training',
    industry: 'services',
    subIndustry: 'seo_consulting',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Crowded SEO market', 'Differentiation', 'Lead generation'],
      capabilities: ['SEO expertise', 'Teaching skills'],
      marketPosition: 'New SEO trainer',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '1',
      revenueGrowth: '$10K/month',
      achievements: ['$10K monthly revenue', 'One-on-one training model', 'Personalized service'],
      newCapabilities: ['Training methodology', 'Client success systems'],
      marketPosition: 'Personalized SEO trainer',
    },
    strategyType: 'personalization',
    expansionType: 'vertical',
    targetMarket: 'business_owners',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Focused on 1-on-1 training model', impact: 'Premium pricing justified', difficulty: 'moderate' },
      { action: 'Built personalized curriculum', impact: 'Better client outcomes', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 6 },
    lessonsLearned: 'Personalized training commands premium prices over group courses.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-seo-consulting-training-business',
    sourcePlatform: 'starter_story',
    tags: ['consulting', 'seo', 'training', 'solo'],
    matchingKeywords: ['seo training', 'seo consulting', 'digital marketing training'],
    confidenceLevel: 'high',
    summary: 'Started a $10K/month SEO consulting and training business.',
  },
  {
    companyName: 'Ellen Yin Media',
    industry: 'services',
    subIndustry: 'business_coaching',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Building audience', 'Creating curriculum', 'Member retention'],
      capabilities: ['Marketing expertise', 'Content creation'],
      marketPosition: 'New online business coach',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '2_5',
      revenueGrowth: 'Six figures',
      achievements: ['Six-figure membership', 'Helps coaches hit $10K months', 'Community built'],
      newCapabilities: ['Membership model', 'Community management'],
      marketPosition: 'Coach for service providers',
    },
    strategyType: 'membership_model',
    expansionType: 'horizontal',
    targetMarket: 'coaches_service_providers',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built membership community', impact: 'Recurring revenue model', difficulty: 'moderate' },
      { action: 'Focused on $10K month milestone', impact: 'Clear transformation promise', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Clear outcome-based promises attract committed members.',
    sourceUrl: 'https://www.starterstory.com/how-to-launch-online-course-for-marketers-consultants',
    sourcePlatform: 'starter_story',
    tags: ['coaching', 'membership', 'online_business', 'service_providers'],
    matchingKeywords: ['business coaching', 'online membership', 'service provider coaching'],
    confidenceLevel: 'high',
    summary: 'Launched a six-figure online membership helping coaches hit their first $10K month.',
  },

  // ===== Subscription Box =====
  {
    companyName: 'Atlas Coffee Club',
    industry: 'ecommerce',
    subIndustry: 'subscription_box',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Supply chain', 'Customer acquisition', 'Retention'],
      capabilities: ['Coffee expertise', 'E-commerce knowledge'],
      marketPosition: 'New coffee subscription',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '11_20',
      revenueGrowth: '$22M ARR ($1.83M/month)',
      achievements: ['$22M ARR', 'Global coffee sourcing', 'Strong subscription base'],
      newCapabilities: ['Global sourcing', 'Subscription optimization'],
      marketPosition: 'Leading coffee subscription service',
    },
    strategyType: 'subscription_growth',
    expansionType: 'horizontal',
    targetMarket: 'coffee_lovers',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Built world tour coffee concept', impact: 'Unique value proposition', difficulty: 'moderate' },
      { action: 'Optimized subscription retention', impact: 'Strong recurring revenue', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 200 },
    lessonsLearned: 'Subscription businesses thrive with unique value props and retention focus.',
    sourceUrl: 'https://www.starterstory.com/atlas-coffee-club-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['subscription', 'coffee', 'ecommerce', 'recurring_revenue'],
    matchingKeywords: ['coffee subscription', 'subscription box', 'coffee club'],
    confidenceLevel: 'high',
    summary: 'Transformed a coffee subscription business to $22M ARR.',
  },
];

export async function seedBatch6() {
  console.log('🌱 Seeding Batch 6: SaaS, Home Services, Automotive, Real Estate, Agencies, Consulting, Subscription...');

  let successCount = 0;
  let errorCount = 0;

  for (const study of batch6CaseStudies) {
    try {
      await db.insert(caseStudies).values(study as CaseStudyInsert);
      successCount++;
      console.log(`  ✓ ${study.companyName}`);
    } catch (error) {
      errorCount++;
      console.error(`  ✗ ${study.companyName}:`, error instanceof Error ? error.message : 'Unknown error');
    }
  }

  console.log(`\nBatch 6 seeding complete!`);
  console.log(`✓ Successfully seeded: ${successCount}`);
  console.log(`✗ Errors: ${errorCount}`);

  return { success: successCount, errors: errorCount };
}

// Run if called directly
seedBatch6()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
