import { db } from '../../lib/db';
import { caseStudies } from '../schema';

type KeyAction = {
  action: string;
  impact: string;
  difficulty?: 'easy' | 'moderate' | 'hard';
};

const batch4CaseStudies = [
  // ========== PET SERVICES ==========
  {
    companyName: 'Furry Fellas Pet Service',
    industry: 'pet_services',
    subIndustry: 'pet_sitting',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Building trust', 'Scaling service', 'Staffing'],
      capabilities: ['Animal care', 'Customer service'],
      marketPosition: 'Local pet sitter',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '11_25',
      revenueGrowth: '20x+',
      achievements: ['$54K/month revenue', '15+ years in business', 'Online store launched'],
      newCapabilities: ['Pet sitting', 'Dog walking', 'Pet products retail'],
      marketPosition: 'Established pet services company',
    },
    strategyType: 'service_business',
    expansionType: 'horizontal',
    targetMarket: 'pet_owners',
    timeline: { totalMonths: 180 },
    keyActions: [
      { action: 'Started pet sitting and dog walking', impact: 'Initial revenue', difficulty: 'easy' },
      { action: 'Built team of pet care professionals', impact: 'Scalability', difficulty: 'moderate' },
      { action: 'Launched online pet products store', impact: 'New revenue stream', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Pet services can evolve into multi-channel businesses over time.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-pet-sitting-dog-walking',
    sourcePlatform: 'starter_story',
    tags: ['pet_services', 'pet_sitting', 'dog_walking', 'ecommerce'],
    matchingKeywords: ['pet sitting', 'dog walking', 'pet care'],
    confidenceLevel: 'high',
    summary: 'Melodi Landi built Furry Fellas to $54K/month pet sitting and dog walking business.',
  },
  {
    companyName: 'Pawstruck',
    industry: 'ecommerce',
    subIndustry: 'pet_products',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Product sourcing', 'Competition from Amazon', 'Brand building'],
      capabilities: ['Ecommerce knowledge', 'Pet industry passion'],
      marketPosition: 'New pet supplies seller',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '11_25',
      revenueGrowth: '100x+',
      achievements: ['$7M+ revenue increase in 2 years', 'Major pet supplies brand'],
      newCapabilities: ['Private label products', 'Subscription model', 'Multi-channel retail'],
      marketPosition: 'Leading online pet supplies brand',
    },
    strategyType: 'ecommerce_brand',
    expansionType: 'product',
    targetMarket: 'pet_owners',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Started selling pet supplies online', impact: 'Market entry', difficulty: 'moderate' },
      { action: 'Developed private label products', impact: 'Better margins', difficulty: 'hard' },
      { action: 'Scaled marketing and operations', impact: 'Rapid growth', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Pet ecommerce can scale massively with the right product focus.',
    sourceUrl: 'https://www.starterstory.com/stories/how-we-increased-our-revenue-by-7m-in-two-years',
    sourcePlatform: 'starter_story',
    tags: ['ecommerce', 'pet_products', 'dtc'],
    matchingKeywords: ['pet supplies', 'dog treats', 'pet ecommerce'],
    confidenceLevel: 'high',
    summary: 'Kyle Goguen increased Pawstruck revenue by $7M in 2 years.',
  },
  {
    companyName: 'Animal Behavior College',
    industry: 'education',
    subIndustry: 'pet_education',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Curriculum development', 'Accreditation', 'Student recruitment'],
      capabilities: ['Animal expertise', 'Education background'],
      marketPosition: 'New animal education provider',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '50_100',
      revenueGrowth: '100x+',
      achievements: ['$1M/month revenue', '72 employees', 'Leading animal career school'],
      newCapabilities: ['Multiple certifications', 'Online learning', 'Job placement'],
      marketPosition: 'Leading animal career training school',
    },
    strategyType: 'education_business',
    expansionType: 'product',
    targetMarket: 'career_changers',
    timeline: { totalMonths: 240 },
    keyActions: [
      { action: 'Created animal training certifications', impact: 'Core product', difficulty: 'hard' },
      { action: 'Built online learning platform', impact: 'Scalability', difficulty: 'hard' },
      { action: 'Expanded to multiple animal careers', impact: 'Market size', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Career education in growing industries can build substantial businesses.',
    sourceUrl: 'https://www.starterstory.com/animal-behavior',
    sourcePlatform: 'starter_story',
    tags: ['education', 'pet_industry', 'career_training', 'online_learning'],
    matchingKeywords: ['animal training', 'pet career', 'dog training certification'],
    confidenceLevel: 'high',
    summary: 'Steven Applebaum built Animal Behavior College to $1M/month.',
  },
  {
    companyName: 'Stringtown Animal Hospital',
    industry: 'healthcare',
    subIndustry: 'veterinary',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Equipment costs', 'Building clientele', 'Staffing'],
      capabilities: ['Veterinary medicine', 'Animal care passion'],
      marketPosition: 'New veterinary practice',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '11_25',
      revenueGrowth: '30x+',
      achievements: ['$200K/month revenue', 'Full-service animal hospital'],
      newCapabilities: ['Surgery', 'Emergency care', 'Specialty services'],
      marketPosition: 'Established veterinary hospital',
    },
    strategyType: 'professional_practice',
    expansionType: 'service',
    targetMarket: 'pet_owners',
    timeline: { totalMonths: 120 },
    keyActions: [
      { action: 'Started veterinary practice', impact: 'Core service', difficulty: 'hard' },
      { action: 'Added specialty services', impact: 'Higher revenue per visit', difficulty: 'moderate' },
      { action: 'Built loyal client base', impact: 'Recurring revenue', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 30 },
    lessonsLearned: 'Veterinary practices can build significant revenue with quality care.',
    sourceUrl: 'https://www.starterstory.com/love-animals-start-veterinary-hospital',
    sourcePlatform: 'starter_story',
    tags: ['veterinary', 'healthcare', 'pet_services'],
    matchingKeywords: ['veterinary', 'animal hospital', 'pet healthcare'],
    confidenceLevel: 'high',
    summary: 'Stringtown Animal Hospital grew to $200K/month veterinary practice.',
  },
  {
    companyName: 'The Cat Cafe',
    industry: 'food_service',
    subIndustry: 'cafe',
    location: 'California, USA',
    startingState: {
      revenue: 'zero',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Health regulations', 'Cat care', 'Unique concept marketing'],
      capabilities: ['Hospitality', 'Animal welfare passion'],
      marketPosition: 'First cat cafe in Southern California',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '6_10',
      revenueGrowth: 'startup_to_profit',
      achievements: ['$40K/month revenue', 'First cat cafe in SoCal', 'Cat adoption partner'],
      newCapabilities: ['Cafe operations', 'Cat adoption program', 'Event hosting'],
      marketPosition: 'Pioneer cat cafe in region',
    },
    strategyType: 'niche_concept',
    expansionType: 'local',
    targetMarket: 'cat_lovers',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Created first cat cafe in region', impact: 'First mover advantage', difficulty: 'hard' },
      { action: 'Partnered with cat rescue', impact: 'Mission alignment', difficulty: 'easy' },
      { action: 'Built community around concept', impact: 'Customer loyalty', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 40 },
    lessonsLearned: 'Unique cafe concepts can succeed by combining experience with purpose.',
    sourceUrl: 'https://www.starterstory.com/stories/the-cat-cafe',
    sourcePlatform: 'starter_story',
    tags: ['cafe', 'cats', 'adoption', 'hospitality'],
    matchingKeywords: ['cat cafe', 'cat adoption', 'cafe'],
    confidenceLevel: 'high',
    summary: 'The Cat Cafe became first in SoCal with $40K/month revenue.',
  },

  // ========== PHOTOGRAPHY ==========
  {
    companyName: 'Studio 31',
    industry: 'photography',
    subIndustry: 'wedding_photography',
    location: 'India',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Competition', 'Pricing', 'Scaling creative work'],
      capabilities: ['Photography', 'Business mindset'],
      marketPosition: 'New wedding photographer',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '11_25',
      revenueGrowth: '20x+',
      achievements: ['$50K/month revenue', 'Startup-like operations', 'Team of photographers'],
      newCapabilities: ['Team management', 'Workflow automation', 'Multiple simultaneous weddings'],
      marketPosition: 'Leading wedding studio in region',
    },
    strategyType: 'scalable_service',
    expansionType: 'team',
    targetMarket: 'couples',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built wedding photography studio', impact: 'Initial revenue', difficulty: 'moderate' },
      { action: 'Systematized operations like a startup', impact: 'Scalability', difficulty: 'hard' },
      { action: 'Built team of photographers', impact: 'Capacity', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Photography studios can scale with startup mentality and systems.',
    sourceUrl: 'https://www.starterstory.com/how-to-run-a-wedding-photography-studio',
    sourcePlatform: 'starter_story',
    tags: ['photography', 'wedding', 'creative_services'],
    matchingKeywords: ['wedding photography', 'photography studio'],
    confidenceLevel: 'high',
    summary: 'Pranesh built Studio 31 to $50K/month wedding photography studio.',
  },
  {
    companyName: 'Results Imagery',
    industry: 'photography',
    subIndustry: 'product_photography',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Equipment costs', 'Client acquisition', 'Quality consistency'],
      capabilities: ['Photography', 'Video production'],
      marketPosition: 'New product photography company',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '6_10',
      revenueGrowth: '15x+',
      achievements: ['$45K/month revenue', 'Product photography and video studio'],
      newCapabilities: ['Video production', 'Amazon photography', 'E-commerce content'],
      marketPosition: 'Established product content studio',
    },
    strategyType: 'service_business',
    expansionType: 'service',
    targetMarket: 'ecommerce_brands',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Started product photography company', impact: 'Core service', difficulty: 'moderate' },
      { action: 'Added video production', impact: 'Higher value services', difficulty: 'moderate' },
      { action: 'Focused on e-commerce clients', impact: 'Recurring work', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 15 },
    lessonsLearned: 'Product photography for e-commerce is a growing opportunity.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-product-photography-company',
    sourcePlatform: 'starter_story',
    tags: ['photography', 'product_photography', 'ecommerce'],
    matchingKeywords: ['product photography', 'Amazon photography', 'ecommerce content'],
    confidenceLevel: 'high',
    summary: 'Kyle Nelson built Results Imagery to $45K/month product photography.',
  },
  {
    companyName: 'Puptrait Studio',
    industry: 'photography',
    subIndustry: 'pet_photography',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Niche market', 'Pet behavior', 'Marketing'],
      capabilities: ['Photography', 'Animal handling'],
      marketPosition: 'New pet photographer',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: 'solo',
      revenueGrowth: '10x+',
      achievements: ['$10K/month revenue', 'Specialized pet photography studio'],
      newCapabilities: ['Pet handling expertise', 'Niche marketing'],
      marketPosition: 'Established pet photography studio',
    },
    strategyType: 'niche_specialization',
    expansionType: 'local',
    targetMarket: 'pet_owners',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Specialized in pet photography', impact: 'Niche differentiation', difficulty: 'moderate' },
      { action: 'Built pet handling skills', impact: 'Quality results', difficulty: 'moderate' },
      { action: 'Marketing to pet communities', impact: 'Client acquisition', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Pet photography is a viable niche for photographers who love animals.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-pet-photography-studio',
    sourcePlatform: 'starter_story',
    tags: ['photography', 'pet_photography', 'niche'],
    matchingKeywords: ['pet photography', 'dog photography', 'animal portraits'],
    confidenceLevel: 'high',
    summary: 'J.B. Shepard built Puptrait to $10K/month pet photography studio.',
  },
  {
    companyName: 'Sophie Crew Photography',
    industry: 'photography',
    subIndustry: 'newborn_photography',
    location: 'San Diego, USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Newborn safety', 'Timing', 'Marketing to parents'],
      capabilities: ['Photography', 'Patience with babies'],
      marketPosition: 'New newborn photographer',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: 'solo',
      revenueGrowth: '10x+',
      achievements: ['$10K/month revenue', 'Specialized newborn studio'],
      newCapabilities: ['Newborn posing expertise', 'Parent marketing'],
      marketPosition: 'Established newborn photographer',
    },
    strategyType: 'niche_specialization',
    expansionType: 'local',
    targetMarket: 'new_parents',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Specialized in newborn photography', impact: 'Niche expertise', difficulty: 'moderate' },
      { action: 'Built reputation with quality work', impact: 'Referrals', difficulty: 'moderate' },
      { action: 'Premium pricing strategy', impact: 'Profitability', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Newborn photography commands premium prices with specialized skills.',
    sourceUrl: 'https://www.starterstory.com/stories/sophie-crew-photography',
    sourcePlatform: 'starter_story',
    tags: ['photography', 'newborn', 'portrait'],
    matchingKeywords: ['newborn photography', 'baby photography', 'portrait'],
    confidenceLevel: 'high',
    summary: 'Sophie Britton built $10K/month newborn photography studio in San Diego.',
  },
  {
    companyName: 'picjumbo',
    industry: 'media',
    subIndustry: 'stock_photography',
    location: 'Europe',
    startingState: {
      revenue: 'zero',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Competition from stock giants', 'Traffic generation', 'Monetization'],
      capabilities: ['Photography', 'Web development'],
      marketPosition: 'New stock photo site',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: 'solo',
      revenueGrowth: 'startup_to_profit',
      achievements: ['$120K/year revenue', 'Popular free stock photo site', 'Solo founder success'],
      newCapabilities: ['Freemium model', 'SEO traffic', 'Premium collections'],
      marketPosition: 'Popular stock photography platform',
    },
    strategyType: 'freemium',
    expansionType: 'digital',
    targetMarket: 'designers',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Created free stock photo website', impact: 'Traffic and awareness', difficulty: 'moderate' },
      { action: 'Added premium collections', impact: 'Monetization', difficulty: 'easy' },
      { action: 'Built SEO traffic', impact: 'Sustainable growth', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Solo founders can build profitable stock photography sites.',
    sourceUrl: 'https://www.starterstory.com/stories/picjumbo-ddaf231a-aed2-443e-b4f7-d6437d35243a',
    sourcePlatform: 'starter_story',
    tags: ['stock_photography', 'freemium', 'solo_founder'],
    matchingKeywords: ['stock photos', 'free photos', 'photography'],
    confidenceLevel: 'high',
    summary: 'Viktor Hanacek built picjumbo to $120K/year stock photo site as solo founder.',
  },

  // ========== FOOD & RESTAURANT ==========
  {
    companyName: 'Kyra\'s Bake Shop',
    industry: 'food_service',
    subIndustry: 'bakery',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Recipe development', 'Scaling production', 'Marketing'],
      capabilities: ['Baking expertise', 'Gluten-free specialty'],
      marketPosition: 'Home baker',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '11_25',
      revenueGrowth: '30x+',
      achievements: ['$120K/month revenue', 'Award-winning pastries', 'Gluten-free specialty'],
      newCapabilities: ['Commercial kitchen', 'Wholesale', 'Online sales'],
      marketPosition: 'Award-winning bakery',
    },
    strategyType: 'product_excellence',
    expansionType: 'channel',
    targetMarket: 'gluten_free_consumers',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Created award-winning gluten-free pastries', impact: 'Product differentiation', difficulty: 'hard' },
      { action: 'Won baking competitions', impact: 'Credibility and PR', difficulty: 'moderate' },
      { action: 'Scaled to commercial production', impact: 'Revenue growth', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 30 },
    lessonsLearned: 'Specialty dietary bakeries can build significant businesses.',
    sourceUrl: 'https://www.starterstory.com/gluten-free-pastries-cupcakes',
    sourcePlatform: 'starter_story',
    tags: ['bakery', 'gluten_free', 'food_service'],
    matchingKeywords: ['gluten-free bakery', 'pastries', 'cupcakes'],
    confidenceLevel: 'high',
    summary: 'Kyra Johnson built $120K/month award-winning gluten-free bakery.',
  },
  {
    companyName: 'New York Food Truck Association',
    industry: 'food_service',
    subIndustry: 'food_truck',
    location: 'New York, USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['NYC regulations', 'Vendor coordination', 'Corporate clients'],
      capabilities: ['Food industry knowledge', 'Event planning'],
      marketPosition: 'New food truck coordinator',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '11_25',
      revenueGrowth: '50x+',
      achievements: ['$200K/month revenue', 'NYC food truck industry leader'],
      newCapabilities: ['Corporate catering', 'Event coordination', 'Vendor network'],
      marketPosition: 'Leading NYC food truck association',
    },
    strategyType: 'platform_play',
    expansionType: 'network',
    targetMarket: 'corporate_events',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Created food truck association', impact: 'Industry organization', difficulty: 'moderate' },
      { action: 'Built corporate event services', impact: 'High-value clients', difficulty: 'hard' },
      { action: 'Coordinated large-scale events', impact: 'Revenue scale', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Organizing an industry can be more lucrative than participating in it.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-food-truck-association',
    sourcePlatform: 'starter_story',
    tags: ['food_truck', 'events', 'catering', 'nyc'],
    matchingKeywords: ['food truck', 'catering', 'corporate events'],
    confidenceLevel: 'high',
    summary: 'Jen and Ben Goldberg built NYC Food Truck Association to $200K/month.',
  },
  {
    companyName: 'Roaming Hunger',
    industry: 'food_service',
    subIndustry: 'food_truck_platform',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Two-sided marketplace', 'Trust building', 'Scaling'],
      capabilities: ['Tech development', 'Food industry passion'],
      marketPosition: 'New food truck marketplace',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '50_100',
      revenueGrowth: '200x+',
      achievements: ['$18M business', 'Corporate food truck booking platform'],
      newCapabilities: ['National network', 'Corporate account management', 'Technology platform'],
      marketPosition: 'Leading food truck booking platform',
    },
    strategyType: 'marketplace',
    expansionType: 'geographic',
    targetMarket: 'corporations',
    timeline: { totalMonths: 120 },
    keyActions: [
      { action: 'Built food truck booking platform', impact: 'Two-sided marketplace', difficulty: 'hard' },
      { action: 'Focused on corporate events', impact: 'High-value clients', difficulty: 'hard' },
      { action: 'Scaled nationally', impact: 'Market dominance', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 200 },
    lessonsLearned: 'Food truck marketplaces can scale massively with corporate focus.',
    sourceUrl: 'https://www.starterstory.com/stories/how-i-took-food-trucks-corporate-and-built-a-18m-business',
    sourcePlatform: 'starter_story',
    tags: ['food_truck', 'marketplace', 'corporate', 'platform'],
    matchingKeywords: ['food truck booking', 'catering platform', 'corporate catering'],
    confidenceLevel: 'high',
    summary: 'Jeffrey Mora built Roaming Hunger food truck platform to $18M business.',
  },
  {
    companyName: 'Pastreez',
    industry: 'food_service',
    subIndustry: 'online_bakery',
    location: 'USA',
    startingState: {
      revenue: 'zero',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Shipping baked goods', 'Building brand in new country', 'Competition'],
      capabilities: ['French pastry expertise', 'Ecommerce knowledge'],
      marketPosition: 'New online French bakery',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '2_5',
      revenueGrowth: 'startup_to_profit',
      achievements: ['Six-figure revenue', 'Online French bakery', 'American Dream achieved'],
      newCapabilities: ['Shipping nationwide', 'Online marketing', 'Gift market'],
      marketPosition: 'Established online French bakery',
    },
    strategyType: 'ecommerce',
    expansionType: 'digital',
    targetMarket: 'food_lovers',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Created authentic French pastry brand', impact: 'Differentiation', difficulty: 'moderate' },
      { action: 'Solved shipping challenges', impact: 'National reach', difficulty: 'hard' },
      { action: 'Targeted gift market', impact: 'Higher margins', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Authentic cuisine can be shipped nationwide with the right approach.',
    sourceUrl: 'https://www.starterstory.com/stories/pastreez',
    sourcePlatform: 'starter_story',
    tags: ['bakery', 'ecommerce', 'french', 'food'],
    matchingKeywords: ['French bakery', 'online bakery', 'macarons'],
    confidenceLevel: 'high',
    summary: 'French couple built Pastreez to six-figure online bakery in USA.',
  },
  {
    companyName: 'Cape Whoopies',
    industry: 'food_service',
    subIndustry: 'specialty_bakery',
    location: 'Maine, USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Scaling home kitchen', 'Seasonal business', 'Marketing'],
      capabilities: ['Baking', 'Family recipes'],
      marketPosition: 'Home kitchen bakery',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '2_5',
      revenueGrowth: '10x+',
      achievements: ['$300K/year revenue', '75% growth through organic marketing'],
      newCapabilities: ['Social media marketing', 'SEO', 'Wholesale'],
      marketPosition: 'Established Maine whoopie pie brand',
    },
    strategyType: 'organic_growth',
    expansionType: 'digital',
    targetMarket: 'food_lovers',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Started baking whoopie pies from home', impact: 'Initial product', difficulty: 'easy' },
      { action: 'Grew 75% through social media and SEO', impact: 'Organic acquisition', difficulty: 'moderate' },
      { action: 'Built wholesale relationships', impact: 'B2B revenue', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Regional specialty foods can grow significantly with organic marketing.',
    sourceUrl: 'https://www.starterstory.com/stories/cape-whoopies',
    sourcePlatform: 'starter_story',
    tags: ['bakery', 'specialty_food', 'organic_marketing'],
    matchingKeywords: ['whoopie pies', 'Maine bakery', 'specialty desserts'],
    confidenceLevel: 'high',
    summary: 'Marcia Wiggins grew Cape Whoopies to $300K/year through organic marketing.',
  },

  // ========== NEWSLETTERS ==========
  {
    companyName: 'ConvertKit',
    industry: 'saas',
    subIndustry: 'email_marketing',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Competing with Mailchimp', 'Building platform', 'Finding niche'],
      capabilities: ['Software development', 'Creator understanding'],
      marketPosition: 'Solo founder side project',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '50_100',
      revenueGrowth: '500x+',
      achievements: ['$25M/year revenue', 'Leading creator email platform'],
      newCapabilities: ['Full email platform', 'Landing pages', 'Commerce features'],
      marketPosition: 'Leading email platform for creators',
    },
    strategyType: 'niche_saas',
    expansionType: 'product',
    targetMarket: 'creators',
    timeline: { totalMonths: 120 },
    keyActions: [
      { action: 'Built email tool for creators', impact: 'Niche focus', difficulty: 'hard' },
      { action: 'Grew through creator partnerships', impact: 'Organic growth', difficulty: 'moderate' },
      { action: 'Expanded product features', impact: 'Increased LTV', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 500 },
    lessonsLearned: 'Focusing on a specific audience (creators) can beat generic competitors.',
    sourceUrl: 'https://www.starterstory.com/stories/convertkit-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'email_marketing', 'creators', 'bootstrap'],
    matchingKeywords: ['email marketing', 'newsletter platform', 'creators'],
    confidenceLevel: 'high',
    summary: 'Nathan Barry built ConvertKit from solopreneur to $25M/year.',
  },
  {
    companyName: 'Marketing Examined',
    industry: 'media',
    subIndustry: 'newsletter',
    location: 'USA',
    startingState: {
      revenue: 'zero',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Building audience', 'Monetization', 'Content creation'],
      capabilities: ['Marketing expertise', 'Writing ability'],
      marketPosition: 'New marketing newsletter',
    },
    endingState: {
      revenue: '1m_2.5m',
      teamSize: '2_5',
      revenueGrowth: 'startup_to_$1m_arr',
      achievements: ['$1M ARR in months', 'Leading marketing newsletter'],
      newCapabilities: ['Sponsorships', 'Premium content', 'Community'],
      marketPosition: 'Top marketing newsletter',
    },
    strategyType: 'content_led_growth',
    expansionType: 'audience',
    targetMarket: 'marketers',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Created valuable marketing content', impact: 'Audience building', difficulty: 'moderate' },
      { action: 'Grew rapidly through quality', impact: 'Subscriber growth', difficulty: 'moderate' },
      { action: 'Monetized with sponsorships', impact: 'Revenue', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Quality marketing newsletters can reach $1M ARR quickly.',
    sourceUrl: 'https://www.starterstory.com/marketing-examined-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['newsletter', 'marketing', 'content', 'media'],
    matchingKeywords: ['marketing newsletter', 'email newsletter'],
    confidenceLevel: 'high',
    summary: 'Alex Garcia grew Marketing Examined newsletter to $1M ARR in months.',
  },
  {
    companyName: 'YOLO Intel',
    industry: 'media',
    subIndustry: 'travel_newsletter',
    location: 'USA',
    startingState: {
      revenue: 'zero',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Job loss motivation', 'Building audience', 'Monetization'],
      capabilities: ['Travel expertise', 'Writing'],
      marketPosition: 'New travel newsletter',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: 'solo',
      revenueGrowth: 'startup_to_$20k_mo',
      achievements: ['$20K/month revenue', 'Top travel newsletter on Substack'],
      newCapabilities: ['Substack growth', 'Travel deals curation'],
      marketPosition: 'Leading travel deals newsletter',
    },
    strategyType: 'content_led_growth',
    expansionType: 'audience',
    targetMarket: 'travelers',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Started travel newsletter after job loss', impact: 'Content creation', difficulty: 'moderate' },
      { action: 'Curated best travel deals', impact: 'Value proposition', difficulty: 'moderate' },
      { action: 'Grew to top Substack travel newsletter', impact: 'Platform success', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Job loss can be the motivation to build newsletter business.',
    sourceUrl: 'https://www.starterstory.com/stories/yolo-intel',
    sourcePlatform: 'starter_story',
    tags: ['newsletter', 'travel', 'substack'],
    matchingKeywords: ['travel newsletter', 'travel deals', 'Substack'],
    confidenceLevel: 'high',
    summary: 'Yolanda Edwards built YOLO Intel to $20K/month after losing her job.',
  },
  {
    companyName: 'Alpha Letter',
    industry: 'media',
    subIndustry: 'finance_newsletter',
    location: 'USA',
    startingState: {
      revenue: 'zero',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Building Twitter audience', 'Finance expertise sharing', 'Monetization'],
      capabilities: ['Finance knowledge', 'Social media savvy'],
      marketPosition: 'Finance Twitter account',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: 'solo',
      revenueGrowth: 'startup_to_$420k_year',
      achievements: ['$420K/year revenue', 'Twitter audience leverage'],
      newCapabilities: ['Newsletter monetization', 'Community building'],
      marketPosition: 'Popular finance newsletter',
    },
    strategyType: 'audience_first',
    expansionType: 'monetization',
    targetMarket: 'investors',
    timeline: { totalMonths: 18 },
    keyActions: [
      { action: 'Built Twitter audience in finance', impact: 'Distribution channel', difficulty: 'moderate' },
      { action: 'Launched newsletter to monetize', impact: 'Revenue generation', difficulty: 'moderate' },
      { action: 'Provided investment research', impact: 'Value delivery', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Twitter audiences can be leveraged into substantial newsletter revenue.',
    sourceUrl: 'https://www.starterstory.com/stories/alpha-letter',
    sourcePlatform: 'starter_story',
    tags: ['newsletter', 'finance', 'investing', 'twitter'],
    matchingKeywords: ['finance newsletter', 'investment research'],
    confidenceLevel: 'high',
    summary: 'Pseudonymous founder leveraged Twitter to build $420K/year Alpha Letter.',
  },
  {
    companyName: 'No Code Exits',
    industry: 'media',
    subIndustry: 'tech_newsletter',
    location: 'USA',
    startingState: {
      revenue: 'zero',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Finding niche', 'Content creation', 'Monetization'],
      capabilities: ['No-code expertise', 'Writing'],
      marketPosition: 'New no-code newsletter',
    },
    endingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      revenueGrowth: 'startup_to_$33k',
      achievements: ['$33K revenue', 'Built with no-code tools'],
      newCapabilities: ['Newsletter business', 'Community building'],
      marketPosition: 'Established no-code community newsletter',
    },
    strategyType: 'niche_content',
    expansionType: 'audience',
    targetMarket: 'no_code_builders',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Created no-code focused newsletter', impact: 'Niche audience', difficulty: 'moderate' },
      { action: 'Used no-code tools to build business', impact: 'Meta demonstration', difficulty: 'easy' },
      { action: 'Curated no-code success stories', impact: 'Valuable content', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Niche newsletters can be profitable even at smaller scales.',
    sourceUrl: 'https://www.starterstory.com/no-code-exits-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['newsletter', 'no_code', 'tech'],
    matchingKeywords: ['no-code', 'newsletter', 'startup exits'],
    confidenceLevel: 'high',
    summary: 'Katt Risen built No Code Exits newsletter to $33K using no-code tools.',
  },

  // ========== ECOMMERCE / RETAIL ==========
  {
    companyName: 'Allbirds',
    industry: 'ecommerce',
    subIndustry: 'footwear',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Manufacturing', 'Brand building', 'Competition'],
      capabilities: ['Product design', 'Sustainability focus'],
      marketPosition: 'New sustainable shoe brand',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '100_plus',
      revenueGrowth: '1000x+',
      achievements: ['$600M+ valuation', '$20M/month revenue', 'Iconic sustainable brand'],
      newCapabilities: ['Sustainable materials', 'DTC mastery', 'Global retail'],
      marketPosition: 'Leading sustainable footwear brand',
    },
    strategyType: 'dtc_brand',
    expansionType: 'product',
    targetMarket: 'eco_conscious_consumers',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Created sustainable wool shoes', impact: 'Product differentiation', difficulty: 'hard' },
      { action: 'Built DTC brand', impact: 'Direct customer relationships', difficulty: 'hard' },
      { action: 'Expanded product line', impact: 'Revenue growth', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'Sustainable products with great design can build billion-dollar brands.',
    sourceUrl: 'https://www.starterstory.com/allbirds-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['ecommerce', 'footwear', 'sustainable', 'dtc'],
    matchingKeywords: ['sustainable shoes', 'wool shoes', 'DTC footwear'],
    confidenceLevel: 'high',
    summary: 'Tim Brown built Allbirds from bootstrapped idea to $600M+ shoe brand.',
  },
  {
    companyName: 'Boll & Branch',
    industry: 'ecommerce',
    subIndustry: 'bedding',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Manufacturing', 'Luxury positioning', 'Trust building'],
      capabilities: ['Business background', 'Quality focus'],
      marketPosition: 'New luxury bedding brand',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '100_plus',
      revenueGrowth: '400x+',
      achievements: ['$200M revenue', '$16.7M/month', 'Luxury bedding empire'],
      newCapabilities: ['Ethical sourcing', 'Premium DTC', 'Product expansion'],
      marketPosition: 'Leading luxury bedding brand',
    },
    strategyType: 'luxury_dtc',
    expansionType: 'product',
    targetMarket: 'affluent_consumers',
    timeline: { totalMonths: 120 },
    keyActions: [
      { action: 'Created ethical luxury bedding', impact: 'Premium positioning', difficulty: 'hard' },
      { action: 'Built direct-to-consumer brand', impact: 'Customer relationships', difficulty: 'hard' },
      { action: 'Expanded product categories', impact: 'Lifetime value', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 400 },
    lessonsLearned: 'Luxury DTC brands can build massive businesses with quality and ethics.',
    sourceUrl: 'https://www.starterstory.com/boll-branch-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['ecommerce', 'bedding', 'luxury', 'dtc'],
    matchingKeywords: ['luxury bedding', 'sheets', 'DTC home'],
    confidenceLevel: 'high',
    summary: 'Scott Tannen built Boll & Branch luxury bedding to $200M revenue.',
  },
  {
    companyName: 'Tini Lux',
    industry: 'ecommerce',
    subIndustry: 'jewelry',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Niche product', 'Manufacturing', 'Marketing'],
      capabilities: ['Product development', 'Ecommerce'],
      marketPosition: 'New hypoallergenic earring brand',
    },
    endingState: {
      revenue: '2.5m_5m',
      teamSize: '6_10',
      revenueGrowth: '100x+',
      achievements: ['$4M/year revenue', '10x growth', 'Niche market leader'],
      newCapabilities: ['Product line expansion', 'DTC marketing'],
      marketPosition: 'Leading hypoallergenic earring brand',
    },
    strategyType: 'niche_ecommerce',
    expansionType: 'product',
    targetMarket: 'sensitive_skin_consumers',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Created hypoallergenic earrings', impact: 'Niche solution', difficulty: 'moderate' },
      { action: 'Grew over 10x', impact: 'Market dominance', difficulty: 'hard' },
      { action: 'Expanded product line', impact: 'Revenue growth', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Solving specific pain points creates loyal niche customer bases.',
    sourceUrl: 'https://www.starterstory.com/stories/how-i-launched-a-profitable-earrings-business-in-one-year',
    sourcePlatform: 'starter_story',
    tags: ['ecommerce', 'jewelry', 'niche', 'dtc'],
    matchingKeywords: ['hypoallergenic earrings', 'jewelry', 'sensitive skin'],
    confidenceLevel: 'high',
    summary: 'Jackie Burke grew Tini Lux niche earring brand over 10x to $4M/year.',
  },
  {
    companyName: 'Cotopaxi',
    industry: 'ecommerce',
    subIndustry: 'outdoor_gear',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Competing with established brands', 'Supply chain', 'Mission integration'],
      capabilities: ['Outdoor industry knowledge', 'Social mission focus'],
      marketPosition: 'New outdoor gear brand',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '50_100',
      revenueGrowth: '200x+',
      achievements: ['Major outdoor gear brand', 'B Corp certified', 'Humanitarian mission'],
      newCapabilities: ['Product development', 'Retail partnerships', 'Mission marketing'],
      marketPosition: 'Leading mission-driven outdoor brand',
    },
    strategyType: 'mission_driven',
    expansionType: 'product',
    targetMarket: 'conscious_outdoor_enthusiasts',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Created mission-driven outdoor brand', impact: 'Differentiation', difficulty: 'hard' },
      { action: 'Built humanitarian focus into business', impact: 'Brand loyalty', difficulty: 'moderate' },
      { action: 'Expanded product line', impact: 'Revenue growth', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 200 },
    lessonsLearned: 'Mission-driven brands attract loyal customers and employees.',
    sourceUrl: 'https://www.starterstory.com/davis-smith',
    sourcePlatform: 'starter_story',
    tags: ['ecommerce', 'outdoor_gear', 'mission_driven', 'b_corp'],
    matchingKeywords: ['outdoor gear', 'backpacks', 'sustainable'],
    confidenceLevel: 'high',
    summary: 'Davis Smith built Cotopaxi outdoor brand with humanitarian mission.',
  },

  // ========== SUBSCRIPTION BOXES ==========
  {
    companyName: 'Atlas Coffee Club',
    industry: 'ecommerce',
    subIndustry: 'coffee_subscription',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: 'solo',
      yearsInBusiness: 0,
      challenges: ['Sourcing coffee', 'Subscription logistics', 'Competition'],
      capabilities: ['Coffee expertise', 'Ecommerce'],
      marketPosition: 'New coffee subscription',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '26_50',
      revenueGrowth: '200x+',
      achievements: ['$22M ARR', 'World coffee exploration concept'],
      newCapabilities: ['Global sourcing', 'Subscription optimization', 'Gift market'],
      marketPosition: 'Leading world coffee subscription',
    },
    strategyType: 'subscription_box',
    expansionType: 'product',
    targetMarket: 'coffee_lovers',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Created world coffee tour concept', impact: 'Unique positioning', difficulty: 'moderate' },
      { action: 'Built subscription infrastructure', impact: 'Recurring revenue', difficulty: 'hard' },
      { action: 'Optimized for gift market', impact: 'New customer acquisition', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 200 },
    lessonsLearned: 'Coffee subscriptions can scale with unique positioning and gift focus.',
    sourceUrl: 'https://www.starterstory.com/atlas-coffee-club-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['subscription', 'coffee', 'ecommerce'],
    matchingKeywords: ['coffee subscription', 'specialty coffee', 'subscription box'],
    confidenceLevel: 'high',
    summary: 'Michael Shewmake built Atlas Coffee Club to $22M ARR.',
  },
  {
    companyName: 'Hemp Crate Co.',
    industry: 'ecommerce',
    subIndustry: 'cbd_subscription',
    location: 'USA',
    startingState: {
      revenue: 'zero',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Regulatory challenges', 'Supplier vetting', 'Marketing restrictions'],
      capabilities: ['CBD industry knowledge', 'Ecommerce'],
      marketPosition: 'New CBD subscription box',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '2_5',
      revenueGrowth: 'startup_to_$50k_mo',
      achievements: ['$50K/month revenue', 'Side hustle success', 'CBD curation expertise'],
      newCapabilities: ['CBD product curation', 'Subscription management'],
      marketPosition: 'Leading CBD subscription box',
    },
    strategyType: 'subscription_box',
    expansionType: 'niche',
    targetMarket: 'cbd_consumers',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Created CBD subscription box', impact: 'Niche market entry', difficulty: 'moderate' },
      { action: 'Curated quality CBD products', impact: 'Trust building', difficulty: 'moderate' },
      { action: 'Built as side hustle', impact: 'Low-risk growth', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Subscription boxes in emerging categories can build quickly.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-subscription-box-side-hustle',
    sourcePlatform: 'starter_story',
    tags: ['subscription', 'cbd', 'side_hustle'],
    matchingKeywords: ['CBD subscription', 'hemp products', 'subscription box'],
    confidenceLevel: 'high',
    summary: 'Ryan Culver built Hemp Crate Co. to $50K/month as side hustle.',
  },
  {
    companyName: 'Bambox',
    industry: 'ecommerce',
    subIndustry: 'baby_subscription',
    location: 'Argentina',
    startingState: {
      revenue: 'zero',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['New parents trust', 'Product curation', 'Subscription logistics'],
      capabilities: ['Baby product knowledge', 'Ecommerce'],
      marketPosition: 'New baby subscription box',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '6_10',
      revenueGrowth: 'startup_to_$60k_mrr',
      achievements: ['$60K MRR', 'Baby subscription leader in region'],
      newCapabilities: ['Baby product curation', 'Parent community'],
      marketPosition: 'Leading baby subscription in Argentina',
    },
    strategyType: 'subscription_box',
    expansionType: 'regional',
    targetMarket: 'new_parents',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Created baby subscription box', impact: 'Market entry', difficulty: 'moderate' },
      { action: 'Curated quality baby products', impact: 'Parent trust', difficulty: 'moderate' },
      { action: 'Built parent community', impact: 'Retention', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 60 },
    lessonsLearned: 'Baby subscription boxes succeed with quality curation and trust.',
    sourceUrl: 'https://www.starterstory.com/baby-subscription-box',
    sourcePlatform: 'starter_story',
    tags: ['subscription', 'baby', 'parenting'],
    matchingKeywords: ['baby subscription', 'baby box', 'new parents'],
    confidenceLevel: 'high',
    summary: 'Charles Carette grew Bambox baby subscription to $60K MRR.',
  },
];

async function seedBatch4() {
  console.log('Seeding case studies batch 4...');
  console.log(`Total case studies to seed: ${batch4CaseStudies.length}`);

  let successCount = 0;
  let errorCount = 0;

  for (const cs of batch4CaseStudies) {
    try {
      await db.insert(caseStudies).values({
        ...cs,
        startingState: cs.startingState,
        endingState: cs.endingState,
        timeline: cs.timeline,
        keyActions: cs.keyActions as KeyAction[],
        outcomes: cs.outcomes,
        pitfalls: [],
      });
      console.log(`✓ Seeded: ${cs.companyName}`);
      successCount++;
    } catch (error: unknown) {
      const err = error as Error;
      console.error(`✗ Error seeding ${cs.companyName}:`, err.message);
      errorCount++;
    }
  }

  console.log(`\nBatch 4 seeding complete!`);
  console.log(`✓ Successfully seeded: ${successCount}`);
  console.log(`✗ Errors: ${errorCount}`);
  process.exit(0);
}

seedBatch4().catch((e) => {
  console.error('Seed failed:', e);
  process.exit(1);
});
