import { db } from '../../lib/db';
import { caseStudies } from '../schema';

type CaseStudyInsert = typeof caseStudies.$inferInsert;

const batch12CaseStudies = [
  // === LOGISTICS / SUPPLY CHAIN ===
  {
    companyName: 'Ecomflow',
    industry: 'logistics',
    subIndustry: 'supply_chain',
    location: 'Netherlands/China',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Supply chain complexity', 'Young founder', 'China operations'],
      capabilities: ['China connections', 'E-commerce knowledge', 'Entrepreneurship'],
      marketPosition: 'New supply chain startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: 'Multi-million dollar business',
      achievements: ['Multi-million revenue by age 26', 'Supply chain expertise', 'Global operations'],
      newCapabilities: ['End-to-end supply chain', 'China sourcing', 'E-commerce fulfillment'],
      marketPosition: 'Established supply chain company',
    },
    strategyType: 'operational_excellence',
    expansionType: 'global',
    targetMarket: 'ecommerce_brands',
    timeline: { totalMonths: 132 },
    keyActions: [
      { action: 'Built multi-million supply chain business by age 26', impact: 'Young success', difficulty: 'hard' },
      { action: 'Leveraged China connections for e-commerce supply chain', impact: 'Competitive advantage', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 500 },
    lessonsLearned: 'Young founders with geographic advantages can build significant businesses.',
    sourceUrl: 'https://www.starterstory.com/ecomflow-com-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['supply_chain', 'ecommerce', 'logistics', 'young_founder'],
    matchingKeywords: ['ecomflow', 'supply chain', 'ecommerce logistics'],
    confidenceLevel: 'high',
    summary: 'Built multi-million supply chain business by age 26.',
  },
  {
    companyName: 'Celigo',
    industry: 'technology',
    subIndustry: 'integration_platform',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Enterprise integration complexity', 'Platform development', 'Market competition'],
      capabilities: ['Integration expertise', 'Technical skills', 'Enterprise knowledge'],
      marketPosition: 'New integration platform',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '500_plus',
      revenueGrowth: '$95M revenue ($7.67M/month)',
      achievements: ['$95M revenue', 'Leading integration platform', 'Enterprise success'],
      newCapabilities: ['iPaaS platform', 'No-code integration', 'Enterprise workflows'],
      marketPosition: 'Leading integration platform',
    },
    strategyType: 'enterprise_saas',
    expansionType: 'enterprise',
    targetMarket: 'enterprises',
    timeline: { totalMonths: 180 },
    keyActions: [
      { action: 'Built iPaaS integration platform to $95M revenue', impact: 'Major scale', difficulty: 'hard' },
      { action: 'Created no-code integration solution for enterprises', impact: 'Market leadership', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'Enterprise integration platforms can achieve massive scale.',
    sourceUrl: 'https://www.starterstory.com/celigo-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['integration', 'ipaas', 'enterprise', 'saas'],
    matchingKeywords: ['celigo', 'integration platform', 'ipaas'],
    confidenceLevel: 'high',
    summary: 'Grew integration platform to $95M in revenue.',
  },
  {
    companyName: 'Inquizity Metanoia',
    industry: 'logistics',
    subIndustry: 'supply_chain_software',
    location: 'India',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Supply chain planning', 'Enterprise sales', 'Product development'],
      capabilities: ['Supply chain expertise', 'Software development', 'Industry knowledge'],
      marketPosition: 'New supply chain SaaS',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '6_10',
      revenueGrowth: '$30K/month',
      achievements: ['$30K/month revenue', 'Supply chain automation', 'Enterprise clients'],
      newCapabilities: ['Demand planning', 'Supply chain automation', 'Analytics'],
      marketPosition: 'Growing supply chain SaaS',
    },
    strategyType: 'vertical_saas',
    expansionType: 'enterprise',
    targetMarket: 'manufacturers',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built supply chain planning and automation software', impact: 'Product-market fit', difficulty: 'medium' },
      { action: 'Grew to $30K/month serving enterprise clients', impact: 'Sustainable revenue', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 30 },
    lessonsLearned: 'Supply chain SaaS requires deep domain expertise.',
    sourceUrl: 'https://www.starterstory.com/supply-chain-automation-software',
    sourcePlatform: 'starter_story',
    tags: ['supply_chain', 'automation', 'saas', 'enterprise'],
    matchingKeywords: ['inquizity', 'supply chain automation', 'demand planning'],
    confidenceLevel: 'high',
    summary: 'Built $30K/month supply chain planning and automation software.',
  },

  // === HR / RECRUITING ===
  {
    companyName: 'Dover',
    industry: 'hr_tech',
    subIndustry: 'ai_recruitment',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Recruitment automation', 'AI development', 'Market competition'],
      capabilities: ['AI/ML expertise', 'Recruitment knowledge', 'Product skills'],
      marketPosition: 'New AI recruitment platform',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '11_50',
      revenueGrowth: '$7M ARR ($583K/month)',
      achievements: ['$7M ARR', 'AI-powered recruitment', '3 founders'],
      newCapabilities: ['AI sourcing', 'Automated outreach', 'Candidate matching'],
      marketPosition: 'Leading AI recruitment tool',
    },
    strategyType: 'product_led_growth',
    expansionType: 'product',
    targetMarket: 'recruiters',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built AI-powered recruitment platform', impact: 'Product differentiation', difficulty: 'hard' },
      { action: 'Reached $7M ARR revolutionizing recruitment with AI', impact: 'Strong scale', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 70 },
    lessonsLearned: 'AI can significantly improve recruitment efficiency.',
    sourceUrl: 'https://www.starterstory.com/dover-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['hr_tech', 'ai', 'recruitment', 'saas'],
    matchingKeywords: ['dover', 'ai recruitment', 'hiring automation'],
    confidenceLevel: 'high',
    summary: 'Reached $7M ARR by revolutionizing recruitment with AI.',
  },
  {
    companyName: 'Oyster HR',
    industry: 'hr_tech',
    subIndustry: 'global_employment',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Global employment complexity', 'Compliance', 'Market timing'],
      capabilities: ['HR expertise', 'Global knowledge', 'Vision'],
      marketPosition: 'New global HR platform',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '500_plus',
      revenueGrowth: 'Unicorn status ($150M Series C)',
      achievements: ['Unicorn valuation', '$150M Series C', 'Global employment leader'],
      newCapabilities: ['Global payroll', 'Compliance automation', 'Remote hiring'],
      marketPosition: 'Leading global employment platform',
    },
    strategyType: 'venture_backed',
    expansionType: 'global',
    targetMarket: 'global_companies',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Achieved unicorn status in just 2 years', impact: 'Rapid valuation', difficulty: 'hard' },
      { action: 'Raised $150M Series C for global employment platform', impact: 'Major funding', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 10000 },
    lessonsLearned: 'Remote work trend enabled rapid HR tech growth.',
    sourceUrl: 'https://www.starterstory.com/oyster-hr-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['hr_tech', 'global', 'unicorn', 'remote_work'],
    matchingKeywords: ['oyster hr', 'global employment', 'remote hiring'],
    confidenceLevel: 'high',
    summary: 'Achieved unicorn status with $150M Series C in 2 years.',
  },
  {
    companyName: 'Rippling',
    industry: 'hr_tech',
    subIndustry: 'hr_it_platform',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['HR/IT integration', 'Zenefits aftermath', 'Platform complexity'],
      capabilities: ['HR tech experience (Zenefits)', 'Technical skills', 'Founder resilience'],
      marketPosition: 'Second-time founder in HR',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '500_plus',
      revenueGrowth: '$350M ARR',
      achievements: ['$350M ARR', 'HR & IT integration', 'Breakthrough platform'],
      newCapabilities: ['Unified HR/IT', 'Employee management', 'Device management'],
      marketPosition: 'Leading HR/IT platform',
    },
    strategyType: 'platform',
    expansionType: 'product',
    targetMarket: 'businesses',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Built integrated HR & IT platform after Zenefits', impact: 'Founder redemption', difficulty: 'hard' },
      { action: 'Achieved $350M ARR with breakthrough approach', impact: 'Massive scale', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 5000 },
    lessonsLearned: 'Second-time founders can achieve even greater success.',
    sourceUrl: 'https://www.starterstory.com/rippling-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['hr_tech', 'it', 'platform', 'saas'],
    matchingKeywords: ['rippling', 'hr platform', 'employee management'],
    confidenceLevel: 'high',
    summary: 'Achieved $350M ARR with breakthrough HR & IT SaaS platform.',
  },
  {
    companyName: 'Beamery',
    industry: 'hr_tech',
    subIndustry: 'talent_platform',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Talent management complexity', 'Enterprise sales', 'Platform building'],
      capabilities: ['HR expertise', 'Enterprise knowledge', 'Technical skills'],
      marketPosition: 'New talent platform',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '201_500',
      revenueGrowth: '$1 billion unicorn valuation',
      achievements: ['$1B unicorn', '3 founders', '387K monthly traffic'],
      newCapabilities: ['Talent operating system', 'AI matching', 'Enterprise HR'],
      marketPosition: 'Leading talent operating system',
    },
    strategyType: 'enterprise_saas',
    expansionType: 'enterprise',
    targetMarket: 'enterprises',
    timeline: { totalMonths: 120 },
    keyActions: [
      { action: 'Built talent operating system to unicorn status', impact: 'Massive valuation', difficulty: 'hard' },
      { action: 'Three founders scaled enterprise HR platform', impact: 'Strong execution', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 10000 },
    lessonsLearned: 'Enterprise talent platforms can achieve unicorn valuations.',
    sourceUrl: 'https://www.starterstory.com/beamery-talent-operating-system-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['hr_tech', 'talent', 'unicorn', 'enterprise'],
    matchingKeywords: ['beamery', 'talent operating system', 'hr platform'],
    confidenceLevel: 'high',
    summary: 'Three founders built Beamery to $1 billion unicorn success.',
  },
  {
    companyName: 'Mercor',
    industry: 'hr_tech',
    subIndustry: 'ai_recruitment',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['College dropout status', 'AI recruitment competition', 'Credibility'],
      capabilities: ['AI expertise', 'Ambition', 'Technical skills'],
      marketPosition: 'Young AI recruitment startup',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$2 billion valuation',
      achievements: ['$2B valuation', 'College dropout founders', 'AI recruitment empire'],
      newCapabilities: ['AI interviewing', 'Talent matching', 'Scale recruitment'],
      marketPosition: 'Leading AI recruitment platform',
    },
    strategyType: 'venture_backed',
    expansionType: 'market',
    targetMarket: 'companies',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'College dropouts built AI recruitment to $2B valuation', impact: 'Extraordinary success', difficulty: 'hard' },
      { action: 'Scaled AI recruitment empire rapidly', impact: 'Market capture', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100000 },
    lessonsLearned: 'AI in recruitment can achieve massive valuations quickly.',
    sourceUrl: 'https://www.starterstory.com/mercor-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['ai', 'recruitment', 'unicorn', 'young_founders'],
    matchingKeywords: ['mercor', 'ai recruitment', 'talent platform'],
    confidenceLevel: 'high',
    summary: 'College dropouts scaled AI recruitment empire to $2B valuation.',
  },

  // === MARKETING / SEO ===
  {
    companyName: 'GR0',
    industry: 'marketing',
    subIndustry: 'seo_agency',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['SEO agency competition', 'Client acquisition', 'Scale operations'],
      capabilities: ['Google experience', 'SEO expertise', 'Sales skills'],
      marketPosition: 'New SEO agency',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$18M/year',
      achievements: ['$18M/year revenue', 'Ex-Google founder', 'Top SEO agency'],
      newCapabilities: ['Enterprise SEO', 'Content strategy', 'Link building'],
      marketPosition: 'Leading SEO agency',
    },
    strategyType: 'service_excellence',
    expansionType: 'market',
    targetMarket: 'businesses',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Ex-Google employee started SEO agency', impact: 'Credibility boost', difficulty: 'medium' },
      { action: 'Grew to $18M/year in SEO services', impact: 'Major scale', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 200 },
    lessonsLearned: 'Big tech experience builds credibility for agency success.',
    sourceUrl: 'https://www.starterstory.com/stories/this-former-google-employee-started-an-seo-agency-and-grew-it-to-18m-year',
    sourcePlatform: 'starter_story',
    tags: ['seo', 'agency', 'marketing', 'google'],
    matchingKeywords: ['gr0', 'seo agency', 'google employee'],
    confidenceLevel: 'high',
    summary: 'Former Google employee grew SEO agency to $18M/year.',
  },
  {
    companyName: 'Powered by Search',
    industry: 'marketing',
    subIndustry: 'seo_agency',
    location: 'Canada',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['SEO market competition', 'B2B focus', 'Scale services'],
      capabilities: ['SEO expertise', 'B2B knowledge', 'Agency operations'],
      marketPosition: 'New B2B SEO agency',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$30M revenue',
      achievements: ['$30M revenue', 'B2B SaaS focus', 'Long-term growth'],
      newCapabilities: ['B2B SEO', 'SaaS marketing', 'Content strategy'],
      marketPosition: 'Leading B2B SEO agency',
    },
    strategyType: 'specialization',
    expansionType: 'market',
    targetMarket: 'b2b_saas',
    timeline: { totalMonths: 192 },
    keyActions: [
      { action: 'Built B2B-focused SEO agency to $30M revenue', impact: 'Major scale', difficulty: 'hard' },
      { action: 'Specialized in SaaS company marketing', impact: 'Niche leadership', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 300 },
    lessonsLearned: 'B2B specialization in SEO creates sustainable agencies.',
    sourceUrl: 'https://www.starterstory.com/powered-by-search-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['seo', 'agency', 'b2b', 'saas'],
    matchingKeywords: ['powered by search', 'b2b seo', 'saas marketing'],
    confidenceLevel: 'high',
    summary: 'Built B2B SEO agency to $30M in revenue.',
  },
  {
    companyName: 'Mariah Magazine (SEO Consulting)',
    industry: 'marketing',
    subIndustry: 'seo_consulting',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Small audience', 'Consulting sales', 'Authority building'],
      capabilities: ['SEO expertise', 'Content creation', 'Personal brand'],
      marketPosition: 'Solo SEO consultant',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '1_5',
      revenueGrowth: '$120K/year ($10K/month)',
      achievements: ['$120K/year', 'Small audience success', 'Solo consultant'],
      newCapabilities: ['SEO consulting', 'Content strategy', 'Personal brand'],
      marketPosition: 'Successful solo consultant',
    },
    strategyType: 'personal_brand',
    expansionType: 'service',
    targetMarket: 'small_businesses',
    timeline: { totalMonths: 120 },
    keyActions: [
      { action: 'Built SEO consulting with small audience', impact: 'Efficient marketing', difficulty: 'medium' },
      { action: 'Grew to $120K/year as solo consultant', impact: 'Lifestyle business', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 15 },
    lessonsLearned: 'Small audiences can generate significant consulting revenue.',
    sourceUrl: 'https://www.starterstory.com/mariah-magazine-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['seo', 'consulting', 'solopreneur', 'personal_brand'],
    matchingKeywords: ['mariah magazine', 'seo consulting', 'small audience'],
    confidenceLevel: 'high',
    summary: 'Grew SEO consulting to $120K/year with small audience.',
  },

  // === FITNESS ===
  {
    companyName: 'SWEAT (Kayla Itsines)',
    industry: 'fitness',
    subIndustry: 'fitness_app',
    location: 'Australia',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Fitness app competition', 'Personal brand building', 'App development'],
      capabilities: ['Fitness expertise', 'Social media skills', 'Personal training'],
      marketPosition: 'Personal trainer with following',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '201_500',
      revenueGrowth: '$8.33M/month, $400M exit',
      achievements: ['$400M acquisition', '$8.33M/month revenue', 'Fitness empire'],
      newCapabilities: ['Fitness app platform', 'Influencer marketing', 'Community building'],
      marketPosition: 'Leading fitness app globally',
    },
    strategyType: 'influencer_led',
    expansionType: 'global',
    targetMarket: 'women',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Built fitness app empire on personal brand', impact: 'Massive following', difficulty: 'hard' },
      { action: 'Sold SWEAT for $400 million', impact: 'Major exit', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 50000 },
    lessonsLearned: 'Personal brand + fitness app = massive exit potential.',
    sourceUrl: 'https://www.starterstory.com/sweat-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['fitness', 'app', 'influencer', 'exit'],
    matchingKeywords: ['sweat', 'kayla itsines', 'fitness app'],
    confidenceLevel: 'high',
    summary: 'Kayla Itsines built fitness app empire sold for $400 million.',
  },
  {
    companyName: 'Gym Streak',
    industry: 'fitness',
    subIndustry: 'fitness_app',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Fitness app competition', 'Solo development', 'User acquisition'],
      capabilities: ['App development', 'Fitness knowledge', 'Bootstrap mindset'],
      marketPosition: 'Solo fitness app developer',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '1_5',
      revenueGrowth: '$2.5M/year ($208K/month)',
      achievements: ['$2.5M/year', 'Bootstrapped success', 'Solo founder'],
      newCapabilities: ['AI workout planning', 'Mobile app', 'Subscription model'],
      marketPosition: 'Popular fitness tracking app',
    },
    strategyType: 'bootstrap',
    expansionType: 'product',
    targetMarket: 'gym_goers',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Solo founder bootstrapped fitness app to $2.5M/year', impact: 'Major solo success', difficulty: 'hard' },
      { action: 'Built AI-powered workout planning', impact: 'Product differentiation', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 250 },
    lessonsLearned: 'Solo founders can build multi-million fitness apps.',
    sourceUrl: 'https://www.starterstory.com/gym-streak-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['fitness', 'app', 'bootstrap', 'solo_founder'],
    matchingKeywords: ['gym streak', 'fitness app', 'workout tracker'],
    confidenceLevel: 'high',
    summary: 'Solo founder bootstrapped fitness app to $2.5M annually.',
  },
  {
    companyName: 'Gymdesk',
    industry: 'fitness',
    subIndustry: 'gym_management',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Gym software competition', 'Solo development', 'Market fragmentation'],
      capabilities: ['Software development', 'Gym industry knowledge', 'Bootstrap focus'],
      marketPosition: 'New gym management software',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '6_10',
      revenueGrowth: '$32.5M exit',
      achievements: ['$32.5M acquisition', 'Bootstrapped exit', 'Solo founder'],
      newCapabilities: ['Gym management', 'Membership tracking', 'Payment processing'],
      marketPosition: 'Acquired gym software',
    },
    strategyType: 'bootstrap',
    expansionType: 'product',
    targetMarket: 'gym_owners',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Solo founder bootstrapped gym management software', impact: 'Lean operation', difficulty: 'hard' },
      { action: 'Achieved $32.5M exit', impact: 'Major acquisition', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 400 },
    lessonsLearned: 'Bootstrapped vertical SaaS can achieve significant exits.',
    sourceUrl: 'https://www.starterstory.com/gymdesk-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['fitness', 'saas', 'bootstrap', 'exit'],
    matchingKeywords: ['gymdesk', 'gym management', 'fitness software'],
    confidenceLevel: 'high',
    summary: 'Solo founder bootstrapped gym management software to $32.5M exit.',
  },
  {
    companyName: 'GymBros',
    industry: 'fitness',
    subIndustry: 'fitness_app',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['App discovery', 'User acquisition', 'Monetization'],
      capabilities: ['TikTok marketing', 'App development', 'Content creation'],
      marketPosition: 'New fitness social app',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '1_5',
      revenueGrowth: '$19K MRR',
      achievements: ['$19K MRR in months', 'TikTok viral growth', 'Rapid user acquisition'],
      newCapabilities: ['Social fitness', 'Viral marketing', 'Community features'],
      marketPosition: 'Growing fitness social app',
    },
    strategyType: 'viral_marketing',
    expansionType: 'user_growth',
    targetMarket: 'gen_z_fitness',
    timeline: { totalMonths: 6 },
    keyActions: [
      { action: 'Leveraged TikTok to achieve $19K MRR in months', impact: 'Rapid growth', difficulty: 'medium' },
      { action: 'Built social fitness features', impact: 'Engagement driver', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'TikTok can drive rapid fitness app growth.',
    sourceUrl: 'https://www.starterstory.com/gym-bros-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['fitness', 'tiktok', 'social', 'app'],
    matchingKeywords: ['gymbros', 'fitness app', 'tiktok marketing'],
    confidenceLevel: 'high',
    summary: 'Leveraged TikTok to achieve $19K MRR in months.',
  },
  {
    companyName: 'PushPress',
    industry: 'fitness',
    subIndustry: 'gym_management',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Gym software competition', 'Feature development', 'Customer acquisition'],
      capabilities: ['Software development', 'Gym ownership experience', 'Industry knowledge'],
      marketPosition: 'New gym management platform',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '11_50',
      revenueGrowth: '$100K/month',
      achievements: ['$100K/month revenue', 'Gym management platform', 'Industry leader'],
      newCapabilities: ['Gym operations', 'Member management', 'Billing systems'],
      marketPosition: 'Leading gym management software',
    },
    strategyType: 'vertical_saas',
    expansionType: 'market',
    targetMarket: 'gym_owners',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built gym management software to $100K/month', impact: 'Strong revenue', difficulty: 'medium' },
      { action: 'Created comprehensive gym operations platform', impact: 'Full solution', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Gym-specific software can achieve significant scale.',
    sourceUrl: 'https://www.starterstory.com/software-for-fitness-centers',
    sourcePlatform: 'starter_story',
    tags: ['fitness', 'saas', 'gym_management', 'vertical'],
    matchingKeywords: ['pushpress', 'gym software', 'fitness management'],
    confidenceLevel: 'high',
    summary: 'Built gym management software reaching $100K/month revenue.',
  },

  // === BEAUTY / SKINCARE ===
  {
    companyName: 'Glow Recipe',
    industry: 'beauty',
    subIndustry: 'skincare',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Beauty market competition', 'K-beauty positioning', 'Brand building'],
      capabilities: ['Beauty industry experience', 'K-beauty knowledge', 'Marketing skills'],
      marketPosition: 'New K-beauty brand',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$100 million in sales',
      achievements: ['$100M in sales', 'K-beauty leader', 'Two female founders'],
      newCapabilities: ['Product development', 'Retail distribution', 'Brand marketing'],
      marketPosition: 'Leading K-beauty skincare brand',
    },
    strategyType: 'brand_building',
    expansionType: 'product',
    targetMarket: 'skincare_enthusiasts',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Two founders built K-beauty brand to $100M sales', impact: 'Major scale', difficulty: 'hard' },
      { action: 'Created fruit-forward skincare category', impact: 'Product innovation', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'K-beauty positioning can create major skincare brands.',
    sourceUrl: 'https://www.starterstory.com/glow-recipe-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['beauty', 'skincare', 'kbeauty', 'dtc'],
    matchingKeywords: ['glow recipe', 'kbeauty', 'skincare brand'],
    confidenceLevel: 'high',
    summary: 'Christine & Sarah grew Glow Recipe to $100 million in sales.',
  },
  {
    companyName: 'BLAQ',
    industry: 'beauty',
    subIndustry: 'skincare',
    location: 'Australia',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Skincare market entry', 'Australian market', 'DTC competition'],
      capabilities: ['Product development', 'E-commerce skills', 'Beauty knowledge'],
      marketPosition: 'New Aussie skincare brand',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '11_50',
      revenueGrowth: '$7M Australian skincare empire',
      achievements: ['$7M revenue', 'Australian success', 'Activated charcoal focus'],
      newCapabilities: ['Skincare formulation', 'DTC operations', 'Brand building'],
      marketPosition: 'Leading Australian skincare brand',
    },
    strategyType: 'niche_focus',
    expansionType: 'product',
    targetMarket: 'skincare_consumers',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built $7M Australian skincare empire', impact: 'Regional leadership', difficulty: 'medium' },
      { action: 'Focused on activated charcoal products', impact: 'Niche differentiation', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 80 },
    lessonsLearned: 'Niche ingredient focus creates skincare differentiation.',
    sourceUrl: 'https://www.starterstory.com/stories/blaq',
    sourcePlatform: 'starter_story',
    tags: ['beauty', 'skincare', 'australia', 'dtc'],
    matchingKeywords: ['blaq', 'australian skincare', 'charcoal'],
    confidenceLevel: 'high',
    summary: 'Built $7M Australian skincare empire.',
  },
  {
    companyName: 'Tree To Tub',
    industry: 'beauty',
    subIndustry: 'personal_care',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Personal care competition', 'Retail distribution', 'Sustainable positioning'],
      capabilities: ['Product development', 'Sustainability focus', 'E-commerce'],
      marketPosition: 'New sustainable personal care',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '11_50',
      revenueGrowth: '$6M/year revenue',
      achievements: ['$6M/year', 'iHerb partnership', 'Sustainable personal care'],
      newCapabilities: ['Retail partnerships', 'Sustainable sourcing', 'Product line expansion'],
      marketPosition: 'Growing sustainable brand',
    },
    strategyType: 'partnership',
    expansionType: 'distribution',
    targetMarket: 'eco_conscious_consumers',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Landed major deal with iHerb', impact: 'Distribution channel', difficulty: 'hard' },
      { action: 'Grew to $6M/year in sustainable personal care', impact: 'Strong revenue', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 70 },
    lessonsLearned: 'Retail partnerships accelerate sustainable brand growth.',
    sourceUrl: 'https://www.starterstory.com/stories/tree-to-tub',
    sourcePlatform: 'starter_story',
    tags: ['beauty', 'sustainable', 'personal_care', 'retail'],
    matchingKeywords: ['tree to tub', 'sustainable skincare', 'iherb'],
    confidenceLevel: 'high',
    summary: 'Landed iHerb deal and reached $6M in revenue.',
  },
  {
    companyName: 'Wild (Deodorant)',
    industry: 'beauty',
    subIndustry: 'personal_care',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Deodorant market disruption', 'Refillable concept', 'Consumer behavior change'],
      capabilities: ['Product innovation', 'Sustainability focus', 'DTC expertise'],
      marketPosition: 'New refillable deodorant brand',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: '$30M revenue ($2.8M/month)',
      achievements: ['$30M revenue', 'Refillable innovation', '50 employees'],
      newCapabilities: ['Refillable systems', 'Sustainable packaging', 'DTC operations'],
      marketPosition: 'Leading refillable deodorant brand',
    },
    strategyType: 'sustainability_innovation',
    expansionType: 'product',
    targetMarket: 'eco_conscious_consumers',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built $30M refillable deodorant brand', impact: 'Category innovation', difficulty: 'hard' },
      { action: 'Changed consumer behavior with sustainable solution', impact: 'Market shift', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 350 },
    lessonsLearned: 'Sustainable innovation in personal care creates significant value.',
    sourceUrl: 'https://www.starterstory.com/stories/wild',
    sourcePlatform: 'starter_story',
    tags: ['beauty', 'sustainable', 'deodorant', 'dtc'],
    matchingKeywords: ['wild deodorant', 'refillable', 'sustainable'],
    confidenceLevel: 'high',
    summary: 'Two founders built $30M refillable deodorant brand.',
  },
  {
    companyName: 'Plaine Products',
    industry: 'beauty',
    subIndustry: 'hair_body_care',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Sustainability differentiation', 'Refill model logistics', 'Consumer education'],
      capabilities: ['Sustainability passion', 'Product development', 'E-commerce'],
      marketPosition: 'New sustainable hair/body care',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '6_10',
      revenueGrowth: '$2.4M/year',
      achievements: ['$2.4M/year', 'Sustainable refill model', 'Hair & body care'],
      newCapabilities: ['Refill logistics', 'Sustainable packaging', 'Subscription model'],
      marketPosition: 'Leading sustainable hair/body care',
    },
    strategyType: 'sustainability_focus',
    expansionType: 'product',
    targetMarket: 'eco_conscious_consumers',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built sustainable hair & body care to $2.4M/year', impact: 'Strong revenue', difficulty: 'medium' },
      { action: 'Created refillable product model', impact: 'Sustainability differentiation', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 30 },
    lessonsLearned: 'Sustainability passion creates loyal customer base.',
    sourceUrl: 'https://www.starterstory.com/stories/we-turned-our-passion-for-sustainability-into-a-2-4m-year-hair-body-care-brand',
    sourcePlatform: 'starter_story',
    tags: ['beauty', 'sustainable', 'hair_care', 'refillable'],
    matchingKeywords: ['plaine products', 'sustainable beauty', 'refillable'],
    confidenceLevel: 'high',
    summary: 'Turned sustainability passion into $2.4M/year hair & body care brand.',
  },
  {
    companyName: 'Fur',
    industry: 'beauty',
    subIndustry: 'body_care',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Taboo product category', 'Consumer education', 'Market creation'],
      capabilities: ['Product innovation', 'Marketing skills', 'Category vision'],
      marketPosition: 'Creating new beauty category',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '51_200',
      revenueGrowth: 'Millions in revenue, 100 employees',
      achievements: ['Multi-million revenue', 'Category creation', 'Taboo normalized'],
      newCapabilities: ['Body hair care', 'Brand building', 'Retail distribution'],
      marketPosition: 'Category leader in body hair care',
    },
    strategyType: 'category_creation',
    expansionType: 'product',
    targetMarket: 'women',
    timeline: { totalMonths: 120 },
    keyActions: [
      { action: 'Bootstrapped taboo beauty category to millions', impact: 'Category creation', difficulty: 'hard' },
      { action: 'Normalized body hair care conversation', impact: 'Market shift', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Taboo categories can become mainstream with right approach.',
    sourceUrl: 'https://www.starterstory.com/fur-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['beauty', 'body_care', 'taboo', 'category_creation'],
    matchingKeywords: ['fur beauty', 'body hair care', 'taboo beauty'],
    confidenceLevel: 'high',
    summary: 'Bootstrapped taboo beauty business to millions.',
  },

  // === PRODUCTIVITY / SAAS ===
  {
    companyName: 'Heptabase',
    industry: 'technology',
    subIndustry: 'productivity',
    location: 'Taiwan',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Note-taking competition', 'Visual interface design', 'User acquisition'],
      capabilities: ['Product design', 'Development skills', 'Vision'],
      marketPosition: 'New visual note-taking tool',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '6_10',
      revenueGrowth: '$200K/month ($2.4M/year)',
      achievements: ['$200K/month', 'Bootstrapped success', 'Visual note-taking leader'],
      newCapabilities: ['Visual knowledge management', 'Whiteboard notes', 'Connected thinking'],
      marketPosition: 'Leading visual note-taking tool',
    },
    strategyType: 'bootstrap',
    expansionType: 'product',
    targetMarket: 'knowledge_workers',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Bootstrapped visual note-taking tool to $200K/month', impact: 'Strong solo success', difficulty: 'hard' },
      { action: 'Created unique visual knowledge management', impact: 'Product differentiation', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 200 },
    lessonsLearned: 'Visual approaches to note-taking create differentiation.',
    sourceUrl: 'https://www.starterstory.com/heptabase-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['productivity', 'notes', 'visual', 'bootstrap'],
    matchingKeywords: ['heptabase', 'visual notes', 'knowledge management'],
    confidenceLevel: 'high',
    summary: 'Bootstrapped visual note-taking tool to $200K/month.',
  },
  {
    companyName: 'Loops',
    industry: 'technology',
    subIndustry: 'email_marketing',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Email tool competition', 'SaaS differentiation', 'User acquisition'],
      capabilities: ['Product development', 'Email expertise', 'Design skills'],
      marketPosition: 'New email marketing tool',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '1_5',
      revenueGrowth: '$731K revenue in 2 years ($61K/month)',
      achievements: ['$731K revenue', '2-year growth', '3 employees'],
      newCapabilities: ['Email automation', 'SaaS email', 'Transactional email'],
      marketPosition: 'Growing email tool for SaaS',
    },
    strategyType: 'product_led_growth',
    expansionType: 'product',
    targetMarket: 'saas_companies',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Built email tool to $731K revenue in 2 years', impact: 'Rapid growth', difficulty: 'medium' },
      { action: 'Focused on SaaS company email needs', impact: 'Niche positioning', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 70 },
    lessonsLearned: 'SaaS-focused email tools find product-market fit.',
    sourceUrl: 'https://www.starterstory.com/loops-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['email', 'saas', 'productivity', 'marketing'],
    matchingKeywords: ['loops', 'email marketing', 'saas email'],
    confidenceLevel: 'high',
    summary: 'Two founders built email tool to $731K revenue in 2 years.',
  },
  {
    companyName: 'monday.com',
    industry: 'technology',
    subIndustry: 'project_management',
    location: 'Israel',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Project management competition', 'Enterprise sales', 'Global expansion'],
      capabilities: ['Product development', 'Enterprise experience', 'Growth skills'],
      marketPosition: 'New work OS platform',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '500_plus',
      revenueGrowth: '$120M ARR ($83.3M/month), 18.4M traffic',
      achievements: ['$120M ARR in 3 years', 'Public company', '2500 employees'],
      newCapabilities: ['Work OS platform', 'No-code workflows', 'Enterprise scale'],
      marketPosition: 'Leading work management platform',
    },
    strategyType: 'product_led_growth',
    expansionType: 'global',
    targetMarket: 'businesses',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Co-CEOs scaled to $120M ARR in 3 years', impact: 'Rapid scale', difficulty: 'hard' },
      { action: 'Built work OS platform competing with major players', impact: 'Market capture', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 15000 },
    lessonsLearned: 'Work management can scale rapidly with right positioning.',
    sourceUrl: 'https://www.starterstory.com/monday-com-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['productivity', 'project_management', 'saas', 'public'],
    matchingKeywords: ['monday.com', 'work os', 'project management'],
    confidenceLevel: 'high',
    summary: 'Co-CEOs scaled monday.com to $120M ARR in 3 years.',
  },
  {
    companyName: 'Keap (Infusionsoft)',
    industry: 'technology',
    subIndustry: 'crm_automation',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['CRM competition', 'Small business focus', 'Feature development'],
      capabilities: ['CRM development', 'Small business knowledge', 'Automation expertise'],
      marketPosition: 'Garage startup CRM',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '201_500',
      revenueGrowth: '$90M revenue ($7.5M/month)',
      achievements: ['$90M revenue', 'Garage to major company', '323 employees'],
      newCapabilities: ['Marketing automation', 'CRM platform', 'Small business tools'],
      marketPosition: 'Leading small business CRM',
    },
    strategyType: 'bootstrap_to_scale',
    expansionType: 'product',
    targetMarket: 'small_businesses',
    timeline: { totalMonths: 288 },
    keyActions: [
      { action: 'Grew from garage startup to $90M revenue', impact: 'Major scale', difficulty: 'hard' },
      { action: 'Built comprehensive small business automation', impact: 'Full platform', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'Small business CRM can achieve significant scale over time.',
    sourceUrl: 'https://www.starterstory.com/keap-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['crm', 'automation', 'small_business', 'saas'],
    matchingKeywords: ['keap', 'infusionsoft', 'small business crm'],
    confidenceLevel: 'high',
    summary: 'Grew from garage startup to $90M revenue business.',
  },
  {
    companyName: 'Basecamp',
    industry: 'technology',
    subIndustry: 'project_management',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['Project management market', 'Bootstrapping', 'Counter-culture approach'],
      capabilities: ['Web development', 'Design skills', 'Unique philosophy'],
      marketPosition: 'Web design agency',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '11_50',
      revenueGrowth: 'Tens of millions ($23.3M/month)',
      achievements: ['Tens of millions revenue', 'Counter-culture success', '45 employees'],
      newCapabilities: ['Project management', 'Team communication', 'Company philosophy'],
      marketPosition: 'Iconic project management tool',
    },
    strategyType: 'bootstrap',
    expansionType: 'organic',
    targetMarket: 'teams',
    timeline: { totalMonths: 252 },
    keyActions: [
      { action: 'Grew to tens of millions without rapid scaling', impact: 'Sustainable growth', difficulty: 'hard' },
      { action: 'Built counter-culture company philosophy', impact: 'Brand differentiation', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 2000 },
    lessonsLearned: 'Sustainable growth without VC can build iconic companies.',
    sourceUrl: 'https://www.starterstory.com/basecamp-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['productivity', 'bootstrap', 'project_management', 'philosophy'],
    matchingKeywords: ['basecamp', 'project management', '37signals'],
    confidenceLevel: 'high',
    summary: 'Grew to tens of millions without rapid scaling.',
  },
  {
    companyName: 'Streak',
    industry: 'technology',
    subIndustry: 'crm',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1_5',
      yearsInBusiness: 0,
      challenges: ['CRM competition', 'Gmail integration', 'Platform dependency'],
      capabilities: ['Gmail expertise', 'CRM knowledge', 'Chrome extension development'],
      marketPosition: 'New Gmail CRM',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '11_50',
      revenueGrowth: '$10M ARR ($833K/month)',
      achievements: ['$10M ARR', 'Gmail-native CRM', '400K monthly traffic'],
      newCapabilities: ['Gmail CRM', 'Pipeline management', 'Chrome extension'],
      marketPosition: 'Leading Gmail CRM',
    },
    strategyType: 'platform_integration',
    expansionType: 'product',
    targetMarket: 'gmail_users',
    timeline: { totalMonths: 156 },
    keyActions: [
      { action: 'Built CRM inside Gmail to $10M ARR', impact: 'Unique positioning', difficulty: 'hard' },
      { action: 'Leveraged Gmail platform for distribution', impact: 'Growth channel', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Platform integration CRMs can achieve significant scale.',
    sourceUrl: 'https://www.starterstory.com/streak-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['crm', 'gmail', 'productivity', 'chrome'],
    matchingKeywords: ['streak', 'gmail crm', 'email crm'],
    confidenceLevel: 'high',
    summary: 'Built $10M ARR CRM business inside Gmail.',
  },
];

async function seedBatch12() {
  console.log('🌱 Seeding Batch 12: Logistics, HR, Marketing, Fitness, Beauty, Productivity...');

  let successCount = 0;
  let errorCount = 0;

  for (const caseStudy of batch12CaseStudies) {
    try {
      await db.insert(caseStudies).values({
        ...caseStudy,
        startingState: caseStudy.startingState,
        endingState: caseStudy.endingState,
        timeline: caseStudy.timeline,
        keyActions: caseStudy.keyActions,
        outcomes: caseStudy.outcomes,
      } as CaseStudyInsert);
      console.log(`  ✓ ${caseStudy.companyName}`);
      successCount++;
    } catch (error: unknown) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      console.error(`  ✗ ${caseStudy.companyName}: ${errorMessage}`);
      errorCount++;
    }
  }

  console.log(`\nBatch 12 seeding complete!`);
  console.log(`✓ Successfully seeded: ${successCount}`);
  console.log(`✗ Errors: ${errorCount}`);

  process.exit(0);
}

seedBatch12().catch((error) => {
  console.error('Seeding failed:', error);
  process.exit(1);
});
