import { db } from '../../lib/db';
import { caseStudies } from '../schema';

type CaseStudyInsert = typeof caseStudies.$inferInsert;

const batch7CaseStudies = [
  // ===== EdTech =====
  {
    companyName: 'Duolingo',
    industry: 'edtech',
    subIndustry: 'language_learning',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Making learning free', 'Gamification design', 'User engagement'],
      capabilities: ['Tech expertise', 'Academic background', 'CAPTCHA inventor'],
      marketPosition: 'New language learning app',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '500_plus',
      revenueGrowth: '$62.3M/month ($9B valuation)',
      achievements: ['$9 billion valuation', '650+ employees', '76M monthly traffic', 'Public company'],
      newCapabilities: ['AI-powered learning', 'Subscription model', 'Global scale'],
      marketPosition: 'World\'s most popular language app',
    },
    strategyType: 'platform_scale',
    expansionType: 'global',
    targetMarket: 'language_learners',
    timeline: { totalMonths: 156 },
    keyActions: [
      { action: 'Made language learning free and gamified', impact: 'Massive user adoption', difficulty: 'hard' },
      { action: 'Built freemium subscription model', impact: 'Sustainable revenue at scale', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 10000 },
    lessonsLearned: 'Gamification and free access can disrupt traditional education markets.',
    sourceUrl: 'https://www.starterstory.com/duolingo-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['edtech', 'language_learning', 'gamification', 'unicorn'],
    matchingKeywords: ['language learning', 'education app', 'duolingo'],
    confidenceLevel: 'high',
    summary: 'Built Duolingo to a $9 billion EdTech giant with 76M monthly users.',
  },
  {
    companyName: 'AnswersAI',
    industry: 'edtech',
    subIndustry: 'ai_tutoring',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['AI accuracy', 'User trust', 'Rapid growth'],
      capabilities: ['AI development', 'EdTech understanding'],
      marketPosition: 'New AI tutoring startup',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '2_5',
      revenueGrowth: '300K users quickly',
      achievements: ['300K users fast', 'AI tutoring platform', 'Profitable early'],
      newCapabilities: ['AI homework help', 'Student engagement'],
      marketPosition: 'Fast-growing AI tutoring platform',
    },
    strategyType: 'ai_first',
    expansionType: 'horizontal',
    targetMarket: 'students',
    timeline: { totalMonths: 12 },
    keyActions: [
      { action: 'Built AI-powered tutoring system', impact: 'Instant homework help', difficulty: 'hard' },
      { action: 'Focused on student experience', impact: 'Rapid user adoption', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 15 },
    lessonsLearned: 'AI tutoring fills a gap in on-demand educational support.',
    sourceUrl: 'https://www.starterstory.com/answersai-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['edtech', 'ai', 'tutoring', 'students'],
    matchingKeywords: ['ai tutoring', 'homework help', 'education ai'],
    confidenceLevel: 'high',
    summary: 'Three founders propelled AI tutoring startup to 300K users fast.',
  },
  {
    companyName: 'Heptabase',
    industry: 'edtech',
    subIndustry: 'note_taking',
    location: 'Taiwan',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Product differentiation', 'User acquisition', 'Solo development'],
      capabilities: ['Product design', 'Visual thinking'],
      marketPosition: 'New note-taking tool',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '2_5',
      revenueGrowth: '$200K/month',
      achievements: ['$200K MRR', 'Bootstrapped', 'Visual note-taking leader'],
      newCapabilities: ['Visual knowledge management', 'Research workflows'],
      marketPosition: 'Leading visual note-taking tool',
    },
    strategyType: 'bootstrapped_growth',
    expansionType: 'horizontal',
    targetMarket: 'researchers_students',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built unique visual note-taking approach', impact: 'Differentiated from competitors', difficulty: 'hard' },
      { action: 'Bootstrapped to profitability', impact: 'Full control and focus', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Unique product vision can create new categories in crowded markets.',
    sourceUrl: 'https://www.starterstory.com/heptabase-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['edtech', 'note_taking', 'productivity', 'bootstrapped'],
    matchingKeywords: ['note taking', 'visual notes', 'knowledge management'],
    confidenceLevel: 'high',
    summary: 'Bootstrapped a visual note-taking tool to $200K/month.',
  },

  // ===== Fitness Apps =====
  {
    companyName: 'STRETCHIT',
    industry: 'fitness',
    subIndustry: 'fitness_app',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Niche positioning', 'Content creation', 'User retention'],
      capabilities: ['Flexibility training expertise', 'App development'],
      marketPosition: 'New stretching app',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '6_10',
      revenueGrowth: 'Profitable fitness app',
      achievements: ['Leading stretching app', 'Sister founding team', 'Global user base'],
      newCapabilities: ['Video content production', 'App engagement'],
      marketPosition: 'Leading stretching and flexibility app',
    },
    strategyType: 'niche_focus',
    expansionType: 'horizontal',
    targetMarket: 'fitness_enthusiasts',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Focused exclusively on stretching niche', impact: 'Dominated underserved market', difficulty: 'moderate' },
      { action: 'Built comprehensive stretching programs', impact: 'High user engagement', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Niche fitness apps can outperform general fitness platforms.',
    sourceUrl: 'https://www.starterstory.com/stretchit-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['fitness', 'app', 'stretching', 'wellness'],
    matchingKeywords: ['stretching app', 'flexibility', 'fitness app'],
    confidenceLevel: 'high',
    summary: 'Two sisters built STRETCHIT into a leading fitness app.',
  },
  {
    companyName: 'Nuli',
    industry: 'fitness',
    subIndustry: 'fitness_app',
    location: 'Israel',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['App store competition', 'User acquisition', 'Content quality'],
      capabilities: ['Fitness expertise', 'App development'],
      marketPosition: 'New fitness app',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '20_50',
      revenueGrowth: '$1M+ ARR ($83K/month)',
      achievements: ['$1M+ ARR', '21K subscribers', '30 employees'],
      newCapabilities: ['Subscription retention', 'Workout content'],
      marketPosition: 'Growing fitness subscription app',
    },
    strategyType: 'subscription_growth',
    expansionType: 'horizontal',
    targetMarket: 'women_fitness',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built women-focused fitness content', impact: 'Strong target audience', difficulty: 'moderate' },
      { action: 'Achieved 21K subscribers', impact: '$1M+ ARR milestone', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 30 },
    lessonsLearned: 'Focused demographics enable better product-market fit.',
    sourceUrl: 'https://www.starterstory.com/nuli-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['fitness', 'app', 'subscription', 'women'],
    matchingKeywords: ['fitness app', 'workout app', 'women fitness'],
    confidenceLevel: 'high',
    summary: 'Hit 21K subscribers and over $1M ARR in 3 years.',
  },
  {
    companyName: 'Hevy',
    industry: 'fitness',
    subIndustry: 'workout_tracking',
    location: 'Spain',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['App store ranking', 'User engagement', 'Feature development'],
      capabilities: ['App development', 'Fitness knowledge'],
      marketPosition: 'New workout tracking app',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '11_20',
      revenueGrowth: '$160K MRR',
      achievements: ['$160K MRR', '13 employees', 'Revolutionized workout tracking'],
      newCapabilities: ['Social fitness features', 'Data analytics'],
      marketPosition: 'Popular workout tracking app',
    },
    strategyType: 'product_excellence',
    expansionType: 'horizontal',
    targetMarket: 'gym_goers',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built superior workout tracking UX', impact: 'Strong user retention', difficulty: 'hard' },
      { action: 'Added social features', impact: 'Viral growth mechanics', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 80 },
    lessonsLearned: 'Superior UX in fitness apps creates loyal users.',
    sourceUrl: 'https://www.starterstory.com/hevy-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['fitness', 'workout_tracking', 'app', 'social'],
    matchingKeywords: ['workout tracker', 'gym app', 'fitness tracking'],
    confidenceLevel: 'high',
    summary: 'Achieved $160K MRR by revolutionizing workout tracking.',
  },
  {
    companyName: 'World Fitness',
    industry: 'fitness',
    subIndustry: 'equipment',
    location: 'Australia',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Equipment sourcing', 'E-commerce operations', 'Competition'],
      capabilities: ['Fitness industry knowledge', 'Retail experience'],
      marketPosition: 'New fitness equipment retailer',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '6_10',
      revenueGrowth: '130% sales growth',
      achievements: ['130% sales growth', '10 employees', 'Major equipment retailer'],
      newCapabilities: ['Supply chain management', 'E-commerce scale'],
      marketPosition: 'Leading Australian fitness equipment retailer',
    },
    strategyType: 'ecommerce_scale',
    expansionType: 'horizontal',
    targetMarket: 'home_gym_owners',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Built comprehensive equipment catalog', impact: 'One-stop shop positioning', difficulty: 'moderate' },
      { action: 'Scaled e-commerce operations', impact: '130% sales growth', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 25 },
    lessonsLearned: 'E-commerce fitness equipment benefits from comprehensive selection.',
    sourceUrl: 'https://www.starterstory.com/freddy-seoud',
    sourcePlatform: 'starter_story',
    tags: ['fitness', 'equipment', 'ecommerce', 'retail'],
    matchingKeywords: ['fitness equipment', 'home gym', 'workout gear'],
    confidenceLevel: 'high',
    summary: 'Built a fitness equipment business with 130% sales growth.',
  },
  {
    companyName: 'Hexbox Fitness',
    industry: 'fitness',
    subIndustry: 'gym_facility',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Facility costs', 'Member acquisition', 'Class development'],
      capabilities: ['Fitness expertise', 'Business management'],
      marketPosition: 'New boutique fitness studio',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '6_10',
      revenueGrowth: 'Profitable gym franchise',
      achievements: ['Unique HXBX classes', 'Upscale facility', 'Strong membership'],
      newCapabilities: ['Branded fitness programs', 'Membership retention'],
      marketPosition: 'Premium boutique fitness studio',
    },
    strategyType: 'premium_experience',
    expansionType: 'local',
    targetMarket: 'fitness_enthusiasts',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Created unique branded classes', impact: 'Differentiated offering', difficulty: 'moderate' },
      { action: 'Built upscale facility experience', impact: 'Premium pricing', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 15 },
    lessonsLearned: 'Branded experiences command premium pricing in fitness.',
    sourceUrl: 'https://www.starterstory.com/stories/hexbox-fitness-a-business-model-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['fitness', 'gym', 'boutique', 'classes'],
    matchingKeywords: ['boutique gym', 'fitness studio', 'group fitness'],
    confidenceLevel: 'high',
    summary: 'Built a premium boutique fitness studio with unique branded classes.',
  },

  // ===== Wedding/Events =====
  {
    companyName: 'SvenStudios',
    industry: 'photography',
    subIndustry: 'wedding',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Building portfolio', 'Client acquisition', 'Pricing'],
      capabilities: ['Photography skills', 'Creative vision'],
      marketPosition: 'New wedding photographer',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '2_5',
      revenueGrowth: 'Six figures per year',
      achievements: ['Six-figure annual revenue', 'Premium positioning', 'Strong referrals'],
      newCapabilities: ['Wedding expertise', 'Client experience'],
      marketPosition: 'Premium wedding photographer',
    },
    strategyType: 'premium_service',
    expansionType: 'vertical',
    targetMarket: 'couples',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built premium wedding photography brand', impact: 'Higher pricing power', difficulty: 'moderate' },
      { action: 'Focused on client experience', impact: 'Strong referral business', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 10 },
    lessonsLearned: 'Premium positioning in wedding photography enables six-figure income.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-a-professional-wedding-photographer-career',
    sourcePlatform: 'starter_story',
    tags: ['photography', 'wedding', 'premium', 'creative'],
    matchingKeywords: ['wedding photography', 'wedding photographer', 'events'],
    confidenceLevel: 'high',
    summary: 'Built a wedding photography career generating over six figures per year.',
  },
  {
    companyName: 'Studio 31 Wedding Photography',
    industry: 'photography',
    subIndustry: 'wedding',
    location: 'India',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Team scaling', 'Consistent quality', 'Process optimization'],
      capabilities: ['Photography expertise', 'Business mindset'],
      marketPosition: 'New wedding studio',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '11_20',
      revenueGrowth: '$50K/month',
      achievements: ['$50K monthly revenue', 'Startup-like operations', 'Scaled team'],
      newCapabilities: ['Process automation', 'Team management'],
      marketPosition: 'Leading wedding photography studio',
    },
    strategyType: 'operational_excellence',
    expansionType: 'horizontal',
    targetMarket: 'couples',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Ran studio with startup mindset', impact: 'Efficient scaling', difficulty: 'hard' },
      { action: 'Built systematic processes', impact: 'Consistent quality at scale', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 25 },
    lessonsLearned: 'Startup methodologies can transform traditional service businesses.',
    sourceUrl: 'https://www.starterstory.com/how-to-run-a-wedding-photography-studio',
    sourcePlatform: 'starter_story',
    tags: ['photography', 'wedding', 'startup_mindset', 'scale'],
    matchingKeywords: ['wedding studio', 'photography business', 'wedding photography'],
    confidenceLevel: 'high',
    summary: 'Runs a $50K/month wedding photography studio like a startup.',
  },

  // ===== Kids/Baby Products =====
  {
    companyName: 'Trunki',
    industry: 'ecommerce',
    subIndustry: 'kids_products',
    location: 'UK',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Product development', 'Manufacturing', 'Dragons Den rejection'],
      capabilities: ['Product design', 'Innovation mindset'],
      marketPosition: 'New kids travel product',
    },
    endingState: {
      revenue: '5m_10m',
      teamSize: '50_100',
      revenueGrowth: '$12M/year',
      achievements: ['$12M annual revenue', 'Global distribution', 'Iconic product'],
      newCapabilities: ['Global manufacturing', 'Retail partnerships'],
      marketPosition: 'Iconic kids suitcase brand',
    },
    strategyType: 'product_innovation',
    expansionType: 'global',
    targetMarket: 'parents_travelers',
    timeline: { totalMonths: 180 },
    keyActions: [
      { action: 'Created ride-on kids suitcase', impact: 'Created new product category', difficulty: 'hard' },
      { action: 'Persisted after Dragons Den rejection', impact: 'Proved market demand', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 200 },
    lessonsLearned: 'Innovative products can create entirely new categories despite early rejection.',
    sourceUrl: 'https://www.starterstory.com/trunki-dragons-den-kids-suitcase',
    sourcePlatform: 'starter_story',
    tags: ['kids', 'travel', 'product_design', 'innovation'],
    matchingKeywords: ['kids suitcase', 'travel products', 'children travel'],
    confidenceLevel: 'high',
    summary: 'Innovative kids suitcase design became a $12M/year company.',
  },
  {
    companyName: 'Storkland',
    industry: 'retail',
    subIndustry: 'baby_products',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Inventory management', 'Competition', 'Location selection'],
      capabilities: ['Retail experience', 'Baby product knowledge'],
      marketPosition: 'New baby retail store',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '2_5',
      revenueGrowth: 'Long-running business',
      achievements: ['40+ years in business', 'Community institution', 'Multi-generational customers'],
      newCapabilities: ['Customer service excellence', 'Product curation'],
      marketPosition: 'Established baby retail destination',
    },
    strategyType: 'community_building',
    expansionType: 'local',
    targetMarket: 'new_parents',
    timeline: { totalMonths: 504 },
    keyActions: [
      { action: 'Built community trust over decades', impact: 'Multi-generational loyalty', difficulty: 'moderate' },
      { action: 'Focused on customer service', impact: 'Strong word of mouth', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 20 },
    lessonsLearned: 'Local retail can thrive through community relationships and service.',
    sourceUrl: 'https://www.starterstory.com/retail-business',
    sourcePlatform: 'starter_story',
    tags: ['retail', 'baby', 'local_business', 'longevity'],
    matchingKeywords: ['baby store', 'baby products', 'retail'],
    confidenceLevel: 'high',
    summary: 'Launched and grew a baby brand serving multiple generations.',
  },

  // ===== Gaming/Streaming =====
  {
    companyName: 'Streamloots',
    industry: 'gaming',
    subIndustry: 'streaming_platform',
    location: 'Spain',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Platform development', 'Streamer acquisition', 'Monetization'],
      capabilities: ['Tech development', 'Gaming industry knowledge'],
      marketPosition: 'New streamer monetization platform',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '11_20',
      revenueGrowth: '$150K/month',
      achievements: ['$150K monthly revenue', 'Streamer monetization platform', 'Fan engagement tools'],
      newCapabilities: ['Virtual goods marketplace', 'Creator economy'],
      marketPosition: 'Leading streamer monetization platform',
    },
    strategyType: 'platform_build',
    expansionType: 'horizontal',
    targetMarket: 'streamers',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built fan engagement and monetization tools', impact: 'New revenue stream for streamers', difficulty: 'hard' },
      { action: 'Created virtual goods marketplace', impact: 'Recurring transactions', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 75 },
    lessonsLearned: 'Creator economy platforms can scale by enabling new monetization methods.',
    sourceUrl: 'https://www.starterstory.com/streamers-monetize-audience',
    sourcePlatform: 'starter_story',
    tags: ['gaming', 'streaming', 'creator_economy', 'platform'],
    matchingKeywords: ['streamer monetization', 'twitch', 'creator tools'],
    confidenceLevel: 'high',
    summary: 'Built a $150K/month platform where streamers can monetize their audience.',
  },
  {
    companyName: 'Overgear',
    industry: 'gaming',
    subIndustry: 'gaming_services',
    location: 'Ukraine',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Marketplace trust', 'Service quality', 'Scaling supply'],
      capabilities: ['Gaming expertise', 'Marketplace development'],
      marketPosition: 'New gaming services marketplace',
    },
    endingState: {
      revenue: '5m_10m',
      teamSize: '50_100',
      revenueGrowth: '$1M/month',
      achievements: ['$1M monthly revenue', 'Leading boosting marketplace', 'Global gamer network'],
      newCapabilities: ['Quality assurance', 'Global operations'],
      marketPosition: 'Leading video game boosting marketplace',
    },
    strategyType: 'marketplace_scale',
    expansionType: 'global',
    targetMarket: 'gamers',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built trusted gaming services marketplace', impact: 'Connected gamers with services', difficulty: 'hard' },
      { action: 'Ensured quality and trust', impact: 'Repeat customers', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 200 },
    lessonsLearned: 'Gaming services marketplaces can reach massive scale with trust systems.',
    sourceUrl: 'https://www.starterstory.com/video-games-boosting-services-marketplace',
    sourcePlatform: 'starter_story',
    tags: ['gaming', 'marketplace', 'boosting', 'services'],
    matchingKeywords: ['game boosting', 'gaming services', 'esports'],
    confidenceLevel: 'high',
    summary: 'Launched a $1M/month video games boosting services marketplace.',
  },

  // ===== Arts & Crafts =====
  {
    companyName: 'Popov Leather',
    industry: 'ecommerce',
    subIndustry: 'handmade_goods',
    location: 'Canada',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Handmade scaling', 'Quality consistency', 'Brand building'],
      capabilities: ['Leatherworking skills', 'Craftsmanship'],
      marketPosition: 'New handmade leather goods brand',
    },
    endingState: {
      revenue: '1m_5m',
      teamSize: '20_50',
      revenueGrowth: '$200K/month',
      achievements: ['$200K monthly revenue', '21 employees', 'Premium leather goods'],
      newCapabilities: ['Workshop scaling', 'E-commerce optimization'],
      marketPosition: 'Leading handmade leather goods brand',
    },
    strategyType: 'craftsmanship_scale',
    expansionType: 'horizontal',
    targetMarket: 'quality_seekers',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Maintained handmade quality at scale', impact: 'Premium positioning', difficulty: 'hard' },
      { action: 'Built strong e-commerce presence', impact: 'Global reach', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Handmade businesses can scale while maintaining quality and premium pricing.',
    sourceUrl: 'https://www.starterstory.com/stories/popov-leather-from-handmade-leather-wallets-to-900k-revenue',
    sourcePlatform: 'starter_story',
    tags: ['handmade', 'leather', 'ecommerce', 'craftsmanship'],
    matchingKeywords: ['leather goods', 'handmade wallets', 'craftsmanship'],
    confidenceLevel: 'high',
    summary: 'From handmade leather wallets to $200K/month revenue.',
  },
  {
    companyName: 'Ann + Joy',
    industry: 'ecommerce',
    subIndustry: 'handmade_jewelry',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Product uniqueness', 'Etsy competition', 'Scaling production'],
      capabilities: ['Jewelry making', 'Resin art skills'],
      marketPosition: 'New Etsy jewelry shop',
    },
    endingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      revenueGrowth: '$4K/month',
      achievements: ['$4K monthly revenue', 'Unique flower resin jewelry', 'Etsy success'],
      newCapabilities: ['Etsy optimization', 'Product photography'],
      marketPosition: 'Established Etsy jewelry brand',
    },
    strategyType: 'etsy_growth',
    expansionType: 'horizontal',
    targetMarket: 'jewelry_lovers',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Created unique flower and resin jewelry', impact: 'Product differentiation', difficulty: 'moderate' },
      { action: 'Optimized Etsy presence', impact: 'Steady sales growth', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 5 },
    lessonsLearned: 'Unique handmade products can find audiences on established marketplaces.',
    sourceUrl: 'https://www.starterstory.com/handmade-jewelry',
    sourcePlatform: 'starter_story',
    tags: ['handmade', 'jewelry', 'etsy', 'resin'],
    matchingKeywords: ['handmade jewelry', 'etsy shop', 'flower jewelry'],
    confidenceLevel: 'high',
    summary: 'Started a $4K/month handmade flower and resin jewelry business.',
  },
  {
    companyName: 'Raghaus',
    industry: 'ecommerce',
    subIndustry: 'handmade_goods',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Market differentiation', 'Organic growth', 'Partnership development'],
      capabilities: ['Craftsmanship', 'Photography background'],
      marketPosition: 'New handmade goods brand',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '2_5',
      revenueGrowth: '$25K/month',
      achievements: ['$25K monthly revenue', 'Etsy success', 'Brand partnerships'],
      newCapabilities: ['Wholesale relationships', 'Organic marketing'],
      marketPosition: 'Growing handmade goods brand',
    },
    strategyType: 'organic_growth',
    expansionType: 'horizontal',
    targetMarket: 'home_decor_buyers',
    timeline: { totalMonths: 72 },
    keyActions: [
      { action: 'Grew organically through partnerships', impact: 'No paid advertising needed', difficulty: 'moderate' },
      { action: 'Leveraged Etsy marketplace', impact: 'Built customer base', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 15 },
    lessonsLearned: 'Organic growth through partnerships can be more sustainable than paid ads.',
    sourceUrl: 'https://www.starterstory.com/stories/how-we-grew-organically-through-partnerships-and-etsy',
    sourcePlatform: 'starter_story',
    tags: ['handmade', 'etsy', 'partnerships', 'organic_growth'],
    matchingKeywords: ['handmade goods', 'etsy business', 'crafts'],
    confidenceLevel: 'high',
    summary: 'Grew organically through partnerships and Etsy to $25K/month.',
  },

  // ===== Audio/Podcast Production =====
  {
    companyName: 'Audivita Studios',
    industry: 'media',
    subIndustry: 'audio_production',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Studio setup', 'Client acquisition', 'Service diversification'],
      capabilities: ['Audio production', 'Voice direction'],
      marketPosition: 'New audio production studio',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '6_10',
      revenueGrowth: '$30K/month',
      achievements: ['$30K monthly revenue', 'Audiobooks and podcasts', 'Full-service studio'],
      newCapabilities: ['Podcast production', 'Audiobook narration'],
      marketPosition: 'Full-service audio production studio',
    },
    strategyType: 'service_diversification',
    expansionType: 'horizontal',
    targetMarket: 'authors_podcasters',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Offered both audiobooks and podcasts', impact: 'Diversified revenue streams', difficulty: 'moderate' },
      { action: 'Built full-service production capability', impact: 'Higher value clients', difficulty: 'moderate' },
    ],
    outcomes: { revenueMultiplier: 15 },
    lessonsLearned: 'Audio production services benefit from diversification across formats.',
    sourceUrl: 'https://www.starterstory.com/how-to-start-audiobooks-podcasts-production-company',
    sourcePlatform: 'starter_story',
    tags: ['audio', 'podcast', 'audiobooks', 'production'],
    matchingKeywords: ['audio production', 'podcast production', 'audiobooks'],
    confidenceLevel: 'high',
    summary: 'Started a $30K/month audiobooks and podcasts production company.',
  },

  // ===== Outdoor/Recreation =====
  {
    companyName: 'Cotopaxi (Batch 7 Detail)',
    industry: 'ecommerce',
    subIndustry: 'outdoor_gear',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Sustainable manufacturing', 'Brand differentiation', 'Social mission integration'],
      capabilities: ['E-commerce expertise', 'Product design'],
      marketPosition: 'New outdoor gear brand',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '50_100',
      revenueGrowth: 'Multi-million revenue',
      achievements: ['Certified B Corp', '70+ employees', 'Humanitarian mission integration'],
      newCapabilities: ['Sustainable supply chain', 'Brand advocacy'],
      marketPosition: 'Leading sustainable outdoor brand',
    },
    strategyType: 'mission_driven',
    expansionType: 'national',
    targetMarket: 'outdoor_enthusiasts',
    timeline: { totalMonths: 96 },
    keyActions: [
      { action: 'Built brand around humanitarian mission', impact: 'Strong brand loyalty', difficulty: 'hard' },
      { action: 'Used sustainable materials', impact: 'Premium positioning', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Mission-driven brands can command loyalty in competitive markets.',
    sourceUrl: 'https://www.starterstory.com/davis-smith',
    sourcePlatform: 'starter_story',
    tags: ['outdoor', 'sustainable', 'mission_driven', 'gear'],
    matchingKeywords: ['outdoor gear', 'sustainable outdoor', 'adventure gear'],
    confidenceLevel: 'high',
    summary: 'Created an outdoor gear brand with a humanitarian mission.',
  },
];

export async function seedBatch7() {
  console.log('🌱 Seeding Batch 7: EdTech, Fitness Apps, Wedding, Kids, Gaming, Crafts, Audio...');

  let successCount = 0;
  let errorCount = 0;

  for (const study of batch7CaseStudies) {
    try {
      await db.insert(caseStudies).values(study as CaseStudyInsert);
      successCount++;
      console.log(`  ✓ ${study.companyName}`);
    } catch (error) {
      errorCount++;
      console.error(`  ✗ ${study.companyName}:`, error instanceof Error ? error.message : 'Unknown error');
    }
  }

  console.log(`\nBatch 7 seeding complete!`);
  console.log(`✓ Successfully seeded: ${successCount}`);
  console.log(`✗ Errors: ${errorCount}`);

  return { success: successCount, errors: errorCount };
}

// Run if called directly
seedBatch7()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
