import { db } from '../../lib/db';
import { caseStudies } from '../schema';

type CaseStudyInsert = typeof caseStudies.$inferInsert;

const batch9CaseStudies = [
  // === MOBILE APPS ===
  {
    companyName: 'Locket',
    industry: 'consumer_app',
    subIndustry: 'social',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Solo developer', '14 days to build', 'App store competition'],
      capabilities: ['iOS development', 'Product intuition', 'Speed of execution'],
      marketPosition: 'New photo widget app',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '6_10',
      revenueGrowth: '50 million signups',
      achievements: ['50M signups', 'Viral growth', '#1 App Store', 'Built in 14 days'],
      newCapabilities: ['Widget technology', 'Viral mechanics', 'Social features'],
      marketPosition: 'Leading photo widget app',
    },
    strategyType: 'viral_growth',
    expansionType: 'organic',
    targetMarket: 'gen_z',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built viral photo widget app in 14 days', impact: 'Speed to market', difficulty: 'medium' },
      { action: 'Achieved 50M signups through organic growth', impact: 'Massive scale', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 500 },
    lessonsLearned: 'Simple, viral mechanics can reach massive scale incredibly fast.',
    sourceUrl: 'https://www.starterstory.com/locket-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['mobile_app', 'social', 'viral', 'widget'],
    matchingKeywords: ['photo app', 'widget', 'locket'],
    confidenceLevel: 'high',
    summary: 'Developer built Locket app to 50M signups, built in just 14 days.',
  },
  {
    companyName: 'Adam Lyttle Apps',
    industry: 'consumer_app',
    subIndustry: 'app_portfolio',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Massive debt', 'Learning development', 'App store discovery'],
      capabilities: ['Determination', 'Self-taught development', 'Persistence'],
      marketPosition: 'New indie app developer',
    },
    endingState: {
      revenue: '500k_1m',
      teamSize: '1',
      revenueGrowth: '$50K/month ($1M+ empire)',
      achievements: ['$1M+ app revenue', 'Multiple successful apps', 'Debt to wealth story'],
      newCapabilities: ['App development', 'ASO expertise', 'Revenue optimization'],
      marketPosition: 'Successful indie app developer',
    },
    strategyType: 'portfolio_approach',
    expansionType: 'horizontal',
    targetMarket: 'consumers',
    timeline: { totalMonths: 240 },
    keyActions: [
      { action: 'Turned massive debt into $1M app empire', impact: 'Life transformation', difficulty: 'hard' },
      { action: 'Built portfolio of successful apps solo', impact: 'Diversified revenue', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 500 },
    lessonsLearned: 'Persistence and learning development can transform financial situations.',
    sourceUrl: 'https://www.starterstory.com/adam-lyttle-apps-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['mobile_app', 'indie_developer', 'solo', 'portfolio'],
    matchingKeywords: ['app developer', 'indie apps', 'mobile apps'],
    confidenceLevel: 'high',
    summary: 'Turned massive debt into $1M app empire as solo developer.',
  },
  {
    companyName: 'Flighty',
    industry: 'consumer_app',
    subIndustry: 'travel',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Small team', 'Premium pricing', 'Travel app competition'],
      capabilities: ['iOS expertise', 'Design focus', 'Flight data access'],
      marketPosition: 'New flight tracking app',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '2_5',
      revenueGrowth: '$500K/month',
      achievements: ['$500K/month', 'Just 3 employees', 'Apple Design Award', 'Premium pricing works'],
      newCapabilities: ['Real-time flight data', 'Beautiful UX', 'Push notifications'],
      marketPosition: 'Leading premium flight tracking app',
    },
    strategyType: 'premium_positioning',
    expansionType: 'vertical',
    targetMarket: 'frequent_travelers',
    timeline: { totalMonths: 60 },
    keyActions: [
      { action: 'Built premium flight app with just 3 employees', impact: 'Maximum efficiency', difficulty: 'hard' },
      { action: 'Achieved $500K/month revenue', impact: 'Proves premium pricing', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 500 },
    lessonsLearned: 'Small teams with premium products can generate massive revenue.',
    sourceUrl: 'https://www.starterstory.com/flighty-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['mobile_app', 'travel', 'premium', 'small_team'],
    matchingKeywords: ['flight tracking', 'travel app', 'flighty'],
    confidenceLevel: 'high',
    summary: 'Grew Flighty to $500K monthly revenue with just 3 employees.',
  },
  {
    companyName: 'Calm',
    industry: 'consumer_app',
    subIndustry: 'health_wellness',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Million Dollar Homepage founder pivoting', 'Wellness space competition', 'Subscription model'],
      capabilities: ['Tech entrepreneurship', 'Product vision', 'Fundraising skills'],
      marketPosition: 'New meditation app',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '200_500',
      revenueGrowth: '$2B valuation',
      achievements: ['$2B valuation', 'Unicorn status', 'Category leader', '100M+ downloads'],
      newCapabilities: ['Celebrity content', 'Sleep stories', 'Corporate wellness'],
      marketPosition: 'Leading meditation and sleep app',
    },
    strategyType: 'category_leadership',
    expansionType: 'global',
    targetMarket: 'wellness_seekers',
    timeline: { totalMonths: 144 },
    keyActions: [
      { action: 'Built meditation app to $2B valuation', impact: 'Unicorn status', difficulty: 'hard' },
      { action: 'Created category-defining sleep and meditation content', impact: 'Content moat', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 20000 },
    lessonsLearned: 'Wellness apps with great content can achieve massive valuations.',
    sourceUrl: 'https://www.starterstory.com/calm-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['mobile_app', 'wellness', 'meditation', 'unicorn'],
    matchingKeywords: ['calm', 'meditation', 'sleep app'],
    confidenceLevel: 'high',
    summary: 'Built Calm to $2 billion sleep & meditation app.',
  },
  {
    companyName: 'Insight Timer',
    industry: 'consumer_app',
    subIndustry: 'health_wellness',
    location: 'Australia',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['$0 starting costs', 'Free model competition', 'Content creation'],
      capabilities: ['Meditation knowledge', 'Community building', 'App development'],
      marketPosition: 'New meditation app',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '10_50',
      revenueGrowth: '$1.16M/month',
      achievements: ['31M users', '$1.16M/month', '824K traffic', 'Worlds largest free meditation app'],
      newCapabilities: ['220K+ free tracks', 'Teacher marketplace', 'Community features'],
      marketPosition: 'Largest free meditation app',
    },
    strategyType: 'freemium_scale',
    expansionType: 'global',
    targetMarket: 'meditators',
    timeline: { totalMonths: 180 },
    keyActions: [
      { action: 'Built largest free meditation app with 31M users', impact: 'Massive reach', difficulty: 'hard' },
      { action: 'Created marketplace with 220K+ tracks', impact: 'Content scale', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 116 },
    lessonsLearned: 'Free-first models can build massive user bases and monetize at scale.',
    sourceUrl: 'https://www.starterstory.com/insight-timer-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['mobile_app', 'meditation', 'freemium', 'marketplace'],
    matchingKeywords: ['insight timer', 'meditation', 'wellness app'],
    confidenceLevel: 'high',
    summary: 'Grew meditation app to 31M users and $1.16M/month.',
  },
  {
    companyName: 'RiseApp',
    industry: 'consumer_app',
    subIndustry: 'productivity',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['$8K starting costs', '4 months to launch', 'App discovery'],
      capabilities: ['Development skills', 'Product focus', 'Growth hacking'],
      marketPosition: 'New productivity app',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '2_5',
      revenueGrowth: '$20K MRR in 4 months',
      achievements: ['$20K MRR', '4 months to scale', 'Fast growth'],
      newCapabilities: ['User engagement', 'Retention features', 'Growth mechanics'],
      marketPosition: 'Growing productivity app',
    },
    strategyType: 'rapid_growth',
    expansionType: 'organic',
    targetMarket: 'productivity_seekers',
    timeline: { totalMonths: 4 },
    keyActions: [
      { action: 'Built app to $20K MRR in just 4 months', impact: 'Rapid scaling', difficulty: 'hard' },
      { action: 'Started with only $8K investment', impact: 'Capital efficient', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 25 },
    lessonsLearned: 'Apps can reach significant revenue in months with right approach.',
    sourceUrl: 'https://www.starterstory.com/riseapp-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['mobile_app', 'productivity', 'rapid_growth', 'bootstrapped'],
    matchingKeywords: ['productivity app', 'riseapp', 'mobile app'],
    confidenceLevel: 'high',
    summary: 'Grew RiseApp to $20K MRR in just 4 months.',
  },

  // === MARKETPLACES ===
  {
    companyName: 'Whop',
    industry: 'marketplace',
    subIndustry: 'digital_products',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Marketplace cold start', 'Creator acquisition', 'Payment infrastructure'],
      capabilities: ['Technical skills', 'Creator network', 'Product vision'],
      marketPosition: 'New digital product marketplace',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '50_200',
      revenueGrowth: '$354K/month',
      achievements: ['$354K/month', '50 employees', 'Profitable', 'Creator economy leader'],
      newCapabilities: ['Payment processing', 'Creator tools', 'Community features'],
      marketPosition: 'Leading digital product marketplace',
    },
    strategyType: 'marketplace_growth',
    expansionType: 'platform',
    targetMarket: 'creators',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built digital product marketplace to $354K/month', impact: 'Platform scale', difficulty: 'hard' },
      { action: 'Scaled to 50 employees while profitable', impact: 'Sustainable growth', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 354 },
    lessonsLearned: 'Digital product marketplaces can scale rapidly in creator economy.',
    sourceUrl: 'https://www.starterstory.com/whop-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['marketplace', 'creator_economy', 'digital_products', 'platform'],
    matchingKeywords: ['whop', 'creator marketplace', 'digital products'],
    confidenceLevel: 'high',
    summary: 'Scaled Whop marketplace to $354K/month revenue.',
  },
  {
    companyName: 'AppSumo',
    industry: 'marketplace',
    subIndustry: 'software_deals',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['$50 starting budget', 'Deal sourcing', 'Audience building'],
      capabilities: ['Marketing expertise', 'Network', 'Hustle'],
      marketPosition: 'New software deals site',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '50_200',
      revenueGrowth: '$80M/year',
      achievements: ['$80M revenue', 'Started with $50', 'Category creator', 'Millions of customers'],
      newCapabilities: ['Deal platform', 'Email marketing', 'Software partnerships'],
      marketPosition: 'Leading software deals platform',
    },
    strategyType: 'marketplace_growth',
    expansionType: 'audience',
    targetMarket: 'entrepreneurs',
    timeline: { totalMonths: 180 },
    keyActions: [
      { action: 'Started software deals platform with $50', impact: 'Ultimate bootstrapping', difficulty: 'easy' },
      { action: 'Grew to $80M/year revenue', impact: 'Massive scale', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 1600000 },
    lessonsLearned: 'Curated deal platforms can create entirely new categories.',
    sourceUrl: 'https://www.starterstory.com/appsumo-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['marketplace', 'deals', 'software', 'bootstrapped'],
    matchingKeywords: ['appsumo', 'software deals', 'noah kagan'],
    confidenceLevel: 'high',
    summary: 'Noah Kagan grew AppSumo from $50 to $80M/year business.',
  },
  {
    companyName: 'Art.com',
    industry: 'marketplace',
    subIndustry: 'art',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['$35K starting costs', 'Art curation', 'E-commerce in 1994'],
      capabilities: ['Art industry knowledge', 'E-commerce vision', 'Operations'],
      marketPosition: 'New online art marketplace',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '500_plus',
      revenueGrowth: '$8.33M/month ($200M/year)',
      achievements: ['$200M revenue', '1000 employees', '2.2M monthly traffic', 'Sold to Walmart'],
      newCapabilities: ['Art printing', 'Framing services', 'Enterprise scale'],
      marketPosition: 'Leading online art marketplace',
    },
    strategyType: 'category_creation',
    expansionType: 'acquisition',
    targetMarket: 'art_buyers',
    timeline: { totalMonths: 300 },
    keyActions: [
      { action: 'Bootstrapped art marketplace to $200M/year', impact: 'Category dominance', difficulty: 'hard' },
      { action: 'Sold to Walmart for major exit', impact: 'Liquidity event', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 5714 },
    lessonsLearned: 'Category-defining marketplaces can achieve massive exits.',
    sourceUrl: 'https://www.starterstory.com/art-com-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['marketplace', 'art', 'ecommerce', 'exit'],
    matchingKeywords: ['art marketplace', 'art.com', 'online art'],
    confidenceLevel: 'high',
    summary: 'Bootstrapped Art.com to $200M/year before selling to Walmart.',
  },
  {
    companyName: 'DotMarket',
    industry: 'marketplace',
    subIndustry: 'business_sales',
    location: 'Europe',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Marketplace for businesses', 'Trust building', 'Deal flow'],
      capabilities: ['Online business experience', 'Marketplace knowledge', 'Network'],
      marketPosition: 'New online business marketplace',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '2_5',
      revenueGrowth: '$360K/year',
      achievements: ['$360K revenue', 'European focus', 'Business M&A platform'],
      newCapabilities: ['Due diligence', 'Valuation tools', 'Escrow services'],
      marketPosition: 'Growing online business marketplace',
    },
    strategyType: 'niche_marketplace',
    expansionType: 'regional',
    targetMarket: 'business_buyers_sellers',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built marketplace for buying/selling online businesses', impact: 'Niche focus', difficulty: 'medium' },
      { action: 'Scaled to $360K/year in Europe', impact: 'Regional success', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 36 },
    lessonsLearned: 'Business acquisition marketplaces can build sustainable businesses.',
    sourceUrl: 'https://www.starterstory.com/stories/dotmarket',
    sourcePlatform: 'starter_story',
    tags: ['marketplace', 'business_sales', 'europe', 'ma'],
    matchingKeywords: ['buy online business', 'sell website', 'business marketplace'],
    confidenceLevel: 'high',
    summary: 'Built $360K/year marketplace to buy and sell online businesses.',
  },
  {
    companyName: 'Sharetribe',
    industry: 'saas',
    subIndustry: 'marketplace_builder',
    location: 'Finland',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Crowdfunding for SaaS', 'Marketplace complexity', 'Competition'],
      capabilities: ['Technical expertise', 'Community building', 'Product vision'],
      marketPosition: 'New marketplace builder platform',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '10_50',
      revenueGrowth: '7-figure SaaS',
      achievements: ['7-figure revenue', '$1M+ crowdfunding', 'Powers thousands of marketplaces'],
      newCapabilities: ['No-code marketplace', 'Custom development', 'Transaction processing'],
      marketPosition: 'Leading marketplace builder',
    },
    strategyType: 'platform_enabler',
    expansionType: 'global',
    targetMarket: 'marketplace_entrepreneurs',
    timeline: { totalMonths: 144 },
    keyActions: [
      { action: 'Built 7-figure SaaS marketplace builder', impact: 'Enables other marketplaces', difficulty: 'hard' },
      { action: 'Raised $1M+ through crowdfunding', impact: 'Community-funded growth', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Meta-platforms enabling marketplaces can build sustainable SaaS.',
    sourceUrl: 'https://www.starterstory.com/stories/sharetribe-create-an-online-marketplace',
    sourcePlatform: 'starter_story',
    tags: ['saas', 'marketplace_builder', 'no_code', 'crowdfunding'],
    matchingKeywords: ['sharetribe', 'marketplace platform', 'create marketplace'],
    confidenceLevel: 'high',
    summary: 'Built 7-figure SaaS for creating online marketplaces.',
  },
  {
    companyName: 'BitsForDigits',
    industry: 'marketplace',
    subIndustry: 'acquisitions',
    location: 'Europe',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['$0 marketing budget', 'Marketplace liquidity', 'Trust building'],
      capabilities: ['Digital asset experience', 'SEO skills', 'Marketplace knowledge'],
      marketPosition: 'New online acquisition marketplace',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '2_5',
      revenueGrowth: '$72K/year',
      achievements: ['$72K revenue', '$0 marketing spend', 'Bootstrapped', 'Organic growth'],
      newCapabilities: ['SEO traffic', 'Escrow services', 'Valuation tools'],
      marketPosition: 'Growing acquisition marketplace',
    },
    strategyType: 'organic_growth',
    expansionType: 'global',
    targetMarket: 'digital_entrepreneurs',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Built marketplace with $0 marketing budget', impact: 'Pure organic growth', difficulty: 'hard' },
      { action: 'Bootstrapped to $72K/year', impact: 'Sustainable model', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 72 },
    lessonsLearned: 'Niche marketplaces can grow organically without marketing spend.',
    sourceUrl: 'https://www.starterstory.com/stories/bitsfordigits',
    sourcePlatform: 'starter_story',
    tags: ['marketplace', 'acquisitions', 'organic', 'bootstrapped'],
    matchingKeywords: ['digital acquisitions', 'buy websites', 'online business'],
    confidenceLevel: 'high',
    summary: 'Bootstrapped $72K/year acquisition marketplace with $0 marketing.',
  },

  // === AI STARTUPS ===
  {
    companyName: 'Anthropic',
    industry: 'ai',
    subIndustry: 'foundation_models',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['$124M starting investment', 'Competing with OpenAI', 'AI safety focus'],
      capabilities: ['Ex-OpenAI team', 'Research expertise', 'Safety focus'],
      marketPosition: 'New AI safety company',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '200_500',
      revenueGrowth: '$250M/month',
      achievements: ['$250M/month revenue', '480 employees', '100K customers', 'Claude AI'],
      newCapabilities: ['Constitutional AI', 'Claude models', 'Enterprise API'],
      marketPosition: 'Leading AI safety company',
    },
    strategyType: 'research_commercialization',
    expansionType: 'global',
    targetMarket: 'enterprise_developers',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Built AI safety-focused foundation model company', impact: 'Category differentiation', difficulty: 'hard' },
      { action: 'Achieved $250M/month revenue with Claude', impact: 'Massive commercial success', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 24 },
    lessonsLearned: 'Safety-focused AI can achieve massive commercial success.',
    sourceUrl: 'https://www.starterstory.com/anthropic-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['ai', 'foundation_models', 'safety', 'enterprise'],
    matchingKeywords: ['anthropic', 'claude', 'ai safety'],
    confidenceLevel: 'high',
    summary: 'Anthropic achieved $200M+ revenue with Claude AI by 2024.',
  },
  {
    companyName: 'Hugging Face',
    industry: 'ai',
    subIndustry: 'ml_platform',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Open source monetization', 'Community building', 'Competing with big tech'],
      capabilities: ['ML expertise', 'Community focus', 'Open source ethos'],
      marketPosition: 'New ML platform',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '200_500',
      revenueGrowth: '$4.5B valuation',
      achievements: ['$4.5B valuation', 'ML community leader', 'Open source AI hub'],
      newCapabilities: ['Model hub', 'Transformers library', 'Enterprise solutions'],
      marketPosition: 'Leading open-source AI platform',
    },
    strategyType: 'open_source_growth',
    expansionType: 'community',
    targetMarket: 'ml_practitioners',
    timeline: { totalMonths: 84 },
    keyActions: [
      { action: 'Built open-source ML platform to $4.5B valuation', impact: 'Community-driven scale', difficulty: 'hard' },
      { action: 'Created GitHub for AI models', impact: 'Network effects', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 4500 },
    lessonsLearned: 'Open-source platforms with strong community can achieve massive valuations.',
    sourceUrl: 'https://www.starterstory.com/hugging-face-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['ai', 'open_source', 'platform', 'community'],
    matchingKeywords: ['hugging face', 'transformers', 'ml platform'],
    confidenceLevel: 'high',
    summary: 'Grew Hugging Face to $4.5B valuation in seven years.',
  },
  {
    companyName: 'Jenni AI',
    industry: 'ai',
    subIndustry: 'writing',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['27-year-old founder', 'AI writing competition', 'Academic market'],
      capabilities: ['Technical skills', 'Product intuition', 'Speed'],
      marketPosition: 'New AI writing assistant',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '10_50',
      revenueGrowth: '$5M ARR in 2 years',
      achievements: ['$5M ARR', 'Rapid growth', 'Academic focus differentiation'],
      newCapabilities: ['AI writing', 'Citation features', 'Research tools'],
      marketPosition: 'Leading AI writing assistant',
    },
    strategyType: 'product_led_growth',
    expansionType: 'vertical',
    targetMarket: 'students_researchers',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Built AI writing tool to $5M ARR in 2 years', impact: 'Rapid scaling', difficulty: 'hard' },
      { action: 'Focused on academic writing niche', impact: 'Clear positioning', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 50 },
    lessonsLearned: 'Niche AI tools for specific use cases can scale rapidly.',
    sourceUrl: 'https://www.starterstory.com/jenni-ai-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['ai', 'writing', 'education', 'product_led'],
    matchingKeywords: ['jenni ai', 'ai writing', 'academic writing'],
    confidenceLevel: 'high',
    summary: '27-year-old grew Jenni AI to $5M ARR in 2 years.',
  },
  {
    companyName: 'PDF.ai',
    industry: 'ai',
    subIndustry: 'document_processing',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Simple product idea', 'AI API costs', 'Marketing'],
      capabilities: ['Development skills', 'Product sense', 'Speed'],
      marketPosition: 'New AI PDF tool',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '2_5',
      revenueGrowth: '$1.5M ARR in months',
      achievements: ['$1.5M ARR', 'Rapid scaling', 'Simple product winning'],
      newCapabilities: ['PDF chat', 'Document Q&A', 'API access'],
      marketPosition: 'Leading AI PDF solution',
    },
    strategyType: 'rapid_scaling',
    expansionType: 'organic',
    targetMarket: 'professionals',
    timeline: { totalMonths: 12 },
    keyActions: [
      { action: 'Built AI PDF tool to $1.5M ARR in months', impact: 'Explosive growth', difficulty: 'medium' },
      { action: 'Simple use case, massive demand', impact: 'Product-market fit', difficulty: 'easy' },
    ],
    outcomes: { revenueMultiplier: 150 },
    lessonsLearned: 'Simple AI tools solving clear pain points can scale incredibly fast.',
    sourceUrl: 'https://www.starterstory.com/pdf-ai-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['ai', 'pdf', 'document', 'rapid_growth'],
    matchingKeywords: ['pdf ai', 'chat pdf', 'document ai'],
    confidenceLevel: 'high',
    summary: 'Scaled PDF.ai to $1.5M ARR in months.',
  },
  {
    companyName: 'Keywords AI',
    industry: 'ai',
    subIndustry: 'llm_infrastructure',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['LLM monitoring complexity', 'Developer adoption', 'Infrastructure'],
      capabilities: ['Technical expertise', 'LLM knowledge', 'Developer focus'],
      marketPosition: 'New LLM platform',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '6_10',
      revenueGrowth: '$1.1M ARR',
      achievements: ['$1.1M ARR', 'LLM infrastructure leader', 'Developer-loved'],
      newCapabilities: ['LLM monitoring', 'Cost optimization', 'Performance tracking'],
      marketPosition: 'Growing LLM platform',
    },
    strategyType: 'developer_first',
    expansionType: 'vertical',
    targetMarket: 'ai_developers',
    timeline: { totalMonths: 18 },
    keyActions: [
      { action: 'Built LLM monitoring platform to $1.1M ARR', impact: 'Rapid traction', difficulty: 'hard' },
      { action: 'Focused on developer experience', impact: 'Strong adoption', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 11 },
    lessonsLearned: 'Infrastructure tools for AI developers can scale rapidly.',
    sourceUrl: 'https://www.starterstory.com/keywords-ai-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['ai', 'infrastructure', 'llm', 'developer_tools'],
    matchingKeywords: ['keywords ai', 'llm platform', 'ai infrastructure'],
    confidenceLevel: 'high',
    summary: 'Two founders grew LLM platform to $1.1M ARR.',
  },
  {
    companyName: 'Lutra AI',
    industry: 'ai',
    subIndustry: 'automation',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['AI automation space', 'Enterprise sales', 'Fundraising'],
      capabilities: ['Technical expertise', 'Enterprise experience', 'Vision'],
      marketPosition: 'New AI automation platform',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '6_10',
      revenueGrowth: '$417K/month',
      achievements: ['$417K/month', '$3.8M seed funding', 'Profitable', 'Rapid growth'],
      newCapabilities: ['AI workflows', 'Integration platform', 'Enterprise features'],
      marketPosition: 'Growing AI automation platform',
    },
    strategyType: 'venture_backed',
    expansionType: 'enterprise',
    targetMarket: 'enterprises',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Raised $3.8M seed while already profitable', impact: 'Strong position', difficulty: 'hard' },
      { action: 'Achieved $417K/month revenue quickly', impact: 'Rapid scaling', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 417 },
    lessonsLearned: 'AI automation platforms can achieve rapid revenue growth.',
    sourceUrl: 'https://www.starterstory.com/lutra-ai-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['ai', 'automation', 'enterprise', 'funded'],
    matchingKeywords: ['lutra ai', 'ai automation', 'workflow automation'],
    confidenceLevel: 'high',
    summary: 'Lutra AI went from $0 to $3.8M funding and $417K/month.',
  },
  {
    companyName: 'Codeium',
    industry: 'ai',
    subIndustry: 'developer_tools',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Competing with Copilot', 'Free tier sustainability', 'Enterprise adoption'],
      capabilities: ['AI research', 'Developer experience', 'Startup speed'],
      marketPosition: 'New AI coding assistant',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '50_200',
      revenueGrowth: '$1M/month ($1.25B valuation)',
      achievements: ['$1.25B valuation', '$1M/month', 'Free tier success', 'Enterprise adoption'],
      newCapabilities: ['Code completion', 'Chat features', 'Enterprise deployment'],
      marketPosition: 'Leading free AI coding assistant',
    },
    strategyType: 'freemium_scale',
    expansionType: 'global',
    targetMarket: 'developers',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Built AI coding tool to $1.25B valuation', impact: 'Unicorn status', difficulty: 'hard' },
      { action: 'Offered free tier competing with Copilot', impact: 'Mass adoption', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 1000 },
    lessonsLearned: 'Free AI developer tools can achieve unicorn valuations.',
    sourceUrl: 'https://www.starterstory.com/codeium-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['ai', 'developer_tools', 'coding', 'unicorn'],
    matchingKeywords: ['codeium', 'ai coding', 'code completion'],
    confidenceLevel: 'high',
    summary: 'Codeium skyrocketed to $1.25B valuation with AI-powered coding tools.',
  },
  {
    companyName: 'Mercor',
    industry: 'ai',
    subIndustry: 'recruiting',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['College dropouts', 'Recruiting competition', 'AI trust'],
      capabilities: ['AI expertise', 'Recruiting insight', 'Hustle'],
      marketPosition: 'New AI recruiting platform',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '50_200',
      revenueGrowth: '$2B valuation',
      achievements: ['$2B valuation', 'College dropout founders', 'AI recruiting leader'],
      newCapabilities: ['AI interviews', 'Skill assessment', 'Matching algorithms'],
      marketPosition: 'Leading AI recruiting platform',
    },
    strategyType: 'venture_scale',
    expansionType: 'global',
    targetMarket: 'enterprises',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Built AI recruiting platform to $2B valuation', impact: 'Massive scale', difficulty: 'hard' },
      { action: 'Dropped out of college to scale faster', impact: 'Full commitment', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 20000 },
    lessonsLearned: 'AI in recruiting can achieve massive valuations quickly.',
    sourceUrl: 'https://www.starterstory.com/mercor-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['ai', 'recruiting', 'hr_tech', 'unicorn'],
    matchingKeywords: ['mercor', 'ai recruiting', 'hiring platform'],
    confidenceLevel: 'high',
    summary: 'College dropouts scaled AI recruitment to $2B valuation.',
  },
  {
    companyName: 'Decagon AI',
    industry: 'ai',
    subIndustry: 'customer_support',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['Enterprise customer support', 'AI reliability', 'Integration complexity'],
      capabilities: ['AI research', 'Enterprise experience', 'Product vision'],
      marketPosition: 'New AI support platform',
    },
    endingState: {
      revenue: '10m_plus',
      teamSize: '50_200',
      revenueGrowth: '$100M funding',
      achievements: ['$100M raised', 'Enterprise customer support AI', 'Rapid growth'],
      newCapabilities: ['AI agents', 'Multi-channel support', 'Enterprise integrations'],
      marketPosition: 'Leading enterprise AI support',
    },
    strategyType: 'venture_backed',
    expansionType: 'enterprise',
    targetMarket: 'enterprises',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Raised $100M for enterprise AI support', impact: 'Major funding', difficulty: 'hard' },
      { action: 'Built AI agents for customer support', impact: 'Product differentiation', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 100 },
    lessonsLearned: 'Enterprise AI support represents massive opportunity.',
    sourceUrl: 'https://www.starterstory.com/decagon-ai-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['ai', 'customer_support', 'enterprise', 'funded'],
    matchingKeywords: ['decagon', 'ai support', 'customer service ai'],
    confidenceLevel: 'high',
    summary: 'Decagon AI secured $100M to transform enterprise support.',
  },
  {
    companyName: 'Customers.ai',
    industry: 'ai',
    subIndustry: 'marketing',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Serial entrepreneur', 'AI marketing space', 'Bootstrapping'],
      capabilities: ['Marketing expertise', 'AI knowledge', 'Entrepreneurship'],
      marketPosition: 'New AI marketing platform',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '10_50',
      revenueGrowth: '$3.9M revenue',
      achievements: ['$3.9M revenue', '400 clients', 'Bootstrapped', 'Larry Kim founded'],
      newCapabilities: ['AI marketing', 'Lead generation', 'Automation'],
      marketPosition: 'Growing AI marketing platform',
    },
    strategyType: 'bootstrapped_growth',
    expansionType: 'vertical',
    targetMarket: 'marketers',
    timeline: { totalMonths: 36 },
    keyActions: [
      { action: 'Bootstrapped AI marketing platform to $3.9M', impact: 'Self-funded success', difficulty: 'hard' },
      { action: 'Acquired 400 clients without VC funding', impact: 'Organic growth', difficulty: 'hard' },
    ],
    outcomes: { revenueMultiplier: 39 },
    lessonsLearned: 'AI marketing tools can be bootstrapped successfully.',
    sourceUrl: 'https://www.starterstory.com/customers-ai-breakdown',
    sourcePlatform: 'starter_story',
    tags: ['ai', 'marketing', 'bootstrapped', 'serial_entrepreneur'],
    matchingKeywords: ['customers ai', 'ai marketing', 'larry kim'],
    confidenceLevel: 'high',
    summary: 'Bootstrapped Customers.ai to $3.9M and 400 clients.',
  },
  {
    companyName: 'Addepto',
    industry: 'ai',
    subIndustry: 'consulting',
    location: 'Poland',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['AI consulting from Poland', 'Enterprise clients', 'Team building'],
      capabilities: ['AI expertise', 'Consulting experience', 'Technical team'],
      marketPosition: 'New AI consulting firm',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '10_50',
      revenueGrowth: '$1.26M/year',
      achievements: ['$1.26M revenue', '30+ employees', 'Global clients'],
      newCapabilities: ['Data science', 'ML engineering', 'AI strategy'],
      marketPosition: 'Growing AI consulting firm',
    },
    strategyType: 'consulting_growth',
    expansionType: 'global',
    targetMarket: 'enterprises',
    timeline: { totalMonths: 48 },
    keyActions: [
      { action: 'Built AI consulting firm to 30+ employees', impact: 'Team scale', difficulty: 'hard' },
      { action: 'Achieved $1.26M/year from Poland', impact: 'Global reach', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 12 },
    lessonsLearned: 'AI consulting can scale from anywhere with right expertise.',
    sourceUrl: 'https://www.starterstory.com/stories/we-built-a-1-26m-year-ai-consulting-business-over-30-employees',
    sourcePlatform: 'starter_story',
    tags: ['ai', 'consulting', 'poland', 'services'],
    matchingKeywords: ['ai consulting', 'data science', 'ml consulting'],
    confidenceLevel: 'high',
    summary: 'Built $1.26M/year AI consulting business with 30+ employees.',
  },
  {
    companyName: 'Rytr',
    industry: 'ai',
    subIndustry: 'writing',
    location: 'India',
    startingState: {
      revenue: 'under_100k',
      teamSize: '1',
      yearsInBusiness: 0,
      challenges: ['Simple AI tool', 'Competition with Jasper', 'Pricing strategy'],
      capabilities: ['Development skills', 'GPT-3 early access', 'Product focus'],
      marketPosition: 'New AI writing tool',
    },
    endingState: {
      revenue: '100k_500k',
      teamSize: '2_5',
      revenueGrowth: '$60K/year',
      achievements: ['$60K revenue', 'Simple successful product', 'Early AI writing'],
      newCapabilities: ['Multiple use cases', 'Templates', 'API access'],
      marketPosition: 'Growing AI writing tool',
    },
    strategyType: 'simple_product',
    expansionType: 'organic',
    targetMarket: 'content_creators',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Built simple AI writing tool to $60K/year', impact: 'Validated market', difficulty: 'easy' },
      { action: 'Early mover in AI writing space', impact: 'Market timing', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 6 },
    lessonsLearned: 'Simple AI tools can generate meaningful revenue.',
    sourceUrl: 'https://www.starterstory.com/stories/i-built-a-simple-ai-writing-tool-that-makes-60k-year',
    sourcePlatform: 'starter_story',
    tags: ['ai', 'writing', 'india', 'simple_product'],
    matchingKeywords: ['rytr', 'ai writing', 'content generation'],
    confidenceLevel: 'high',
    summary: 'Built simple AI writing tool that makes $60K/year.',
  },
  {
    companyName: 'GetPoppy AI',
    industry: 'ai',
    subIndustry: 'content',
    location: 'USA',
    startingState: {
      revenue: 'under_100k',
      teamSize: '2_5',
      yearsInBusiness: 0,
      challenges: ['AI content space', 'Differentiation', 'Scaling'],
      capabilities: ['Technical skills', 'Content knowledge', 'Growth skills'],
      marketPosition: 'New AI content platform',
    },
    endingState: {
      revenue: '1m_10m',
      teamSize: '6_10',
      revenueGrowth: '$4M/year',
      achievements: ['$4M revenue', 'AI content leader', 'Rapid growth'],
      newCapabilities: ['Email writing', 'Content generation', 'Templates'],
      marketPosition: 'Leading AI content app',
    },
    strategyType: 'product_led_growth',
    expansionType: 'organic',
    targetMarket: 'marketers',
    timeline: { totalMonths: 24 },
    keyActions: [
      { action: 'Built AI content app to $4M/year', impact: 'Strong growth', difficulty: 'hard' },
      { action: 'Focused on email writing use case', impact: 'Clear positioning', difficulty: 'medium' },
    ],
    outcomes: { revenueMultiplier: 40 },
    lessonsLearned: 'Focused AI content tools can scale to millions.',
    sourceUrl: 'https://www.starterstory.com/stories/poppyai-write-emails-that-sell',
    sourcePlatform: 'starter_story',
    tags: ['ai', 'content', 'email', 'saas'],
    matchingKeywords: ['poppy ai', 'ai content', 'email writing'],
    confidenceLevel: 'high',
    summary: 'Built $4M/year AI content app.',
  },
];

export async function seedBatch9() {
  console.log('🌱 Seeding Batch 9: Mobile Apps, Marketplaces, AI Startups...');

  let successCount = 0;
  let errorCount = 0;

  for (const study of batch9CaseStudies) {
    try {
      await db.insert(caseStudies).values(study as CaseStudyInsert);
      console.log(`  ✓ ${study.companyName}`);
      successCount++;
    } catch (error) {
      console.error(`  ✗ ${study.companyName}:`, error);
      errorCount++;
    }
  }

  console.log(`\nBatch 9 seeding complete!`);
  console.log(`✓ Successfully seeded: ${successCount}`);
  console.log(`✗ Errors: ${errorCount}`);
}

seedBatch9()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
